In [ ]:
import requests
import json

API_KEY = '' #Bisa menggunakan API Key sendiri
VIDEO_ID = '50KZ16zj5LE' #ID Video yang akan di Scrapping
URL = 'https://www.googleapis.com/youtube/v3/commentThreads'

comments = []
params = {
    'part': 'snippet',
    'videoId': VIDEO_ID,
    'key': API_KEY,
    'textFormat': 'plainText'
}

while True:
    response = requests.get(URL, params=params)
    data = response.json()

    for item in data.get('items', []):
        comment = item['snippet']['topLevelComment']['snippet']['textDisplay']
        comments.append(comment)

    if 'nextPageToken' in data:
        params['pageToken'] = data['nextPageToken']
    else:
        break

print(f'Total komentar: {len(comments)}')

Total komentar: 3714

In [ ]:
import pandas as pd

df = pd.DataFrame(comments, columns=['Comment'])
df

                                                Comment
0     Harga batrei mobil listrik itu 300tj sampai 400jt
1                     Mobil gk ada suara malah serem..😅
2     PLTU sama limbah batery linbah dan emisi..lah ...
3     Kalau kehabisan listrik di kebun / plosok desa...
4     Setelah 8 tahun mau jual ke siapa? Siapa pemin...
...                                                 ...
3709  karena gagal dalam pengelolaan layanan transpo...
3710  Harusnya pemerintah indo mencotoh china, bukny...
3711  Diindonesia juga belum ada mekanisme pengolaha...
3712  Mobil listrik tidak ramah lingkungan\nKarena l...
3713  Dan nanti... Nanti nih Yah... Begitu pengguna ...

[3714 rows x 1 columns]

In [ ]:
!pip install sastrawi
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StopWordRemoverFactory()
stopword = factory.create_stop_word_remover()

stem_factory = StemmerFactory()
stemmer = stem_factory.create_stemmer()


df['Cleaned_Comment'] = df['Comment'].apply(lambda x: stopword.remove(x))
df['Stemmed_Comment'] = df['Cleaned_Comment'].apply(lambda x: stemmer.stem(x))

Requirement already satisfied: sastrawi in /usr/local/lib/python3.12/dist-packages (1.0.1)

In [ ]:
df

,Comment,Cleaned_Comment,Stemmed_Comment
0,Harga batrei mobil listrik itu 300tj sampai 400jt,Harga batrei mobil listrik 300tj 400jt,harga batrei mobil listrik 300tj 400jt
1,Mobil gk ada suara malah serem..😅,Mobil gk suara malah serem..😅,mobil gk suara malah rem
2,PLTU sama limbah batery linbah dan emisi..lah ...,PLTU sama limbah batery linbah emisi..lah bapak,pltu sama limbah batery linbah emisi lah bapak
3,Kalau kehabisan listrik di kebun / plosok desa...,Kalau kehabisan listrik kebun / plosok desa gi...,kalau habis listrik kebun plosok desa gimana e...
4,Setelah 8 tahun mau jual ke siapa? Siapa pemin...,Setelah 8 tahun mau jual siapa? Siapa peminat ...,telah 8 tahun mau jual siapa siapa minat mobil...
...,...,...,...
3709,karena gagal dalam pengelolaan layanan transpo...,"gagal pengelolaan layanan transportasi umum, b...",gagal kelola layan transportasi umum beliau ma...
3710,"Harusnya pemerintah indo mencotoh china, bukny...","Harusnya pemerintah indo mencotoh china, bukny...",harus perintah indo mencotoh china buk bangga ...
3711,Diindonesia juga belum ada mekanisme pengolaha...,Diindonesia belum mekanisme pengolahan limbah ...,indonesia belum mekanisme olah limbah batere j...
3712,Mobil listrik tidak ramah lingkungan\nKarena l...,Mobil listrik ramah lingkungan\nKarena listrik...,mobil listrik ramah lingkung karena listrik ma...
3713,Dan nanti... Nanti nih Yah... Begitu pengguna ...,Dan nanti... Nanti nih Yah... Begitu pengguna ...,dan nanti nanti nih yah begitu guna kendara d ...

In [ ]:
df = df['Stemmed_Comment']
df

0                  harga batrei mobil listrik 300tj 400jt
1                                mobil gk suara malah rem
2          pltu sama limbah batery linbah emisi lah bapak
3       kalau habis listrik kebun plosok desa gimana e...
4       telah 8 tahun mau jual siapa siapa minat mobil...
                              ...
3709    gagal kelola layan transportasi umum beliau ma...
3710    harus perintah indo mencotoh china buk bangga ...
3711    indonesia belum mekanisme olah limbah batere j...
3712    mobil listrik ramah lingkung karena listrik ma...
3713    dan nanti nanti nih yah begitu guna kendara d ...
Name: Stemmed_Comment, Length: 3714, dtype: object

In [ ]:
df.to_csv('Short1.csv', index=False)