In [2]:
from pathlib import Path
import pandas as pd

folder_data = Path("data")
csv = []

for file in folder_data.glob("*.csv"):
    file_csv = pd.read_csv(file)
    csv.append(file_csv)

df = pd.concat(csv)

In [2]:
df

,id_asli,text_asli,model_ai,prompt_index,output_nonformal
0,4282,Asrama Mahasiswa Kabupaten Mempawah menggelar ...,deepseek/deepseek-v4-flash,Prompt 3,"Nah guys, gini lho ceritanya. Asrama Mahasiswa..."
1,4283,Siapa pemain paling penting dalam skuad Arsena...,deepseek/deepseek-v4-flash,Prompt 3,"Btw, lo pada tau gak siapa pemain paling penti..."
2,4284,adalah salah satu amalan yang wajib dilaksanak...,deepseek/deepseek-v4-flash,Prompt 3,"Guys, ngomongin soal Ramadhan, pasti gak lepas..."
3,4285,"Moms, menahan haus dan lapar selama menjalanka...",deepseek/deepseek-v4-flash,Prompt 3,"Moms, ternyata menahan haus dan lapar pas puas..."
4,4286,Itu penggalan ceramah saya di acara dengan wal...,deepseek/deepseek-v4-flash,Prompt 3,"Gini lho, kemarin saya ada ceramah di acara ba..."
...,...,...,...,...,...
0,0,TEL AVIV Pernyataan keras dan kontroversial te...,deepseek/deepseek-v4-flash,Prompt 2,"Gini loh, baru-baru ini Menteri Keuangan Israe..."
1,1,Gempa bumi susulan kembali terjadi di Kota Jay...,deepseek/deepseek-v4-flash,Prompt 2,"Eh guys, gempa susulan lagi nih di Kota Jayapu..."
2,2,Indeks Harga Saham Gabungan (IHSG) berakhir di...,deepseek/deepseek-v4-flash,Prompt 2,"Wah, IHSG lagi merah banget nih. Hari Senin, 2..."
3,3,PT Pegadaian berhasil meraih penghargaan di Aj...,deepseek/deepseek-v4-flash,Prompt 2,Pegadaian baru aja dapet penghargaan di Linked...
4,4,Gaya hidup hedonisme para pejabat negara tenga...,deepseek/deepseek-v4-flash,Prompt 2,Gaya hidup hedon pejabat lagi disorot nih. Uda...

In [7]:
valid = df[df["output_nonformal"] != "ERROR_API"]

In [8]:
valid

,id_asli,text_asli,model_ai,prompt_index,output_nonformal
0,4282,Asrama Mahasiswa Kabupaten Mempawah menggelar ...,deepseek/deepseek-v4-flash,Prompt 3,"Nah guys, gini lho ceritanya. Asrama Mahasiswa..."
1,4283,Siapa pemain paling penting dalam skuad Arsena...,deepseek/deepseek-v4-flash,Prompt 3,"Btw, lo pada tau gak siapa pemain paling penti..."
2,4284,adalah salah satu amalan yang wajib dilaksanak...,deepseek/deepseek-v4-flash,Prompt 3,"Guys, ngomongin soal Ramadhan, pasti gak lepas..."
3,4285,"Moms, menahan haus dan lapar selama menjalanka...",deepseek/deepseek-v4-flash,Prompt 3,"Moms, ternyata menahan haus dan lapar pas puas..."
4,4286,Itu penggalan ceramah saya di acara dengan wal...,deepseek/deepseek-v4-flash,Prompt 3,"Gini lho, kemarin saya ada ceramah di acara ba..."
...,...,...,...,...,...
0,0,TEL AVIV Pernyataan keras dan kontroversial te...,deepseek/deepseek-v4-flash,Prompt 2,"Gini loh, baru-baru ini Menteri Keuangan Israe..."
1,1,Gempa bumi susulan kembali terjadi di Kota Jay...,deepseek/deepseek-v4-flash,Prompt 2,"Eh guys, gempa susulan lagi nih di Kota Jayapu..."
2,2,Indeks Harga Saham Gabungan (IHSG) berakhir di...,deepseek/deepseek-v4-flash,Prompt 2,"Wah, IHSG lagi merah banget nih. Hari Senin, 2..."
3,3,PT Pegadaian berhasil meraih penghargaan di Aj...,deepseek/deepseek-v4-flash,Prompt 2,Pegadaian baru aja dapet penghargaan di Linked...
4,4,Gaya hidup hedonisme para pejabat negara tenga...,deepseek/deepseek-v4-flash,Prompt 2,Gaya hidup hedon pejabat lagi disorot nih. Uda...

In [9]:
valid.to_csv("sudah_nonformal.csv", index=False)

In [4]:
referensi = pd.read_csv("referensi.csv")
referensi

                                                   text
0     TEL AVIV Pernyataan keras dan kontroversial te...
1     Gempa bumi susulan kembali terjadi di Kota Jay...
2     Indeks Harga Saham Gabungan (IHSG) berakhir di...
3     PT Pegadaian berhasil meraih penghargaan di Aj...
4     Gaya hidup hedonisme para pejabat negara tenga...
...                                                 ...
8559  Karyawan Jakarta International Container Termi...
8560  Wakil Presiden Gibran Rakabuming Raka menjanji...
8561  Fajar Alfian/Muhammad Shohibul Fikri melaju ke...
8562  Bencana kembali melanda Tanah Air. Kali ini, l...
8563  muncul renovasi rumah subsidi yang hasilnya bi...

[8564 rows x 1 columns]

In [14]:
berita_set = set(valid["text_asli"])
belum_keliatan = []

for data in referensi["text"]:
    # print(data)
    if data not in berita_set:
        belum_keliatan.append(data)

df_hasil = pd.DataFrame(belum_keliatan, columns=["text"])

df_hasil.to_csv("referensi2.csv", index=False)

In [17]:
# bisa gini juga ya biar lebih cepet misahin pake pandas
kondisi = ~referensi["text"].isin(berita_set)

belum = referensi.loc[kondisi, "text"].tolist()

In [ ]:
# cek aja takut salah
panjang_valid = len(valid)
panjang_referensi = len(referensi)

print(f"panjang data valid = {panjang_valid}")
print(f"panjang data referensi = {panjang_referensi}")
print(f"panjang data baru harusnya = {panjang_referensi} - {panjang_valid}: {panjang_referensi - panjang_valid}")

output = pd.read_csv("referensi2.csv")
print(f"panjang data baru beneran = {len(output)}")

panjang data valid = 1580
panjang data referensi = 8564
panjang data baru harusnya = 8564 - 1580: 6984
panjang data baru beneran = 6984

ok, udah ok

## Gabungin semua CSV

In [16]:
folder_data = Path("data")
semua_csv = []

for file in folder_data.glob("*.csv"):
    file_csv = pd.read_csv(file)
    semua_csv.append(file_csv)

df_gabungan = pd.concat(semua_csv)

In [17]:
df_gabungan

,id_asli,text_asli,model_ai,prompt_index,output_nonformal
0,4282,Asrama Mahasiswa Kabupaten Mempawah menggelar ...,deepseek/deepseek-v4-flash,Prompt 3,"Nah guys, gini lho ceritanya. Asrama Mahasiswa..."
1,4283,Siapa pemain paling penting dalam skuad Arsena...,deepseek/deepseek-v4-flash,Prompt 3,"Btw, lo pada tau gak siapa pemain paling penti..."
2,4284,adalah salah satu amalan yang wajib dilaksanak...,deepseek/deepseek-v4-flash,Prompt 3,"Guys, ngomongin soal Ramadhan, pasti gak lepas..."
3,4285,"Moms, menahan haus dan lapar selama menjalanka...",deepseek/deepseek-v4-flash,Prompt 3,"Moms, ternyata menahan haus dan lapar pas puas..."
4,4286,Itu penggalan ceramah saya di acara dengan wal...,deepseek/deepseek-v4-flash,Prompt 3,"Gini lho, kemarin saya ada ceramah di acara ba..."
...,...,...,...,...,...
4995,9995,Era digital telah meluas ke seantero negeri. T...,deepseek/deepseek-v4-flash,Prompt 1,"Eh guys, era digital udah sampe ke seluruh pen..."
4996,9996,Plt Ketua Umum PPP Tawarkan Suharso Monoarfa P...,deepseek/deepseek-v4-flash,Prompt 1,"Plt Ketua Umum PPP, Muhamad Mardiono, bilang k..."
4997,9997,"Transisi Energi, Transisi Deforestasi. Ringkas...",deepseek/deepseek-v4-flash,Prompt 1,"Transisi energi, transisi deforestasi. Intinya..."
4998,9998,Ini lokasi dan jadwal penukaran uang baru di J...,deepseek/deepseek-v4-flash,Prompt 1,Ini dia lokasi dan jadwal penukaran uang baru ...
4999,9999,Mensesneg Tegaskan Efisiensi Hanya Diterapkan ...,deepseek/deepseek-v4-flash,Prompt 1,Mensesneg Prasetyo Hadi negesin kalo kebijakan...

In [18]:
valid = df_gabungan[df_gabungan["output_nonformal"] != "ERROR_API"]
tidak_valid =  df_gabungan[df_gabungan["output_nonformal"] == "ERROR_API"]

In [19]:
valid

,id_asli,text_asli,model_ai,prompt_index,output_nonformal
0,4282,Asrama Mahasiswa Kabupaten Mempawah menggelar ...,deepseek/deepseek-v4-flash,Prompt 3,"Nah guys, gini lho ceritanya. Asrama Mahasiswa..."
1,4283,Siapa pemain paling penting dalam skuad Arsena...,deepseek/deepseek-v4-flash,Prompt 3,"Btw, lo pada tau gak siapa pemain paling penti..."
2,4284,adalah salah satu amalan yang wajib dilaksanak...,deepseek/deepseek-v4-flash,Prompt 3,"Guys, ngomongin soal Ramadhan, pasti gak lepas..."
3,4285,"Moms, menahan haus dan lapar selama menjalanka...",deepseek/deepseek-v4-flash,Prompt 3,"Moms, ternyata menahan haus dan lapar pas puas..."
4,4286,Itu penggalan ceramah saya di acara dengan wal...,deepseek/deepseek-v4-flash,Prompt 3,"Gini lho, kemarin saya ada ceramah di acara ba..."
...,...,...,...,...,...
4995,9995,Era digital telah meluas ke seantero negeri. T...,deepseek/deepseek-v4-flash,Prompt 1,"Eh guys, era digital udah sampe ke seluruh pen..."
4996,9996,Plt Ketua Umum PPP Tawarkan Suharso Monoarfa P...,deepseek/deepseek-v4-flash,Prompt 1,"Plt Ketua Umum PPP, Muhamad Mardiono, bilang k..."
4997,9997,"Transisi Energi, Transisi Deforestasi. Ringkas...",deepseek/deepseek-v4-flash,Prompt 1,"Transisi energi, transisi deforestasi. Intinya..."
4998,9998,Ini lokasi dan jadwal penukaran uang baru di J...,deepseek/deepseek-v4-flash,Prompt 1,Ini dia lokasi dan jadwal penukaran uang baru ...
4999,9999,Mensesneg Tegaskan Efisiensi Hanya Diterapkan ...,deepseek/deepseek-v4-flash,Prompt 1,Mensesneg Prasetyo Hadi negesin kalo kebijakan...

In [20]:
tidak_valid

,id_asli,text_asli,model_ai,prompt_index,output_nonformal
370,4652,"Sebagai sekutu Amerika Serikat (AS), Arab Saud...",deepseek/deepseek-v4-flash,Prompt 2,ERROR_API
371,4653,Bank Indonesia (BI) membuka layanan penukaran ...,deepseek/deepseek-v4-flash,Prompt 2,ERROR_API
372,4654,Masjid Al-Aqsa Palestina kembali menjadi sasar...,deepseek/deepseek-v4-flash,Prompt 2,ERROR_API
373,4655,"Beijing, China dikabarkan marah besar atas ter...",deepseek/deepseek-v4-flash,Prompt 2,ERROR_API
374,4656,Artis kondang Soimah mengaku pernah didatangi ...,deepseek/deepseek-v4-flash,Prompt 2,ERROR_API
...,...,...,...,...,...
3775,8795,"Di Tengah Kemelut China-Taiwan, Biden Akan Ber...",deepseek/deepseek-v4-flash,Prompt 1,ERROR_API
3776,8796,Celah Korupsi Penerimaan Murid Baru. Ringkasan...,deepseek/deepseek-v4-flash,Prompt 1,ERROR_API
3777,8797,Menteri Energi dan Sumber Daya Mineral (ESDM) ...,deepseek/deepseek-v4-flash,Prompt 1,ERROR_API
3778,8798,Bahlil Lantik Sejumlah Pejabat Eselon I ESDM: ...,deepseek/deepseek-v4-flash,Prompt 1,ERROR_API
3779,8799,Foto udara kondisi rumah yang ambruk akibat pe...,deepseek/deepseek-v4-flash,Prompt 1,ERROR_API

In [28]:
referensi4 = tidak_valid[["text_asli"]]

In [31]:
referensi4 = referensi4.rename(columns={"text_asli": "text"})

In [32]:
referensi4

                                                   text
370   Sebagai sekutu Amerika Serikat (AS), Arab Saud...
371   Bank Indonesia (BI) membuka layanan penukaran ...
372   Masjid Al-Aqsa Palestina kembali menjadi sasar...
373   Beijing, China dikabarkan marah besar atas ter...
374   Artis kondang Soimah mengaku pernah didatangi ...
...                                                 ...
3775  Di Tengah Kemelut China-Taiwan, Biden Akan Ber...
3776  Celah Korupsi Penerimaan Murid Baru. Ringkasan...
3777  Menteri Energi dan Sumber Daya Mineral (ESDM) ...
3778  Bahlil Lantik Sejumlah Pejabat Eselon I ESDM: ...
3779  Foto udara kondisi rumah yang ambruk akibat pe...

[2797 rows x 1 columns]

In [33]:
referensi4.to_csv("run_ulang.csv", index=False)

In [15]:
valid.to_csv("done.csv")