In [1]:
from pathlib import Path
import pandas as pd

folder_data = Path("data")
csv = []

for file in folder_data.glob("*.csv"):
    file_csv = pd.read_csv(file)
    csv.append(file_csv)

df = pd.concat(csv)

In [2]:
df

,id_asli,text_asli,model_ai,prompt_index,output_nonformal
0,4282,Asrama Mahasiswa Kabupaten Mempawah menggelar ...,deepseek/deepseek-v4-flash,Prompt 3,"Nah guys, gini lho ceritanya. Asrama Mahasiswa..."
1,4283,Siapa pemain paling penting dalam skuad Arsena...,deepseek/deepseek-v4-flash,Prompt 3,"Btw, lo pada tau gak siapa pemain paling penti..."
2,4284,adalah salah satu amalan yang wajib dilaksanak...,deepseek/deepseek-v4-flash,Prompt 3,"Guys, ngomongin soal Ramadhan, pasti gak lepas..."
3,4285,"Moms, menahan haus dan lapar selama menjalanka...",deepseek/deepseek-v4-flash,Prompt 3,"Moms, ternyata menahan haus dan lapar pas puas..."
4,4286,Itu penggalan ceramah saya di acara dengan wal...,deepseek/deepseek-v4-flash,Prompt 3,"Gini lho, kemarin saya ada ceramah di acara ba..."
...,...,...,...,...,...
0,0,TEL AVIV Pernyataan keras dan kontroversial te...,deepseek/deepseek-v4-flash,Prompt 2,"Gini loh, baru-baru ini Menteri Keuangan Israe..."
1,1,Gempa bumi susulan kembali terjadi di Kota Jay...,deepseek/deepseek-v4-flash,Prompt 2,"Eh guys, gempa susulan lagi nih di Kota Jayapu..."
2,2,Indeks Harga Saham Gabungan (IHSG) berakhir di...,deepseek/deepseek-v4-flash,Prompt 2,"Wah, IHSG lagi merah banget nih. Hari Senin, 2..."
3,3,PT Pegadaian berhasil meraih penghargaan di Aj...,deepseek/deepseek-v4-flash,Prompt 2,Pegadaian baru aja dapet penghargaan di Linked...
4,4,Gaya hidup hedonisme para pejabat negara tenga...,deepseek/deepseek-v4-flash,Prompt 2,Gaya hidup hedon pejabat lagi disorot nih. Uda...

In [7]:
valid = df[df["output_nonformal"] != "ERROR_API"]

In [8]:
valid

,id_asli,text_asli,model_ai,prompt_index,output_nonformal
0,4282,Asrama Mahasiswa Kabupaten Mempawah menggelar ...,deepseek/deepseek-v4-flash,Prompt 3,"Nah guys, gini lho ceritanya. Asrama Mahasiswa..."
1,4283,Siapa pemain paling penting dalam skuad Arsena...,deepseek/deepseek-v4-flash,Prompt 3,"Btw, lo pada tau gak siapa pemain paling penti..."
2,4284,adalah salah satu amalan yang wajib dilaksanak...,deepseek/deepseek-v4-flash,Prompt 3,"Guys, ngomongin soal Ramadhan, pasti gak lepas..."
3,4285,"Moms, menahan haus dan lapar selama menjalanka...",deepseek/deepseek-v4-flash,Prompt 3,"Moms, ternyata menahan haus dan lapar pas puas..."
4,4286,Itu penggalan ceramah saya di acara dengan wal...,deepseek/deepseek-v4-flash,Prompt 3,"Gini lho, kemarin saya ada ceramah di acara ba..."
...,...,...,...,...,...
0,0,TEL AVIV Pernyataan keras dan kontroversial te...,deepseek/deepseek-v4-flash,Prompt 2,"Gini loh, baru-baru ini Menteri Keuangan Israe..."
1,1,Gempa bumi susulan kembali terjadi di Kota Jay...,deepseek/deepseek-v4-flash,Prompt 2,"Eh guys, gempa susulan lagi nih di Kota Jayapu..."
2,2,Indeks Harga Saham Gabungan (IHSG) berakhir di...,deepseek/deepseek-v4-flash,Prompt 2,"Wah, IHSG lagi merah banget nih. Hari Senin, 2..."
3,3,PT Pegadaian berhasil meraih penghargaan di Aj...,deepseek/deepseek-v4-flash,Prompt 2,Pegadaian baru aja dapet penghargaan di Linked...
4,4,Gaya hidup hedonisme para pejabat negara tenga...,deepseek/deepseek-v4-flash,Prompt 2,Gaya hidup hedon pejabat lagi disorot nih. Uda...

In [9]:
valid.to_csv("sudah_nonformal.csv", index=False)

In [4]:
referensi = pd.read_csv("referensi.csv")
referensi

                                                   text
0     TEL AVIV Pernyataan keras dan kontroversial te...
1     Gempa bumi susulan kembali terjadi di Kota Jay...
2     Indeks Harga Saham Gabungan (IHSG) berakhir di...
3     PT Pegadaian berhasil meraih penghargaan di Aj...
4     Gaya hidup hedonisme para pejabat negara tenga...
...                                                 ...
8559  Karyawan Jakarta International Container Termi...
8560  Wakil Presiden Gibran Rakabuming Raka menjanji...
8561  Fajar Alfian/Muhammad Shohibul Fikri melaju ke...
8562  Bencana kembali melanda Tanah Air. Kali ini, l...
8563  muncul renovasi rumah subsidi yang hasilnya bi...

[8564 rows x 1 columns]

In [14]:
berita_set = set(valid["text_asli"])
belum_keliatan = []

for data in referensi["text"]:
    # print(data)
    if data not in berita_set:
        belum_keliatan.append(data)

df_hasil = pd.DataFrame(belum_keliatan, columns=["text"])

df_hasil.to_csv("referensi2.csv", index=False)

In [17]:
# bisa gini juga ya biar lebih cepet misahin pake pandas
kondisi = ~referensi["text"].isin(berita_set)

belum = referensi.loc[kondisi, "text"].tolist()

In [ ]:
# cek aja takut salah
panjang_valid = len(valid)
panjang_referensi = len(referensi)

print(f"panjang data valid = {panjang_valid}")
print(f"panjang data referensi = {panjang_referensi}")
print(f"panjang data baru harusnya = {panjang_referensi} - {panjang_valid}: {panjang_referensi - panjang_valid}")

output = pd.read_csv("referensi2.csv")
print(f"panjang data baru beneran = {len(output)}")

panjang data valid = 1580
panjang data referensi = 8564
panjang data baru harusnya = 8564 - 1580: 6984
panjang data baru beneran = 6984

ok, udah ok