In [788]:
import pandas as pd
from pathlib import Path
pd.set_option('display.max_colwidth', None)
# pd.reset_option('display.max_colwidth')

In [789]:
instructiones = """Anda adalah sistem ahli yang mengklasifikasikan [Komentar] media sosial Indonesia ke dalam label resmi: [Netral, Disinformasi, Fitnah, Ujaran Kebencian], dengan dibantu [Artikel Rujukan] jika tersedia.

Aturan Penalaran:

1. Prioritaskan analisis pada [Komentar] untuk menentukan apakah teks tersebut mengandung klaim faktual yang memerlukan verifikasi, termasuk indikasi ujaran kebencian/SARA, atau sekadar interaksi santai.
2. Jika [Komentar] mengandung unsur serangan atau penghinaan berdasarkan identitas (SARA, ras, etnis, agama, gender, disabilitas), langsung klasifikasikan sebagai 'Ujaran Kebencian' dan ABAIKAN [Artikel Rujukan].
3. Jika tidak mengandung ujaran kebencian, gunakan [Artikel Rujukan] (atau pengetahuan internal jika rujukan kosong) untuk menilai klaim:
* Netral: Konten faktual, opini, ekspresi emosional, kritik kebijakan, atau interaksi normal yang tidak mengandung kebohongan spesifik untuk menjatuhkan reputasi.
* Disinformasi: Informasi keliru/menyesatkan yang berpotensi meresahkan masyarakat atau memicu polarisasi.
* Fitnah: Tuduhan atau klaim bohong yang spesifik dan sengaja dibuat untuk menyerang karakter, kehormatan, atau reputasi individu/kelompok.

**Format Output WAJIB (Jangan diubah):**
Penjelasan:
[Tulis analisis ringkas terhadap Komentar, perbandingannya dengan Artikel Rujukan, dan alasan pemilihan label]

Kesimpulan:
Label: [NamaLabel]."""

# Fitnah

In [790]:
folderData = Path("Dataset_Fitnah")
files = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    files.append(df_sementara)

df = pd.concat(files, ignore_index=True)

In [642]:
df_fitnah = df[df["is_layak"] == 1]

In [643]:
df_fitnah[df_fitnah["cot_bantuh_fitnah"].notna()]

,url,title,published_at,text,sumber_berita,label,is_layak,claim_fitnah,cot_bantah_fitnah,reasoning_fitnah,cot_bantuh_fitnah
4305,https://banten.indozone.id/news/2486375917/hingga-september-2025-capaian-pajak-kota-tembus-7019-persen-dari-target-tahunan?page=all,"Hingga September 2025, Capaian Pajak Kota Tembus 70,19 persen Dari Target Tahunan",2025-10-10 12:02:12,"Kepala Bapenda Kota Serang, W Hari Pamungkas (Doc.Mamo erfanto)\n- Capaian pendapatanpajakdaerahKota Serangmenunjukkan tren positif sepanjang tahun 2025. Hingga 30 September 2025, Badan Pendapatan Daerah (Bapenda)Kota Serangmencatat realisasipajaktelah mencapai 70,19 persen dari target tahunan.\nKepalaBapenda Kota Serang, W Hari Pamungkas, mengatakan capaian tersebut menjadi sinyal positif atas meningkatnya kesadaran wajibpajakserta tumbuhnya sektor usaha diKota Serang. Jumat 10 Oktober 2025.\n""Dari Januari sampai 30 September kami sudah mencapai akumulatif 70,19 persen. Target kami selama setahun Rp341,2 miliar, dan hingga triwulan ketiga sudah terealisasi Rp239,5 miliar,"" ujar Hari.\nBendahara Desa Petir Bawa Kabur Dana Desa 1Milyar TA 2025\n12 Cabor Yang Akan Di Pertandingkan Di PORKOT IV Kota Serang\nPencapaian ini jauh lebih tinggi dibandingkan periode yang sama tahun sebelumnya. Pada 2024, realisasi pajak hingga akhir tahun hanya sebesar Rp221 miliar.\nArtinya, per September 2025, Kota Serang telah mencatat surplus sekitar Rp19 miliar dibandingkan capaian tahun lalu.\n""Ini progres yang bagus untuk pajak daerah di Kota Serang,"" kata Hari.",indozone,Ekonomi & Bisnis,1.0,"Pemerintah Kota Serang korup, target pajak yang tinggi hanya untuk memperkaya diri sendiri!",NaN,"Fakta bahwa capaian pajak meningkat signifikan dibandingkan tahun sebelumnya dan surplus yang tercipta menunjukkan efektivitas kebijakan pemerintah, bukan indikasi korupsi. Tuduhan korupsi adalah insinuasi negatif yang tidak berdasar.","[Capaian pajak 70,19 persen dari target tahunan adalah hasil dari peningkatan kesadaran wajib pajak dan pertumbuhan sektor usaha, bukan indikasi korupsi., Pencapaian ini jauh lebih tinggi dibandingkan periode yang sama tahun sebelumnya, menunjukkan efektivitas kebijakan pemerintah dalam pengumpulan pajak., Surplus sekitar Rp19 miliar dibandingkan capaian tahun lalu menunjukkan peningkatan kinerja fiskal, bukan keuntungan pribadi., Pernyataan bahwa target pajak tinggi hanya untuk memperkaya diri sendiri tidak didasarkan pada bukti konkrit dan mengabaikan fakta bahwa dana tersebut digunakan untuk pembangunan daerah.]"
11532,https://news.indozone.id/world-update/914860610/kronologi-penembakan-donald-trump-saat-kampanye-akbar-di-pennsylvania?page=all,Kronologi Penembakan Donald Trump saat Kampanye Akbar di Pennsylvania,2024-07-14 10:13:12,"- Sebuah penembakan terjadi pada rapat umumDonald Trumppada hari sabtu waktu setempat, diikuti oleh mantan presiden yang dilarikan dari panggung dengan darah di sekitar telinganya.\nTrumpsedang berbicara di sebuah rapat umum di Butler, Pennsylvania, ketika suara keras terdengar di tengah kerumunan sekitar pukul 18.13 waktu Pennsylvania.\nTrumptampaknya terkena sesuatu di bagian telinga kanannya saat dia berbicara, dan video menunjukkan dia dengan cepat memegangi telinganya dan kemudian menunduk ke tanah, ketika agen keamanan dan yang lainnya melompat untuk membantunya.\nTrumpberdiri dengan darah di sisi wajahnya dan tampak mengatakan ""lawan, lawan"" sambil mengepalkan tinjunya.\nTrumpkemudian dengan cepat dikawal dari panggung dan masuk ke dalam kendaraannya. Lokasi rapat umum kini menjadi tempat kejadian perkara.\nTimTrumpdan Secret Service mengkonfirmasi bahwa dia ""baik-baik saja"" dan sedang diperiksa di fasilitas medis setempat.\nJaksa wilayah Butler mengkonfirmasi bahwa tersangka penembak dan seorang peserta rapat umum telah tewas. Satu orang lainnya yang hadir dalam rapat umum tersebut berada dalam kondisi serius.\nPenembakan tersebut sedang diselidiki sebagai percobaan pembunuhan.\nKonten ini adalah kiriman dari Z Creators Indozone. Yuk, bikin cerita dan konten serumu, serta dapatkan berbagai reward menarik! Let's join Z Creators dengan klikdi sini.",indozone,Politik,1.0,Trump sengaja terkena tembakan untuk mendapatkan simpati publik!,NaN,"Claim tersebut menggunakan insinuasi dan framing negatif dengan menuduh Trump sengaja terkena tembakan untuk mendapatkan simpati publik. Fakta menunjukkan bahwa penembakan tersebut adalah peristiwa nyata dengan korban yang jelas, dan investigasi sedang berlangsung sebagai percobaan pembunuhan.","[Fakta menunjukkan bahwa penembakan terjadi saat Trump sedang berbicara di rapat umum, dan video menunjukkan dia dengan cepat memegangi telinganya dan menunduk ke tanah., Tim Trump dan Secret Service mengkonfirmasi bahwa dia 'baik-baik saja' dan sedang diperiksa di fasilitas medis setempat., Jaksa wilayah Butler mengkonfirmasi bahwa tersangka penembak dan seorang peserta rapat umum telah tewas, menunjukkan kejadian tersebut sangat serius., Kondisi serius satu orang lainnya yang hadir dalam rapat umum tersebut menunjukkan bahwa penembakan tersebut bukanlah aksi palsu., Investigasi sedang dilakukan sebagai percobaan pembunuhan, yang menegaskan kejadian tersebut adalah peristiwa nyata dan bukan settingan.]"

In [644]:
df_fitnah["cot_bantah_fitnah"] = df_fitnah["cot_bantah_fitnah"].fillna(df_fitnah["cot_bantuh_fitnah"])
df_fitnah = df_fitnah.drop(columns=["cot_bantuh_fitnah", "url", "published_at", "sumber_berita", "label", "is_layak"])

C:\Users\Dipo\AppData\Local\Temp\ipykernel_134436\883797873.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fitnah["cot_bantah_fitnah"] = df_fitnah["cot_bantah_fitnah"].fillna(df_fitnah["cot_bantuh_fitnah"])

In [645]:
df_fitnah.isna().sum()

title                0
text                 0
claim_fitnah         0
cot_bantah_fitnah    0
reasoning_fitnah     1
dtype: int64

In [646]:
df_fitnah = df_fitnah.dropna()

In [647]:
df_fitnah.isna().sum()

title                0
text                 0
claim_fitnah         0
cot_bantah_fitnah    0
reasoning_fitnah     0
dtype: int64

In [648]:
df_fitnah["label"] = "Fitnah"

In [649]:
df_fitnah = df_fitnah.to_dict("records")

In [650]:
len(df_fitnah)

7211

In [651]:
import json
import random

def generate_sft_dataset_with_context(raw_data_list, instructions, output_file):
    dataset = []
    
    for data in raw_data_list:
        instruct = instructions
        claim = data.get("claim_fitnah", "")
        berita = data.get("text", "") 
        label = data.get("label")
        reasoning = data.get("reasoning_fitnah", "")
        cot_list = data.get("cot_bantah_fitnah", [])
        
        # Susun poin-poin fakta
        fakta_points = "\n".join([f"* {point}" for point in cot_list])
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Komentar: '{claim}';\n\n"
            f"Artikel Rujukan: {berita}"
        )

        full_output = (
            f"Penjelasan: {reasoning}\n\n"
            f"Berikut adalah beberapa poin penting:\n"
            f"{fakta_points}\n\n"
            f"Kesimpulan:\n"
            f"Label: {label}."
        )
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(df_fitnah, instructiones, "fitnah.jsonl")

Berhasil membuat 7211 data dengan konteks berita di fitnah.jsonl

In [652]:
df = pd.read_json("fitnah.jsonl", lines=True)
df.head(1)

,instruction,input,output
0,"Anda adalah sistem ahli yang mengklasifikasikan [Komentar] media sosial Indonesia ke dalam label resmi: [Netral, Disinformasi, Fitnah, Ujaran Kebencian], dengan dibantu [Artikel Rujukan] jika tersedia.\n\nAturan Penalaran:\n\n1. Prioritaskan analisis pada [Komentar] untuk menentukan apakah teks tersebut mengandung klaim faktual yang memerlukan verifikasi, termasuk indikasi ujaran kebencian/SARA, atau sekadar interaksi santai.\n2. Jika [Komentar] mengandung unsur serangan atau penghinaan berdasarkan identitas (SARA, ras, etnis, agama, gender, disabilitas), langsung klasifikasikan sebagai 'Ujaran Kebencian' dan ABAIKAN [Artikel Rujukan].\n3. Jika tidak mengandung ujaran kebencian, gunakan [Artikel Rujukan] (atau pengetahuan internal jika rujukan kosong) untuk menilai klaim:\n* Netral: Konten faktual, opini, ekspresi emosional, kritik kebijakan, atau interaksi normal yang tidak mengandung kebohongan spesifik untuk menjatuhkan reputasi.\n* Disinformasi: Informasi keliru/menyesatkan yang berpotensi meresahkan masyarakat atau memicu polarisasi.\n* Fitnah: Tuduhan atau klaim bohong yang spesifik dan sengaja dibuat untuk menyerang karakter, kehormatan, atau reputasi individu/kelompok.\n\n**Format Output WAJIB (Jangan diubah):**\nPenjelasan:\n[Tulis analisis ringkas terhadap Komentar, perbandingannya dengan Artikel Rujukan, dan alasan pemilihan label]\n\nKesimpulan:\nLabel: [NamaLabel].","Komentar: 'BNN sengaja pilih kampung miskin buat dijadikan kambing hitam soal narkoba';\n\nArtikel Rujukan: BNN menggedebek kampung narkoba di Berlan, Matraman, Jakarta Timur. (Antara Foto/Fauzan)\n- Badan Narkotika Nasional (BNN) bersama petugas gabungan menggerebek kawasan Berlan, Matraman, Jakarta Timur, terkait dugaan peredarannarkobapada Selasa (25/11/2025) siang.\nDalam operasi tersebut, puluhan orang yang diduga sebagai pengedar berhasil diamankan.\nPenggerebekan dilakukan sekitar pukul 11.00 WIB. Petugas gabungan melakukan penyisiran ke sejumlah rumah dan langsung melakukan penggeledahan di titik-titik yang telah ditargetkan.\nDari lokasi, petugas menemukan berbagai jenis barang bukti narkoba dalam bentuk bubuk maupun cairan.\nSejumlah paket narkoba ditemukan disembunyikan di lemari hingga gudang-gudang kecil yang berada di dalam rumah warga.\nTerungkap! Ekstasi Rp 207 M Ditemukan Saat Mobil Kecelakaan di Lampung Hendak Disebar di Jakarta\nUntuk mempermudah pencarian barang bukti, petugas juga mengerahkan anjing pelacak (K9).\nLangkah ini dilakukan untuk memastikan tidak ada narkoba yang terlewatkan selama proses penggeledahan.\nDirektur Psikotropika dan Prekursor Deputi Bidang Pemberantasan BNN, Aldrin Marihot Pandapotan Hutabarat, menyampaikan bahwa pihaknya mengamankan puluhan orang dalam operasi tersebut.\n""Ada 10–15 titik yang menjadi target penggerebekan di kawasan Berlan. Dari rangkaian penggerebekan itu, kami mengamankan 25 pelaku,"" ujar Aldrin.\nSeluruh orang yang diamankan langsung dibawa ke kantor BNN untuk pemeriksaan lebih lanjut. Ia menyebut bahwa para pelaku merupakan warga sekitar.\n""Kawasan ini merupakan perkampungan. Semua yang kami amankan adalah warga sipil. Kami akan dalami peran masing-masing,"" pungkasnya.","Penjelasan: Fakta dipelintir dengan menuduh BNN memilih kampung miskin sebagai kambing hitam, padahal operasi ini didasarkan pada informasi intelijen dan bukti yang ditemukan di lapangan\n\nBerikut adalah beberapa poin penting:\n* BNN melakukan penggerebekan di Berlan, Matraman, berdasarkan informasi dan indikasi kuat adanya peredaran narkoba di kawasan tersebut\n* Operasi ini melibatkan petugas gabungan dan menggunakan anjing pelacak (K9) untuk memastikan keakuratan dan efektivitas penggeledahan\n* Berbagai jenis barang bukti narkoba ditemukan di lokasi, termasuk bubuk dan cairan yang disembunyikan di lemari dan gudang-gudang kecil\n* Penggerebekan ini mengamankan puluhan orang yang diduga sebagai pengedar, bukan sembarangan warga miskin\n* Tindakan BNN ini adalah bagian dari upaya nasional untuk memerangi peredaran narkoba, tidak ada indikasi pemilihan target berdasarkan status sosial ekonomi\n\nKesimpulan:\nLabel: Fitnah."

# Disinformasi

In [653]:
folderData = Path("Dataset_disinformasi")
files = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    files.append(df_sementara)

df_disinformasi = pd.concat(files, ignore_index=True)

In [654]:
df_disinformasi = df_disinformasi[df_disinformasi["is_layak"] == 1]

In [655]:
len(df_disinformasi)

7995

In [656]:
df_disinformasi.isna().sum()

claim_disinformasi            0
berita_asli                   0
label                         0
is_layak                      0
cot_bantah_disinformasi       4
reasoning_disinformasi        0
cot_bantuh_disinformasi    7991
dtype: int64

In [657]:
df_disinformasi["cot_bantah_disinformasi"] = df_disinformasi["cot_bantah_disinformasi"].fillna(df_disinformasi["cot_bantuh_disinformasi"])

In [658]:
df_disinformasi = df_disinformasi.drop(columns=["cot_bantuh_disinformasi", "is_layak"])

In [659]:
df_disinformasi.head(1)

,claim_disinformasi,berita_asli,label,cot_bantah_disinformasi,reasoning_disinformasi
0,"Heboh! Pemuda Bakar Mobil Mercedes Karena Buatan Prancis, Padahal Aslinya...","Beredar di media sosial sebuah video yang diklaim memperlihatkan seorang pemuda membakar mobil karena buatan Prancis. Faktanya, klaim adanya pemuda yang membakar mobil miliknya karena mobil tersebut buatan Prancis adalah salah. Dikutip dari Turnbackhoax.id, mobil yang dibakar di video itu adalah Mercedes AMG GT 63 S buatan Jerman. Pria dalam video tersebut bernama Misha atau dikenal sebagai Mikhail Litvin, vlogger asal Rusia. Aksi membakar mobil itu disebabkan oleh rasa kesal karena mobil senilai 13 juta rubel Rusia (Rp 2 miliar) yang dibelinya sering rusak dan keengganan pabrikan untuk menerima tanggung jawab (menanggung biaya perbaikan). Jadi, aksi membakar mobil tersebut tidak ada kaitannya dengan Prancis.",Disinformasi,"[Mobil yang dibakar adalah Mercedes AMG GT 63 S, buatan Jerman, bukan Prancis (sumber: Turnbackhoax.id)., Pria dalam video tersebut adalah Mikhail Litvin, vlogger asal Rusia, yang membakar mobil karena masalah teknis dan keengganan pabrikan untuk bertanggung jawab., Aksi pembakaran mobil tidak ada hubungannya dengan asal negara pembuatan mobil tersebut.]",Ini adalah konten menyesatkan yang mencatut nama negara pembuatan mobil untuk menciptakan narasi yang provokatif dan mengecoh publik.

In [660]:
df_disinformasi = df_disinformasi.to_dict("records")

In [661]:
import json
import random

def generate_sft_dataset_with_context(raw_data_list, instructions, output_file):
    dataset = []
    
    for data in raw_data_list:
        instruct = instructions
        claim = data.get("claim_disinformasi", "")
        berita = data.get("berita_asli", "") 
        label = data.get("label")
        reasoning = data.get("reasoning_disinformasi", "")
        cot_list = data.get("cot_bantah_disinformasi", [])
        
        # Susun poin-poin fakta
        fakta_points = "\n".join([f"* {point}" for point in cot_list])
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Komentar: '{claim}';\n\n"
            f"Artikel Rujukan: {berita}"
        )

        full_output = (
            f"Penjelasan: {reasoning}\n\n"
            f"Berikut adalah beberapa poin penting:\n"
            f"{fakta_points}\n\n"
            f"Kesimpulan:\n"
            f"Label: {label}."
        )
        
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(df_disinformasi, instructiones, "disinformasi.jsonl")

Berhasil membuat 7995 data dengan konteks berita di disinformasi.jsonl

In [662]:
tes_disinformasi = pd.read_json("disinformasi.jsonl", lines=True)

In [663]:
tes_disinformasi.head(1)

,instruction,input,output
0,"Anda adalah sistem ahli yang mengklasifikasikan [Komentar] media sosial Indonesia ke dalam label resmi: [Netral, Disinformasi, Fitnah, Ujaran Kebencian], dengan dibantu [Artikel Rujukan] jika tersedia.\n\nAturan Penalaran:\n\n1. Prioritaskan analisis pada [Komentar] untuk menentukan apakah teks tersebut mengandung klaim faktual yang memerlukan verifikasi, termasuk indikasi ujaran kebencian/SARA, atau sekadar interaksi santai.\n2. Jika [Komentar] mengandung unsur serangan atau penghinaan berdasarkan identitas (SARA, ras, etnis, agama, gender, disabilitas), langsung klasifikasikan sebagai 'Ujaran Kebencian' dan ABAIKAN [Artikel Rujukan].\n3. Jika tidak mengandung ujaran kebencian, gunakan [Artikel Rujukan] (atau pengetahuan internal jika rujukan kosong) untuk menilai klaim:\n* Netral: Konten faktual, opini, ekspresi emosional, kritik kebijakan, atau interaksi normal yang tidak mengandung kebohongan spesifik untuk menjatuhkan reputasi.\n* Disinformasi: Informasi keliru/menyesatkan yang berpotensi meresahkan masyarakat atau memicu polarisasi.\n* Fitnah: Tuduhan atau klaim bohong yang spesifik dan sengaja dibuat untuk menyerang karakter, kehormatan, atau reputasi individu/kelompok.\n\n**Format Output WAJIB (Jangan diubah):**\nPenjelasan:\n[Tulis analisis ringkas terhadap Komentar, perbandingannya dengan Artikel Rujukan, dan alasan pemilihan label]\n\nKesimpulan:\nLabel: [NamaLabel].","Komentar: 'Heboh! Pemuda Bakar Mobil Mercedes Karena Buatan Prancis, Padahal Aslinya...';\n\nArtikel Rujukan: Beredar di media sosial sebuah video yang diklaim memperlihatkan seorang pemuda membakar mobil karena buatan Prancis. Faktanya, klaim adanya pemuda yang membakar mobil miliknya karena mobil tersebut buatan Prancis adalah salah. Dikutip dari Turnbackhoax.id, mobil yang dibakar di video itu adalah Mercedes AMG GT 63 S buatan Jerman. Pria dalam video tersebut bernama Misha atau dikenal sebagai Mikhail Litvin, vlogger asal Rusia. Aksi membakar mobil itu disebabkan oleh rasa kesal karena mobil senilai 13 juta rubel Rusia (Rp 2 miliar) yang dibelinya sering rusak dan keengganan pabrikan untuk menerima tanggung jawab (menanggung biaya perbaikan). Jadi, aksi membakar mobil tersebut tidak ada kaitannya dengan Prancis.","Penjelasan: Ini adalah konten menyesatkan yang mencatut nama negara pembuatan mobil untuk menciptakan narasi yang provokatif dan mengecoh publik.\n\nBerikut adalah beberapa poin penting:\n* Mobil yang dibakar adalah Mercedes AMG GT 63 S, buatan Jerman, bukan Prancis (sumber: Turnbackhoax.id).\n* Pria dalam video tersebut adalah Mikhail Litvin, vlogger asal Rusia, yang membakar mobil karena masalah teknis dan keengganan pabrikan untuk bertanggung jawab.\n* Aksi pembakaran mobil tidak ada hubungannya dengan asal negara pembuatan mobil tersebut.\n\nKesimpulan:\nLabel: Disinformasi."

# Fakta

In [664]:
folderData = Path("Dataset_fakta")
files = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    files.append(df_sementara)

df = pd.concat(files, ignore_index=True)

In [665]:
df_fakta = df[df["is_layak"]==1]

In [666]:
df_fakta = df_fakta.drop(columns=["url", "title", "published_at", "sumber_berita", "label", "is_layak"])
df_fakta["label"] = "Fakta"

In [667]:
df_fakta.head(1)

,text,claim_fakta,cot_analisis_fakta,reasoning_fakta,label
0,"Konsumsi rokok dan minuman beralkohol masyarakat Kabupaten Pangandaran tercatat lebih tinggi dibandingkan belanja ikan dan telur. Kondisi ini mencerminkan adanya kecenderungan prioritas pengeluaran tertentu dalam kelompok konsumsi makanan masyarakat setempat.\nBerdasarkan data Badan Pusat Statistik (BPS) Kabupaten Pangandaran dalam laporan Kabupaten Pangandaran dalam Angka 2025, rokok dan minuman beralkohol diklasifikasikan ke dalam kelompok pengeluaran makanan. Menariknya, alokasi belanja untuk kategori tersebut justru melampaui pengeluaran untuk sumber pangan bergizi seperti ayam, telur, dan ikan.\nMeski demikian, secara umum BPS mencatat bahwa total pengeluaran penduduk Pangandaran untuk konsumsi makanan masih lebih besar dibandingkan pengeluaran non-makanan.\nSCROLL TO CONTINUE WITH CONTENT\nRata-rata pengeluaran per kapita per bulan penduduk Kabupaten Pangandaran pada 2024 tercatat sebesar Rp1.367.729. Dari jumlah tersebut, pengeluaran untuk kelompok makanan mencapai Rp809.992 atau 59,22 persen, sedangkan pengeluaran non-makanan sebesar Rp557.738 atau 40,78 persen.\nJika dibandingkan dengan tahun 2023, proporsi pengeluaran untuk makanan mengalami peningkatan. Pada 2023, pengeluaran makanan tercatat sebesar 55,72 persen, lalu naik menjadi 59,22 persen pada 2024.\nPada kelompok makanan tahun 2024, pengeluaran terbesar dialokasikan untuk makanan dan minuman jadi sebesar 15,56 persen, diikuti kelompok kacang-kacangan, buah-buahan, dan sayuran sebesar 10,51 persen, serta padi-padian dan umbi-umbian sebesar 9,59 persen.\nSementara itu, pengeluaran untuk kelompok ikan, daging, telur, dan susu hanya mencapai 8,76 persen, lebih rendah dibandingkan pengeluaran untuk rokok dan tembakau yang mencapai 9,20 persen. Pada 2023, proporsi belanja rokok dan tembakau tercatat sebesar 8,81 persen dan meningkat pada 2024.\nPada kelompok non-makanan tahun 2024, pengeluaran terbesar dialokasikan untuk perumahan, bahan bakar, penerangan, dan air dengan kontribusi 21,45 persen dari total pengeluaran. Sebaliknya, pengeluaran paling kecil terdapat pada keperluan pesta dan upacara adat yang hanya mencapai 1,13 persen.\nJika dibandingkan dengan tahun 2023, proporsi pengeluaran non-makanan secara keseluruhan mengalami penurunan. Pada 2023, pengeluaran non-makanan tercatat sebesar 23,28 persen, sedangkan pada 2024 tercatat sebesar 40,78 persen seiring meningkatnya total nilai pengeluaran masyarakat.\nPengeluaran untuk aneka barang dan jasa, biaya pendidikan, serta kesehatan tergolong relatif rendah. Pada 2023, kelompok ini menyumbang 9,03 persen dari total pengeluaran, kemudian menurun menjadi 8,82 persen pada 2024. Pengeluaran untuk pakaian dan alas kaki tercatat sebesar 2,80 persen pada 2023 dan turun menjadi 2,46 persen pada 2024.\nTingginya proporsi pengeluaran untuk makanan menunjukkan bahwa tingkat kesejahteraan masyarakat Kabupaten Pangandaran masih tergolong rendah, karena sebagian besar pendapatan digunakan untuk memenuhi kebutuhan dasar.\nNamun, data BPS juga menunjukkan bahwa pada kelompok pengeluaran 20 persen teratas, pola konsumsi mulai bergeser. Pada kelompok ini, pengeluaran non-makanan cenderung lebih besar dibandingkan pengeluaran makanan, yang mengindikasikan peningkatan taraf hidup dan diversifikasi kebutuhan.","Wah, orang di Pangandaran belanjanya lebih banyak buat rokok daripada makanan bergizi kayak ikan dan telur!","[Data BPS menunjukkan bahwa pengeluaran untuk rokok dan minuman beralkohol di Kabupaten Pangandaran mencapai 9,20 persen dari total pengeluaran makanan., Pengeluaran untuk ikan, daging, telur, dan susu hanya 8,76 persen, lebih rendah dari pengeluaran untuk rokok dan tembakau., Total pengeluaran per kapita per bulan penduduk Pangandaran pada 2024 tercatat sebesar Rp1.367.729, dengan pengeluaran untuk makanan mencapai Rp809.992 atau 59,22 persen.]","Klaim ini sesuai dengan data BPS yang menunjukkan pengeluaran untuk rokok dan minuman beralkohol lebih tinggi dibandingkan pengeluaran untuk ikan, daging, telur, dan susu di Kabupaten Pangandaran.",Fakta

In [668]:
len(df_fakta)

7790

In [669]:
df_fakta = df_fakta[:1500]

In [670]:
df_fakta.isna().sum()

text                  0
claim_fakta           0
cot_analisis_fakta    0
reasoning_fakta       0
label                 0
dtype: int64

In [671]:
df_fakta = df_fakta.to_dict("records")

In [673]:
import json
import random

def generate_sft_dataset_with_context(raw_data_list, instructions, output_file):
    dataset = [] # gw ganti netral bae dah, biar konsisten sama tim sebelah
    label = "Netral" 
    for data in raw_data_list:
        instruct = instructions
        claim = data.get("claim_fakta", "")
        berita = data.get("text", "") 
        reasoning = data.get("reasoning_fakta", "")
        cot_list = data.get("cot_analisis_fakta", [])
        
        # Susun poin-poin fakta
        fakta_points = "\n".join([f"* {point}" for point in cot_list])
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Komentar: '{claim}';\n\n"
            f"Artikel Rujukan: {berita}"
        )

        full_output = (
            f"Penjelasan: {reasoning}\n\n"
            f"Berikut adalah beberapa poin penting:\n"
            f"{fakta_points}\n\n"
            f"Kesimpulan:\n"
            f"Label: {label}."
        )
        
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(df_fakta, instructiones, "fakta.jsonl")

Berhasil membuat 1500 data dengan konteks berita di fakta.jsonl

In [674]:
tes_fakta = pd.read_json("fakta.jsonl", lines=True)

In [675]:
tes_fakta.head(1)

,instruction,input,output
0,"Anda adalah sistem ahli yang mengklasifikasikan [Komentar] media sosial Indonesia ke dalam label resmi: [Netral, Disinformasi, Fitnah, Ujaran Kebencian], dengan dibantu [Artikel Rujukan] jika tersedia.\n\nAturan Penalaran:\n\n1. Prioritaskan analisis pada [Komentar] untuk menentukan apakah teks tersebut mengandung klaim faktual yang memerlukan verifikasi, termasuk indikasi ujaran kebencian/SARA, atau sekadar interaksi santai.\n2. Jika [Komentar] mengandung unsur serangan atau penghinaan berdasarkan identitas (SARA, ras, etnis, agama, gender, disabilitas), langsung klasifikasikan sebagai 'Ujaran Kebencian' dan ABAIKAN [Artikel Rujukan].\n3. Jika tidak mengandung ujaran kebencian, gunakan [Artikel Rujukan] (atau pengetahuan internal jika rujukan kosong) untuk menilai klaim:\n* Netral: Konten faktual, opini, ekspresi emosional, kritik kebijakan, atau interaksi normal yang tidak mengandung kebohongan spesifik untuk menjatuhkan reputasi.\n* Disinformasi: Informasi keliru/menyesatkan yang berpotensi meresahkan masyarakat atau memicu polarisasi.\n* Fitnah: Tuduhan atau klaim bohong yang spesifik dan sengaja dibuat untuk menyerang karakter, kehormatan, atau reputasi individu/kelompok.\n\n**Format Output WAJIB (Jangan diubah):**\nPenjelasan:\n[Tulis analisis ringkas terhadap Komentar, perbandingannya dengan Artikel Rujukan, dan alasan pemilihan label]\n\nKesimpulan:\nLabel: [NamaLabel].","Komentar: 'Wah, orang di Pangandaran belanjanya lebih banyak buat rokok daripada makanan bergizi kayak ikan dan telur!';\n\nArtikel Rujukan: Konsumsi rokok dan minuman beralkohol masyarakat Kabupaten Pangandaran tercatat lebih tinggi dibandingkan belanja ikan dan telur. Kondisi ini mencerminkan adanya kecenderungan prioritas pengeluaran tertentu dalam kelompok konsumsi makanan masyarakat setempat.\nBerdasarkan data Badan Pusat Statistik (BPS) Kabupaten Pangandaran dalam laporan Kabupaten Pangandaran dalam Angka 2025, rokok dan minuman beralkohol diklasifikasikan ke dalam kelompok pengeluaran makanan. Menariknya, alokasi belanja untuk kategori tersebut justru melampaui pengeluaran untuk sumber pangan bergizi seperti ayam, telur, dan ikan.\nMeski demikian, secara umum BPS mencatat bahwa total pengeluaran penduduk Pangandaran untuk konsumsi makanan masih lebih besar dibandingkan pengeluaran non-makanan.\nSCROLL TO CONTINUE WITH CONTENT\nRata-rata pengeluaran per kapita per bulan penduduk Kabupaten Pangandaran pada 2024 tercatat sebesar Rp1.367.729. Dari jumlah tersebut, pengeluaran untuk kelompok makanan mencapai Rp809.992 atau 59,22 persen, sedangkan pengeluaran non-makanan sebesar Rp557.738 atau 40,78 persen.\nJika dibandingkan dengan tahun 2023, proporsi pengeluaran untuk makanan mengalami peningkatan. Pada 2023, pengeluaran makanan tercatat sebesar 55,72 persen, lalu naik menjadi 59,22 persen pada 2024.\nPada kelompok makanan tahun 2024, pengeluaran terbesar dialokasikan untuk makanan dan minuman jadi sebesar 15,56 persen, diikuti kelompok kacang-kacangan, buah-buahan, dan sayuran sebesar 10,51 persen, serta padi-padian dan umbi-umbian sebesar 9,59 persen.\nSementara itu, pengeluaran untuk kelompok ikan, daging, telur, dan susu hanya mencapai 8,76 persen, lebih rendah dibandingkan pengeluaran untuk rokok dan tembakau yang mencapai 9,20 persen. Pada 2023, proporsi belanja rokok dan tembakau tercatat sebesar 8,81 persen dan meningkat pada 2024.\nPada kelompok non-makanan tahun 2024, pengeluaran terbesar dialokasikan untuk perumahan, bahan bakar, penerangan, dan air dengan kontribusi 21,45 persen dari total pengeluaran. Sebaliknya, pengeluaran paling kecil terdapat pada keperluan pesta dan upacara adat yang hanya mencapai 1,13 persen.\nJika dibandingkan dengan tahun 2023, proporsi pengeluaran non-makanan secara keseluruhan mengalami penurunan. Pada 2023, pengeluaran non-makanan tercatat sebesar 23,28 persen, sedangkan pada 2024 tercatat sebesar 40,78 persen seiring meningkatnya total nilai pengeluaran masyarakat.\nPengeluaran untuk aneka barang dan jasa, biaya pendidikan, serta kesehatan tergolong relatif rendah. Pada 2023, kelompok ini menyumbang 9,03 persen dari total pengeluaran, kemudian menurun menjadi 8,82 persen pada 2024. Pengeluaran untuk pakaian dan alas kaki tercatat sebesar 2,80 persen pada 2023 dan turun menjadi 2,46 persen pada 2024.\nTingginya proporsi pengeluaran untuk makanan menunjukkan bahwa tingkat kesejahteraan masyarakat Kabupaten Pangandaran masih tergolong rendah, karena sebagian besar pendapatan digunakan untuk memenuhi kebutuhan dasar.\nNamun, data BPS juga menunjukkan bahwa pada kelompok pengeluaran 20 persen teratas, pola konsumsi mulai bergeser. Pada kelompok ini, pengeluaran non-makanan cenderung lebih besar dibandingkan pengeluaran makanan, yang mengindikasikan peningkatan taraf hidup dan diversifikasi kebutuhan.","Penjelasan: Klaim ini sesuai dengan data BPS yang menunjukkan pengeluaran untuk rokok dan minuman beralkohol lebih tinggi dibandingkan pengeluaran untuk ikan, daging, telur, dan susu di Kabupaten Pangandaran.\n\nBerikut adalah beberapa poin penting:\n* Data BPS menunjukkan bahwa pengeluaran untuk rokok dan minuman beralkohol di Kabupaten Pangandaran mencapai 9,20 persen dari total pengeluaran makanan.\n* Pengeluaran untuk ikan, daging, telur, dan susu hanya 8,76 persen, lebih rendah dari pengeluaran untuk rokok dan tembakau.\n* Total pengeluaran per kapita per bulan penduduk Pangandaran pada 2024 tercatat sebesar Rp1.367.729, dengan pengeluaran untuk makanan mencapai Rp809.992 atau 59,22 persen.\n\nKesimpulan:\nLabel: Netral."

# Non-DFK

In [676]:
folderData = Path("Dataset_nonDFK")
komentar = []


for file in folderData.glob("*.jsonl"):
    if file.name == "panduan_komunitas.jsonl":
        continue
    
    df_sementara = pd.read_json(file, lines=True)
    komentar.append(df_sementara)

df_nondfk = pd.concat(komentar, ignore_index=True)

In [677]:
df_nondfk["gaya_komentar"].unique()

array(['brutal', 'sarkas', 'simpati', 'enthusiastis', 'halus', 'gaul',
       'ceplas-ceplos', 'nyeletuk', 'enthusiast', 'kebingungan',
       'harapan', 'irasional', 'penasaran', 'reflektif', 'simpatik',
       'informasi', 'alay', 'positif', 'puji', 'empati', 'setuju',
       'harap', 'peduli', 'kaget', 'pikir', 'khawatir', 'hype', 'heran',
       'kesal', 'neutral', 'peringatan', 'netral', 'sarcastik', 'pemuji',
       'sentimental', 'gembira', 'reaksi', 'humor', 'informal',
       'emosional', 'optimis', 'antusias', 'senang', 'normal', 'casual',
       'memuji', 'kagum', 'bujuk rayu', 'mengagumi', 'opinif', 'serius',
       'ringan', 'sedih', 'simpatetik', 'terima kasih', 'curious',
       'stereotip', 'generalisasi kebiasaan buruk', 'celetukan', 'ramah',
       'informatif', 'dukungan', 'ringkas', 'biasa', 'nasihat',
       'pendukung', 'kecewa', 'terkejut', 'keheranan', 'hangat',
       'terkesan', 'singkat', 'praktis', 'resah', 'nostalgia', 'cemas',
       'skeptis', 'tertarik', 'pertanyaan', 'saran', 'empathetic',
       'sarcastic', 'uforia', 'non-stereotip', 'insinuasi',
       'sharing info', 'tanya dong', 'ungkapan kagum',
       'ungkapan antusias', 'sharing', 'seru', 'tag teman',
       'ungkapan kaget', 'dorongan semangat', 'ekspresi kaget',
       'refleksi', 'pembantu', 'info dong', 'nyimak',
       'sharing pengalaman', 'komentar santai', 'ceplas ceplos', 'pujian',
       'komentar nyimak', 'opini', 'expressing concern',
       'expressing hope', 'ekspresi keresahan', 'ekspresi simpati',
       'apresiasi', 'tanya', 'syukur', 'reaksi kaget'], dtype=object)

In [678]:
df_nondfk[df_nondfk["gaya_komentar"] =="stereotip"].head(1)

,title,text,claim_nonDFK,gaya_komentar,is_layak,cot_analisis,reasoning_nonDFK
3225,Film Terlaris Indonesia Skenarionya Ditulis Perempuan,"Di semester pertama tahun 2025 ini, Indonesia memiliki film terlaris yang mampu menggeser posisi film lainnya, yaitu Jumbo. Film animasi pertama di Indonesia ini berhasil meraih box office, sekaligus menjadi film terlaris di Asia Tenggara.\nDi balik cerita yang menyentuh dan hangat, ada sosok seorang perempuan bernama Widya Arifianti, yang bertindak sebagai penulis kenario.\nTak hanya Widya Arifianti sebagai penulis skenario Jumbo, ada sembilan perempuan lainnya yang menulis film laris di Indonesia.","bjir, gue kagum banget sama Widya, nulis skenario keren banget!",stereotip,1,"[Komentar ini hanya mengungkapkan rasa kagum terhadap Widya Arifianti tanpa menambahkan klaim fakta baru., Komentar tidak mengandung fitnah atau tuduhan tanpa bukti., Komentar tidak mengandung ujaran kebencian atau serangan SARA.]","Komentar ini bersifat ekspresif dan hanya mengekspresikan rasa kagum, tanpa menambahkan informasi atau klaim baru. Tidak ada unsur DFK."

In [679]:
len(df_nondfk[df_nondfk["is_layak"] == 1])

6663

In [680]:
layak = df_nondfk[df_nondfk["is_layak"] == 1]
layak["label"] = "Bukan DFK" # di kemudian hari jadi Netral

C:\Users\Dipo\AppData\Local\Temp\ipykernel_134436\2944450594.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layak["label"] = "Bukan DFK" # di kemudian hari jadi Netral

In [681]:
layak = layak[:1500]

In [682]:
layak.head(1)

,title,text,claim_nonDFK,gaya_komentar,is_layak,cot_analisis,reasoning_nonDFK,label
0,Perubahan Positif saat Perempuan Mulai Fokus Perbaiki Diri,"Perempuan sering kali mengalami overthinking atas beragam hal dihadapinya. Mulai dari menjalani kehidupan sehari-hari, melakoni pekerjaan, urusan percintaan, dan lain-lain, bisa membuat mereka begitu kewalahan.\nPadahal, tidak semuanya perlu dipikirkan secara rumit karena memang pada kenyataannya sebagian merupakan hal yang sederhana saja. Namun, kebiasaan overthinking semacam ini tentu tidak muncul begitu saja.\nKaum hawa sering kali belum bisa memegang prinsipnya secara kuat, sehingga mudah terpengaruh ucapan orang lain yang bahkan belum tentu mengerti apa yang disampaikannya. Akibatnya, mereka jadi bingung dan sulit untuk mendapatkan ketenangan.\nOleh karena itu, para perempuan harus belajar untuk mulai fokus pada diri sendiri karena keputusan ini akan menciptakan beragam perubahan positif sebagai berikut.","anjir betul, gw udh mulai fokus ke diri sendiri, beneran beds banget!",brutal,1,"[Komentar ini hanya menyampaikan perasaan pribadi dan pengalaman sendiri tanpa menambahkan informasi baru., Komentar tidak mengandung klaim fakta baru atau pelintiran berita., Komentar tidak mengandung fitnah atau ujaran kebencian., Komentar bersifat ekspresif dan mendukung konten artikel tanpa menimbulkan kontroversi.]","Komentar ini hanya menyampaikan pengalaman pribadi tentang fokus diri sendiri dan perubahan positif yang dirasakan. Tidak ada klaim baru atau informasi yang ditambahkan, serta tidak mengandung fitnah atau ujaran kebencian.",Bukan DFK

In [683]:
layak.isna().sum()

title               0
text                0
claim_nonDFK        0
gaya_komentar       0
is_layak            0
cot_analisis        0
reasoning_nonDFK    0
label               0
dtype: int64

In [684]:
layak = layak.to_dict("records")

In [685]:
import json
import random

def generate_sft_dataset_with_context(raw_data_list, instructions, output_file):
    dataset = []
    label = "Netral" 
    
    for data in raw_data_list:
        instruct = instructions
        claim = data.get("claim_nonDFK", "")
        teks = data.get("text", "") 
        reasoning = data.get("reasoning_nonDFK", "")
        cot_list = data.get("cot_analisis", [])
        
        fakta_points = "\n".join([f"* {point}" for point in cot_list])
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Komentar: '{claim}';\n\n"
            f"Artikel Rujukan: {teks}"
        )

        full_output = (
            f"Penjelasan: {reasoning}\n\n"
            f"Berikut merupakan alasan alasannya:\n"
            f"{fakta_points}\n\n"
            f"Kesimpulan:\n"
            f"Label: {label}."
        )
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(layak, instructiones, "nonDFK.jsonl")

Berhasil membuat 1500 data dengan konteks berita di nonDFK.jsonl

In [686]:
tes_nonDFK = pd.read_json("nonDFK.jsonl", lines=True)

In [687]:
tes_nonDFK.head(1)

,instruction,input,output
0,"Anda adalah sistem ahli yang mengklasifikasikan [Komentar] media sosial Indonesia ke dalam label resmi: [Netral, Disinformasi, Fitnah, Ujaran Kebencian], dengan dibantu [Artikel Rujukan] jika tersedia.\n\nAturan Penalaran:\n\n1. Prioritaskan analisis pada [Komentar] untuk menentukan apakah teks tersebut mengandung klaim faktual yang memerlukan verifikasi, termasuk indikasi ujaran kebencian/SARA, atau sekadar interaksi santai.\n2. Jika [Komentar] mengandung unsur serangan atau penghinaan berdasarkan identitas (SARA, ras, etnis, agama, gender, disabilitas), langsung klasifikasikan sebagai 'Ujaran Kebencian' dan ABAIKAN [Artikel Rujukan].\n3. Jika tidak mengandung ujaran kebencian, gunakan [Artikel Rujukan] (atau pengetahuan internal jika rujukan kosong) untuk menilai klaim:\n* Netral: Konten faktual, opini, ekspresi emosional, kritik kebijakan, atau interaksi normal yang tidak mengandung kebohongan spesifik untuk menjatuhkan reputasi.\n* Disinformasi: Informasi keliru/menyesatkan yang berpotensi meresahkan masyarakat atau memicu polarisasi.\n* Fitnah: Tuduhan atau klaim bohong yang spesifik dan sengaja dibuat untuk menyerang karakter, kehormatan, atau reputasi individu/kelompok.\n\n**Format Output WAJIB (Jangan diubah):**\nPenjelasan:\n[Tulis analisis ringkas terhadap Komentar, perbandingannya dengan Artikel Rujukan, dan alasan pemilihan label]\n\nKesimpulan:\nLabel: [NamaLabel].","Komentar: 'anjir betul, gw udh mulai fokus ke diri sendiri, beneran beds banget!';\n\nArtikel Rujukan: Perempuan sering kali mengalami overthinking atas beragam hal dihadapinya. Mulai dari menjalani kehidupan sehari-hari, melakoni pekerjaan, urusan percintaan, dan lain-lain, bisa membuat mereka begitu kewalahan.\nPadahal, tidak semuanya perlu dipikirkan secara rumit karena memang pada kenyataannya sebagian merupakan hal yang sederhana saja. Namun, kebiasaan overthinking semacam ini tentu tidak muncul begitu saja.\nKaum hawa sering kali belum bisa memegang prinsipnya secara kuat, sehingga mudah terpengaruh ucapan orang lain yang bahkan belum tentu mengerti apa yang disampaikannya. Akibatnya, mereka jadi bingung dan sulit untuk mendapatkan ketenangan.\nOleh karena itu, para perempuan harus belajar untuk mulai fokus pada diri sendiri karena keputusan ini akan menciptakan beragam perubahan positif sebagai berikut.","Penjelasan: Komentar ini hanya menyampaikan pengalaman pribadi tentang fokus diri sendiri dan perubahan positif yang dirasakan. Tidak ada klaim baru atau informasi yang ditambahkan, serta tidak mengandung fitnah atau ujaran kebencian.\n\nBerikut merupakan alasan alasannya:\n* Komentar ini hanya menyampaikan perasaan pribadi dan pengalaman sendiri tanpa menambahkan informasi baru.\n* Komentar tidak mengandung klaim fakta baru atau pelintiran berita.\n* Komentar tidak mengandung fitnah atau ujaran kebencian.\n* Komentar bersifat ekspresif dan mendukung konten artikel tanpa menimbulkan kontroversi.\n\nKesimpulan:\nLabel: Netral."

# Gabungin non-dfk dan fakta menjadi Netral
## sama tambahin data

In [828]:
folderData = Path("Dataset_yt")
komentar = []


for file in folderData.glob("*.csv"):
    df_sementara = pd.read_csv(file)
    komentar.append(df_sementara)

df_komentaryt = pd.concat(komentar, ignore_index=True)

In [829]:
import re
def bersih_(teks):
    bersih = re.sub(r'_{2,}', ' ', teks)

    return " ".join(bersih.split())

df_komentaryt["komentar_asli"] = df_komentaryt["komentar_asli"].apply(bersih_)

In [830]:
kalimat_target = "Biadab mereka zionis apalagi mereka pendukung nya"
alasan = """Terdeteksi Ujaran Kebencian / SARA: Kata "Biadab" adalah kata yang sangat kuat dan dehumanizing. 
Artinya brutal, tidak beradab, savage. Ini bukan kritik biasa, 
tapi langsung menyerang martabat/kemanusiaan kelompok tersebut. 
Frasa "mereka zionis" + "mereka pendukungnya" melakukan generalisasi massal."""

df_komentaryt.loc[df_komentaryt["komentar_asli"] == kalimat_target, "alasan_non_dfk"] = alasan

In [831]:
import numpy as np
kondisi = df_komentaryt['alasan_non_dfk'].str.contains("Terdeteksi Ujaran Kebencian|Terdeteksi unsur seksisme", na=False)
df_komentaryt['kategori_flag'] = np.where(kondisi, "Ujaran Kebencian", "Netral")

In [832]:
df_komentaryt[df_komentaryt["komentar_asli"].str.contains('Tahun lalu gelut krn nempel nempel di photobox trs disogok bunga damai bbrp hari besoknya malah duduk sampingan sama si perek lanjut gelut part 2 akwoakwoakwo makasih bunganya')]

,komentar_asli,mengandung_klaim,search_query,alasan_non_dfk,kategori_flag
2964,Tahun lalu gelut krn nempel nempel di photobox trs disogok bunga damai bbrp hari besoknya malah duduk sampingan sama si perek lanjut gelut part 2 akwoakwoakwo makasih bunganya,False,TIDAK_BUTUH_RAG,"Terdeteksi Ujaran Kebencian / SARA karena penggunaan istilah ""si perek"" yang bersifat seksis dan merendahkan perempuan",Ujaran Kebencian

In [833]:
netral = df_komentaryt[df_komentaryt["kategori_flag"] == "Netral"]
hate = df_komentaryt[df_komentaryt["kategori_flag"] == "Ujaran Kebencian"] # ini nanti di digabung ke dataset ujaran kebencian

netral = netral[netral["search_query"] == "TIDAK_BUTUH_RAG"]
hate = hate[hate["search_query"] == "TIDAK_BUTUH_RAG"]

print(len(netral))
print(len(hate))

3589
484

In [834]:
netral[netral["alasan_non_dfk"].str.contains("agama")]

,komentar_asli,mengandung_klaim,search_query,alasan_non_dfk,kategori_flag
317,Ngga bener inihmemberi BUKAN INVESTASImemberi adalah bagian Dr Iman yg seharus nya dikeluarkan dgn hati tulus tanpa meminta timbal balik,False,TIDAK_BUTUH_RAG,Hanya berupa penjelasan opini keagamaan tentang memberi tanpa muatan klaim fakta,Netral
406,Memang alkitab adalah sumber segala ilmu Ibu segala pengetahuan,False,TIDAK_BUTUH_RAG,Berupa pernyataan keyakinan agama tanpa klaim informasi aktual yang perlu diverifikasi,Netral
425,Dari sini Qta Bisa Belajar Bahwa Berkorban Belajar IKHLAS untung Qta di suruh Kambing Coba yg qta Cintai di korbankan Pasti byk orang Gak mampu Beli Hp harga 3jt an ke atas mampu beli motor bisa ketika di suru beli KAMBING Buat Berkorban Di Bagikan bilang gak MAMPU,False,TIDAK_BUTUH_RAG,Hanya berupa refleksi atau nasihat keagamaan tanpa klaim fakta yang perlu diverifikasi,Netral
456,Tujuan hidup kita beribadah kpd Allah,False,TIDAK_BUTUH_RAG,Berupa pernyataan keyakinan agama pribadi tanpa klaim yang perlu diverifikasi,Netral
551,Rahasia Khusyuk Para Sahabat Nabi ﷺ Kita sering bertanya Mengapa sholat para sahabat mampu mengubah dunia Mengapa mereka sedikit jumlahnya tetapi imannya mengguncang langit Jawabannya bukan pada lamanya sholat tetapi pada khusyuknya hati mereka Para sahabat tidak hanya melakukan sholat mereka hidup di dalam sholat 1 Mereka Masuk Sholat Seolah Ini Sholat Terakhir Sebelum takbir para sahabat sudah menyiapkan hati Diriwayatkan bahwa sebagian sahabat berkata Jika aku berdiri sholat aku menganggap tidak akan hidup setelahnya Karena itu tak ada pikiran dunia tak ada rencana setelah salam hanya ada Allah Mereka tidak menunggu khusyuk datang Mereka memutus dunia sebelum sholat dimulai 2 Hati Mereka Sudah Bersama Allah Sebelum Takbir Para sahabat tidak langsung berdiri sholat setelah sibuk dunia Mereka berwudhu perlahan memperbanyak dzikir menenangkan hati Sebagian tabiin berkata Sholat dimulai sejak wudhu bukan sejak takbir Karena hati perlu perjalanan untuk sampai kepada Allah 3 Mereka Memahami Setiap Bacaan Saat membaca AlFatihah mereka sadar Allah sedang menjawab Bukan sekadar membaca tetapi dialog langsung dengan Rabb semesta Itulah sebabnya ayat yang sama tidak pernah terasa membosankan bagi mereka Karena setiap sholat adalah percakapan baru dengan Allah 4 Tubuh Mereka Diam Hati Mereka Hidup Dikisahkan Ada sahabat yang terkena anak panah saat perang Mereka menunggu sampai ia sholat untuk mencabut panah itu karena saat sholat ia tidak merasakan sakit dunia Mengapa Karena hatinya tenggelam dalam kehadiran Allah 5 Mereka Takut Sholatnya Tidak Diterima Walau dijamin surga para sahabat tetap menangis setelah sholat Bukan karena lelah tetapi karena takut Apakah Allah menerimanya Inilah rahasia terbesar khusyuk orang yang merasa sholatnya sudah baik akan kehilangan khusyuk orang yang takut ditolak akan terus memperbaikinya 6 Dunia Kecil di Mata Mereka Khusyuk bukan teknik Khusyuk adalah hasil dari hati yang mengenal Allah Saat dunia kecil Allah menjadi besar Saat Allah besar segala gangguan mengecil Rahasia Intinya Para sahabat tidak mencari cara khusyuk Mereka mencintai Allah merindukan pertemuan denganNya merasa sholat adalah tempat pulang jiwa Karena itu sholat bukan kewajiban berat tetapi kenikmatan terbesar Renungan Bayangkan Jika sahabat yang dijamin surga saja masih gemetar saat sholat lalu bagaimana dengan kita yang penuh dosa Mungkin masalah kita bukan kurang waktu tetapi belum benarbenar sadar siapa yang kita temui dalam sholat Wallāhu alam bishshawāb,False,TIDAK_BUTUH_RAG,Hanya berupa konten dakwah atau renungan agama tanpa klaim fakta aktual yang perlu diverifikasi,Netral
...,...,...,...,...,...
4519,Ngga boleh gitu mas Kafir ato enggak biar Tuhan yg urus Kita ngurus pikiran ucapan tulisan dan perilaku kita sj Dlm Hindu itu disebut Tri Kaya Parisudha Pikiran ucapan dan perbuatan hrs baik Kita tdk bisa me,False,TIDAK_BUTUH_RAG,Merupakan diskusi mengenai ajaran agama dan toleransi tanpa klaim fakta yang dapat diverifikasi,Netral
4557,kucingku islam semua tapi yang 1 rajin sholat dan ngaji yang 1 sholatnya boling bolong yang 1 islam ktp gatau dah gimana maunya enih yang islam ktp soalna dah jarang sholat,False,TIDAK_BUTUH_RAG,Merupakan ungkapan humor mengenai kucing dengan analogi agama tanpa muatan klaim fakta,Netral
4570,p orang2 yg naksir nana adu sini udh pernah dikasih pap tanpa minta belom hheheh hai cantik makasih papnya,False,TIDAK_BUTUH_RAG,"Komentar ini berisi candaan vulgar dan interaksi santai tanpa klaim fakta maupun unsur rasisme, seksisme, atau hinaan agama",Netral
4573,gemesan pake krudung tp sayang aku kris10,False,TIDAK_BUTUH_RAG,"Komentar ini menyatakan pernyataan pribadi secara humoris tanpa klaim fakta maupun unsur rasisme, seksisme, atau hinaan agama",Netral
4659,Cincang pemimpin dan wakilnya yg berutak ogj yg gk pecus mimpin negara cuma mulut donol yg keras tapi palsu bohonngdiatas namakan rakyat,False,TIDAK_BUTUH_RAG,"Berupa kritik dan hinaan politik terhadap pemimpin tanpa klaim fakta spesifik atau unsur rasisme, seksisme, dan hinaan agama.",Netral

In [835]:
netral.head(1)

,komentar_asli,mengandung_klaim,search_query,alasan_non_dfk,kategori_flag
0,BEM bayaran singaparna Investor asing sedang keluar Eh dia malah bikin rusuh bikin kacau aja nih Belajar aja yang benar BEM,False,TIDAK_BUTUH_RAG,Hanya berupa opini dan tuduhan tanpa klaim fakta spesifik yang bisa diverifikasi,Netral

In [836]:
datatambahan = netral.to_dict("records")

In [837]:
import json
import random

def generate_sft_dataset_with_context(raw_data_list, instructions, output_file):
    dataset = []
    label = "Netral" 
    
    for data in raw_data_list:
        instruct = instructions
        claim = data.get("komentar_asli", "")
        reasoning = data.get("alasan_non_dfk", "")
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Komentar: '{claim}';\n\n"
        )

        full_output = (
            f"Penjelasan: {reasoning}\n\n"
            f"Kesimpulan:\n"
            f"Label: {label}."
        )
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(datatambahan, instructiones, "netral.jsonl")

Berhasil membuat 3589 data dengan konteks berita di netral.jsonl

In [838]:
nonDFK = pd.read_json("nonDFK.jsonl", lines=True)
fakta = pd.read_json("fakta.jsonl", lines=True)
netral = pd.read_json("netral.jsonl", lines=True)

In [839]:
import pandas as pd

# Load data kamu
netral2 = pd.read_json("netrals.jsonl", lines=True)

def bersihkan_output(teks):
    if isinstance(teks, str):
        teks = teks.replace("**", "")
        
        teks = teks.replace("\n*", "")

        target_keyword = "Label: Netral."
        
        # ambil teks berdasarkan keyword, ambil bagian sebelum keyword (indeks 0)
        if target_keyword in teks:
            teks_bersih = teks.split(target_keyword)[0]
            return (teks_bersih + target_keyword).strip()
            
    return teks

netral2["output"] = netral2["output"].apply(bersihkan_output)

In [840]:
dataNetral = pd.concat([nonDFK, fakta, netral, netral2], ignore_index=True)
dataNetral.to_json("dataNetral.jsonl", orient='records', lines=True)

In [841]:
dataNetral.tail(1)

,instruction,input,output
6638,"\nAnda adalah sistem ahli analisis konten media sosial Indonesia yang mengklasifikasikan teks ke dalam salah satu label: [Fakta, Disinformasi, Fitnah, Ujaran Kebencian, Bukan DFK] dan memberikan alasan objektif. \n\nAnda akan diberikan [Komentar] dan kadang-kadang disertai [Artikel Rujukan] jika tersedia. \n\nIkuti aturan penalaran berikut:\n1. Prioritaskan analisis teks pada [Komentar] terlebih dahulu untuk menentukan apakah teks tersebut mengandung klaim faktual yang membutuhkan verifikasi, berupa ujaran kebencian/SARA, atau sekadar interaksi santai.\n2. Jika [Komentar] dinilai sebagai 'Bukan DFK' (hanya ekspresi, sapaan, request) atau 'Ujaran Kebencian' (rasisme, seksisme, hinaan agama), Anda harus langsung menentukan label tersebut dan mengabaikan [Artikel Rujukan] meskipun artikel tersebut ada.\n3. Gunakan [Artikel Rujukan] HANYA untuk membantu membedakan label 'Fakta', 'Disinformasi', atau 'Fitnah' jika [Komentar] terbukti memuat klaim informasi spesifik. Jika artikel rujukan kosong atau tidak relevan dengan klaim, gunakan pengetahuan internal Anda secara objektif.\n\nFormat output WAJIB:\nLabel: **[NamaLabel]**\nPenjelasan: [Tulis alasan penalaran Anda di sini secara detail dan kontekstual]\n","Komentar: 'Tetep fokus suarakan kemanusiaan dan maki kelakuan jahat Israel di timeline, jangan biarin isu ini tenggelam!';\n\n",Penjelasan: Hanya berupa ajakan konsisten untuk menjaga atensi publik dan terus menyuarakan isu kemanusiaan di lini masa.\n\nKesimpulan:\nLabel: Netral.

# Buat Dataset Ujaran Kebencian

In [842]:
folderData = Path("Dataset_UjaranKebencian")
komentar = []


for file in folderData.glob("*.jsonl"):
    if file.name == "panduan_komunitas.jsonl":
        continue
    
    df_sementara = pd.read_json(file, lines=True)
    komentar.append(df_sementara)

df_ujarankb = pd.concat(komentar, ignore_index=True)

In [843]:
df_ujarankb.isna().sum()

claim_disinformasi               0
target                           0
label                            0
jenis                            0
isExplicit                       4
IDPelanggaran                   13
cot_analisis                     4
reasoning_ujaran_kebencian       5
IDPelangguaran                7301
IDPelangguuran                7304
IDPelangguan                  7300
dtype: int64

In [844]:
df_ujarankb = df_ujarankb.drop(df_ujarankb[df_ujarankb["reasoning_ujaran_kebencian"].isna()].index)

In [845]:
eksplisit = df_ujarankb[df_ujarankb["isExplicit"] == 1]
print(len(eksplisit))

5268

In [846]:
eksplisit.isna().sum()

claim_disinformasi               0
target                           0
label                            0
jenis                            0
isExplicit                       0
IDPelanggaran                    7
cot_analisis                     0
reasoning_ujaran_kebencian       0
IDPelangguaran                5265
IDPelangguuran                5268
IDPelangguan                  5264
dtype: int64

In [847]:
# semua yang 5268 kita drop
eksplisit = eksplisit.drop(columns=["IDPelangguuran"])

In [848]:
eksplisit.isna().sum()

claim_disinformasi               0
target                           0
label                            0
jenis                            0
isExplicit                       0
IDPelanggaran                    7
cot_analisis                     0
reasoning_ujaran_kebencian       0
IDPelangguaran                5265
IDPelangguan                  5264
dtype: int64

In [849]:
eksplisit["IDPelangguaran"] = eksplisit["IDPelangguaran"].fillna(eksplisit["IDPelangguan"])
eksplisit["IDPelanggaran"] = eksplisit["IDPelanggaran"].fillna(eksplisit["IDPelangguaran"])

In [850]:
eksplisit.insert(0, "claim_ujaranKebencian", eksplisit["claim_disinformasi"])

In [851]:
eksplisit = eksplisit.drop(columns=["IDPelangguaran", "IDPelangguan", "claim_disinformasi"])

In [852]:
len(eksplisit)

5268

In [853]:
eksplisit.head(1)

,claim_ujaranKebencian,target,label,jenis,isExplicit,IDPelanggaran,cot_analisis,reasoning_ujaran_kebencian
0,"etnis tionghoa emang ges licik main uang panas dr china, ngebulu aja lo semua!",etnis tionghoa,Ujaran Kebencian,komentar,1.0,HS_STEREOTYPE,"[Claim menggunakan kata 'ges licik' yang merendahkan etnis Tionghoa secara kolektif., Menghubungkan perilaku 'main uang panas' dengan etnis Tionghoa, seolah-olah seluruh anggota etnis tersebut memiliki sifat licik., Penggunaan kata 'ngebulu aja lo semua' menunjukkan generalisasi negatif terhadap seluruh anggota etnis Tionghoa.]","Perilaku 'main uang panas' digunakan untuk menggeneralisasi sifat licik pada seluruh etnis Tionghoa, mencerminkan generalisasi negatif berdasarkan etnis (HS_STEREOTYPE). Target: etnis Tionghoa."

In [855]:
eksplisit["IDPelanggaran"].unique()

array(['HS_STEREOTYPE', 'HS_POLITICAL_SARA', 'HS_EXCLUSION', 'HS_GENDER',
       'HS_DEHUMAN', 'HS_CULTURAL', 'HS_VIOLENCE'], dtype=object)

## Panduan Komunitas ga jadi, soalnya ngga ke hit
### ada sedikit salah paham sama tim 2. jadi RAG nya ga kena ke panduan komunitasnya

In [16]:
path_panduanKomunitas = folderData / "panduan_komunitas.jsonl"

panduan_komunitas = pd.read_json(path_panduanKomunitas, lines=True)
panduan_komunitas

,ID,indikator pelanggaran,isi,keywords
0,HS_DEHUMAN,Penggunaan metafora yang menyamakan kelompok masyarakat dengan ancaman kesehatan atau kebersihan lingkungan.,"Segala bentuk komunikasi yang merendahkan martabat manusia dengan cara menyamakan, mengibaratkan, atau melabeli individu maupun kelompok tertentu sebagai hewan, hama, serangga, penyakit, parasit, atau benda mati yang berkonotasi kotor dan menjijikkan. Tindakan ini dilarang karena bertujuan menghilangkan sisi kemanusiaan suatu golongan sehingga memicu pembenaran atas kekerasan atau pengucilan.","Hama, parasit, virus, kuman, sampah masyarakat, kecoa, anjing, babi, tikus, kotoran, dibasmi, disemprot, dibersihkan, penyakit masyarakat, beban bumi"
1,HS_STEREOTYPE,"Penggunaan kata 'semua', 'selalu', atau penyebutan nama suku/ras yang diikuti dengan klaim perilaku negatif, watak jahat, atau kecenderungan kriminal kolektif.","Tindakan memberikan label negatif, atribut buruk, atau tuduhan kriminal secara pukul rata (generalisasi) kepada seluruh anggota kelompok berdasarkan latar belakang suku, ras, etnis, atau agama tertentu. Pelanggaran terjadi ketika perilaku individu digunakan untuk menghakimi seluruh identitas golongan. Hal ini mencakup tuduhan sifat bawaan (genetik) yang buruk terhadap etnis tertentu.","Suku itu licik, Ras ini pelit, memang wataknya jahat, keturunan pemberontak, genetik kriminal, tidak bisa dipercaya, sok ramah padahal busuk, orang daerah itu kasar, kaum itu memang tukang buat onar."
2,HS_EXCLUSION,"Adanya kalimat perintah atau ajakan untuk memindahkan, mengusir, atau melarang keberadaan suatu kelompok di suatu wilayah geografis atau lingkungan sosial tertentu.","Pernyataan yang mengandung ajakan, hasutan, desakan, atau dukungan untuk melakukan pemisahan wilayah secara paksa (segregasi), pengusiran, boikot tempat tinggal, atau pembatasan hak hidup suatu golongan dari suatu lingkungan masyarakat atau negara. Tindakan ini dianggap sebagai ancaman serius terhadap integrasi sosial dan keselamatan kelompok tertentu.","Usir mereka, kembalikan ke asalnya, jangan kasih tempat tinggal, bersihkan wilayah kita, jangan mau bertetangga, boikot keberadaannya, ganyang, pindahkan paksa, jangan kasih ijin tinggal, bersihkan dari tanah kita."
3,HS_GENDER,"Penggunaan istilah yang merendahkan harga diri berdasarkan peran gender, penyebutan label seksis, atau narasi yang memposisikan satu gender sebagai kelompok yang inferior/lemah.","Segala bentuk penghinaan, perendahan, atau serangan yang menargetkan identitas gender tertentu (laki-laki atau perempuan). Hal ini mencakup penggunaan kata-kata ejekan yang merendahkan maskulinitas atau feminitas, serta generalisasi negatif terhadap perilaku salah satu gender sebagai bentuk serangan kolektif.","Laki-laki banci, perempuan samsak, laki-laki semua sama saja, lemah, tidak berguna, objek, merendahkan martabat gender, serangan berbasis jenis kelamin."
4,HS_POLITICAL_SARA,"Mengaitkan identitas SARA secara langsung dengan label pengkhianat negara, gerakan radikal, atau sejarah organisasi terlarang dengan tujuan menciptakan stigma berbahaya.","Tindakan memberikan label atau tuduhan keterlibatan dalam ideologi politik terlarang, kelompok teroris, atau organisasi terlarang kepada suatu kelompok etnis atau agama tanpa bukti hukum yang sah. Tuduhan ini sering digunakan untuk memicu kebencian publik dan persekusi terhadap kelompok tersebut.","Keturunan PKI, antek asing, kelompok teroris, pengkhianat negara, radikal, ekstremis, penyusup ideologi, menghancurkan negara dari dalam."

In [17]:
print(f"jumlah qwen halu IDPelanggaran baru 'HS_VIOLENCE' sebanyak: {len(eksplisit[eksplisit['IDPelanggaran'] == 'HS_VIOLENCE'])}")
print(f"jumlah qwen halu IDPelanggaran baru 'HS_CULTURAL' sebanyak: {len(eksplisit[eksplisit['IDPelanggaran'] == 'HS_CULTURAL'])}")

jumlah qwen halu IDPelanggaran baru 'HS_VIOLENCE' sebanyak: 1
jumlah qwen halu IDPelanggaran baru 'HS_CULTURAL' sebanyak: 1

In [19]:
eksplisit["IDPelanggaran"].value_counts()

IDPelanggaran
HS_STEREOTYPE        4132
HS_GENDER             645
HS_EXCLUSION          292
HS_POLITICAL_SARA     179
HS_DEHUMAN             18
HS_CULTURAL             1
HS_VIOLENCE             1
Name: count, dtype: int64

In [55]:
def panduanKomunitas(baris):
    return (
        f"### PEDOMAN KOMUNITAS: {baris['ID']}\n\n"
        f"**INDIKATOR PELANGGARAN:** {baris['indikator pelanggaran']}\n"
        f"**DEFINISI:** {baris['isi']}\n"
        f"**KATA KUNCI PEMICU:** {baris['keywords']}"
    )

panduan_komunitas["penjelasan"] = panduan_komunitas.apply(panduanKomunitas, axis=1)

In [56]:
panduan_komunitas

,ID,indikator pelanggaran,isi,keywords,penjelasan
0,HS_DEHUMAN,Penggunaan metafora yang menyamakan kelompok masyarakat dengan ancaman kesehatan atau kebersihan lingkungan.,"Segala bentuk komunikasi yang merendahkan martabat manusia dengan cara menyamakan, mengibaratkan, atau melabeli individu maupun kelompok tertentu sebagai hewan, hama, serangga, penyakit, parasit, atau benda mati yang berkonotasi kotor dan menjijikkan. Tindakan ini dilarang karena bertujuan menghilangkan sisi kemanusiaan suatu golongan sehingga memicu pembenaran atas kekerasan atau pengucilan.","Hama, parasit, virus, kuman, sampah masyarakat, kecoa, anjing, babi, tikus, kotoran, dibasmi, disemprot, dibersihkan, penyakit masyarakat, beban bumi","### PEDOMAN KOMUNITAS: HS_DEHUMAN\n\n**INDIKATOR PELANGGARAN:** Penggunaan metafora yang menyamakan kelompok masyarakat dengan ancaman kesehatan atau kebersihan lingkungan.\n**DEFINISI:** Segala bentuk komunikasi yang merendahkan martabat manusia dengan cara menyamakan, mengibaratkan, atau melabeli individu maupun kelompok tertentu sebagai hewan, hama, serangga, penyakit, parasit, atau benda mati yang berkonotasi kotor dan menjijikkan. Tindakan ini dilarang karena bertujuan menghilangkan sisi kemanusiaan suatu golongan sehingga memicu pembenaran atas kekerasan atau pengucilan.\n**KATA KUNCI PEMICU:** Hama, parasit, virus, kuman, sampah masyarakat, kecoa, anjing, babi, tikus, kotoran, dibasmi, disemprot, dibersihkan, penyakit masyarakat, beban bumi"
1,HS_STEREOTYPE,"Penggunaan kata 'semua', 'selalu', atau penyebutan nama suku/ras yang diikuti dengan klaim perilaku negatif, watak jahat, atau kecenderungan kriminal kolektif.","Tindakan memberikan label negatif, atribut buruk, atau tuduhan kriminal secara pukul rata (generalisasi) kepada seluruh anggota kelompok berdasarkan latar belakang suku, ras, etnis, atau agama tertentu. Pelanggaran terjadi ketika perilaku individu digunakan untuk menghakimi seluruh identitas golongan. Hal ini mencakup tuduhan sifat bawaan (genetik) yang buruk terhadap etnis tertentu.","Suku itu licik, Ras ini pelit, memang wataknya jahat, keturunan pemberontak, genetik kriminal, tidak bisa dipercaya, sok ramah padahal busuk, orang daerah itu kasar, kaum itu memang tukang buat onar.","### PEDOMAN KOMUNITAS: HS_STEREOTYPE\n\n**INDIKATOR PELANGGARAN:** Penggunaan kata 'semua', 'selalu', atau penyebutan nama suku/ras yang diikuti dengan klaim perilaku negatif, watak jahat, atau kecenderungan kriminal kolektif.\n**DEFINISI:** Tindakan memberikan label negatif, atribut buruk, atau tuduhan kriminal secara pukul rata (generalisasi) kepada seluruh anggota kelompok berdasarkan latar belakang suku, ras, etnis, atau agama tertentu. Pelanggaran terjadi ketika perilaku individu digunakan untuk menghakimi seluruh identitas golongan. Hal ini mencakup tuduhan sifat bawaan (genetik) yang buruk terhadap etnis tertentu.\n**KATA KUNCI PEMICU:** Suku itu licik, Ras ini pelit, memang wataknya jahat, keturunan pemberontak, genetik kriminal, tidak bisa dipercaya, sok ramah padahal busuk, orang daerah itu kasar, kaum itu memang tukang buat onar."
2,HS_EXCLUSION,"Adanya kalimat perintah atau ajakan untuk memindahkan, mengusir, atau melarang keberadaan suatu kelompok di suatu wilayah geografis atau lingkungan sosial tertentu.","Pernyataan yang mengandung ajakan, hasutan, desakan, atau dukungan untuk melakukan pemisahan wilayah secara paksa (segregasi), pengusiran, boikot tempat tinggal, atau pembatasan hak hidup suatu golongan dari suatu lingkungan masyarakat atau negara. Tindakan ini dianggap sebagai ancaman serius terhadap integrasi sosial dan keselamatan kelompok tertentu.","Usir mereka, kembalikan ke asalnya, jangan kasih tempat tinggal, bersihkan wilayah kita, jangan mau bertetangga, boikot keberadaannya, ganyang, pindahkan paksa, jangan kasih ijin tinggal, bersihkan dari tanah kita.","### PEDOMAN KOMUNITAS: HS_EXCLUSION\n\n**INDIKATOR PELANGGARAN:** Adanya kalimat perintah atau ajakan untuk memindahkan, mengusir, atau melarang keberadaan suatu kelompok di suatu wilayah geografis atau lingkungan sosial tertentu.\n**DEFINISI:** Pernyataan yang mengandung ajakan, hasutan, desakan, atau dukungan untuk melakukan pemisahan wilayah secara paksa (segregasi), pengusiran, boikot tempat tinggal, atau pembatasan hak hidup suatu golongan dari suatu lingkungan masyarakat atau negara. Tindakan ini dianggap sebagai ancaman serius terhadap integrasi sosial dan keselamatan kelompok tertentu.\n**KATA KUNCI PEMICU:** Usir mereka, kembalikan ke asalnya, jangan kasih tempat tinggal, bersihkan wilayah kita, jangan mau bertetangga, boikot keberadaannya, ganyang, pindahkan paksa, jangan kasih ijin tinggal, bersihkan dari tanah kita."
3,HS_GENDER,"Penggunaan istilah yang merendahkan harga diri berdasarkan peran gender, penyebutan label seksis, atau narasi yang memposisikan satu gender sebagai kelompok yang inferior/lemah.","Segala bentuk penghinaan, perendahan, atau serangan yang menargetkan identitas gender tertentu (laki-laki atau perempuan). Hal ini mencakup penggunaan kata-kata ejekan yang merendahkan maskulinitas atau feminitas, serta generalisasi negatif terhadap perilaku salah satu gender sebagai bentuk serangan kolektif.","Laki-laki banci, perempuan samsak, laki-laki semua sama saja, lemah, tidak berguna, objek, merendahkan martabat gender, serangan berbasis jenis kelamin.","### PEDOMAN KOMUNITAS: HS_GENDER\n\n**INDIKATOR PELANGGARAN:** Penggunaan istilah yang merendahkan harga diri berdasarkan peran gender, penyebutan label seksis, atau narasi yang memposisikan satu gender sebagai kelompok yang inferior/lemah.\n**DEFINISI:** Segala bentuk penghinaan, perendahan, atau serangan yang menargetkan identitas gender tertentu (laki-laki atau perempuan). Hal ini mencakup penggunaan kata-kata ejekan yang merendahkan maskulinitas atau feminitas, serta generalisasi negatif terhadap perilaku salah satu gender sebagai bentuk serangan kolektif.\n**KATA KUNCI PEMICU:** Laki-laki banci, perempuan samsak, laki-laki semua sama saja, lemah, tidak berguna, objek, merendahkan martabat gender, serangan berbasis jenis kelamin."
4,HS_POLITICAL_SARA,"Mengaitkan identitas SARA secara langsung dengan label pengkhianat negara, gerakan radikal, atau sejarah organisasi terlarang dengan tujuan menciptakan stigma berbahaya.","Tindakan memberikan label atau tuduhan keterlibatan dalam ideologi politik terlarang, kelompok teroris, atau organisasi terlarang kepada suatu kelompok etnis atau agama tanpa bukti hukum yang sah. Tuduhan ini sering digunakan untuk memicu kebencian publik dan persekusi terhadap kelompok tersebut.","Keturunan PKI, antek asing, kelompok teroris, pengkhianat negara, radikal, ekstremis, penyusup ideologi, menghancurkan negara dari dalam.","### PEDOMAN KOMUNITAS: HS_POLITICAL_SARA\n\n**INDIKATOR PELANGGARAN:** Mengaitkan identitas SARA secara langsung dengan label pengkhianat negara, gerakan radikal, atau sejarah organisasi terlarang dengan tujuan menciptakan stigma berbahaya.\n**DEFINISI:** Tindakan memberikan label atau tuduhan keterlibatan dalam ideologi politik terlarang, kelompok teroris, atau organisasi terlarang kepada suatu kelompok etnis atau agama tanpa bukti hukum yang sah. Tuduhan ini sering digunakan untuk memicu kebencian publik dan persekusi terhadap kelompok tersebut.\n**KATA KUNCI PEMICU:** Keturunan PKI, antek asing, kelompok teroris, pengkhianat negara, radikal, ekstremis, penyusup ideologi, menghancurkan negara dari dalam."

In [57]:
id_penjelasan = dict(
    zip(
        panduan_komunitas["ID"],
        panduan_komunitas["penjelasan"]
    )
)

In [58]:
id_penjelasan

{'HS_DEHUMAN': '### PEDOMAN KOMUNITAS: HS_DEHUMAN\n\n**INDIKATOR PELANGGARAN:** Penggunaan metafora yang menyamakan kelompok masyarakat dengan ancaman kesehatan atau kebersihan lingkungan.\n**DEFINISI:** Segala bentuk komunikasi yang merendahkan martabat manusia dengan cara menyamakan, mengibaratkan, atau melabeli individu maupun kelompok tertentu sebagai hewan, hama, serangga, penyakit, parasit, atau benda mati yang berkonotasi kotor dan menjijikkan. Tindakan ini dilarang karena bertujuan menghilangkan sisi kemanusiaan suatu golongan sehingga memicu pembenaran atas kekerasan atau pengucilan.\n**KATA KUNCI PEMICU:** Hama, parasit, virus, kuman, sampah masyarakat, kecoa, anjing, babi, tikus, kotoran, dibasmi, disemprot, dibersihkan, penyakit masyarakat, beban bumi',
 'HS_STEREOTYPE': "### PEDOMAN KOMUNITAS: HS_STEREOTYPE\n\n**INDIKATOR PELANGGARAN:** Penggunaan kata 'semua', 'selalu', atau penyebutan nama suku/ras yang diikuti dengan klaim perilaku negatif, watak jahat, atau kecenderungan kriminal kolektif.\n**DEFINISI:** Tindakan memberikan label negatif, atribut buruk, atau tuduhan kriminal secara pukul rata (generalisasi) kepada seluruh anggota kelompok berdasarkan latar belakang suku, ras, etnis, atau agama tertentu. Pelanggaran terjadi ketika perilaku individu digunakan untuk menghakimi seluruh identitas golongan. Hal ini mencakup tuduhan sifat bawaan (genetik) yang buruk terhadap etnis tertentu.\n**KATA KUNCI PEMICU:** Suku itu licik, Ras ini pelit, memang wataknya jahat, keturunan pemberontak, genetik kriminal, tidak bisa dipercaya, sok ramah padahal busuk, orang daerah itu kasar, kaum itu memang tukang buat onar.",
 'HS_EXCLUSION': '### PEDOMAN KOMUNITAS: HS_EXCLUSION\n\n**INDIKATOR PELANGGARAN:** Adanya kalimat perintah atau ajakan untuk memindahkan, mengusir, atau melarang keberadaan suatu kelompok di suatu wilayah geografis atau lingkungan sosial tertentu.\n**DEFINISI:** Pernyataan yang mengandung ajakan, hasutan, desakan, atau dukungan untuk melakukan pemisahan wilayah secara paksa (segregasi), pengusiran, boikot tempat tinggal, atau pembatasan hak hidup suatu golongan dari suatu lingkungan masyarakat atau negara. Tindakan ini dianggap sebagai ancaman serius terhadap integrasi sosial dan keselamatan kelompok tertentu.\n**KATA KUNCI PEMICU:** Usir mereka, kembalikan ke asalnya, jangan kasih tempat tinggal, bersihkan wilayah kita, jangan mau bertetangga, boikot keberadaannya, ganyang, pindahkan paksa, jangan kasih ijin tinggal, bersihkan dari tanah kita.',
 'HS_GENDER': '### PEDOMAN KOMUNITAS: HS_GENDER\n\n**INDIKATOR PELANGGARAN:** Penggunaan istilah yang merendahkan harga diri berdasarkan peran gender, penyebutan label seksis, atau narasi yang memposisikan satu gender sebagai kelompok yang inferior/lemah.\n**DEFINISI:** Segala bentuk penghinaan, perendahan, atau serangan yang menargetkan identitas gender tertentu (laki-laki atau perempuan). Hal ini mencakup penggunaan kata-kata ejekan yang merendahkan maskulinitas atau feminitas, serta generalisasi negatif terhadap perilaku salah satu gender sebagai bentuk serangan kolektif.\n**KATA KUNCI PEMICU:** Laki-laki banci, perempuan samsak, laki-laki semua sama saja, lemah, tidak berguna, objek, merendahkan martabat gender, serangan berbasis jenis kelamin.',
 'HS_POLITICAL_SARA': '### PEDOMAN KOMUNITAS: HS_POLITICAL_SARA\n\n**INDIKATOR PELANGGARAN:** Mengaitkan identitas SARA secara langsung dengan label pengkhianat negara, gerakan radikal, atau sejarah organisasi terlarang dengan tujuan menciptakan stigma berbahaya.\n**DEFINISI:** Tindakan memberikan label atau tuduhan keterlibatan dalam ideologi politik terlarang, kelompok teroris, atau organisasi terlarang kepada suatu kelompok etnis atau agama tanpa bukti hukum yang sah. Tuduhan ini sering digunakan untuk memicu kebencian publik dan persekusi terhadap kelompok tersebut.\n**KATA KUNCI PEMICU:** Keturunan PKI, antek asing, kelompok teroris, pengkhianat negara, radikal, ekstremis, penyusup ideologi, menghancurkan negara dari dalam.'}

In [59]:
eksplisit["IDPelanggaran"] = eksplisit["IDPelanggaran"].map(id_penjelasan)

## Langsung lanjut sini
### abaiin aja proses pedomean komunitas

In [856]:
eksplisit.isna().sum()

claim_ujaranKebencian         0
target                        0
label                         0
jenis                         0
isExplicit                    0
IDPelanggaran                 0
cot_analisis                  0
reasoning_ujaran_kebencian    0
dtype: int64

In [857]:
eksplisit = eksplisit.dropna()

In [858]:
eksplisit["label"] = "Ujaran Kebencian"
eksplisit.head(1)

,claim_ujaranKebencian,target,label,jenis,isExplicit,IDPelanggaran,cot_analisis,reasoning_ujaran_kebencian
0,"etnis tionghoa emang ges licik main uang panas dr china, ngebulu aja lo semua!",etnis tionghoa,Ujaran Kebencian,komentar,1.0,HS_STEREOTYPE,"[Claim menggunakan kata 'ges licik' yang merendahkan etnis Tionghoa secara kolektif., Menghubungkan perilaku 'main uang panas' dengan etnis Tionghoa, seolah-olah seluruh anggota etnis tersebut memiliki sifat licik., Penggunaan kata 'ngebulu aja lo semua' menunjukkan generalisasi negatif terhadap seluruh anggota etnis Tionghoa.]","Perilaku 'main uang panas' digunakan untuk menggeneralisasi sifat licik pada seluruh etnis Tionghoa, mencerminkan generalisasi negatif berdasarkan etnis (HS_STEREOTYPE). Target: etnis Tionghoa."

In [859]:
eksplisit = eksplisit.to_dict("records")

In [860]:
import json
import random

def generate_sft_dataset_with_context(raw_data_list, instructions, output_file):
    dataset = []
    
    for data in raw_data_list:
        instruct = instructions
        claim = data.get("claim_ujaranKebencian", "")
        # teks = data.get("IDPelanggaran", "") # ga jadi kupake 
        label = data.get("label")
        # reasoning = data.get("reasoning_ujaran_kebencian", "") # ga jadi dipake
        cot_list = data.get("cot_analisis", [])
        
        # Susun poin-poin fakta
        fakta_points = "\n".join([f"* {point}" for point in cot_list])

        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Komentar: '{claim}';\n\n"
        )

        full_output = (
            f"Penjelasan:\n"
            f"{fakta_points}\n\n"
            f"Kesimpulan:\n"
            f"Label: {label}."
        )
        
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(eksplisit, instructiones, "ujarankebencian.jsonl")

Berhasil membuat 5268 data dengan konteks berita di ujarankebencian.jsonl

In [861]:
tes = pd.read_json("ujarankebencian.jsonl", lines=True)
tes.head(1)

,instruction,input,output
0,"Anda adalah sistem ahli yang mengklasifikasikan [Komentar] media sosial Indonesia ke dalam label resmi: [Netral, Disinformasi, Fitnah, Ujaran Kebencian], dengan dibantu [Artikel Rujukan] jika tersedia.\n\nAturan Penalaran:\n\n1. Prioritaskan analisis pada [Komentar] untuk menentukan apakah teks tersebut mengandung klaim faktual yang memerlukan verifikasi, termasuk indikasi ujaran kebencian/SARA, atau sekadar interaksi santai.\n2. Jika [Komentar] mengandung unsur serangan atau penghinaan berdasarkan identitas (SARA, ras, etnis, agama, gender, disabilitas), langsung klasifikasikan sebagai 'Ujaran Kebencian' dan ABAIKAN [Artikel Rujukan].\n3. Jika tidak mengandung ujaran kebencian, gunakan [Artikel Rujukan] (atau pengetahuan internal jika rujukan kosong) untuk menilai klaim:\n* Netral: Konten faktual, opini, ekspresi emosional, kritik kebijakan, atau interaksi normal yang tidak mengandung kebohongan spesifik untuk menjatuhkan reputasi.\n* Disinformasi: Informasi keliru/menyesatkan yang berpotensi meresahkan masyarakat atau memicu polarisasi.\n* Fitnah: Tuduhan atau klaim bohong yang spesifik dan sengaja dibuat untuk menyerang karakter, kehormatan, atau reputasi individu/kelompok.\n\n**Format Output WAJIB (Jangan diubah):**\nPenjelasan:\n[Tulis analisis ringkas terhadap Komentar, perbandingannya dengan Artikel Rujukan, dan alasan pemilihan label]\n\nKesimpulan:\nLabel: [NamaLabel].","Komentar: 'etnis tionghoa emang ges licik main uang panas dr china, ngebulu aja lo semua!';\n\n","Penjelasan:\n* Claim menggunakan kata 'ges licik' yang merendahkan etnis Tionghoa secara kolektif.\n* Menghubungkan perilaku 'main uang panas' dengan etnis Tionghoa, seolah-olah seluruh anggota etnis tersebut memiliki sifat licik.\n* Penggunaan kata 'ngebulu aja lo semua' menunjukkan generalisasi negatif terhadap seluruh anggota etnis Tionghoa.\n\nKesimpulan:\nLabel: Ujaran Kebencian."

## Data tambahan

In [862]:
hate.tail(1)

,komentar_asli,mengandung_klaim,search_query,alasan_non_dfk,kategori_flag
4938,Bahelamah Jablay teh dikota ayenamah tatanga JD jablay,False,TIDAK_BUTUH_RAG,Terdeteksi Ujaran Kebencian / SARA karena menggunakan istilah 'jablay' yang bersifat merendahkan dan seksis terhadap perempuan,Ujaran Kebencian

In [863]:
hate = hate.to_dict("records")

In [864]:
def generate_sft_dataset_with_context(raw_data_list, instructions, output_file):
    dataset = []
    
    for data in raw_data_list:
        instruct = instructions
        claim = data.get("komentar_asli", "")
        # teks = data.get("IDPelanggaran", "") # ga jadi kupake 
        label = "Ujaran Kebencian"
        reasoning = data.get("alasan_non_dfk", "") 
        # cot_list = data.get("cot_analisis", []) # ga jadi dipake
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Komentar: '{claim}';\n\n"
        )

        full_output = (
            f"Penjelasan: {reasoning}\n\n"
            f"Kesimpulan:\n"
            f"Label: {label}."
        )
        
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(hate, instructiones, "ujarankebencian2.jsonl")

Berhasil membuat 484 data dengan konteks berita di ujarankebencian2.jsonl

### Gabungin data ujaran kebencian sama tambahannya

In [865]:
ujarankebencian1 = pd.read_json("ujarankebencian.jsonl", lines=True)
ujarankebencian2 = pd.read_json("ujarankebencian2.jsonl", lines=True)

dataUjaranKebencian = pd.concat(
    [ujarankebencian1, ujarankebencian2], ignore_index=True
)

dataUjaranKebencian.to_json(
    "dataUjaranKebencian.jsonl", orient="records", lines=True
)

In [868]:
print(f"{len(ujarankebencian1)}")
print(f"{len(ujarankebencian2)}")
print(f"{len(dataUjaranKebencian)}")

5268
484
5752

In [869]:
dataUjaranKebencian.tail(1)

,instruction,input,output
5751,"Anda adalah sistem ahli yang mengklasifikasikan [Komentar] media sosial Indonesia ke dalam label resmi: [Netral, Disinformasi, Fitnah, Ujaran Kebencian], dengan dibantu [Artikel Rujukan] jika tersedia.\n\nAturan Penalaran:\n\n1. Prioritaskan analisis pada [Komentar] untuk menentukan apakah teks tersebut mengandung klaim faktual yang memerlukan verifikasi, termasuk indikasi ujaran kebencian/SARA, atau sekadar interaksi santai.\n2. Jika [Komentar] mengandung unsur serangan atau penghinaan berdasarkan identitas (SARA, ras, etnis, agama, gender, disabilitas), langsung klasifikasikan sebagai 'Ujaran Kebencian' dan ABAIKAN [Artikel Rujukan].\n3. Jika tidak mengandung ujaran kebencian, gunakan [Artikel Rujukan] (atau pengetahuan internal jika rujukan kosong) untuk menilai klaim:\n* Netral: Konten faktual, opini, ekspresi emosional, kritik kebijakan, atau interaksi normal yang tidak mengandung kebohongan spesifik untuk menjatuhkan reputasi.\n* Disinformasi: Informasi keliru/menyesatkan yang berpotensi meresahkan masyarakat atau memicu polarisasi.\n* Fitnah: Tuduhan atau klaim bohong yang spesifik dan sengaja dibuat untuk menyerang karakter, kehormatan, atau reputasi individu/kelompok.\n\n**Format Output WAJIB (Jangan diubah):**\nPenjelasan:\n[Tulis analisis ringkas terhadap Komentar, perbandingannya dengan Artikel Rujukan, dan alasan pemilihan label]\n\nKesimpulan:\nLabel: [NamaLabel].",Komentar: 'Bahelamah Jablay teh dikota ayenamah tatanga JD jablay';\n\n,Penjelasan: Terdeteksi Ujaran Kebencian / SARA karena menggunakan istilah 'jablay' yang bersifat merendahkan dan seksis terhadap perempuan\n\nKesimpulan:\nLabel: Ujaran Kebencian.

# Sampling dan Gabungin semua dataset
## Jangan lupa kita acak acak biar modelnya nanti belajar

In [870]:
df_disinformasi = pd.read_json("disinformasi.jsonl", lines=True)
df_fitnah = pd.read_json("fitnah.jsonl", lines=True)
df_netral = pd.read_json("dataNetral.jsonl", lines=True)
df_kebencian = pd.read_json("dataUjaranKebencian.jsonl", lines=True)

In [876]:
# sampling, jumlah 5269 kita ikutin total data ujaran kebencian. jadi biar balance 
# kecuali netral, kita banyakin.
jumlahNetral = len(df_netral) # 6639
jumlahData = len(df_kebencian) # 5752

df_netral = df_netral.sample(n=jumlahNetral)
df_disinformasi = df_disinformasi.sample(n=jumlahData)
df_fitnah = df_fitnah.sample(n=jumlahData)
df_ujarankb = df_kebencian.sample(n=jumlahData)

In [877]:
# df_disinformasi.to_csv("df_disinformasi.csv", index=False)
# df_fitnah.to_csv("df_fitnah.csv", index=False)
# df_fakta.to_csv("df_fakta.csv", index=False)

In [878]:
df_combined = pd.concat([
    df_disinformasi,
    df_fitnah,
    df_netral,
    df_ujarankb
])

df_combined = df_combined.sample(frac=1, random_state=42).reset_index(drop=True)
print(len(df_combined))

df_combined.to_json('dataset_sampled.jsonl', orient='records', lines=True)

23895

## Bersihin teks dari kalimat iklan

In [879]:
allDF = pd.read_json("dataset_sampled.jsonl", lines=True)

In [880]:
allDF.head()

,instruction,input,output
0,"Anda adalah sistem ahli yang mengklasifikasikan [Komentar] media sosial Indonesia ke dalam label resmi: [Netral, Disinformasi, Fitnah, Ujaran Kebencian], dengan dibantu [Artikel Rujukan] jika tersedia.\n\nAturan Penalaran:\n\n1. Prioritaskan analisis pada [Komentar] untuk menentukan apakah teks tersebut mengandung klaim faktual yang memerlukan verifikasi, termasuk indikasi ujaran kebencian/SARA, atau sekadar interaksi santai.\n2. Jika [Komentar] mengandung unsur serangan atau penghinaan berdasarkan identitas (SARA, ras, etnis, agama, gender, disabilitas), langsung klasifikasikan sebagai 'Ujaran Kebencian' dan ABAIKAN [Artikel Rujukan].\n3. Jika tidak mengandung ujaran kebencian, gunakan [Artikel Rujukan] (atau pengetahuan internal jika rujukan kosong) untuk menilai klaim:\n* Netral: Konten faktual, opini, ekspresi emosional, kritik kebijakan, atau interaksi normal yang tidak mengandung kebohongan spesifik untuk menjatuhkan reputasi.\n* Disinformasi: Informasi keliru/menyesatkan yang berpotensi meresahkan masyarakat atau memicu polarisasi.\n* Fitnah: Tuduhan atau klaim bohong yang spesifik dan sengaja dibuat untuk menyerang karakter, kehormatan, atau reputasi individu/kelompok.\n\n**Format Output WAJIB (Jangan diubah):**\nPenjelasan:\n[Tulis analisis ringkas terhadap Komentar, perbandingannya dengan Artikel Rujukan, dan alasan pemilihan label]\n\nKesimpulan:\nLabel: [NamaLabel].",Komentar: 'wkwk beneran gmn sih islam mudah banget nyolok kafir sj';\n\n,Penjelasan:\n* Claim menggeneralisir seluruh umat Islam sebagai mudah menyerang (nyolok) orang yang tidak beragama (kafir).\n* Penggunaan kata 'mudah nyolok' menunjukkan penilaian negatif terhadap seluruh kelompok Islam.\n* Generalisasi ini menciptakan narasi bahwa umat Islam cenderung agresif dan intoleran.\n\nKesimpulan:\nLabel: Ujaran Kebencian.
1,"Anda adalah sistem ahli yang mengklasifikasikan [Komentar] media sosial Indonesia ke dalam label resmi: [Netral, Disinformasi, Fitnah, Ujaran Kebencian], dengan dibantu [Artikel Rujukan] jika tersedia.\n\nAturan Penalaran:\n\n1. Prioritaskan analisis pada [Komentar] untuk menentukan apakah teks tersebut mengandung klaim faktual yang memerlukan verifikasi, termasuk indikasi ujaran kebencian/SARA, atau sekadar interaksi santai.\n2. Jika [Komentar] mengandung unsur serangan atau penghinaan berdasarkan identitas (SARA, ras, etnis, agama, gender, disabilitas), langsung klasifikasikan sebagai 'Ujaran Kebencian' dan ABAIKAN [Artikel Rujukan].\n3. Jika tidak mengandung ujaran kebencian, gunakan [Artikel Rujukan] (atau pengetahuan internal jika rujukan kosong) untuk menilai klaim:\n* Netral: Konten faktual, opini, ekspresi emosional, kritik kebijakan, atau interaksi normal yang tidak mengandung kebohongan spesifik untuk menjatuhkan reputasi.\n* Disinformasi: Informasi keliru/menyesatkan yang berpotensi meresahkan masyarakat atau memicu polarisasi.\n* Fitnah: Tuduhan atau klaim bohong yang spesifik dan sengaja dibuat untuk menyerang karakter, kehormatan, atau reputasi individu/kelompok.\n\n**Format Output WAJIB (Jangan diubah):**\nPenjelasan:\n[Tulis analisis ringkas terhadap Komentar, perbandingannya dengan Artikel Rujukan, dan alasan pemilihan label]\n\nKesimpulan:\nLabel: [NamaLabel].","Komentar: 'Massa Prabowo-Gibran bikin macet parah, polisi nggak bisa ngapa-ngapain!';\n\nArtikel Rujukan: - Masyarakat tampaknya harus menghindari ruas Jalan Gatot Subroto, yang mengarah ke Stadion Utama Gelora Bung Karno (GBK), Jakarta Pusat hari ini.Pasalnya, siang hari ini saja, ruas jalan tersebut sudah dipadati kendaraan.Pantauan INDOZONE di ruas Jalan Cawang termasuk Jalan Gatot Subroto yang mengarah ke GBK, Sabtu (10/2/2023), sekitar pukul 10.00 WIB, kepadatan lalu lintas sudah terjadi.Kepadatan terjadi akibat banyaknya pendukung pasangan calon nomor urut dua, yang hendak datang ke area kampanye akbar di GBK.Terpantau, banyak peserta kampanye yang mengenakan atribut berbau Prabowo maupun Gibran.Ada pula yang membawa bendera-bendera partai pengusung dari paslon nomor urut 02 tersebut.\nMasih di sekitar lokasi, terlihat aparat kepolisian tengah berupaya mengatur arus lalu lintas. Kepadatan terlibat bertumpu di kawasan GBK.Memasuki area GBK, para peserta kampanye terlihat masih berangsur-angsur masuk ke area dalam GBK. Massa serentak mengenakan kaos berwarna biru khas paslon nomor 02.Pasangan Prabowo Subianto dan Gibran Rakabuming Raka pada hari ini menggelar kampanye akbar mereka di Stadion Utama GBK. Keduanya diperkirakan bakar hadir menjelang sore nanti.\nKepadatan relawan menuju lokasi Kampanye Akbar Prabowo-Gibran di GBK, Jakpus.Di sisi lain, Polri dalam hal ini Polda Metro Jaya sudah mengerahkan ribuan personelnya untuk mengamankan jalannya kampanye akbar tersebut.Tak hanya itu, Polda Metro Jaya juga menyiapkan rekayasa lalu lintas untuk menghindari penumpukan kendaraan imbas dari kegiatan kampanye.\nBerikut rekayasa lalu lintas yang bakal diterapkan:1. Arus lalu lintas dari Jalan Gatot Subroto yang akan menuju ke Jalan Gerbang Pemuda diarahkan lurus ke arah Slipi.2. Arus lalu lintas dari arah Slipi diarahkan lurus ke arah Semanggi, tidak ada yang menuju Layang Ladokgi ke arah Jalan Gerbang Pemuda.3. Arus lalu lintas dari Bundaran Senayan menuju ke Jalan Pintu I Senayan diluruskan ke Jalan Jenderal Sudirman arah Semanggi.4. Arus lalu lintas dari Jalan Mustopo menuju ke Jalan Asia Afrika dibelokkan ke kanan ke Jalan Hang Tuah.5. Arus lalu lintas dari Jalan Patal Senayan 1 yang menuju ke Jalan Asia Afrika dibelokkan ke kiri ke Jalan Tentara Pelajar.6. Arus lalu lintas arah Manggala Wanabakti yang akan menuju Jalan Lapangan tembak diluruskan ke Jalan Tentara Pelajar.","Penjelasan: Fakta dipelintir dengan menekankan bahwa polisi tidak berdaya menghadapi kepadatan lalu lintas, padahal berita asli menyebutkan bahwa polisi sedang berusaha mengatur arus lalu lintas.\n\nBerikut adalah beberapa poin penting:\n* Berita asli menyebutkan bahwa polisi sedang berupaya mengatur arus lalu lintas di kawasan GBK.\n* Kepadatan lalu lintas disebabkan oleh banyaknya pendukung pasangan calon nomor urut 02 yang datang ke area kampanye.\n* Tidak disebutkan bahwa polisi tidak bisa melakukan apa-apa, melainkan sedang berusaha mengatasi kepadatan.\n* Berita asli tidak menunjukkan bahwa situasi sudah tidak terkendali atau polisi gagal dalam tugasnya.\n\nKesimpulan:\nLabel: Fitnah."
2,"Anda adalah sistem ahli yang mengklasifikasikan [Komentar] media sosial Indonesia ke dalam label resmi: [Netral, Disinformasi, Fitnah, Ujaran Kebencian], dengan dibantu [Artikel Rujukan] jika tersedia.\n\nAturan Penalaran:\n\n1. Prioritaskan analisis pada [Komentar] untuk menentukan apakah teks tersebut mengandung klaim faktual yang memerlukan verifikasi, termasuk indikasi ujaran kebencian/SARA, atau sekadar interaksi santai.\n2. Jika [Komentar] mengandung unsur serangan atau penghinaan berdasarkan identitas (SARA, ras, etnis, agama, gender, disabilitas), langsung klasifikasikan sebagai 'Ujaran Kebencian' dan ABAIKAN [Artikel Rujukan].\n3. Jika tidak mengandung ujaran kebencian, gunakan [Artikel Rujukan] (atau pengetahuan internal jika rujukan kosong) untuk menilai klaim:\n* Netral: Konten faktual, opini, ekspresi emosional, kritik kebijakan, atau interaksi normal yang tidak mengandung kebohongan spesifik untuk menjatuhkan reputasi.\n* Disinformasi: Informasi keliru/menyesatkan yang berpotensi meresahkan masyarakat atau memicu polarisasi.\n* Fitnah: Tuduhan atau klaim bohong yang spesifik dan sengaja dibuat untuk menyerang karakter, kehormatan, atau reputasi individu/kelompok.\n\n**Format Output WAJIB (Jangan diubah):**\nPenjelasan:\n[Tulis analisis ringkas terhadap Komentar, perbandingannya dengan Artikel Rujukan, dan alasan pemilihan label]\n\nKesimpulan:\nLabel: [NamaLabel].","Komentar: 'Wagub dan Kadinkes Lampung dipenjara, gegerkan masyarakat!';\n\nArtikel Rujukan: Beredar sebuah unggahan video yang menampilkan foto Wakil Gubernur (Wagub) Lampung Chusnunia Chalim dan Kepala Dinas Kesehatan (Kadinkes) Provinsi Lampung Reihana dimasukkan ke penjara. Unggahan video tersebut disertai dengan narasi ""G3ger W4gub L4mpvng Dan Kad1nkes B4kal M3mbusvk Dip3njara Ak1bat U1ah Send1ri"". Faktanya, dikutip dari kompas.com, narasi yang menyebutkan Wagub Lampung Chusnunia Chalim dan Kadinkes Provinsi Lampung Reihana dimasukkan ke penjara adalah hoaks. Klaim pada judul video yang beredar tidak sesuai dengan isi video. Narasi dalam video hanya membahas mengenai penjadwalan pemeriksaan Chusnunia Chalim oleh KPK untuk mengklarifikasi Laporan Harta Kekayaan Penyelenggara Negara (LKHPN).","Penjelasan: Kabar ini adalah konten menyesatkan yang bertujuan untuk menciptakan kegaduhan dan ketidakpercayaan terhadap pejabat publik. Modus ini sering digunakan untuk mendapatkan perhatian dan viral di media sosial.\n\nBerikut adalah beberapa poin penting:\n* Klarifikasi dari Kompas.com menyatakan bahwa narasi yang menyebutkan Wagub Lampung Chusnunia Chalim dan Kadinkes Provinsi Lampung Reihana dimasukkan ke penjara adalah hoaks.\n* Klaim pada judul video yang beredar tidak sesuai dengan isi video. Narasi dalam video hanya membahas mengenai penjadwalan pemeriksaan Chusnunia Chalim oleh KPK untuk mengklarifikasi Laporan Harta Kekayaan Penyelenggara Negara (LKHPN).\n* Pihak KPK juga telah mengklarifikasi bahwa Chusnunia Chalim dan Reihana hanya dipanggil untuk klarifikasi, bukan penahanan.\n* Masyarakat disarankan untuk memverifikasi informasi melalui sumber resmi seperti pernyataan dari KPK atau pemerintah daerah.\n* Penggunaan bahasa yang ambigu dan sensasional dalam judul video bertujuan untuk menarik perhatian dan mendapatkan engagement di media sosial.\n\nKesimpulan:\nLabel: Disinformasi."
3,"Anda adalah sistem ahli yang mengklasifikasikan [Komentar] media sosial Indonesia ke dalam label resmi: [Netral, Disinformasi, Fitnah, Ujaran Kebencian], dengan dibantu [Artikel Rujukan] jika tersedia.\n\nAturan Penalaran:\n\n1. Prioritaskan analisis pada [Komentar] untuk menentukan apakah teks tersebut mengandung klaim faktual yang memerlukan verifikasi, termasuk indikasi ujaran kebencian/SARA, atau sekadar interaksi santai.\n2. Jika [Komentar] mengandung unsur serangan atau penghinaan berdasarkan identitas (SARA, ras, etnis, agama, gender, disabilitas), langsung klasifikasikan sebagai 'Ujaran Kebencian' dan ABAIKAN [Artikel Rujukan].\n3. Jika tidak mengandung ujaran kebencian, gunakan [Artikel Rujukan] (atau pengetahuan internal jika rujukan kosong) untuk menilai klaim:\n* Netral: Konten faktual, opini, ekspresi emosional, kritik kebijakan, atau interaksi normal yang tidak mengandung kebohongan spesifik untuk menjatuhkan reputasi.\n* Disinformasi: Informasi keliru/menyesatkan yang berpotensi meresahkan masyarakat atau memicu polarisasi.\n* Fitnah: Tuduhan atau klaim bohong yang spesifik dan sengaja dibuat untuk menyerang karakter, kehormatan, atau reputasi individu/kelompok.\n\n**Format Output WAJIB (Jangan diubah):**\nPenjelasan:\n[Tulis analisis ringkas terhadap Komentar, perbandingannya dengan Artikel Rujukan, dan alasan pemilihan label]\n\nKesimpulan:\nLabel: [NamaLabel].","Komentar: 'Warga Palu sengaja kirim bantuan ke Sumut untuk mendapat perhatian pemerintah pusat';\n\nArtikel Rujukan: Gubernur Sumatera Utara, Muhammad Bobby Afif Nasution, menyampaikan apresiasi mendalam atasbantuankemanusiaandari masyarakat KotaPalu.Bantuantersebut diserahkan secara simbolis oleh Wakil Wali KotaPalu, Imelda Liliana Muhidin, di Kantor Gubernur Sumut.\nDalam kesempatan itu, Bobby menegaskan bahwa seluruhbantuanakan disalurkan langsung ke daerah-daerah yang terdampak banjir, banjir bandang, dan longsor. Sumut sendiri saat ini memasuki masa perpanjangan tanggap darurat selama dua pekan.\nBobby menjelaskan bahwa pemerintah provinsi bersama pemerintah kabupaten/kota masih terus fokus pada mitigasi serta antisipasi bencana susulan. Ia juga menyebutkan bahwa Presiden direncanakan kembali datang meninjau kondisi terbaru.\nDalam pemaparannya, Bobby menyampaikan bahwa terdapat 17 kabupaten/kota yang terdampak bencana. Dari seluruh wilayah tersebut, tercatat 343 warga meninggal dunia, 98 orang masih hilang, dan lebih dari 53 ribu warga mengungsi.\nPengajian Akbar Medan Selayang, Ribuan Jamaah Doakan Korban Banjir\nIa menambahkan bahwa total warga terdampak mencapai 1,7 juta orang, dengan kondisi terparah terjadi di Tapanuli Tengah, Tapanuli Selatan, Tapanuli Utara, Deliserdang, Langkat, dan Kota Sibolga.\nBobby juga menyatakan bahwa para kepala daerah di Sumut sedang berjuang keras menangani bencana di wilayah masing-masing. Banyak OPD juga terjun langsung ke lapangan untuk mempercepat upaya penanganan.\nDalam kesempatan yang sama, ia menegaskan bahwa bantuan dari masyarakat Palu akan langsung ditransfer ke kabupaten/kota terdampak. Mekanisme penyaluran ini dinilai paling efektif untuk memastikan bantuan tepat sasaran.\nWakil Wali Kota Palu, Imelda Liliana Muhidin, menyampaikan duka mendalam kepada warga Sumut, Aceh, dan Sumatera Barat yang ikut terdampak. Ia mengaku bantuan tersebut diberikan sebagai bentuk empati karena masyarakat Palu pernah mengalami bencana besar pada 2018.\nImelda mengenang bagaimana bencana gempa dan likuifaksi menyebabkan satu dusun hilang. Pengalaman tersebut membuat warga Palu memahami betapa beratnya pemulihan pascabencana.\nSambut Natal & Tahun Baru, Pemko Medan Hadirkan Pasar Murah di 53 Titik\nDalam kunjungannya, Imelda membawa bantuan senilai Rp300 juta dari masyarakat Palu. Bantuan itu diharapkan dapat meringankan beban masyarakat yang terkena dampak.\nAcara serah terima bantuan turut dihadiri sejumlah pejabat, termasuk Asisten Pemerintahan, Kepala BKAD, Kepala BPBD, Kadis Kominfo, dan Kabiro Pemerintahan. Keberadaan mereka menunjukkan dukungan penuh pemerintah dalam penanganan bencana.","Penjelasan: Claim tersebut menyalahgunakan motivasi warga Palu yang sebenarnya bersifat kemanusiaan dan solidaritas. Bantuan ini jelas disalurkan untuk membantu korban bencana, bukan untuk mencari perhatian pemerintah pusat.\n\nBerikut adalah beberapa poin penting:\n* Warga Palu mengirim bantuan sebagai bentuk empati dan solidaritas kemanusiaan, bukan untuk mencari perhatian pemerintah pusat\n* Bantuan tersebut diserahkan secara simbolis oleh Wakil Wali Kota Palu, Imelda Liliana Muhidin, yang menunjukkan kepedulian dan koordinasi antar pemerintah daerah\n* Gubernur Sumut, Muhammad Bobby Afif Nasution, menyampaikan apresiasi atas bantuan tersebut, yang menunjukkan bahwa bantuan ini dihargai dan akan disalurkan langsung ke korban\n* Bantuan ini merupakan bagian dari upaya bersama untuk membantu korban bencana, yang mencakup 17 kabupaten/kota dengan total 1,7 juta warga terdampak\n* Presiden direncanakan kembali meninjau kondisi terbaru, menunjukkan bahwa pemerintah pusat telah memberikan perhatian serius terhadap situasi di Sumut, bukan karena adanya bantuan dari Palu\n\nKesimpulan:\nLabel: Fitnah."
4,"Anda adalah sistem ahli yang mengklasifikasikan [Komentar] media sosial Indonesia ke dalam label resmi: [Netral, Disinformasi, Fitnah, Ujaran Kebencian], dengan dibantu [Artikel Rujukan] jika tersedia.\n\nAturan Penalaran:\n\n1. Prioritaskan analisis pada [Komentar] untuk menentukan apakah teks tersebut mengandung klaim faktual yang memerlukan verifikasi, termasuk indikasi ujaran kebencian/SARA, atau sekadar interaksi santai.\n2. Jika [Komentar] mengandung unsur serangan atau penghinaan berdasarkan identitas (SARA, ras, etnis, agama, gender, disabilitas), langsung klasifikasikan sebagai 'Ujaran Kebencian' dan ABAIKAN [Artikel Rujukan].\n3. Jika tidak mengandung ujaran kebencian, gunakan [Artikel Rujukan] (atau pengetahuan internal jika rujukan kosong) untuk menilai klaim:\n* Netral: Konten faktual, opini, ekspresi emosional, kritik kebijakan, atau interaksi normal yang tidak mengandung kebohongan spesifik untuk menjatuhkan reputasi.\n* Disinformasi: Informasi keliru/menyesatkan yang berpotensi meresahkan masyarakat atau memicu polarisasi.\n* Fitnah: Tuduhan atau klaim bohong yang spesifik dan sengaja dibuat untuk menyerang karakter, kehormatan, atau reputasi individu/kelompok.\n\n**Format Output WAJIB (Jangan diubah):**\nPenjelasan:\n[Tulis analisis ringkas terhadap Komentar, perbandingannya dengan Artikel Rujukan, dan alasan pemilihan label]\n\nKesimpulan:\nLabel: [NamaLabel].","Komentar: 'Waspada! UUD LGBT telah disahkan, PPP dan PKB mendukung, PKS, GERINDRA, dan PAN menangis di DPR!';\n\nArtikel Rujukan: Telah tersebar sebuah informasi melalui pesan berantai Whatsapp yang menyatakan bahwa UUD LGBT telah disahkan dalam pesan tersebut juga dijelaskan bahwasannya PPP dan PKB mendukung akan hal itu sedangkan dari fraksi PKS, GERINDRA dan PAN menangis di DPR. Faktanya adalah isu ini merupakan daur ulang yang diangkat kembali, sebenarnya ini bukan di Undang-undang dasar(UUD) melainkan dalam pasal di Rancangan Kitab Undang-undang Hukum Pidana(RKHUP) yang justru melarang LGBT dengan ancaman pidana, bukan membolehkan seperti premis yang dibangun oleh pesan berantai yang diedarkan.","Penjelasan: Ini adalah modus pencatutan nama yang menyesatkan, yang mengambil keuntungan dari isu sensitif untuk menimbulkan kepanikan dan ketidakpercayaan terhadap institusi pemerintah.\n\nBerikut adalah beberapa poin penting:\n* Pesan berantai tersebut adalah daur ulang isu lama. Isu ini sebenarnya berkaitan dengan Rancangan Kitab Undang-undang Hukum Pidana (RKUHP), bukan UUD.\n* RKUHP justru melarang LGBT dengan ancaman pidana, bukan membolehkannya seperti yang disebutkan dalam pesan berantai.\n* Faksi-faksi politik yang disebutkan dalam pesan berantai tidak memiliki posisi resmi yang konsisten terkait isu ini.\n* Sumber resmi dari DPR dan pemerintah tidak pernah mengumumkan adanya UUD LGBT.\n\nKesimpulan:\nLabel: Disinformasi."

In [886]:
allDF["input"] = allDF["input"].str.replace(r"\.\s*SCROLL TO CONTINUE WITH CONTENT\s*", "", regex=True)

allDF["input"] = allDF["input"].str.replace(r"\nAncaman Bom di Penerbangan Lion Air JT-308, Begini Kata Manajemen\n", "\n", regex=True)

In [887]:
allDF.to_json('datasetSFT.jsonl', orient='records', lines=True)

# dibikin TRL

Buat contoh aja sih, harusnya udah di handle sebelum masuk ke finetuning

In [888]:
input_file_jsonl = "datasetSFT.jsonl"      
output_file_jsonl = "datasetSFT_TRL.jsonl"  



print(f"Memulai konversi file {input_file_jsonl}...")

berhasil = 0
gagal = 0

# Membuka file input (baca) dan file output (tulis) secara bersamaan
with open(input_file_jsonl, "r", encoding="utf-8") as f_in, \
     open(output_file_jsonl, "w", encoding="utf-8") as f_out:
     
    for line_num, line in enumerate(f_in, 1):
        if not line.strip():
            continue 
            
        try:
            data = json.loads(line)
            
            instruction = data.get("instruction", "")
            user_input = data.get("input", "")
            output_response = data.get("output", "")
            
            user_content = f"{user_input}"
            
            chat_structure = {
                "messages": [
                    {"role": "system", "content": instruction},
                    {"role": "user", "content": user_content},
                    {"role": "assistant", "content": output_response}
                ]
            }
            
            
            f_out.write(json.dumps(chat_structure, ensure_ascii=False) + "\n")
            berhasil += 1
            
            # Print progres setiap 2000 data agar bisa pantau
            if berhasil % 2000 == 0:
                print(f"Progres: {berhasil} data selesai diproses...")
                
        except json.JSONDecodeError:
            gagal += 1
            print(f"Peringatan: Gagal membaca baris ke-{line_num}")

print(f"\nSelesai! Berhasil mengonversi {berhasil} data.")
if gagal > 0:
    print(f"Ada {gagal} baris yang gagal/rusak.")

Memulai konversi file datasetSFT.jsonl...
Progres: 2000 data selesai diproses...
Progres: 4000 data selesai diproses...
Progres: 6000 data selesai diproses...
Progres: 8000 data selesai diproses...
Progres: 10000 data selesai diproses...
Progres: 12000 data selesai diproses...
Progres: 14000 data selesai diproses...
Progres: 16000 data selesai diproses...
Progres: 18000 data selesai diproses...
Progres: 20000 data selesai diproses...
Progres: 22000 data selesai diproses...

Selesai! Berhasil mengonversi 23895 data.

In [889]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

trl = pd.read_json("datasetSFT_TRL.jsonl", lines=True)

In [890]:
trl.head(1)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           messages
0  [{'role': 'system', 'content': 'Anda adalah sistem ahli yang mengklasifikasikan [Komentar] media sosial Indonesia ke dalam label resmi: [Netral, Disinformasi, Fitnah, Ujaran Kebencian], dengan dibantu [Artikel Rujukan] jika tersedia.

Aturan Penalaran:

1. Prioritaskan analisis pada [Komentar] untuk menentukan apakah teks tersebut mengandung klaim faktual yang memerlukan verifikasi, termasuk indikasi ujaran kebencian/SARA, atau sekadar interaksi santai.
2. Jika [Komentar] mengandung unsur serangan atau penghinaan berdasarkan identitas (SARA, ras, etnis, agama, gender, disabilitas), langsung klasifikasikan sebagai 'Ujaran Kebencian' dan ABAIKAN [Artikel Rujukan].
3. Jika tidak mengandung ujaran kebencian, gunakan [Artikel Rujukan] (atau pengetahuan internal jika rujukan kosong) untuk menilai klaim:
* Netral: Konten faktual, opini, ekspresi emosional, kritik kebijakan, atau interaksi normal yang tidak mengandung kebohongan spesifik untuk menjatuhkan reputasi.
* Disinformasi: Informasi keliru/menyesatkan yang berpotensi meresahkan masyarakat atau memicu polarisasi.
* Fitnah: Tuduhan atau klaim bohong yang spesifik dan sengaja dibuat untuk menyerang karakter, kehormatan, atau reputasi individu/kelompok.

**Format Output WAJIB (Jangan diubah):**
Penjelasan:
[Tulis analisis ringkas terhadap Komentar, perbandingannya dengan Artikel Rujukan, dan alasan pemilihan label]

Kesimpulan:
Label: [NamaLabel].'}, {'role': 'user', 'content': 'Komentar: 'wkwk beneran gmn sih islam mudah banget nyolok kafir sj';

'}, {'role': 'assistant', 'content': 'Penjelasan:
* Claim menggeneralisir seluruh umat Islam sebagai mudah menyerang (nyolok) orang yang tidak beragama (kafir).
* Penggunaan kata 'mudah nyolok' menunjukkan penilaian negatif terhadap seluruh kelompok Islam.
* Generalisasi ini menciptakan narasi bahwa umat Islam cenderung agresif dan intoleran.

Kesimpulan:
Label: Ujaran Kebencian.'}]