In [2]:
import pandas as pd
from pathlib import Path
# pd.set_option('display.max_colwidth', None)

# Fitnah

In [9]:
folderData = Path("Hasil_Parafrase")
files = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    files.append(df_sementara)

df = pd.concat(files, ignore_index=True)

In [10]:
df_fitnah = df[df["is_layak"] == 1]

In [11]:
df_fitnah[df["cot_bantuh_fitnah"].notna()]

C:\Users\Dipo\AppData\Local\Temp\ipykernel_141412\3554702674.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_fitnah[df["cot_bantuh_fitnah"].notna()]

,url,title,published_at,text,sumber_berita,label,is_layak,claim_fitnah,cot_bantah_fitnah,reasoning_fitnah,cot_bantuh_fitnah
4305,https://banten.indozone.id/news/2486375917/hin...,"Hingga September 2025, Capaian Pajak Kota Tem...",2025-10-10 12:02:12,"Kepala Bapenda Kota Serang, W Hari Pamungkas (...",indozone,Ekonomi & Bisnis,1.0,"Pemerintah Kota Serang korup, target pajak yan...",NaN,Fakta bahwa capaian pajak meningkat signifikan...,"[Capaian pajak 70,19 persen dari target tahuna..."
11532,https://news.indozone.id/world-update/91486061...,Kronologi Penembakan Donald Trump saat Kampany...,2024-07-14 10:13:12,- Sebuah penembakan terjadi pada rapat umumDon...,indozone,Politik,1.0,Trump sengaja terkena tembakan untuk mendapatk...,NaN,Claim tersebut menggunakan insinuasi dan frami...,[Fakta menunjukkan bahwa penembakan terjadi sa...

In [15]:
pinjemFithahnya = df_fitnah[["url", "title", "published_at", "text", "sumber_berita", "label"]]
pinjemFithahnya.to_json('dataset_sampledbuatFakta.jsonl', orient='records', lines=True, force_ascii=False)

In [ ]:
df_fitnah["cot_bantah_fitnah"] = df_fitnah["cot_bantah_fitnah"].fillna(df_fitnah["cot_bantuh_fitnah"])
df_fitnah = df_fitnah.drop(columns=["cot_bantuh_fitnah", "url", "published_at", "sumber_berita", "label", "is_layak"])

C:\Users\Dipo\AppData\Local\Temp\ipykernel_111500\883797873.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fitnah["cot_bantah_fitnah"] = df_fitnah["cot_bantah_fitnah"].fillna(df_fitnah["cot_bantuh_fitnah"])

In [ ]:
df_fitnah[df["reasoning_fitnah"].isna()]

C:\Users\Dipo\AppData\Local\Temp\ipykernel_111500\2068391604.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_fitnah[df["reasoning_fitnah"].isna()]

                                                                                                                  title  \
2759  Gebrakan Pramono Anung Lantik Tim Pembina Posyandu DKI Jakarta, Fokus Berantas Stunting dan TBC Sampai ke Akarnya

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               text  \
2759  Pelantikan Pembina Posyandu DKI Jakarta (timur.jakarta.go.id)\nPernahkah kamu membayangkan bahwa di balik megahnya gedung-gedung pencakar langit ibu kota, ancaman krisis kesehatan yang krusial sepertistuntingdan Tuberkulosis (TBC) masih secara nyata mengintai lingkungan di sekitar kita?\nFakta ini mungkin terdengar kontras dengan kemajuan kota, namun inilah realitas lapangan yang tengah dihadapi oleh Pemerintah Provinsi DKI Jakarta.\nMenyadari urgensi tersebut, Gubernur DKI Jakarta Pramono Anung mengambil langkah taktis pada Selasa (3/3/2026).\nBertempat di Balai Agung, Balai Kota Jakarta, beliau secara resmi melantik Tim Pembina (TP) Pos Pelayanan Terpadu (Posyandu) Tingkat Provinsi dan Kota/Kabupaten se-DKI Jakarta.\nMomen pelantikan ini bukan sekadar seremonial birokrasi biasa, melainkan sebuah deklarasi komitmen untuk "turun gunung" memberantasstuntingdan TBC langsung dari lapisan masyarakat paling bawah.\nGubernur DKI Jakarta Pramono Anung Resmikan Wajah Baru JPO Sarinah yang Penuh Sejarah dan Ramah Disabilitas\nAcara pelantikan yang berlangsung khidmat ini menjadi titik tolak baru bagi sistem pertahanan kesehatan masyarakat di Jakarta.\nDalam agenda strategis tersebut, Gubernur Pramono Anung melantik sejumlah figur sentral yang akan menjadi motor penggerak transformasi Posyandu.\nDua sosok utama di antara yang dilantik adalah Hani Pramono, yang dipercaya memegang tongkat estafet sebagai\nKetua Pembina Posyandu Provinsi DKI Jakarta, serta Essie Feransie Munjirin yang mengemban amanah strategis sebagai Ketua Tim Pembina Posyandu Kota Administrasi Jakarta Timur.\nTidak berhenti di situ, pelantikan ini juga secara serentak mengukuhkan para ketua pembina Posyandu untuk wilayah kota dan kabupaten lainnya di seluruh wilayah DKI Jakarta.\nKehadiran tokoh-tokoh penting daerah, termasuk Wali Kota Administrasi Jakarta Timur, Munjirin, semakin menebalkan pesan bahwa Pemprov DKI sangat serius dalam mengawal isu kesehatan warganya.\nFormasi baru ini diharapkan mampu menciptakan ekosistem pelayanan kesehatan yang lebih terstruktur dan masif.\nLalu, apa sebenarnya target utama dari perombakan dan penguatan struktur Posyandu ini?\nJawabannya bermuara pada dua pekerjaan rumah terbesar di sektor kesehatan ibu kota, yaitu percepatan penurunan angkastuntingpada anak dan pemberantasan penyebaran penyakit menular TBC.\nGubernur Pramono Anung, dalam arahannya, memberikan penekanan khusus pada peran vital yang dimiliki oleh Posyandu.\nBeliau menyadari betul bahwa Posyandu memiliki keistimewaan luar biasa karena kemampuannya menjangkau dan menyentuh denyut nadi masyarakat hingga ke tingkat Rukun Tetangga (RT) dan Rukun Warga (RW).\nSebagai contoh nyata di lapangan, penangananstuntingdi kawasan padat penduduk seperti Jakarta Timur atau wilayah pesisir membutuhkan pendekatan yang jauh lebih personal.\nKasus kurang gizi atau sanitasi buruk sering kali tersembunyi di balik gang-gang sempit yang sulit dipantau setiap hari oleh puskesmas atau rumah sakit.\nDishub DKI Jakarta Raih Predikat Menuju Informatif KIP 2025, Ini Catatan Penting Komisi Informasi\nDi sinilah kader Posyandu, yang notabene adalah tetangga atau bagian dari komunitas itu sendiri, dapat masuk dengan lebih mudah untuk mendeteksi dini dan memberikan edukasi.\n"Posyandu mempunyai tugas yang sangat mulia,"tegas Gubernur Pramono Anung.\nLebih lanjut, beliau menyampaikan instruksi yang sangat jelas mengenai kolaborasi,"Kami ingin Posyandu ikut berperan aktif dalam penanganan stunting, TBC, dan persoalan kesehatan lainnya. Ini harus kita kerjakan bersama antara Pemprov DKI Jakarta dan Posyandu."\nPernyataan ini menjadi alarm pengingat bahwa pemerintah tidak bisa bekerja sendirian tanpa perpanjangan tangan kader di masyarakat.\nSejalan dengan visi besar Gubernur, Ketua TP Posyandu DKI Jakarta, Hani Pramono, turut memaparkan arah baru dari pergerakan Posyandu ke depannya.\nIa menegaskan kembali bahwa Posyandu adalah tulang punggung sekaligus bagian yang tidak terpisahkan dari sistem pelayanan kesehatan masyarakat di kota metropolitan ini.\nMenurut Hani, ada misi fundamental yang harus dikawal ketat, yakni memastikan siklus kesehatan sebuah keluarga berjalan dengan optimal dan tanpa hambatan.\nMisi tersebut mencakup banyak aspek krusial. Posyandu dituntut untuk mampu memastikan bahwa setiap ibu hamil di Jakarta mendapatkan layanan pemeriksaan yang memadai, memantau secara ketat bayi dan balita agar tumbuh kembangnya sehat sesuai standar kurva kesehatan, serta memastikan seluruh anggota keluarga memperoleh edukasi kesehatan yang berkelanjutan.\nTransformasi fungsi Posyandu ini digambarkan secara apik dan visioner oleh Hani Pramono.\n"Ke depan, Posyandu tidak hanya hadir sebagai tempat pelayanan, tetapi juga sebagai pusat pembelajaran keluarga sehat, pusat pemantauan tumbuh kembang anak, dan pusat gerakan hidup sehat masyarakat perkotaan,"ungkapnya dengan penuh optimisme.\nKutipan ini mengisyaratkan sebuah pergeseran paradigma yang masif.\nJika selama ini kamu mungkin menganggap Posyandu sekadar tempat untuk menimbang berat badan balita sebulan sekali dan mendapatkan makanan tambahan, maka pandangan itu harus segera diperbarui.\nPosyandu era baru di Jakarta diproyeksikan menjadi pusat interaksi sosial yang mencerdaskan warganya mengenai gaya hidup sehat, deteksi dini penyakit menular seperti TBC, dan literasi gizi untuk mencegah stunting sejak masa kehamilan.\nTransformasi Posyandu di bawah kepemimpinan Tim Pembina yang baru dilantik ini tentu membawa angin segar bagi warga Jakarta.\nJakarta Garap Perda Sistem Pangan Pertama di Indonesia: Fokus Kelautan Kepulauan Seribu Jadi Kunci Ketahanan Pangan Masa Depan\nNamun, sehebat apa pun program yang dicanangkan oleh Pemprov DKI Jakarta, keberhasilannya pada akhirnya akan sangat bergantung pada partisipasi aktif dari kamu dan seluruh lapisan masyarakat.\nMari kita hilangkan stigma bahwa urusan kesehatan hanyalah tanggung jawab tenaga medis di rumah sakit.\nJangan ragu untuk proaktif mendatangi Posyandu terdekat di lingkungan tempat tinggalmu.\nManfaatkan setiap layanan gratis dan edukasi yang diberikan oleh para kader yang berdedikasi tinggi.\nDengan Posyandu yang semakin berdaya dan masyarakat yang peduli, cita-cita untuk mewujudkan generasi Jakarta yang sehat, cerdas, terbebas dari stunting, dan merdeka dari ancaman TBC bukanlah sekadar angan-angan belaka.\nSemuanya dimulai dari kepedulian kecil di lingkungan terdekat kita sendiri.

                                                                                                         claim_fitnah  \
2759  Pramono Anung hanya memanfaatkan pelantikan Tim Pembina Posyandu untuk pencitraan politik, tanpa ada aksi nyata

                                                                                                                                                                                                                                                                                                                                            cot_bantah_fitnah  \
2759  [Pelantikan Tim Pembina Posyandu merupakan bagian dari strategi kesehatan jangka panjang DKI Jakarta untuk menangani stunting dan TBC, Acara pelantikan dihadiri oleh Gubernur Pramono Anung dan jajaran terkait, menunjukkan bahwa ini adalah langkah yang dianggap penting, Gubernur Pramono Anung menegaskan komitmennya untuk , reasoning_fitnah: ]

     reasoning_fitnah
2759              NaN

In [ ]:
df_fitnah["reasoning_fitnah"] = df_fitnah["reasoning_fitnah"].fillna("Tidak benar")

In [ ]:
df_fitnah.isna().sum()

title                0
text                 0
claim_fitnah         0
cot_bantah_fitnah    0
reasoning_fitnah     0
dtype: int64

In [ ]:
df_fitnah["label"] = "Fitnah"

In [ ]:
# sample, buat dikasih ke mereka udah acc atau belum

# df_fitnah = df_fitnah[["text","claim_fitnah", "cot_bantah_fitnah", "reasoning_fitnah", "label"]]
# df_fitnah = df_fitnah.sample(frac=1, random_state=42).reset_index(drop=True)
# df_fitnah = df_fitnah.sample(n=50)

# df_fitnah.to_csv("sft_fitnah.csv", index=False)

In [ ]:
df_fitnah = df_fitnah.to_dict("records")

In [ ]:
len(df_fitnah)

7212

In [ ]:
instructiones = [
    "Klasifikasikan teks ke dalam salah satu label: Disinformasi, Fitnah, Ujaran Kebencian, atau Bukan DFK. Bandingkan teks dengan konteks fakta yang tersedia jika ada.",
    "Analisis teks berikut dan tentukan kategorinya: Disinformasi, Fitnah, Ujaran Kebencian, atau Bukan DFK. Gunakan rujukan fakta sebagai dasar penilaian.",
    "Periksa apakah pernyataan ini mengandung unsur Disinformasi, Fitnah, atau Ujaran Kebencian. Jika aman, tandai sebagai Bukan DFK dan bandingkan dengan fakta terkait.",
    "Tentukan label keamanan konten untuk teks berikut (Disinformasi/Fitnah/Ujaran Kebencian/Bukan DFK) berdasarkan perbandingan teks dengan informasi valid yang disertakan.",
    "Apakah teks di bawah ini termasuk hoaks (Disinformasi), tuduhan jahat (Fitnah), kebencian (Ujaran Kebencian), atau informasi normal (Bukan DFK)? Jelaskan setelah memeriksa fakta.",
    "Evaluasi narasi berikut. Identifikasi apakah terdapat indikasi Disinformasi, Fitnah, atau Ujaran Kebencian. Bandingkan konten dengan rujukan fakta untuk memastikan akurasi.",
    "Klasifikasikan input berikut ke dalam salah satu label: [Disinformasi, Fitnah, Ujaran Kebencian, Bukan DFK] berdasarkan kontradiksi atau kesesuaian dengan konteks fakta.",
    "Uji integritas teks berikut. Kategorikan sebagai Fitnah (tuduhan), Disinformasi (manipulasi fakta), Ujaran Kebencian (serangan kelompok), atau Bukan DFK (informasi valid).",
    "Lakukan screening pada teks ini dan tentukan kategorinya: Disinformasi, Fitnah, Ujaran Kebencian, atau Bukan DFK. Sertakan alasan yang merujuk pada berita atau fakta terkait.",
    "Identifikasi jenis pelanggaran konten pada teks berikut (Disinformasi/Fitnah/Ujaran Kebencian). Jika tidak ditemukan pelanggaran fakta atau etika, beri label Bukan DFK.",
    "Tolong bantu klasifikasikan pesan ini. Apakah masuk kategori Disinformasi, Fitnah, Ujaran Kebencian, atau informasi aman (Bukan DFK)? Gunakan data fakta terlampir untuk memverifikasi."
]

kalimat_penutup = [
    "**Selalu pastikan untuk memverifikasi informasi melalui saluran berita resmi guna menghindari penyebaran hoaks.**", 
    "**Mari lebih bijak dalam menyerap informasi dengan selalu merujuk pada sumber data yang valid dan terpercaya.**",
    "**Jangan mudah terprovokasi oleh klaim sepihak; pastikan Anda mengecek fakta dari otoritas terkait.**",
    "**Penting untuk selalu melakukan kroscek terhadap berita yang beredar agar terhindar dari pengaruh informasi palsu.**",
    "**Pastikan untuk selalu memeriksa sumber berita resmi dan kredibel guna mendapatkan fakta yang akurat.**",
    "**Lindungi diri dari misinformasi dengan membiasakan cek fakta melalui media informasi pemerintah atau lembaga resmi.**",
    "**Tetap waspada terhadap narasi negatif; selalu cari konfirmasi dari sumber berita yang memiliki reputasi baik.**",
    "**Verifikasi adalah kunci. Selalu bandingkan informasi yang Anda terima dengan laporan dari pihak berwenang.**",
    "**Demi mendapatkan pemahaman yang utuh, pastikan Anda hanya merujuk pada informasi dari kanal-kanal resmi.**",
    "**Ayo lawan hoaks dengan selalu mengutamakan data dari sumber berita yang sah dan dapat dipertanggungjawabkan.**"
]

In [ ]:
import json
import random

def generate_sft_dataset_with_context(raw_data_list, instructions, penutup_list, output_file):
    dataset = []
    
    for data in raw_data_list:
        instruct = random.choice(instructions)
        claim = data.get("claim_fitnah", "")
        berita = data.get("text", "") 
        label = data.get("label")
        reasoning = data.get("reasoning_fitnah", "")
        cot_list = data.get("cot_bantah_fitnah", [])
        
        # Susun poin-poin fakta
        fakta_points = "\n".join([f"* {point}" for point in cot_list])
        closing = random.choice(penutup_list)
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"input: {claim};\n\n"
            f"fakta: {berita}"
        )

        full_output = (
            f"Label: **{label}.** "
            f"penjelasan: {reasoning}\n\n"
            f"Berikut adalah beberapa fakta sebenarnya:\n"
            f"{fakta_points}\n\n"
            f"{closing}"
        )
        
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(df_fitnah, instructiones, kalimat_penutup, "fitnah.jsonl")

Berhasil membuat 7212 data dengan konteks berita di fitnah.jsonl

In [ ]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

df = pd.read_json("fitnah.jsonl", lines=True)
df

,instruction,input,output
0,"Tolong bantu klasifikasikan pesan ini. Apakah masuk kategori Disinformasi, Fitnah, Ujaran Kebencian, atau informasi aman (Bukan DFK)? Gunakan data fakta terlampir untuk memverifikasi.","input: BNN sengaja pilih kampung miskin buat dijadikan kambing hitam soal narkoba;\n\nfakta: BNN menggedebek kampung narkoba di Berlan, Matraman, Jakarta Timur. (Antara Foto/Fauzan)\n- Badan Narkotika Nasional (BNN) bersama petugas gabungan menggerebek kawasan Berlan, Matraman, Jakarta Timur, terkait dugaan peredarannarkobapada Selasa (25/11/2025) siang.\nDalam operasi tersebut, puluhan orang yang diduga sebagai pengedar berhasil diamankan.\nPenggerebekan dilakukan sekitar pukul 11.00 WIB. Petugas gabungan melakukan penyisiran ke sejumlah rumah dan langsung melakukan penggeledahan di titik-titik yang telah ditargetkan.\nDari lokasi, petugas menemukan berbagai jenis barang bukti narkoba dalam bentuk bubuk maupun cairan.\nSejumlah paket narkoba ditemukan disembunyikan di lemari hingga gudang-gudang kecil yang berada di dalam rumah warga.\nTerungkap! Ekstasi Rp 207 M Ditemukan Saat Mobil Kecelakaan di Lampung Hendak Disebar di Jakarta\nUntuk mempermudah pencarian barang bukti, petugas juga mengerahkan anjing pelacak (K9).\nLangkah ini dilakukan untuk memastikan tidak ada narkoba yang terlewatkan selama proses penggeledahan.\nDirektur Psikotropika dan Prekursor Deputi Bidang Pemberantasan BNN, Aldrin Marihot Pandapotan Hutabarat, menyampaikan bahwa pihaknya mengamankan puluhan orang dalam operasi tersebut.\n""Ada 10–15 titik yang menjadi target penggerebekan di kawasan Berlan. Dari rangkaian penggerebekan itu, kami mengamankan 25 pelaku,"" ujar Aldrin.\nSeluruh orang yang diamankan langsung dibawa ke kantor BNN untuk pemeriksaan lebih lanjut. Ia menyebut bahwa para pelaku merupakan warga sekitar.\n""Kawasan ini merupakan perkampungan. Semua yang kami amankan adalah warga sipil. Kami akan dalami peran masing-masing,"" pungkasnya.","Label: **Fitnah.** penjelasan: Fakta dipelintir dengan menuduh BNN memilih kampung miskin sebagai kambing hitam, padahal operasi ini didasarkan pada informasi intelijen dan bukti yang ditemukan di lapangan\n\nBerikut adalah beberapa fakta sebenarnya:\n* BNN melakukan penggerebekan di Berlan, Matraman, berdasarkan informasi dan indikasi kuat adanya peredaran narkoba di kawasan tersebut\n* Operasi ini melibatkan petugas gabungan dan menggunakan anjing pelacak (K9) untuk memastikan keakuratan dan efektivitas penggeledahan\n* Berbagai jenis barang bukti narkoba ditemukan di lokasi, termasuk bubuk dan cairan yang disembunyikan di lemari dan gudang-gudang kecil\n* Penggerebekan ini mengamankan puluhan orang yang diduga sebagai pengedar, bukan sembarangan warga miskin\n* Tindakan BNN ini adalah bagian dari upaya nasional untuk memerangi peredaran narkoba, tidak ada indikasi pemilihan target berdasarkan status sosial ekonomi\n\n**Jangan mudah terprovokasi oleh klaim sepihak; pastikan Anda mengecek fakta dari otoritas terkait.**"
1,"Klasifikasikan teks ke dalam salah satu label: Disinformasi, Fitnah, Ujaran Kebencian, atau Bukan DFK. Bandingkan teks dengan konteks fakta yang tersedia jika ada.","input: DPRD Berau sengaja lambatkan serapan anggaran untuk menutupi korupsi;\n\nfakta: KALIMANTAN TIMUR - Serapan anggaran Pemerintah KabupatenBeraupada semester pertama tahun anggaran 2025 mendapat sorotan dari DPRD. Dalam rapat evaluasi laporan semester pertama dan rencana kerja enam bulan ke depan, DPRD menilai realisasi anggaran masih jauh dari ideal.\nWakil Ketua I DPRD Berau, Subroto, menyebut serapan anggaran secara keseluruhan baru mencapai sekitar 38 persen. Angka tersebut dinilai masih rendah, meski dipahami ada sejumlah proyek besar yang masih dalam tahap lelang.\n""Penyerapan anggaran secara global baru 38 persen. Ini memang belum sesuai harapan, tapi kita pahami banyak pekerjaan besar masih dalam proses lelang,"" kata Subroto.\nBeberapa Organisasi Perangkat Daerah (OPD) seperti Dinas Pendidikan, Dinas Kesehatan, dan Dinas Pekerjaan Umum dan Penataan Ruang (PUPR) disebut sebagai pemilik anggaran terbesar, namun hingga kini masih dalam proses pengadaan.\n""Dari sekitar 400 paket pekerjaan, 90 persen di antaranya sudah masuk proses lelang. Jadi belum bisa diserap ke anggaran karena menunggu tahapan selesai,"" ujarnya.\nSubroto menyebut target penyelesaian proses lelang ditetapkan pada bulan September. Setelah itu, ia berharap serapan anggaran bisa meningkat signifikan di semester kedua.\nIa juga menyoroti persoalan teknis yang menghambat proses lelang, terutama terkait keterbatasan SDM bersertifikasi di Unit Layanan Pengadaan (ULP).\n""Tenaga pelaksana lelang yang bersertifikat masih terbatas, ini jadi kendala utama. Tapi ke depan persoalan ini segera dituntaskan,"" ungkapnya.\nMeski demikian, DPRD tetap optimistis target serapan anggaran di akhir tahun bisa tercapai. Subroto menegaskan pentingnya keseriusan seluruh OPD agar tak terjadi Sisa Lebih Pembiayaan Anggaran (Silpa).\n""Kami harap di akhir tahun nanti serapan bisa maksimal. Jangan sampai ada anggaran yang tidak terserap,"" pungkasnya. (*)","Label: **Fitnah.** penjelasan: Claim ini menggunakan framing negatif dan insinuasi untuk menyudutkan DPRD Berau, padahal fakta menunjukkan bahwa DPRD justru mengkritisi dan memantau proses serapan anggaran dengan transparan.\n\nBerikut adalah beberapa fakta sebenarnya:\n* DPRD Berau menyoroti rendahnya serapan anggaran, bukan menutupinya. Mereka justru mengkritisi hal tersebut.\n* Wakil Ketua I DPRD Berau, Subroto, menjelaskan bahwa banyak proyek besar masih dalam tahap lelang, yang mempengaruhi rendahnya serapan anggaran.\n* Subroto menyebutkan bahwa 90 persen dari sekitar 400 paket pekerjaan sudah masuk proses lelang, menunjukkan transparansi dalam proses pengadaan.\n* Target penyelesaian proses lelang ditetapkan pada bulan September, dan DPRD berharap serapan anggaran akan meningkat signifikan setelah itu.\n\n**Lindungi diri dari misinformasi dengan membiasakan cek fakta melalui media informasi pemerintah atau lembaga resmi.**"
2,Tentukan label keamanan konten untuk teks berikut (Disinformasi/Fitnah/Ujaran Kebencian/Bukan DFK) berdasarkan perbandingan teks dengan informasi valid yang disertakan.,"input: Sandiaga Uno hanya memanfaatkan relawan untuk kepentingan pribadi di Pilpres 2024;\n\nfakta: Sandiaga Uno dalam acara silaturahmi dengan para relawan.- Sandiaga Uno mengingatkan para relawan pendukungnya untuk bekerja keras mendukung pasangan bakal capres dan cawapres Ganjar Pranowo-Mahfud MD.Menurut Sandi, hal ini penting dilakukan karena relawan punya peran penting dalam mendulang suara di masa Pemilu 2024.Hal ini disampaikan Sandiaga Uno dalam acara silaturahmi dengan relawan di Aula Attaqwa Sriwijaya, Kebayoran Baru, Jakarta Selatan, kemarin.Kegiatan inti dari acara ini adalah untuk menyerap aspirasi para relawan dan memungkinkan mereka menyampaikan aspirasinya.Dalam kegiatan tersebut relawan-relawan berkumpul dan memberikan masukan yang berharga, yang akan menjadi dasar untuk merancang program dan gagasan yang mendukung visi Ganjar Pranowo dan Mahfud MD.\nMenurut Sandi, para relawan mengharapkan agar kedepan ekonomi hijau, harga-harga murah, mencari kerja mudah, dan hidup berkah.""Ini yang akan saya sampaikan atas masukan dan aspirasi ke relawan seluruh Indonesia untuk disampaikan kepada para dewan pakar yang nanti akan menyusun satu program gagasan,"" kata Sandiaga Uno dalam pernyataan resmi, Senin (30/10/2023).\nSandiaga Uno dalam acara silaturahmi dengan para relawan.""Nanti ditampilkan bagaimana agar memberikan percepatan pembangunan untuk menghadapi beberapa tantangan yang disampaikan para relawan,"" imbuhnya.Sandiaga juga meminta para relawan untuk tetap berpartisipasi dalam membangun pemilu yang kondusif dan pemilu yang damai yang mempersatukan bangsa. Dia juga meminta para relawan untuk bekerja keras agar pasangan Ganjar-Mahfud meraih kemenangan di Pilpres 2024.\nMenurut politikus PPP ini, para relawan memiliki peran strategis dan krusial untuk mencapai tujuan tersebut. Dia mencontohkan apa yang terjadi pada Pilpres 2019, di mana para relawan menyumbangkan suara strategis bagi para kandidat.\n""Di 2019 peran relawan ini sangat besar, para relawan ini menyumbangkan suara yang sangat signifikan dan diatas prediksi dari para lembaga survei,"" kata Sandiaga.Salah satu relawan, Aisyah Mochamed dari Rumah SandiUno Indonesia (RSI) NTB, mengungkapkan rasa terima kasihnya atas undangan dari Sandiaga Uno. Ia merasa terinspirasi dan bertekad untuk mendukung pasangan Ganjar Pranowo dan Mahfud MD.""Mentor kita kan memang Pak Sandi ya jadi arahan dari beliau Insyaallah kita akan mensupport Pak Ganjar. Terima kasih Pak Sandi sudah mengundang kami, dari sini kedepan kita tau arah tujuan yang diinginkan Pak Sandiaga untuk Indonesia,"" kata Aisyah.","Label: **Fitnah.** penjelasan: Claim ini menggunakan framing negatif dan insinuasi untuk menyudutkan Sandiaga Uno, padahal fakta menunjukkan bahwa acara silaturahmi bertujuan untuk mendukung pasangan Ganjar Pranowo-Mahfud MD dan memperkuat visi mereka.\n\nBerikut adalah beberapa fakta sebenarnya:\n* Sandiaga Uno mengingatkan relawan untuk mendukung pasangan Ganjar Pranowo-Mahfud MD, bukan untuk kepentingan pribadinya.\n* Acara silaturahmi bertujuan untuk menyerap aspirasi relawan dan merancang program yang mendukung visi Ganjar Pranowo dan Mahfud MD.\n* Sandiaga Uno menekankan pentingnya peran relawan dalam mendulang suara untuk pasangan Ganjar-Mahfud, bukan untuk agenda pribadinya.\n* Relawan memberikan masukan yang berharga, yang akan menjadi dasar untuk merancang program dan gagasan yang mendukung visi Ganjar Pranowo dan Mahfud MD.\n\n**Penting untuk selalu melakukan kroscek terhadap berita yang beredar agar terhindar dari pengaruh informasi palsu.**"
3,"Identifikasi jenis pelanggaran konten pada teks berikut (Disinformasi/Fitnah/Ujaran Kebencian). Jika tidak ditemukan pelanggaran fakta atau etika, beri label Bukan DFK.","input: BPBD DKI Jakarta main-main sama cuaca, bikin hujan buatan biar dapet dana darurat!;\n\nfakta: Ilustrasi cuaca ekstrem. (ANTARA FOTO/Dedhez Anggara)\nBadan Penanggulangan Bencana Daerah (BPBD)DKI Jakartakembali melakukan operasimodifikasi cuaca(OMC) dalam rangka mengantisipasicuaca ekstrem. Hal itu disampaikan langsung oleh Kepala PelaksanaBPBDDKI Jakarta, Isnawa Adji.\n""Rencana penerbangan OperasiModifikasi Cuaca(OMC) dalam rangka kesiapsiagaan menghadapi bencana hidrometeorologi ekstrem di ProvinsiDKI Jakarta,"" kata Isnawa, seperti INDOZONE sadur dari Antara, Sabtu (31/1/2026).\nOperasi tersebut, kata dia, merupakan hasil sinergi antara BPBD DKI Jakarta dengan Badan Nasional Penanggulangan Bencana (BNPB), Badan Meteorologi, Klimatologi dan Geofisika (BMKG), TNI Angkatan Udara, serta unsur terkait lainnya.\nRibuan Hektare Sawah di Karawang Terendam Banjir Akibat Cuaca Ekstrem\nDia menjelaskan pada sorti pertama, pesawat melakukan penyemaian awan di perairan utara Jakarta pada ketinggian 8.000-11.000 kaki. Pada sorti ini, digunakan bahan semai berupa Kalsium Oksida (CaO) sebanyak 800 kilogram.\nSorti kedua, dilaksanakan dengan fokus penyemaian awan di wilayah barat daya Jakarta, penerbangan dilakukan pada ketinggian 7.000-8.000 kaki.\nBMKG Ingatkan Cuaca Ekstrem, Hujan hingga Petir Siap Guyur Sejumlah Daerah\n""Pada sorti ini, digunakan bahan semai berupa Natrium Klorida (NaCl) sebanyak 800 kilogram,"" ujar Isnawa.\nLebih lanjut, dia menyebutkan OMC tersebut dilakukan berdasarkan analisis kondisi atmosfer serta pemantauan cuaca secara berkelanjutan, sehingga penyemaian awan dapat diarahkan ke wilayah yang lebih aman.\nBPBD Provinsi DKI Jakarta terus melakukan evaluasi harian terhadap pelaksanaan OMC serta memperkuat koordinasi lintas instansi guna memastikan kesiapsiagaan menghadapi potensi bencana hidrometeorologi di wilayah DKI Jakarta dan sekitarnya.","Label: **Fitnah.** penjelasan: Claim ini memanfaatkan framing negatif dan insinuasi bahwa BPBD DKI Jakarta melakukan manipulasi cuaca untuk keuntungan pribadi. Fakta sebenarnya, OMC adalah upaya preventif yang dilakukan secara profesional dan transparan untuk mengantisipasi bencana cuaca ekstrem.\n\nBerikut adalah beberapa fakta sebenarnya:\n* Operasi Modifikasi Cuaca (OMC) adalah tindakan preventif yang dilakukan BPBD DKI Jakarta untuk mengantisipasi cuaca ekstrem, bukan untuk menciptakan hujan buatan.\n* OMC dilakukan dengan sinergi berbagai institusi seperti BNPB, BMKG, dan TNI Angkatan Udara, bukan aksi sembarangan.\n* Tujuan utama OMC adalah untuk mengurangi risiko bencana hidrometeorologi, bukan untuk mendapatkan dana darurat.\n* Fakta bahwa OMC menggunakan bahan semai Kalsium Oksida (CaO) dan dilakukan di ketinggian tertentu menunjukkan bahwa ini adalah proses ilmiah yang terencana.\n* BPBD DKI Jakarta telah menjelaskan secara transparan tentang rencana dan pelaksanaan OMC, termasuk ketinggian penerbangan dan jumlah bahan semai yang digunakan.\n\n**Penting untuk selalu melakukan kroscek terhadap berita yang beredar agar terhindar dari pengaruh informasi palsu.**"
4,"Uji integritas teks berikut. Kategorikan sebagai Fitnah (tuduhan), Disinformasi (manipulasi fakta), Ujaran Kebencian (serangan kelompok), atau Bukan DFK (informasi valid).","input: Pemprov Sumut hanya main-main dengan UHC, masyarakat masih susah akses kesehatan!;\n\nfakta: Capaian Universal Health Coverage (UHC) Sumatera Utara kini sudah mencapai angka 98,6%. Pemprov Sumut menegaskan komitmennya memberikan layanan kesehatan optimal bagi seluruh warganya.\nHal ini disampaikan Kepala Dinas Kesehatan Sumut, Faisal Hasrimi, dalam konferensi pers di Kantor Gubernur Sumut, Rabu (17/9/2025). Menurutnya, capaian ini diperoleh lewat pembagian beban premi antara Pemprov dengan Pemkab/Pemko.\nSkemanya, kabupaten/kota menanggung 80% dan Pemprov 20%. Dalam lima tahun ke depan, komposisi ini akan berubah menjadi 70% kabupaten/kota dan 30% Pemprov.\nFaisal menegaskan, pembayaran premi tidak tumpang tindih dengan pemerintah pusat. Setiap tingkatan pemerintahan sudah diatur targetnya. Hal ini memastikan efisiensi dalam program kesehatan.\nDorong Keterbukaan, Bobby Nasution Ingatkan OPD Lebih Transparan ke Publik\nSelain itu, tingkat kepatuhan peserta mandiri membayar iuran BPJS Kesehatan juga harus dijaga. Saat ini, sekitar 80% peserta aktif melakukan pembayaran.\nMenurut Faisal, UHC di Sumut bukan sekadar simbol. ""Kita tidak mau UHC ecek-ecek. Komitmen kita agar layanan benar-benar berjalan,"" ujarnya.\nMulai September, masyarakat bisa berobat gratis hanya dengan membawa KTP. Administrasi akan diurus petugas fasilitas kesehatan. Warga tidak perlu lagi repot fotokopi KTP atau syarat lainnya.\nPemprov bersama BPJS Kesehatan sudah bekerja sama dengan 172 rumah sakit, 619 puskesmas, dan 510 klinik untuk mendukung layanan ini. Semua fasilitas diwajibkan melayani pasien terlebih dahulu sebelum urusan administrasi.\nBPJS Ketenagakerjaan Jadi Prioritas, Pemprov Sumut Dorong Kepatuhan Iuran\nSelain layanan kesehatan gratis, Pemprov juga memberikan beasiswa Program Pendidikan Dokter Spesialis (PPDS). Tujuh putra-putri dari Nias menerima beasiswa dan akan kembali mengabdi di daerah asal.\nDi sisi lain, Kepala BKAD Sumut, Timur Tumanggor, menyebut Pemprov telah menyiapkan Rp297 miliar untuk program UHC di 2025. Anggaran ini meningkat menjadi Rp438 miliar pada 2026.\nKonferensi pers juga dihadiri sejumlah pejabat, termasuk Kepala Bappelitbang Sumut Dikky Anugerah, Dirut RSU Haji Medan Sri Suriani Purnamawati, dan Kabid IKP Diskominfo Sumut Harvina Zuhra.\nDengan komitmen ini, Pemprov berharap tidak ada lagi warga yang kesulitan mengakses layanan kesehatan. Semua masyarakat berhak mendapatkan pelayanan yang layak dan cepat.","Label: **Fitnah.** penjelasan: Fakta menunjukkan capaian UHC yang tinggi dan komitmen Pemprov Sumut untuk memastikan layanan kesehatan yang optimal. Narasi negatif ini melebih-lebihkan isu akses kesehatan dan meragukan komitmen pemerintah.\n\nBerikut adalah beberapa fakta sebenarnya:\n* Capaian UHC Sumut mencapai 98,6%, menunjukkan komitmen kuat Pemprov dalam menyediakan layanan kesehatan bagi warga.\n* Pembagian beban premi antara Pemprov dan Pemkab/Pemko memastikan efisiensi dan keberlanjutan program.\n* Kepala Dinas Kesehatan Sumut, Faisal Hasrimi, menegaskan bahwa UHC bukan sekadar simbol, melainkan program yang benar-benar berjalan.\n* Masyarakat kini bisa berobat gratis hanya dengan membawa KTP, mempermudah akses kesehatan.\n\n**Tetap waspada terhadap narasi negatif; selalu cari konfirmasi dari sumber berita yang memiliki reputasi baik.**"
...,...,...,...

In [ ]:
text= "Women Okezone menyajikan berita terbaru dan terpercaya seputar dunia perempuan. Dapatkan informasi terkini tentang gaya hidup, kesehatan, karier, dan inspirasi wanita di Indonesia." 

print(len(text))

180

# Disinformasi

In [ ]:
folderData = Path("Dataset_disinformasi")
files = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    files.append(df_sementara)

df = pd.concat(files, ignore_index=True)

In [ ]:
df_disinformasi = df[df["is_layak"] == 1]

In [ ]:
len(df_disinformasi)

7995

In [ ]:
df_disinformasi.isna().sum()

claim_disinformasi            0
berita_asli                   0
label                         0
is_layak                      0
cot_bantah_disinformasi       4
reasoning_disinformasi        0
cot_bantuh_disinformasi    7991
dtype: int64

In [ ]:
df_disinformasi["cot_bantah_disinformasi"] = df_disinformasi["cot_bantah_disinformasi"].fillna(df_disinformasi["cot_bantuh_disinformasi"])

C:\Users\Dipo\AppData\Local\Temp\ipykernel_111500\3732640420.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_disinformasi["cot_bantah_disinformasi"] = df_disinformasi["cot_bantah_disinformasi"].fillna(df_disinformasi["cot_bantuh_disinformasi"])

In [ ]:
df_disinformasi = df_disinformasi.drop(columns=["cot_bantuh_disinformasi", "is_layak"])

In [ ]:
df_disinformasi

,claim_disinformasi,berita_asli,label,cot_bantah_disinformasi,reasoning_disinformasi
0,"Heboh! Pemuda Bakar Mobil Mercedes Karena Buatan Prancis, Padahal Aslinya...","Beredar di media sosial sebuah video yang diklaim memperlihatkan seorang pemuda membakar mobil karena buatan Prancis. Faktanya, klaim adanya pemuda yang membakar mobil miliknya karena mobil tersebut buatan Prancis adalah salah. Dikutip dari Turnbackhoax.id, mobil yang dibakar di video itu adalah Mercedes AMG GT 63 S buatan Jerman. Pria dalam video tersebut bernama Misha atau dikenal sebagai Mikhail Litvin, vlogger asal Rusia. Aksi membakar mobil itu disebabkan oleh rasa kesal karena mobil senilai 13 juta rubel Rusia (Rp 2 miliar) yang dibelinya sering rusak dan keengganan pabrikan untuk menerima tanggung jawab (menanggung biaya perbaikan). Jadi, aksi membakar mobil tersebut tidak ada kaitannya dengan Prancis.",Disinformasi,"[Mobil yang dibakar adalah Mercedes AMG GT 63 S, buatan Jerman, bukan Prancis (sumber: Turnbackhoax.id)., Pria dalam video tersebut adalah Mikhail Litvin, vlogger asal Rusia, yang membakar mobil karena masalah teknis dan keengganan pabrikan untuk bertanggung jawab., Aksi pembakaran mobil tidak ada hubungannya dengan asal negara pembuatan mobil tersebut.]",Ini adalah konten menyesatkan yang mencatut nama negara pembuatan mobil untuk menciptakan narasi yang provokatif dan mengecoh publik.
1,"Waspada! Paket Narkoba Dikirim ke Rumah Warga, Hoax atau Nyata?","Telah beredar pesan berantai whatsaap tentang pengiriman paket Narkoba dari luar negeri maupun dalam negeri yang ditujukan ke beberapa alamat yang sengaja disalahkan untuk mengecoh petugas yang berwajib. setelah ditelusuri lebih lanjut ternyata pesan tersebut pernah beredar dua tahun yang lalu tepatnya di bulan februari 2017 kemudian di sebar luaskan lagi, jadi pesan berantai tersebut merupakan informasi tidak benar atau hoaks.",Disinformasi,"[Pesan berantai tersebut telah beredar sejak Februari 2017 dan kembali disebar tanpa perubahan konten (sumber: klarifikasi dari otoritas setempat)., Informasi tentang pengiriman paket narkoba ke alamat warga adalah tidak benar dan merupakan hoaks., Otoritas keamanan tidak melaporkan adanya peningkatan kasus pengiriman narkoba melalui paket.]","Ini adalah pesan berantai yang dirancang untuk menakut-nakuti masyarakat dan mengecoh petugas keamanan, dengan menyebarkan informasi yang sudah lama tidak akurat."
2,"Berbahaya! Pinjaman Online Fintech Gunakan Data Gojek dan Tokopedia, Benarkah?","Telah Beredar sebuah postingan di media sosial facebook tentang berita Pinjaman Online Fintech Gunakan Data Gojek dan Tokopedia. Faktanya setelah ditelusuri perusahaan ride-hailing Indonesia Gojek membantah pihaknya memberikan data pengguna kepada pihak lain, termasuk pada aplikasi pinjaman online. Dalam pernyataan Gojek yang diterima Tekno Liputan6.com, Minggu (28/7/2019), Director Corporate Affairs Gojek Nila Marita mengatakan, Gojek selalu menjaga keamanan maksimum dari data pribadi pelanggan maupun para mitra. Sedangkan dari Tokopedia melalui Corporate Communications Nuraini Razak mengatakan, Tokopedia tidak menemukan adanya kebocoran atau pembobolan data oleh pihak ketiga terhadap data rahasia pengguna.",Disinformasi,"[Gojek membantah memberikan data pengguna kepada pihak lain, termasuk aplikasi pinjaman online (sumber: pernyataan resmi Gojek)., Tokopedia juga membantah adanya kebocoran data pengguna ke pihak ketiga (sumber: pernyataan resmi Tokopedia)., Kedua perusahaan menegaskan bahwa mereka menjaga keamanan maksimum dari data pribadi pelanggan.]",Ini adalah konten menyesatkan yang bertujuan untuk merusak reputasi perusahaan dan menimbulkan kekhawatiran publik terhadap keamanan data.
3,"Sensasional! WHO Sebut 377 Orang dari 100.000 Meninggal karena Vaksin, Benarkah?","Beredar unggahan di media sosial Facebook yang berisi data terkait kematian akibat vaksin Covid-19 yang diklaim bersumber dari Badan Kesehatan Dunia (WHO). Pengunggah menuliskan, 377 orang dari setiap 100.000 orang meninggal karena vaksin Covid-19. Dalam postingan itu tertulis, menurut studi WHO yang bocor, jika mereka menghentikan vaksinasi, minimal 377 orang dari setiap 100 ribu orang yang seharusnya disuntik akan hidup. Dilansir dari Kumparan.com yang mengutip dari Reuters, pada akhir Maret 2021, WHO melaporkan vaksin Covid-19 aman dan efektif. Laporan itu dibuat menyusul adanya kasus pembekuan darah yang dikaitkan dengan pemberian vaksin AstraZeneca. Reuters juga menegaskan, pihaknya tidak menemukan data-data terkait kematian yang diklaim oleh pengguna Facebook tersebut. Pihak WHO juga telah memberikan pernyataan bahwa data tersebut tidak pernah ada. Lembaga tersebut menambahkan, ""vaksin, seperti semua obat, dapat memiliki efek samping. Pemberian vaksin didasarkan pada analisis risiko versus manfaat"".",Disinformasi,"[WHO telah membantah adanya data tersebut dan menyatakan bahwa klaim tersebut tidak benar (sumber: pernyataan resmi WHO)., Reuters tidak menemukan data terkait kematian yang diklaim dalam unggahan tersebut., Vaksin, termasuk vaksin Covid-19, telah diuji dan dianggap aman serta efektif oleh WHO.]","Ini adalah modus fabrikasi data yang bertujuan untuk mengecoh publik dan menimbulkan ketakutan terhadap vaksinasi, yang dapat menghambat upaya kesehatan masyarakat."
4,"Mengerikan! Reporter Mursal Meninggal Terbunuh Setelah Memaparkan Limbah Minyak Goreng, Benarkah?","Belakangan beredar broadcast whatsapp tentang seorang reporter bernama mursal terbunuh setelah memaparkan limbah minyak goreng. Setelah ditelusuri ternyata kejadian tersebut tidak terjadi di Indonesia, melainkan terjadi di China pada tahun 2011 lalu. Nama korban yang terbunuh adalah Li Xiang, bukan Mursal seperti yang tertulis dalam pesan broadcast yang beredar. Li Xiang terbunuh setelah mengungkap fasilitas pengolahan limbah bekas dan kotor di Cina. Limbah itu berasal dari saluran pembuangan restoran dan toilet serta sumber limbah minyak kotor lainnya. Minyak goreng olahan yang berasal dari Limbah itu kemudian dijual ke pasaran dengan harga murah. Minyak goreng limbah itu menurut ahli kesehatan sangat membahayakan kesehatan manusia dan dapat menyebabkan kanker ganas.",Disinformasi,"[Kejadian tersebut terjadi di China pada tahun 2011, bukan di Indonesia (sumber: klarifikasi dari otoritas setempat)., Korban bernama Li Xiang, bukan Mursal, dan terbunuh setelah mengungkap fasilitas pengolahan limbah minyak kotor di Cina., Limbah minyak goreng yang dipaparkan oleh Li Xiang berasal dari saluran pembuangan restoran dan toilet, serta sumber limbah minyak kotor lainnya.]",Ini adalah konten menyesatkan yang mencatut nama dan kejadian yang tidak terkait untuk mengecoh publik dan menciptakan narasi yang sensasional.
...,...,...,...,...,...
7995,"Heboh! Kasus Covid-19 di Surabaya Hanyalah Konspirasi Elite Global, Jangan Percaya!","Beredar di sosial media sebuah hasil tangkapan layar berupa percakapan di WhatsApp yang berisi narasi bahwa parahnya kasus virus Corona Covid-19 di Surabaya hanyalah konspirasi elite global. Faktanya dikutip dari cekfakta.tempo.co, klaim bahwa parahnya kasus Covid-19 di Surabaya hanyalah konspirasi elite global adalah keliru. Jumlah kasus Covid-19 di Jawa Timur memang meningkat lebih dari 300 persen namun menurut sejumlah Ahli dan Pejabat Gugus Tugas Percepatan Penanganan Covid-19, terdapat empat faktor yang menyebabkan kasus Covid-19 di Surabaya melonjak, antara lain semakin masifnya tes, besarnya mobilitas penumpang di Bandara Internasional Juanda, transmisi lokal, dan tidak berjalannya PSBB sesuai harapan. Selain itu, penelitian menyatakan bahwa virus Corona penyebab Covid-19, SARS-CoV-2, bukanlah hasil manipulasi laboratorium.",Disinformasi,"[Cekfakta.tempo.co membantah klaim bahwa parahnya kasus Covid-19 di Surabaya adalah konspirasi elite global., Data resmi dari Gugus Tugas Percepatan Penanganan Covid-19 menunjukkan peningkatan kasus di Surabaya disebabkan oleh faktor-faktor seperti semakin masifnya tes, mobilitas tinggi di Bandara Internasional Juanda, transmisi lokal, dan tidak berjalannya PSBB sesuai harapan., Penelitian ilmiah menyatakan bahwa virus SARS-CoV-2, penyebab Covid-19, bukan hasil manipulasi laboratorium, melainkan evolusi alami dari virus korona., Klaim konspirasi tersebut tidak didukung oleh bukti ilmiah dan hanya bertujuan untuk menciptakan ketidakpercayaan terhadap upaya penanganan pandemi.]","Ini adalah modus fabrikasi yang mencoba menggambarkan situasi pandemi sebagai konspirasi. Tujuannya adalah untuk menyebar ketidakpercayaan terhadap otoritas kesehatan dan upaya penanganan pandemi, yang dapat berdampak negatif pada kesehatan publik."
7996,"Wah, ngeri! Ini video jatuhnya pesawat Lion Air JT610 yang hilang kontak di Indonesia!",Video ini BUKAN jatuhnya pesawat Lion Air JT 610. Tetapi ini adalah pesawat Ethiopian Airlines Flight 961 saat jatuh ke Samudra Hindia pada tanggal 23 November 1996.,Disinformasi,"[Video tersebut bukan jatuhnya pesawat Lion Air JT610, melainkan Ethiopian Airlines Flight 961 yang jatuh pada 23 November 1996 di Samudra Hindia., Faktanya, Lion Air JT610 jatuh di perairan Karawang, Jawa Barat, dan tidak ada video rekaman langsung dari kejadian tersebut., Akun resmi Lion Air dan otoritas penerbangan Indonesia tidak pernah membagikan video tersebut sebagai bukti kecelakaan JT610., Video tersebut telah beredar sejak lama dan sering digunakan untuk menyesatkan publik dengan mengaitkannya dengan berbagai kecelakaan pesawat lainnya.]",Ini adalah modus fabrikasi yang menyesatkan dengan mencatut kejadian tragis Lion Air JT610 untuk mendapatkan perhatian dan engagement. Video tersebut telah direkayasa untuk menimbulkan kepanikan dan ketakutan di masyarakat.
7997,"Ngeri! Wanita tewas terjatuh di stasiun MRT Jakarta, patah leher dan dibawa ke RSCM!","Beredar di media sosial Facebook sebuah unggahan video yang merekam kejadian seorang wanita terjatuh saat menuruni anak tangga. Video tersebut beredar dengan narasi yang mengeklaim bahwa kejadian tersebut terjadi di stasiun Mass Rapid Transit (MRT) Jakarta. Kemudian, wanita yang terjatuh itu meninggal seketika akibat patah leher dan dibawa ke Rumah Sakit Umum Pusat Nasional Dr. Cipto Mangunkusumo (RSCM) untuk diautopsi. Faktanya, klaim yang menyebut seorang wanita meninggal akibat terjatuh di stasiun MRT Jakarta adalah keliru. Adapun, kejadian tersebut bukan terjadi di stasiun MRT Jakarta, melainkan terjadi di Kota Hefei, Provinsi Anhui, Cina pada 17 Oktober 2020. Berdasarkan artikel dari media Cina, The Paper, wanita tersebut juga tidak meninggal dunia, melainkan mengalami luka serius di wajahnya. Wanita tersebut juga langsung dilarikan ke rumah sakit untuk mendapat perawatan.",Disinformasi,"[Kejadian tersebut bukan terjadi di stasiun MRT Jakarta, melainkan di Kota Hefei, Provinsi Anhui, Cina pada 17 Oktober 2020., Wanita yang terjatuh tersebut tidak meninggal dunia, melainkan mengalami luka serius di wajahnya dan langsung dilarikan ke rumah sakit untuk perawatan., Media Cina, The Paper, telah melaporkan kejadian tersebut dengan detail dan membenarkan lokasi serta kondisi korban., PT MRT Jakarta dan pihak kepolisian Indonesia tidak pernah melaporkan insiden serupa di stasiun MRT Jakarta., Video dan narasi tersebut merupakan konten menyesatkan yang beredar di media sosial untuk menimbulkan sensasi dan ketakutan.]",Ini adalah modus konten menyesatkan yang mencatut lokasi dan kejadian di Indonesia untuk mendapatkan perhatian lebih. Narasi tersebut sengaja dibuat dramatis dan menakutkan untuk memanipulasi emosi publik dan menyebar ketidakpercayaan.
7998,"Waspada! Ada Akun WhatsApp Palsu Mengatasnamakan Humas Polda Kalsel, Jangan Ditanggapi!","Beredar sebuah akun WhatsApp yang mengatasnamakan Bidang Humas Kepolisian Daerah Kalimantan Selatan (Humas Polda Kalsel). Akun tersebut bernomor +62 838-7219-4238 dan menggunakan foto profil dengan logo Divisi Humas Kepolisian Republik Indonesia (Humas Polri). Faktanya, Humas Polda Kalsel melalui akun Instagram resminya @humas_poldakalsel, memberikan klarifikasi bahwa akun tersebut merupakan akun palsu. Humas Polda Kalsel mengimbau masyarakat untuk tidak menanggapi akun WhatsApp tersebut dan apabila menemukan hal serupa agar segera melaporkan kepada Humas Polda Kalsel untuk ditindaklanjuti.",Disinformasi,"[Humas Polda Kalsel telah memberikan klarifikasi melalui akun Instagram resmi @humas_poldakalsel bahwa akun WhatsApp dengan nomor +62 838-7219-4238 adalah palsu., Akun palsu tersebut menggunakan foto profil dengan logo Divisi Humas Kepolisian Republik Indonesia (Humas Polri) untuk mencatut nama institusi., Masyarakat diimbau untuk tidak menanggapi akun WhatsApp tersebut dan melaporkan ke Humas Polda Kalsel jika menemukan hal serupa., Polda Kalsel hanya akan memberikan informasi resmi melalui akun media sosial resmi mereka.]","Ini adalah modus pencatutan nama yang bertujuan untuk menipu masyarakat. Akun palsu tersebut menggunakan logo resmi untuk menambah kredibilitas, namun Humas Polda Kalsel telah membantah keberadaannya dan mengimbau masyarakat untuk waspada."
7999,"NASA Peringatkan Kiamat Internet Akan Terjadi 25 Juni 2023, Koneksi Internet Tidak Bisa Dipakai Selama Bertahun-tahun!","Beredar sebuah unggahan video di media sosial berisi narasi soal peringatan kiamat internet dari Badan Penerbangan dan Antariksa Amerika Serikat (NASA) pada 25 Juni 2023. Dalam video disebutkan manusia akan dilanda kondisi di mana koneksi internet tidak dapat dipakai selama berbulan-bulan, bahkan bertahun-tahun. Dilansir dari kompas.com, klaim NASA memperingatkan tentang kiamat internet adalah keliru. Berdasarkan penelusuran, video tersebut menggunakan sejumlah tangkapan layar artikel, salah satunya dari The Mirror yang diunggah pada 7 Juni 2023 dan artikel dari JOE.ie. Kedua artikel itu membahas tentang misi Parker Space Probe yang dilakukan NASA. NASA memang telah meluncurkan Parker Space Probe, tetapi tidak pernah ada istilah kiamat internet dalam misi tersebut. Istilah kiamat internet sendiri bersumber dari studi soal Badai Matahari yang ditulis oleh asisten profesor ilmu komputer Universitas California Sangeetha Abdu Jyothi pada 2021. Studi tersebut menganalisis ketahanan infrastruktur internet di seluruh dunia dan menemukan bahwa kabel bawah laut memiliki risiko kegagalan yang lebih tinggi. Apabila terjadi Badai Matahari, maka kabel bawah air akan terganggu dan menghilangkan daya listrik besar-besaran.",Disinformasi,"[Klaim tersebut adalah hoaks dan tidak berdasar. NASA tidak pernah mengeluarkan peringatan tentang kiamat internet., Video yang beredar menggunakan tangkapan layar artikel dari The Mirror dan JOE.ie yang membahas misi Parker Space Probe, bukan kiamat internet., Misi Parker Space Probe memang ada, namun tujuannya adalah untuk mempelajari matahari, bukan untuk memperingatkan tentang kiamat internet., Istilah 'kiamat internet' berasal dari studi ilmiah oleh Sangeetha Abdu Jyothi yang membahas risiko kegagalan kabel bawah laut akibat Badai Matahari, bukan peringatan resmi dari NASA., Kompas.com telah melakukan penelusuran dan menemukan bahwa klaim tersebut adalah keliru dan menyesatkan.]","Ini adalah modus konten menyesatkan yang memanfaatkan informasi sebagian dari studi ilmiah dan mencampuradukannya dengan narasi yang tidak benar. Video tersebut menggunakan elemen yang tampak kredibel, seperti kutipan artikel, untuk membuat klaim yang tidak didukung oleh fakta."

In [ ]:
# df_disinformasi = df_disinformasi[["berita_asli", "claim_disinformasi", "cot_bantah_disinformasi", "reasoning_disinformasi", "label"]]
# df_disinformasi = df_disinformasi.sample(frac=1, random_state=42).reset_index(drop=True)
# df_disinformasi = df_disinformasi.sample(n=50)

# df_disinformasi.to_csv("sft_disinformasi.csv", index=False)

In [ ]:
penutup_disinformasi = [
    "**Waspadai informasi yang tidak berasal dari saluran komunikasi resmi guna menghindari paparan disinformasi.**",
    "**Selalu kroscek kebenaran sebuah informasi dengan membandingkannya terhadap pernyataan dari otoritas atau lembaga terkait.**",
    "**Jangan mudah menyebarkan pesan berantai sebelum memastikan kebenaran isinya melalui sumber berita yang kredibel.**",
    "**Biasakan untuk mencari konteks yang utuh dari sebuah informasi agar tidak terjebak dalam narasi yang menyesatkan.**",
    "**Pastikan Anda hanya mempercayai kanal informasi yang sudah terverifikasi untuk mendapatkan fakta yang sebenarnya.**",
    "**Tetap kritis dalam menerima informasi di media sosial; periksa kembali keaslian sumbernya sebelum mempercayainya.**",
    "**Hindari langsung mempercayai narasi yang terkesan mendesak atau terlalu menjanjikan tanpa ada bukti dari pihak berwenang.**",
    "**Lakukan verifikasi mandiri melalui mesin pencari atau situs cek fakta resmi untuk membongkar potensi disinformasi.**",
    "**Mari bersama memutus rantai informasi palsu dengan selalu merujuk pada fakta yang dirilis oleh sumber-sumber yang sah.**",
    "**Kehati-hatian adalah kunci utama dalam menghadapi berbagai modus informasi yang bertujuan untuk mengelabui publik.**"
]

In [ ]:
df_disinformasi

,claim_disinformasi,berita_asli,label,cot_bantah_disinformasi,reasoning_disinformasi
0,"Heboh! Pemuda Bakar Mobil Mercedes Karena Buatan Prancis, Padahal Aslinya...","Beredar di media sosial sebuah video yang diklaim memperlihatkan seorang pemuda membakar mobil karena buatan Prancis. Faktanya, klaim adanya pemuda yang membakar mobil miliknya karena mobil tersebut buatan Prancis adalah salah. Dikutip dari Turnbackhoax.id, mobil yang dibakar di video itu adalah Mercedes AMG GT 63 S buatan Jerman. Pria dalam video tersebut bernama Misha atau dikenal sebagai Mikhail Litvin, vlogger asal Rusia. Aksi membakar mobil itu disebabkan oleh rasa kesal karena mobil senilai 13 juta rubel Rusia (Rp 2 miliar) yang dibelinya sering rusak dan keengganan pabrikan untuk menerima tanggung jawab (menanggung biaya perbaikan). Jadi, aksi membakar mobil tersebut tidak ada kaitannya dengan Prancis.",Disinformasi,"[Mobil yang dibakar adalah Mercedes AMG GT 63 S, buatan Jerman, bukan Prancis (sumber: Turnbackhoax.id)., Pria dalam video tersebut adalah Mikhail Litvin, vlogger asal Rusia, yang membakar mobil karena masalah teknis dan keengganan pabrikan untuk bertanggung jawab., Aksi pembakaran mobil tidak ada hubungannya dengan asal negara pembuatan mobil tersebut.]",Ini adalah konten menyesatkan yang mencatut nama negara pembuatan mobil untuk menciptakan narasi yang provokatif dan mengecoh publik.
1,"Waspada! Paket Narkoba Dikirim ke Rumah Warga, Hoax atau Nyata?","Telah beredar pesan berantai whatsaap tentang pengiriman paket Narkoba dari luar negeri maupun dalam negeri yang ditujukan ke beberapa alamat yang sengaja disalahkan untuk mengecoh petugas yang berwajib. setelah ditelusuri lebih lanjut ternyata pesan tersebut pernah beredar dua tahun yang lalu tepatnya di bulan februari 2017 kemudian di sebar luaskan lagi, jadi pesan berantai tersebut merupakan informasi tidak benar atau hoaks.",Disinformasi,"[Pesan berantai tersebut telah beredar sejak Februari 2017 dan kembali disebar tanpa perubahan konten (sumber: klarifikasi dari otoritas setempat)., Informasi tentang pengiriman paket narkoba ke alamat warga adalah tidak benar dan merupakan hoaks., Otoritas keamanan tidak melaporkan adanya peningkatan kasus pengiriman narkoba melalui paket.]","Ini adalah pesan berantai yang dirancang untuk menakut-nakuti masyarakat dan mengecoh petugas keamanan, dengan menyebarkan informasi yang sudah lama tidak akurat."
2,"Berbahaya! Pinjaman Online Fintech Gunakan Data Gojek dan Tokopedia, Benarkah?","Telah Beredar sebuah postingan di media sosial facebook tentang berita Pinjaman Online Fintech Gunakan Data Gojek dan Tokopedia. Faktanya setelah ditelusuri perusahaan ride-hailing Indonesia Gojek membantah pihaknya memberikan data pengguna kepada pihak lain, termasuk pada aplikasi pinjaman online. Dalam pernyataan Gojek yang diterima Tekno Liputan6.com, Minggu (28/7/2019), Director Corporate Affairs Gojek Nila Marita mengatakan, Gojek selalu menjaga keamanan maksimum dari data pribadi pelanggan maupun para mitra. Sedangkan dari Tokopedia melalui Corporate Communications Nuraini Razak mengatakan, Tokopedia tidak menemukan adanya kebocoran atau pembobolan data oleh pihak ketiga terhadap data rahasia pengguna.",Disinformasi,"[Gojek membantah memberikan data pengguna kepada pihak lain, termasuk aplikasi pinjaman online (sumber: pernyataan resmi Gojek)., Tokopedia juga membantah adanya kebocoran data pengguna ke pihak ketiga (sumber: pernyataan resmi Tokopedia)., Kedua perusahaan menegaskan bahwa mereka menjaga keamanan maksimum dari data pribadi pelanggan.]",Ini adalah konten menyesatkan yang bertujuan untuk merusak reputasi perusahaan dan menimbulkan kekhawatiran publik terhadap keamanan data.
3,"Sensasional! WHO Sebut 377 Orang dari 100.000 Meninggal karena Vaksin, Benarkah?","Beredar unggahan di media sosial Facebook yang berisi data terkait kematian akibat vaksin Covid-19 yang diklaim bersumber dari Badan Kesehatan Dunia (WHO). Pengunggah menuliskan, 377 orang dari setiap 100.000 orang meninggal karena vaksin Covid-19. Dalam postingan itu tertulis, menurut studi WHO yang bocor, jika mereka menghentikan vaksinasi, minimal 377 orang dari setiap 100 ribu orang yang seharusnya disuntik akan hidup. Dilansir dari Kumparan.com yang mengutip dari Reuters, pada akhir Maret 2021, WHO melaporkan vaksin Covid-19 aman dan efektif. Laporan itu dibuat menyusul adanya kasus pembekuan darah yang dikaitkan dengan pemberian vaksin AstraZeneca. Reuters juga menegaskan, pihaknya tidak menemukan data-data terkait kematian yang diklaim oleh pengguna Facebook tersebut. Pihak WHO juga telah memberikan pernyataan bahwa data tersebut tidak pernah ada. Lembaga tersebut menambahkan, ""vaksin, seperti semua obat, dapat memiliki efek samping. Pemberian vaksin didasarkan pada analisis risiko versus manfaat"".",Disinformasi,"[WHO telah membantah adanya data tersebut dan menyatakan bahwa klaim tersebut tidak benar (sumber: pernyataan resmi WHO)., Reuters tidak menemukan data terkait kematian yang diklaim dalam unggahan tersebut., Vaksin, termasuk vaksin Covid-19, telah diuji dan dianggap aman serta efektif oleh WHO.]","Ini adalah modus fabrikasi data yang bertujuan untuk mengecoh publik dan menimbulkan ketakutan terhadap vaksinasi, yang dapat menghambat upaya kesehatan masyarakat."
4,"Mengerikan! Reporter Mursal Meninggal Terbunuh Setelah Memaparkan Limbah Minyak Goreng, Benarkah?","Belakangan beredar broadcast whatsapp tentang seorang reporter bernama mursal terbunuh setelah memaparkan limbah minyak goreng. Setelah ditelusuri ternyata kejadian tersebut tidak terjadi di Indonesia, melainkan terjadi di China pada tahun 2011 lalu. Nama korban yang terbunuh adalah Li Xiang, bukan Mursal seperti yang tertulis dalam pesan broadcast yang beredar. Li Xiang terbunuh setelah mengungkap fasilitas pengolahan limbah bekas dan kotor di Cina. Limbah itu berasal dari saluran pembuangan restoran dan toilet serta sumber limbah minyak kotor lainnya. Minyak goreng olahan yang berasal dari Limbah itu kemudian dijual ke pasaran dengan harga murah. Minyak goreng limbah itu menurut ahli kesehatan sangat membahayakan kesehatan manusia dan dapat menyebabkan kanker ganas.",Disinformasi,"[Kejadian tersebut terjadi di China pada tahun 2011, bukan di Indonesia (sumber: klarifikasi dari otoritas setempat)., Korban bernama Li Xiang, bukan Mursal, dan terbunuh setelah mengungkap fasilitas pengolahan limbah minyak kotor di Cina., Limbah minyak goreng yang dipaparkan oleh Li Xiang berasal dari saluran pembuangan restoran dan toilet, serta sumber limbah minyak kotor lainnya.]",Ini adalah konten menyesatkan yang mencatut nama dan kejadian yang tidak terkait untuk mengecoh publik dan menciptakan narasi yang sensasional.
...,...,...,...,...,...
7995,"Heboh! Kasus Covid-19 di Surabaya Hanyalah Konspirasi Elite Global, Jangan Percaya!","Beredar di sosial media sebuah hasil tangkapan layar berupa percakapan di WhatsApp yang berisi narasi bahwa parahnya kasus virus Corona Covid-19 di Surabaya hanyalah konspirasi elite global. Faktanya dikutip dari cekfakta.tempo.co, klaim bahwa parahnya kasus Covid-19 di Surabaya hanyalah konspirasi elite global adalah keliru. Jumlah kasus Covid-19 di Jawa Timur memang meningkat lebih dari 300 persen namun menurut sejumlah Ahli dan Pejabat Gugus Tugas Percepatan Penanganan Covid-19, terdapat empat faktor yang menyebabkan kasus Covid-19 di Surabaya melonjak, antara lain semakin masifnya tes, besarnya mobilitas penumpang di Bandara Internasional Juanda, transmisi lokal, dan tidak berjalannya PSBB sesuai harapan. Selain itu, penelitian menyatakan bahwa virus Corona penyebab Covid-19, SARS-CoV-2, bukanlah hasil manipulasi laboratorium.",Disinformasi,"[Cekfakta.tempo.co membantah klaim bahwa parahnya kasus Covid-19 di Surabaya adalah konspirasi elite global., Data resmi dari Gugus Tugas Percepatan Penanganan Covid-19 menunjukkan peningkatan kasus di Surabaya disebabkan oleh faktor-faktor seperti semakin masifnya tes, mobilitas tinggi di Bandara Internasional Juanda, transmisi lokal, dan tidak berjalannya PSBB sesuai harapan., Penelitian ilmiah menyatakan bahwa virus SARS-CoV-2, penyebab Covid-19, bukan hasil manipulasi laboratorium, melainkan evolusi alami dari virus korona., Klaim konspirasi tersebut tidak didukung oleh bukti ilmiah dan hanya bertujuan untuk menciptakan ketidakpercayaan terhadap upaya penanganan pandemi.]","Ini adalah modus fabrikasi yang mencoba menggambarkan situasi pandemi sebagai konspirasi. Tujuannya adalah untuk menyebar ketidakpercayaan terhadap otoritas kesehatan dan upaya penanganan pandemi, yang dapat berdampak negatif pada kesehatan publik."
7996,"Wah, ngeri! Ini video jatuhnya pesawat Lion Air JT610 yang hilang kontak di Indonesia!",Video ini BUKAN jatuhnya pesawat Lion Air JT 610. Tetapi ini adalah pesawat Ethiopian Airlines Flight 961 saat jatuh ke Samudra Hindia pada tanggal 23 November 1996.,Disinformasi,"[Video tersebut bukan jatuhnya pesawat Lion Air JT610, melainkan Ethiopian Airlines Flight 961 yang jatuh pada 23 November 1996 di Samudra Hindia., Faktanya, Lion Air JT610 jatuh di perairan Karawang, Jawa Barat, dan tidak ada video rekaman langsung dari kejadian tersebut., Akun resmi Lion Air dan otoritas penerbangan Indonesia tidak pernah membagikan video tersebut sebagai bukti kecelakaan JT610., Video tersebut telah beredar sejak lama dan sering digunakan untuk menyesatkan publik dengan mengaitkannya dengan berbagai kecelakaan pesawat lainnya.]",Ini adalah modus fabrikasi yang menyesatkan dengan mencatut kejadian tragis Lion Air JT610 untuk mendapatkan perhatian dan engagement. Video tersebut telah direkayasa untuk menimbulkan kepanikan dan ketakutan di masyarakat.
7997,"Ngeri! Wanita tewas terjatuh di stasiun MRT Jakarta, patah leher dan dibawa ke RSCM!","Beredar di media sosial Facebook sebuah unggahan video yang merekam kejadian seorang wanita terjatuh saat menuruni anak tangga. Video tersebut beredar dengan narasi yang mengeklaim bahwa kejadian tersebut terjadi di stasiun Mass Rapid Transit (MRT) Jakarta. Kemudian, wanita yang terjatuh itu meninggal seketika akibat patah leher dan dibawa ke Rumah Sakit Umum Pusat Nasional Dr. Cipto Mangunkusumo (RSCM) untuk diautopsi. Faktanya, klaim yang menyebut seorang wanita meninggal akibat terjatuh di stasiun MRT Jakarta adalah keliru. Adapun, kejadian tersebut bukan terjadi di stasiun MRT Jakarta, melainkan terjadi di Kota Hefei, Provinsi Anhui, Cina pada 17 Oktober 2020. Berdasarkan artikel dari media Cina, The Paper, wanita tersebut juga tidak meninggal dunia, melainkan mengalami luka serius di wajahnya. Wanita tersebut juga langsung dilarikan ke rumah sakit untuk mendapat perawatan.",Disinformasi,"[Kejadian tersebut bukan terjadi di stasiun MRT Jakarta, melainkan di Kota Hefei, Provinsi Anhui, Cina pada 17 Oktober 2020., Wanita yang terjatuh tersebut tidak meninggal dunia, melainkan mengalami luka serius di wajahnya dan langsung dilarikan ke rumah sakit untuk perawatan., Media Cina, The Paper, telah melaporkan kejadian tersebut dengan detail dan membenarkan lokasi serta kondisi korban., PT MRT Jakarta dan pihak kepolisian Indonesia tidak pernah melaporkan insiden serupa di stasiun MRT Jakarta., Video dan narasi tersebut merupakan konten menyesatkan yang beredar di media sosial untuk menimbulkan sensasi dan ketakutan.]",Ini adalah modus konten menyesatkan yang mencatut lokasi dan kejadian di Indonesia untuk mendapatkan perhatian lebih. Narasi tersebut sengaja dibuat dramatis dan menakutkan untuk memanipulasi emosi publik dan menyebar ketidakpercayaan.
7998,"Waspada! Ada Akun WhatsApp Palsu Mengatasnamakan Humas Polda Kalsel, Jangan Ditanggapi!","Beredar sebuah akun WhatsApp yang mengatasnamakan Bidang Humas Kepolisian Daerah Kalimantan Selatan (Humas Polda Kalsel). Akun tersebut bernomor +62 838-7219-4238 dan menggunakan foto profil dengan logo Divisi Humas Kepolisian Republik Indonesia (Humas Polri). Faktanya, Humas Polda Kalsel melalui akun Instagram resminya @humas_poldakalsel, memberikan klarifikasi bahwa akun tersebut merupakan akun palsu. Humas Polda Kalsel mengimbau masyarakat untuk tidak menanggapi akun WhatsApp tersebut dan apabila menemukan hal serupa agar segera melaporkan kepada Humas Polda Kalsel untuk ditindaklanjuti.",Disinformasi,"[Humas Polda Kalsel telah memberikan klarifikasi melalui akun Instagram resmi @humas_poldakalsel bahwa akun WhatsApp dengan nomor +62 838-7219-4238 adalah palsu., Akun palsu tersebut menggunakan foto profil dengan logo Divisi Humas Kepolisian Republik Indonesia (Humas Polri) untuk mencatut nama institusi., Masyarakat diimbau untuk tidak menanggapi akun WhatsApp tersebut dan melaporkan ke Humas Polda Kalsel jika menemukan hal serupa., Polda Kalsel hanya akan memberikan informasi resmi melalui akun media sosial resmi mereka.]","Ini adalah modus pencatutan nama yang bertujuan untuk menipu masyarakat. Akun palsu tersebut menggunakan logo resmi untuk menambah kredibilitas, namun Humas Polda Kalsel telah membantah keberadaannya dan mengimbau masyarakat untuk waspada."
7999,"NASA Peringatkan Kiamat Internet Akan Terjadi 25 Juni 2023, Koneksi Internet Tidak Bisa Dipakai Selama Bertahun-tahun!","Beredar sebuah unggahan video di media sosial berisi narasi soal peringatan kiamat internet dari Badan Penerbangan dan Antariksa Amerika Serikat (NASA) pada 25 Juni 2023. Dalam video disebutkan manusia akan dilanda kondisi di mana koneksi internet tidak dapat dipakai selama berbulan-bulan, bahkan bertahun-tahun. Dilansir dari kompas.com, klaim NASA memperingatkan tentang kiamat internet adalah keliru. Berdasarkan penelusuran, video tersebut menggunakan sejumlah tangkapan layar artikel, salah satunya dari The Mirror yang diunggah pada 7 Juni 2023 dan artikel dari JOE.ie. Kedua artikel itu membahas tentang misi Parker Space Probe yang dilakukan NASA. NASA memang telah meluncurkan Parker Space Probe, tetapi tidak pernah ada istilah kiamat internet dalam misi tersebut. Istilah kiamat internet sendiri bersumber dari studi soal Badai Matahari yang ditulis oleh asisten profesor ilmu komputer Universitas California Sangeetha Abdu Jyothi pada 2021. Studi tersebut menganalisis ketahanan infrastruktur internet di seluruh dunia dan menemukan bahwa kabel bawah laut memiliki risiko kegagalan yang lebih tinggi. Apabila terjadi Badai Matahari, maka kabel bawah air akan terganggu dan menghilangkan daya listrik besar-besaran.",Disinformasi,"[Klaim tersebut adalah hoaks dan tidak berdasar. NASA tidak pernah mengeluarkan peringatan tentang kiamat internet., Video yang beredar menggunakan tangkapan layar artikel dari The Mirror dan JOE.ie yang membahas misi Parker Space Probe, bukan kiamat internet., Misi Parker Space Probe memang ada, namun tujuannya adalah untuk mempelajari matahari, bukan untuk memperingatkan tentang kiamat internet., Istilah 'kiamat internet' berasal dari studi ilmiah oleh Sangeetha Abdu Jyothi yang membahas risiko kegagalan kabel bawah laut akibat Badai Matahari, bukan peringatan resmi dari NASA., Kompas.com telah melakukan penelusuran dan menemukan bahwa klaim tersebut adalah keliru dan menyesatkan.]","Ini adalah modus konten menyesatkan yang memanfaatkan informasi sebagian dari studi ilmiah dan mencampuradukannya dengan narasi yang tidak benar. Video tersebut menggunakan elemen yang tampak kredibel, seperti kutipan artikel, untuk membuat klaim yang tidak didukung oleh fakta."

In [ ]:
df_disinformasi = df_disinformasi.to_dict("records")

In [ ]:
import json
import random

def generate_sft_dataset_with_context(raw_data_list, instructions, penutup_list, output_file):
    dataset = []
    
    for data in raw_data_list:
        instruct = random.choice(instructions)
        claim = data.get("claim_disinformasi", "")
        berita = data.get("berita_asli", "") 
        label = data.get("label")
        reasoning = data.get("reasoning_disinformasi", "")
        cot_list = data.get("cot_bantah_disinformasi", [])
        
        # Susun poin-poin fakta
        fakta_points = "\n".join([f"* {point}" for point in cot_list])
        closing = random.choice(penutup_list)
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Klaim: {claim}\n\n"
            f"Sumber Berita: {berita}"
        )

        full_output = (
            f"Label: **{label}.** "
            f"penjelasan: {reasoning}\n\n"
            f"Berikut adalah beberapa fakta sebenarnya:\n"
            f"{fakta_points}\n\n"
            f"{closing}"
        )
        
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(df_disinformasi, instructiones, penutup_disinformasi, "disinformasi.jsonl")

Berhasil membuat 7995 data dengan konteks berita di disinformasi.jsonl

# Fakta

In [ ]:
folderData = Path("Dataset_fakta")
files = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    files.append(df_sementara)

df = pd.concat(files, ignore_index=True)

In [ ]:
df_fakta = df[df["is_layak"]==1]

In [ ]:
df_fakta = df_fakta.drop(columns=["url", "title", "published_at", "sumber_berita", "label", "is_layak"])
df_fakta["label"] = "Fakta"

In [ ]:
df_fakta

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              text  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Konsumsi rokok dan minuman beralkohol masyarakat Kabupaten Pangandaran tercatat lebih tinggi dibandingkan belanja ikan dan telur. Kondisi ini mencerminkan adanya kecenderungan prioritas pengeluaran tertentu dalam kelompok konsumsi makanan masyarakat setempat.\nBerdasarkan data Badan Pusat Statistik (BPS) Kabupaten Pangandaran dalam laporan Kabupaten Pangandaran dalam Angka 2025, rokok dan minuman beralkohol diklasifikasikan ke dalam kelompok pengeluaran makanan. Menariknya, alokasi belanja untuk kategori tersebut justru melampaui pengeluaran untuk sumber pangan bergizi seperti ayam, telur, dan ikan.\nMeski demikian, secara umum BPS mencatat bahwa total pengeluaran penduduk Pangandaran untuk konsumsi makanan masih lebih besar dibandingkan pengeluaran non-makanan.\nSCROLL TO CONTINUE WITH CONTENT\nRata-rata pengeluaran per kapita per bulan penduduk Kabupaten Pangandaran pada 2024 tercatat sebesar Rp1.367.729. Dari jumlah tersebut, pengeluaran untuk kelompok makanan mencapai Rp809.992 atau 59,22 persen, sedangkan pengeluaran non-makanan sebesar Rp557.738 atau 40,78 persen.\nJika dibandingkan dengan tahun 2023, proporsi pengeluaran untuk makanan mengalami peningkatan. Pada 2023, pengeluaran makanan tercatat sebesar 55,72 persen, lalu naik menjadi 59,22 persen pada 2024.\nPada kelompok makanan tahun 2024, pengeluaran terbesar dialokasikan untuk makanan dan minuman jadi sebesar 15,56 persen, diikuti kelompok kacang-kacangan, buah-buahan, dan sayuran sebesar 10,51 persen, serta padi-padian dan umbi-umbian sebesar 9,59 persen.\nSementara itu, pengeluaran untuk kelompok ikan, daging, telur, dan susu hanya mencapai 8,76 persen, lebih rendah dibandingkan pengeluaran untuk rokok dan tembakau yang mencapai 9,20 persen. Pada 2023, proporsi belanja rokok dan tembakau tercatat sebesar 8,81 persen dan meningkat pada 2024.\nPada kelompok non-makanan tahun 2024, pengeluaran terbesar dialokasikan untuk perumahan, bahan bakar, penerangan, dan air dengan kontribusi 21,45 persen dari total pengeluaran. Sebaliknya, pengeluaran paling kecil terdapat pada keperluan pesta dan upacara adat yang hanya mencapai 1,13 persen.\nJika dibandingkan dengan tahun 2023, proporsi pengeluaran non-makanan secara keseluruhan mengalami penurunan. Pada 2023, pengeluaran non-makanan tercatat sebesar 23,28 persen, sedangkan pada 2024 tercatat sebesar 40,78 persen seiring meningkatnya total nilai pengeluaran masyarakat.\nPengeluaran untuk aneka barang dan jasa, biaya pendidikan, serta kesehatan tergolong relatif rendah. Pada 2023, kelompok ini menyumbang 9,03 persen dari total pengeluaran, kemudian menurun menjadi 8,82 persen pada 2024. Pengeluaran untuk pakaian dan alas kaki tercatat sebesar 2,80 persen pada 2023 dan turun menjadi 2,46 persen pada 2024.\nTingginya proporsi pengeluaran untuk makanan menunjukkan bahwa tingkat kesejahteraan masyarakat Kabupaten Pangandaran masih tergolong rendah, karena sebagian besar pendapatan digunakan untuk memenuhi kebutuhan dasar.\nNamun, data BPS juga menunjukkan bahwa pada kelompok pengeluaran 20 persen teratas, pola konsumsi mulai bergeser. Pada kelompok ini, pengeluaran non-makanan cenderung lebih besar dibandingkan pengeluaran makanan, yang mengindikasikan peningkatan taraf hidup dan diversifikasi kebutuhan.
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        BNN menggedebek kampung narkoba di Berlan, Matraman, Jakarta Timur. (Antara Foto/Fauzan)\n- Badan Narkotika Nasional (BNN) bersama petugas gabungan menggerebek kawasan Berlan, Matraman, Jakarta Timur, terkait dugaan peredarannarkobapada Selasa (25/11/2025) siang.\nDalam operasi tersebut, puluhan orang yang diduga sebagai pengedar berhasil diamankan.\nPenggerebekan dilakukan sekitar pukul 11.00 WIB. Petugas gabungan melakukan penyisiran ke sejumlah rumah dan langsung melakukan penggeledahan di titik-titik yang telah ditargetkan.\nDari lokasi, petugas menemukan berbagai jenis barang bukti narkoba dalam bentuk bubuk maupun cairan.\nSejumlah paket narkoba ditemukan disembunyikan di lemari hingga gudang-gudang kecil yang berada di dalam rumah warga.\nTerungkap! Ekstasi Rp 207 M Ditemukan Saat Mobil Kecelakaan di Lampung Hendak Disebar di Jakarta\nUntuk mempermudah pencarian barang bukti, petugas juga mengerahkan anjing pelacak (K9).\nLangkah ini dilakukan untuk memastikan tidak ada narkoba yang terlewatkan selama proses penggeledahan.\nDirektur Psikotropika dan Prekursor Deputi Bidang Pemberantasan BNN, Aldrin Marihot Pandapotan Hutabarat, menyampaikan bahwa pihaknya mengamankan puluhan orang dalam operasi tersebut.\n"Ada 10–15 titik yang menjadi target penggerebekan di kawasan Berlan. Dari rangkaian penggerebekan itu, kami mengamankan 25 pelaku," ujar Aldrin.\nSeluruh orang yang diamankan langsung dibawa ke kantor BNN untuk pemeriksaan lebih lanjut. Ia menyebut bahwa para pelaku merupakan warga sekitar.\n"Kawasan ini merupakan perkampungan. Semua yang kami amankan adalah warga sipil. Kami akan dalami peran masing-masing," pungkasnya.
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Pemerintah Kabupaten Sragen melakukan hitung cepat atau quick count pada pemilihan Bupati dan wakil Bupati Sragen 2024. Dari hasil hitung cepat yang dilakukan Desk Pilkada, pasangan Calon Bupati dan Wakil Bupati nomor urut 2, Sigit Pamungkas dan Suroto unggul dari pasangan nomor urut 1, Untung Wibowo Sukowati dan Suwardi.\nKepala Dinas Komunikasi dan Informatika Kabupaten Sragen, Catur Sarjanto mengatakan berdasarkan hitung cepat, pasangan Sigit-Suroto mendapat suara 330.358 suara. Sedangkan pasangan Bowo-Suwardi mendapat suara sebanyak 252.719.\n"Hasil hitung cepat kemarin paslon 01 sebanyak 252.719 atau sebesar persentase 43,34 persen, sedangkan Paslon 02 mendapat 330.358 suara atau 56,66 persen," katanya dihubungi, Kamis (28/11/2024).\nSCROLL TO CONTINUE WITH CONTENT\nCatur mengatakan dari 762.352 daftar pemilih tetap atau DPT, hanya 603.235 DPT menggunakan hak pilihnya. Catur menyebut di Kabupaten Sragen ada 1.462 Tempat Pemungutan Suara (TPS).\n"Mekanisme kita ada aplikasi yang buat Diskominfo, kita minta bantuan dengan camat, dari camat kita kirimkan operator untuk input data aplikasi, yang diinput di kantor kecamatan. Dari kecamatan menugaskan petugas untuk mencari data di semua TPS. Kemudian diinput di aplikasi yang ada di kecamatan," bebernya.\nDari data rekapitulasi Pemkab Sragen, pasangan Sigit-Suroto menang di total 20 kecamatan di Kabupaten Sragen.\n"Selesai kemarin pukul 18.00 WIB. Margin error nggak lebih dari 1 persen dengan KPU. Kami untuk aplikasi buka bisa untuk melihat, bisa melihat langsung kita tayangkan dengan video," pungkasnya.

In [ ]:
len(df_fakta)

7790

In [ ]:
df_fakta.isna().sum()

text                  0
claim_fakta           0
cot_analisis_fakta    0
reasoning_fakta       0
label                 0
dtype: int64

In [ ]:
import random

kalimat_akhir = kalimat_penutup + penutup_disinformasi

def ambilRandom():
    return random.choice(kalimat_akhir)

In [ ]:
df_fakta = df_fakta.to_dict("records")

In [ ]:
import json
import random

def generate_sft_dataset_with_context(raw_data_list, instructions, penutup_list, output_file):
    dataset = []
    
    for data in raw_data_list:
        instruct = random.choice(instructions)
        claim = data.get("claim_fakta", "")
        berita = data.get("text", "") 
        label = data.get("label")
        reasoning = data.get("reasoning_fakta", "")
        cot_list = data.get("cot_analisis_fakta", [])
        kalimat_saran = ambilRandom()
        
        # Susun poin-poin fakta
        fakta_points = "\n".join([f"* {point}" for point in cot_list])
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Klaim: {claim}\n\n"
            f"Sumber Berita: {berita}"
        )

        full_output = (
            f"Label: **{label}.** "
            f"penjelasan: {reasoning}\n\n"
            f"Berikut adalah beberapa fakta sebenarnya:\n"
            f"{fakta_points}\n\n"
            f"{kalimat_saran}"
        )
        
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(df_fakta, instructiones, penutup_disinformasi, "fakta.jsonl")

Berhasil membuat 7790 data dengan konteks berita di fakta.jsonl

# Sampling and concatting ting ting ayu ting ting

In [ ]:
df_disinformasi = pd.read_json("disinformasi.jsonl", lines=True)
df_fitnah = pd.read_json("fitnah.jsonl", lines=True)
df_fakta = pd.read_json("fakta.jsonl", lines=True)

In [ ]:
df_disinformasi = df_disinformasi.sample(n=7200)
df_fitnah = df_fitnah.sample(n=7200)
df_fakta = df_fakta.sample(n=7200)

In [ ]:
df_disinformasi.to_csv("df_disinformasi.csv", index=False)
df_fitnah.to_csv("df_fitnah.csv", index=False)
df_fakta.to_csv("df_fakta.csv", index=False)

In [ ]:
df_combined = pd.concat([
    df_disinformasi.sample(n=7200, random_state=42),
    df_fitnah.sample(n=7200, random_state=42),
    df_fakta.sample(n=7200, random_state=42)
])

df_combined = df_combined.sample(frac=1, random_state=42).reset_index(drop=True)

df_combined.to_json('dataset_sampled.jsonl', orient='records', lines=True)

In [ ]:
df_combined

,instruction,input,output
0,Tentukan label keamanan konten untuk teks beri...,Klaim: Gempa Turki-Suriah udah ngebunuh lebih ...,Label: Fakta. Klaim ini sesuai dengan laporan ...
1,Tentukan label keamanan konten untuk teks beri...,Klaim: Guru SD di Tangsel ngebully muridnya sa...,Label: Fitnah. Narasi ini menggunakan framing ...
2,Analisis teks berikut dan tentukan kategorinya...,Klaim: Ayah tiri Alvaro pura-pura mencari anak...,Label: Fitnah. Claim tersebut mencoba menggamb...
3,Evaluasi narasi berikut. Identifikasi apakah t...,"Klaim: AHY Pasang Badan Bela Gibran, Minta Jen...",Label: Disinformasi. Ini adalah modus pencatut...
4,Klasifikasikan input berikut ke dalam salah sa...,"Klaim: Barusan baca, Daop 6 amankan barang ter...",Label: Fakta. Informasi tentang pengamanan bar...
...,...,...,...
21595,Tolong bantu klasifikasikan pesan ini. Apakah ...,Klaim: Wali Nanggroe Aceh hanya peduli dengan ...,Label: Fitnah. Pernyataan Wali Nanggroe dipeli...
21596,Klasifikasikan teks ke dalam salah satu label:...,Klaim: Kemenkeu akan merekrut 300 lulusan SMA ...,Label: Fakta. Informasi rekrutmen 300 lulusan ...
21597,Klasifikasikan teks ke dalam salah satu label:...,Klaim: Lucu banget! Vladimir Putin nggak datan...,Label: Disinformasi. Ini adalah modus pencatut...
21598,Evaluasi narasi berikut. Identifikasi apakah t...,Klaim: Wow! Prof. Boediono Promosikan Obat Aja...,Label: Disinformasi. Ini adalah modus phishing...
21599,Tentukan label keamanan konten untuk teks beri...,Klaim: Komisi XI DPR menyetujui anggaran Kemen...,Label: Fakta. Berita secara jelas mengonfirmas...

# Dataset Ujaran Kebencian

## Artikel

In [3]:
folderData = Path("Dataset_UjaranKebencian/artikel")
files = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    files.append(df_sementara)

df_artikel = pd.concat(files, ignore_index=True)

In [4]:
df_artikel.isna().sum()

judul                  0
teks                   0
target                 1
label                  1
\t                  4799
"  :                4799
{  :                4799
}                   4799
[                   4799
]                   4799
;                   4799
|                   4799
<                   4799
>                   4799
'                   4799
`                   4799
=                   4799
-                   4799
+                   4799
*                   4799
/                   4799
&                   4799
$                   4799
#                   4799
@                   4799
!                   4799
?                   4799
(                   4799
)                   4799
~                   4799
%                   4799
^                   4799
_                   4799
"                   4799
\n                  4799
\r                  4799
\t                  4799
\"                  4799
\'                  4799
\\                  4799
\b                  4799
\f                  4799
\v                  4799
\0                  4799
\xHH                4799
\uHHHH              4799
\u{HHHHHH}          4799
\N{name}            4799
\cX                 4799
\?                  4799
\.                  4799
\:                  4799
\;                  4799
\/                  4799
\\\'\'\''  :        4799
dtype: int64

In [5]:
df_artikel = df_artikel.drop(df_artikel[df_artikel["$"].notna()].index)

In [6]:
df_artikel.columns.unique()

Index(['judul', 'teks', 'target', 'label', '\t', '"  :    ', '{  :    ', '}',
       '[', ']', ';', '|', '<', '>', ''', '`', '=', '-', '+', '*', '/', '&',
       '$', '#', '@', '!', '?', '(', ')', '~', '%', '^', '_', '"', '\n', '\r',
       '\t', '\"', '\'', '\\', '\b', '\f', '\v', '\0', '\xHH', '\uHHHH',
       '\u{HHHHHH}', '\N{name}', '\cX', '\?', '\.', '\:', '\;', '\/',
       '\\\'\'\''  :    '],
      dtype='object')

In [7]:
df_artikel = df_artikel[["judul", "teks", "target", "label"]]

In [8]:
df_artikel.isna().sum()

judul     0
teks      0
target    0
label     0
dtype: int64

In [9]:
def bersihinjudul(df):
    target = str(df["judul"])
    judul = target.split(':')

    return " ".join(judul[1:]).strip()

df_artikel["judul"] = df_artikel.apply(bersihinjudul, axis=1)

In [10]:
mapping = {
    # ======================
    # SUKU / ETNIS
    # ======================
    "Suku Bali": "suku_bali",

    "Suku Batak": "suku_batak",

    "Suku Bugis": "suku_bugis",

    "Suku Minang": "suku_minang",
    "Perempuan Minang": "suku_minang",
    "Etnis Minang": "suku_minang",
    "Orang Minang": "suku_minang",

    "Suku Dayak": "suku_dayak",

    "Suku Jawa": "suku_jawa",
    "Orang Jawa": "suku_jawa",
    "Etnis Jawa": "suku_jawa",
    "Masyarakat Jawa": "suku_jawa",

    "Suku Madura": "suku_madura",
    "Etnis Madura": "suku_madura",
    "Orang Madura": "suku_madura",
    "Pedagang Madura": "suku_madura",
    "Warga Madura": "suku_madura",
    "Masyarakat Madura": "suku_madura",

    "Suku Melayu": "suku_melayu",
    "Masyarakat Melayu": "suku_melayu",
    "Orang Melayu": "suku_melayu",

    "Suku Papua": "suku_papua",

    "Suku Sunda": "suku_sunda",
    "Masyarakat Sunda": "suku_sunda",
    "Orang Tua Sunda": "suku_sunda",
    "Komunitas Sunda": "suku_sunda",
    "Laki-laki Sunda": "suku_sunda",
    "Perempuan Sunda": "suku_sunda",
    "Pria pedesaan Jawa Barat": "suku_sunda",
    "Lelaki Jawa Barat": "suku_sunda",
    "Masyarakat Jawa Barat": "suku_sunda",
    "Laki-laki di pedesaan Jawa Barat": "suku_sunda",
    "Pengangguran di Jawa Barat": "suku_sunda",
    "Laki-laki di Tanah Sunda": "suku_sunda",

    "Suku Tionghoa": "suku_tionghoa",
    "Suku Tionghoa atau Cina": "suku_tionghoa",

    # ======================
    # AGAMA
    # ======================
    "Penganut Islam": "agama_islam",
    "Penganut Kristen": "agama_kristen",

    # ======================
    # GENDER
    # ======================
    "Laki-laki Indonesia": "gender_laki_laki",
    "Perempuan Indonesia": "gender_perempuan",

    # ======================
    # KOMUNITAS / LAINNYA
    # ======================
    "PSHT": "komunitas_psht",
    "Komunitas PSHT": "komunitas_psht",
    "Komunitas Silat Jawa (PSHT)": "komunitas_psht",

    "Pengepul": "pekerjaan_pengepul",
    "Pengepul Madura": "pekerjaan_pengepul",
    "Pengepul Rongsokan": "pekerjaan_pengepul",

    "Orang Tua": "kelompok_orang_tua",
    "Orang Tua Indonesia": "kelompok_orang_tua",
    "Orang Tua yang Mengirim Anak ke Pesantren": "kelompok_orang_tua",

    "Masyarakat yang sering ngeteh dan mengobrol berjam-jam di kedai kopi": "kebiasaan_ngopi",
    "Masyarakat yang gemar 'ngeteh' dan ngobrol di kedai kopi": "kebiasaan_ngopi",
}

df_artikel["target"] = df_artikel["target"].map(mapping).fillna("unknown")

In [11]:
df_artikel[df_artikel["target"] == "komunitas_psht"].head(2)

,judul,teks,target,label
1837,Ancaman dari Dalam,Komunitas Pemuda Setia Hati Teratai (PSHT) kem...,komunitas_psht,Ujaran Kebencian
1850,Komunitas Silat Jawa yang Sering Menjadi Sumbe...,Komunitas Pagar Siliwangi Tunggal Sejati (PSHT...,komunitas_psht,Ujaran Kebencian

In [12]:
df_artikel = df_artikel.to_dict("records")

In [30]:
def artikelmaker(df):
    data = []
    jenis = "artikel"

    for baris in df:
        judul = baris.get("judul", "")
        artikel = baris.get("teks", "")
        target =  baris.get("target", "")
        label =  baris.get("label", "")
        

        fullArtikel = (
        f"Judul: {judul}.\n\n"
        f"Teks: {artikel}"
        )

        artikelAsli = {
            "claim_disinformasi": fullArtikel,
            "target": target,
            "label": label,
            "jenis": jenis
        }

        data.append(artikelAsli)

    return data

df_uk_artikel = artikelmaker(df_artikel)

df_artikel buat artikel type shift

## Komentar

In [32]:
folderData = Path("Dataset_UjaranKebencian/komentar")
komentar = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    komentar.append(df_sementara)

df_komentar = pd.concat(komentar, ignore_index=True)

In [33]:
df_komentar

,komentar,target,label,gaya_komentar
0,anjir suku madura maling kabel listrik tiap ge...,suku madura,Ujaran Kebencian,brutal
1,anjng suku madura cuma bisa bikin demo kecil b...,suku madura,Ujaran Kebencian,brutal
2,anjir suku madura emang hobi judi online sambi...,suku madura,Ujaran Kebencian,brutal
3,anjir suku madura bener2 tolol bgt trhadp cewe...,suku madura,Ujaran Kebencian,brutal
4,"anjng suku madura tolol bgt gak tau pajak apa,...",suku madura,Ujaran Kebencian,brutal
...,...,...,...,...
4794,"bikin anak banyak tp ga kasih masa depan, masa...",orang miskin,Ujaran Kebencian,insinuasi
4795,bajingan orang miskin iri amat liat tetangga p...,orang miskin,Ujaran Kebencian,insinuasi
4796,anjir gila mulu minta bantuan sosial tiap tahu...,orang miskin,Ujaran Kebencian,insinuasi
4797,"anjir beneran nih, susah amat ngomongnya tp gk...",orang miskin,Ujaran Kebencian,insinuasi
4798,anjir gue liat deh orang miskin skrg malah hob...,orang miskin,Ujaran Kebencian,insinuasi

In [34]:
df_komentar = df_komentar[["komentar", "target", "label"]]
df_komentar = df_komentar.rename(columns={"komentar": "claim_disinformasi"})
df_komentar["jenis"] = "komentar"

In [36]:
df_komentar.head(2)

,claim_disinformasi,target,label,jenis
0,anjir suku madura maling kabel listrik tiap ge...,suku madura,Ujaran Kebencian,komentar
1,anjng suku madura cuma bisa bikin demo kecil b...,suku madura,Ujaran Kebencian,komentar

In [37]:
df_komentar = df_komentar.to_dict("records")

In [41]:
df_ujarankebencian = df_uk_artikel + df_komentar
df_ujarankebencian = pd.DataFrame(df_ujarankebencian)
df_ujarankebencian["claim_disinformasi"]  = df_ujarankebencian["claim_disinformasi"].apply(lambda x: str(x).encode().decode('unicode_escape')) 
df_ujarankebencian.to_json("ujaranKebencian.jsonl", orient="records", lines=True)

In [39]:
df_ujarankebencian

,claim_disinformasi,target,label,jenis
0,Judul: Ancaman bagi Persatuan dan Keadilan.\n\...,suku_bali,Ujaran Kebencian,artikel
1,Judul: Hambatan Produktivitas di Bali.\n\nTeks...,suku_bali,Ujaran Kebencian,artikel
2,Judul: Surga yang Hanya Menghormati Turis.\n\n...,suku_bali,Ujaran Kebencian,artikel
3,Judul: Ritual Bali Hanya untuk Tajuk Wisata.\n...,suku_bali,Ujaran Kebencian,artikel
4,Judul: Penjara Budaya yang Mengunci Kemajuan B...,suku_bali,Ujaran Kebencian,artikel
...,...,...,...,...
9593,"bikin anak banyak tp ga kasih masa depan, masa...",orang miskin,Ujaran Kebencian,komentar
9594,bajingan orang miskin iri amat liat tetangga p...,orang miskin,Ujaran Kebencian,komentar
9595,anjir gila mulu minta bantuan sosial tiap tahu...,orang miskin,Ujaran Kebencian,komentar
9596,"anjir beneran nih, susah amat ngomongnya tp gk...",orang miskin,Ujaran Kebencian,komentar
9597,anjir gue liat deh orang miskin skrg malah hob...,orang miskin,Ujaran Kebencian,komentar

# Lain hal nya

In [ ]:
datasett

,Tweet,HS,Abusive,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong
0,- disaat semua cowok berusaha melacak perhatia...,1,1,1,0,0,0,0,0,1,1,0,0
1,RT USER: USER siapa yang telat ngasih tau elu?...,0,1,0,0,0,0,0,0,0,0,0,0
2,"41. Kadang aku berfikir, kenapa aku tetap perc...",0,0,0,0,0,0,0,0,0,0,0,0
3,USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...,0,0,0,0,0,0,0,0,0,0,0,0
4,USER USER Kaum cebong kapir udah keliatan dong...,1,1,0,1,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13164,USER jangan asal ngomong ndasmu. congor lu yg ...,1,1,1,0,0,0,1,0,0,1,0,0
13165,USER Kasur mana enak kunyuk',0,1,0,0,0,0,0,0,0,0,0,0
13166,USER Hati hati bisu :( .g\n\nlagi bosan huft \...,0,0,0,0,0,0,0,0,0,0,0,0
13167,USER USER USER USER Bom yang real mudah terdet...,0,0,0,0,0,0,0,0,0,0,0,0
13168,"USER Mana situ ngasih("": itu cuma foto ya kuti...",1,1,1,0,0,0,0,0,1,1,0,0

In [ ]:
tes = datasett[datasett["HS_Race"]==1]
tes = tes[datasett["HS_Individual"]!=1]

C:\Users\Dipo\AppData\Local\Temp\ipykernel_195400\3338459798.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  tes = tes[datasett["HS_Individual"]!=1]

In [ ]:
tes

,Tweet,HS,Abusive,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong
28,RT USER USER USER PKI hanya muncul jika jelang...,1,0,0,1,0,1,0,0,0,0,1,0
76,tapi masih menikmati kebijakan yang dulu diusu...,1,0,0,1,0,1,0,0,0,0,1,0
77,Kalo seumpama orang cina di usir paksa dari in...,1,0,0,1,0,1,0,0,0,0,1,0
79,RT USER: china babi... china maling...\n#UsirC...,1,1,0,1,0,1,0,0,0,0,0,1
122,Cina perusak bangsa!! Usir !! Stuju??,1,0,0,1,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12980,USER sama halnya dengan cina di indonesia dong...,1,0,0,1,0,1,0,0,0,0,1,0
13014,Orang yang suka Prabowo berarti PKI... URL,1,0,0,1,0,1,0,0,0,0,1,0
13058,USER USER USER USER USER USER USER Mesir komun...,1,1,0,1,1,1,0,0,0,0,1,0
13071,"USER #Pribumi iseng, aparat Sangarrrr #puluhan...",1,1,0,1,0,1,0,0,0,0,1,0
13092,Usir Budha dari Indonesia yg notabene mayorita...,1,0,0,1,1,1,0,0,0,0,0,1

In [ ]:
import re

def clean_twitter_noise(text):
    if not isinstance(text, str):
        return text
    text = re.sub(r'\bRT\s+USER:?\b', '', text, flags=re.IGNORECASE)
    

    text = re.sub(r'\bUSER\b', '', text)

    text = re.sub(r'&amp;', '&', text)

    text = text.encode('ascii', 'ignore').decode('ascii')

    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

# Terapkan ke dataset
tes['text_clean'] = tes['Tweet'].apply(clean_twitter_noise)

In [ ]:
tes[['Tweet', 'text_clean']].head()

,Tweet,text_clean
28,RT USER USER USER PKI hanya muncul jika jelang...,PKI hanya muncul jika jelang pemilihan kepala ...
76,tapi masih menikmati kebijakan yang dulu diusu...,tapi masih menikmati kebijakan yang dulu diusu...
77,Kalo seumpama orang cina di usir paksa dari in...,Kalo seumpama orang cina di usir paksa dari in...
79,RT USER: china babi... china maling...\n#UsirC...,: china babi... china maling...\n#UsirChina ht...
122,Cina perusak bangsa!! Usir !! Stuju??,Cina perusak bangsa!! Usir !! Stuju??

In [ ]:
data_sara = tes[["text_clean"]]

In [ ]:
data_sara.to_csv("data_sara.csv", index=False)

In [ ]:
data_sara.to_json('dataSara.jsonl', orient='records', lines=True)