In [1]:
import pandas as pd
from pathlib import Path
import json
pd.set_option('display.max_colwidth', None)
# pd.reset_option('display.max_colwidth')

In [2]:
instructiones = """Anda adalah sistem ahli klasifikasi komentar media sosial. Klasifikasikan [Komentar] ke salah satu Nama Label: [Netral, Disinformasi, Fitnah, Ujaran Kebencian].
Aturan:
1. Ujaran Kebencian: Serangan SARA/identitas/disabilitas (prioritas utama, abaikan rujukan).
2. Jika bukan ujaran kebencian, gunakan [Artikel Rujukan] jika ada untuk menilai:
- Netral: Faktual, opini, atau interaksi wajar.
- Disinformasi: Informasi keliru yang memicu keresahan/polarisasi.
- Fitnah: Tuduhan bohong untuk menyerang reputasi individu/kelompok.
Format Output WAJIB:
Penjelasan: [Analisis detail dan alasan label]
Label: [Nama Label]"""

"""

Klasifikasikan [Komentar] media sosial Indonesia ke dalam label [Netral, Disinformasi, Fitnah, Ujaran Kebencian] menggunakan [Artikel Rujukan] jika tersedia. Prioritaskan label 'Ujaran Kebencian' jika ada serangan berbasis SARA/identitas; jika tidak, gunakan rujukan untuk membedakan antara tuduhan palsu spesifik ('Fitnah'), informasi menyesatkan publik ('Disinformasi'), atau opini/interaksi wajar ('Netral'). Output WAJIB menggunakan format persis seperti ini: "Penjelasan: [analisis ringkas]\nLabel: [NamaLabel]".
"""

'\n\nKlasifikasikan [Komentar] media sosial Indonesia ke dalam label [Netral, Disinformasi, Fitnah, Ujaran Kebencian] menggunakan [Artikel Rujukan] jika tersedia. Prioritaskan label \'Ujaran Kebencian\' jika ada serangan berbasis SARA/identitas; jika tidak, gunakan rujukan untuk membedakan antara tuduhan palsu spesifik (\'Fitnah\'), informasi menyesatkan publik (\'Disinformasi\'), atau opini/interaksi wajar (\'Netral\'). Output WAJIB menggunakan format persis seperti ini: "Penjelasan: [analisis ringkas]\nLabel: [NamaLabel]".\n'

# Fitnah

In [3]:
folderData = Path("Dataset_Fitnah")
files = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    files.append(df_sementara)

df = pd.concat(files, ignore_index=True)

In [4]:
df_fitnah = df[df["is_layak"] == 1]

In [5]:
df_fitnah[df_fitnah["cot_bantuh_fitnah"].notna()]

,url,title,published_at,text,sumber_berita,label,is_layak,claim_fitnah,cot_bantah_fitnah,reasoning_fitnah,cot_bantuh_fitnah
4305,https://banten.indozone.id/news/2486375917/hingga-september-2025-capaian-pajak-kota-tembus-7019-persen-dari-target-tahunan?page=all,"Hingga September 2025, Capaian Pajak Kota Tembus 70,19 persen Dari Target Tahunan",2025-10-10 12:02:12,"Kepala Bapenda Kota Serang, W Hari Pamungkas (Doc.Mamo erfanto)\n- Capaian pendapatanpajakdaerahKota Serangmenunjukkan tren positif sepanjang tahun 2025. Hingga 30 September 2025, Badan Pendapatan Daerah (Bapenda)Kota Serangmencatat realisasipajaktelah mencapai 70,19 persen dari target tahunan.\nKepalaBapenda Kota Serang, W Hari Pamungkas, mengatakan capaian tersebut menjadi sinyal positif atas meningkatnya kesadaran wajibpajakserta tumbuhnya sektor usaha diKota Serang. Jumat 10 Oktober 2025.\n""Dari Januari sampai 30 September kami sudah mencapai akumulatif 70,19 persen. Target kami selama setahun Rp341,2 miliar, dan hingga triwulan ketiga sudah terealisasi Rp239,5 miliar,"" ujar Hari.\nBendahara Desa Petir Bawa Kabur Dana Desa 1Milyar TA 2025\n12 Cabor Yang Akan Di Pertandingkan Di PORKOT IV Kota Serang\nPencapaian ini jauh lebih tinggi dibandingkan periode yang sama tahun sebelumnya. Pada 2024, realisasi pajak hingga akhir tahun hanya sebesar Rp221 miliar.\nArtinya, per September 2025, Kota Serang telah mencatat surplus sekitar Rp19 miliar dibandingkan capaian tahun lalu.\n""Ini progres yang bagus untuk pajak daerah di Kota Serang,"" kata Hari.",indozone,Ekonomi & Bisnis,1.0,"Pemerintah Kota Serang korup, target pajak yang tinggi hanya untuk memperkaya diri sendiri!",NaN,"Fakta bahwa capaian pajak meningkat signifikan dibandingkan tahun sebelumnya dan surplus yang tercipta menunjukkan efektivitas kebijakan pemerintah, bukan indikasi korupsi. Tuduhan korupsi adalah insinuasi negatif yang tidak berdasar.","[Capaian pajak 70,19 persen dari target tahunan adalah hasil dari peningkatan kesadaran wajib pajak dan pertumbuhan sektor usaha, bukan indikasi korupsi., Pencapaian ini jauh lebih tinggi dibandingkan periode yang sama tahun sebelumnya, menunjukkan efektivitas kebijakan pemerintah dalam pengumpulan pajak., Surplus sekitar Rp19 miliar dibandingkan capaian tahun lalu menunjukkan peningkatan kinerja fiskal, bukan keuntungan pribadi., Pernyataan bahwa target pajak tinggi hanya untuk memperkaya diri sendiri tidak didasarkan pada bukti konkrit dan mengabaikan fakta bahwa dana tersebut digunakan untuk pembangunan daerah.]"
11532,https://news.indozone.id/world-update/914860610/kronologi-penembakan-donald-trump-saat-kampanye-akbar-di-pennsylvania?page=all,Kronologi Penembakan Donald Trump saat Kampanye Akbar di Pennsylvania,2024-07-14 10:13:12,"- Sebuah penembakan terjadi pada rapat umumDonald Trumppada hari sabtu waktu setempat, diikuti oleh mantan presiden yang dilarikan dari panggung dengan darah di sekitar telinganya.\nTrumpsedang berbicara di sebuah rapat umum di Butler, Pennsylvania, ketika suara keras terdengar di tengah kerumunan sekitar pukul 18.13 waktu Pennsylvania.\nTrumptampaknya terkena sesuatu di bagian telinga kanannya saat dia berbicara, dan video menunjukkan dia dengan cepat memegangi telinganya dan kemudian menunduk ke tanah, ketika agen keamanan dan yang lainnya melompat untuk membantunya.\nTrumpberdiri dengan darah di sisi wajahnya dan tampak mengatakan ""lawan, lawan"" sambil mengepalkan tinjunya.\nTrumpkemudian dengan cepat dikawal dari panggung dan masuk ke dalam kendaraannya. Lokasi rapat umum kini menjadi tempat kejadian perkara.\nTimTrumpdan Secret Service mengkonfirmasi bahwa dia ""baik-baik saja"" dan sedang diperiksa di fasilitas medis setempat.\nJaksa wilayah Butler mengkonfirmasi bahwa tersangka penembak dan seorang peserta rapat umum telah tewas. Satu orang lainnya yang hadir dalam rapat umum tersebut berada dalam kondisi serius.\nPenembakan tersebut sedang diselidiki sebagai percobaan pembunuhan.\nKonten ini adalah kiriman dari Z Creators Indozone. Yuk, bikin cerita dan konten serumu, serta dapatkan berbagai reward menarik! Let's join Z Creators dengan klikdi sini.",indozone,Politik,1.0,Trump sengaja terkena tembakan untuk mendapatkan simpati publik!,NaN,"Claim tersebut menggunakan insinuasi dan framing negatif dengan menuduh Trump sengaja terkena tembakan untuk mendapatkan simpati publik. Fakta menunjukkan bahwa penembakan tersebut adalah peristiwa nyata dengan korban yang jelas, dan investigasi sedang berlangsung sebagai percobaan pembunuhan.","[Fakta menunjukkan bahwa penembakan terjadi saat Trump sedang berbicara di rapat umum, dan video menunjukkan dia dengan cepat memegangi telinganya dan menunduk ke tanah., Tim Trump dan Secret Service mengkonfirmasi bahwa dia 'baik-baik saja' dan sedang diperiksa di fasilitas medis setempat., Jaksa wilayah Butler mengkonfirmasi bahwa tersangka penembak dan seorang peserta rapat umum telah tewas, menunjukkan kejadian tersebut sangat serius., Kondisi serius satu orang lainnya yang hadir dalam rapat umum tersebut menunjukkan bahwa penembakan tersebut bukanlah aksi palsu., Investigasi sedang dilakukan sebagai percobaan pembunuhan, yang menegaskan kejadian tersebut adalah peristiwa nyata dan bukan settingan.]"

In [6]:
df_fitnah["cot_bantah_fitnah"] = df_fitnah["cot_bantah_fitnah"].fillna(df_fitnah["cot_bantuh_fitnah"])
df_fitnah = df_fitnah.drop(columns=["cot_bantuh_fitnah", "url", "published_at", "sumber_berita", "label", "is_layak"])

C:\Users\Dipo\AppData\Local\Temp\ipykernel_123472\883797873.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fitnah["cot_bantah_fitnah"] = df_fitnah["cot_bantah_fitnah"].fillna(df_fitnah["cot_bantuh_fitnah"])

In [7]:
df_fitnah.isna().sum()

title                0
text                 0
claim_fitnah         0
cot_bantah_fitnah    0
reasoning_fitnah     1
dtype: int64

In [8]:
df_fitnah = df_fitnah.dropna()

In [9]:
df_fitnah.isna().sum()

title                0
text                 0
claim_fitnah         0
cot_bantah_fitnah    0
reasoning_fitnah     0
dtype: int64

In [10]:
df_fitnah["label"] = "Fitnah"

In [11]:
data_fitnah = df_fitnah.to_dict("records")

oke kita punya df_fitnah yang isinya dataframe. jangan diubah

In [12]:
len(df_fitnah)

7211

In [13]:
def generate_sft_dataset_with_context(raw_data_list, instructions, output_file):
    dataset = []
    
    for data in raw_data_list:
        instruct = instructions
        claim = data.get("claim_fitnah", "")
        berita = data.get("text", "") 
        label = data.get("label")
        reasoning = data.get("reasoning_fitnah", "")
        cot_list = data.get("cot_bantah_fitnah", [])
        
        # Susun poin-poin fakta
        fakta_points = "\n".join([f"* {point}" for point in cot_list])
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Komentar: '{claim}';\n\n"
            f"Artikel Rujukan: {berita}"
        )

        full_output = (
            f"Penjelasan: {reasoning}\n"
            f"Berikut adalah beberapa poin penting:\n"
            f"{fakta_points}\n"
            f"Label: {label}."
        )
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(data_fitnah, instructiones, "fitnah.jsonl")

Berhasil membuat 7211 data dengan konteks berita di fitnah.jsonl

In [14]:
contoh_fitnah = pd.read_json("fitnah.jsonl", lines=True)
contoh_fitnah.head(1)

,instruction,input,output
0,"Anda adalah sistem ahli klasifikasi komentar media sosial. Klasifikasikan [Komentar] ke salah satu Nama Label: [Netral, Disinformasi, Fitnah, Ujaran Kebencian].\nAturan:\n1. Ujaran Kebencian: Serangan SARA/identitas/disabilitas (prioritas utama, abaikan rujukan).\n2. Jika bukan ujaran kebencian, gunakan [Artikel Rujukan] jika ada untuk menilai:\n- Netral: Faktual, opini, atau interaksi wajar.\n- Disinformasi: Informasi keliru yang memicu keresahan/polarisasi.\n- Fitnah: Tuduhan bohong untuk menyerang reputasi individu/kelompok.\nFormat Output WAJIB:\nPenjelasan: [Analisis detail dan alasan label]\nLabel: [Nama Label]","Komentar: 'BNN sengaja pilih kampung miskin buat dijadikan kambing hitam soal narkoba';\n\nArtikel Rujukan: BNN menggedebek kampung narkoba di Berlan, Matraman, Jakarta Timur. (Antara Foto/Fauzan)\n- Badan Narkotika Nasional (BNN) bersama petugas gabungan menggerebek kawasan Berlan, Matraman, Jakarta Timur, terkait dugaan peredarannarkobapada Selasa (25/11/2025) siang.\nDalam operasi tersebut, puluhan orang yang diduga sebagai pengedar berhasil diamankan.\nPenggerebekan dilakukan sekitar pukul 11.00 WIB. Petugas gabungan melakukan penyisiran ke sejumlah rumah dan langsung melakukan penggeledahan di titik-titik yang telah ditargetkan.\nDari lokasi, petugas menemukan berbagai jenis barang bukti narkoba dalam bentuk bubuk maupun cairan.\nSejumlah paket narkoba ditemukan disembunyikan di lemari hingga gudang-gudang kecil yang berada di dalam rumah warga.\nTerungkap! Ekstasi Rp 207 M Ditemukan Saat Mobil Kecelakaan di Lampung Hendak Disebar di Jakarta\nUntuk mempermudah pencarian barang bukti, petugas juga mengerahkan anjing pelacak (K9).\nLangkah ini dilakukan untuk memastikan tidak ada narkoba yang terlewatkan selama proses penggeledahan.\nDirektur Psikotropika dan Prekursor Deputi Bidang Pemberantasan BNN, Aldrin Marihot Pandapotan Hutabarat, menyampaikan bahwa pihaknya mengamankan puluhan orang dalam operasi tersebut.\n""Ada 10–15 titik yang menjadi target penggerebekan di kawasan Berlan. Dari rangkaian penggerebekan itu, kami mengamankan 25 pelaku,"" ujar Aldrin.\nSeluruh orang yang diamankan langsung dibawa ke kantor BNN untuk pemeriksaan lebih lanjut. Ia menyebut bahwa para pelaku merupakan warga sekitar.\n""Kawasan ini merupakan perkampungan. Semua yang kami amankan adalah warga sipil. Kami akan dalami peran masing-masing,"" pungkasnya.","Penjelasan: Fakta dipelintir dengan menuduh BNN memilih kampung miskin sebagai kambing hitam, padahal operasi ini didasarkan pada informasi intelijen dan bukti yang ditemukan di lapangan\nBerikut adalah beberapa poin penting:\n* BNN melakukan penggerebekan di Berlan, Matraman, berdasarkan informasi dan indikasi kuat adanya peredaran narkoba di kawasan tersebut\n* Operasi ini melibatkan petugas gabungan dan menggunakan anjing pelacak (K9) untuk memastikan keakuratan dan efektivitas penggeledahan\n* Berbagai jenis barang bukti narkoba ditemukan di lokasi, termasuk bubuk dan cairan yang disembunyikan di lemari dan gudang-gudang kecil\n* Penggerebekan ini mengamankan puluhan orang yang diduga sebagai pengedar, bukan sembarangan warga miskin\n* Tindakan BNN ini adalah bagian dari upaya nasional untuk memerangi peredaran narkoba, tidak ada indikasi pemilihan target berdasarkan status sosial ekonomi\nLabel: Fitnah."

# Disinformasi

In [15]:
folderData = Path("Dataset_disinformasi")
files = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    files.append(df_sementara)

df_disinformasi = pd.concat(files, ignore_index=True)

In [16]:
df_disinformasi = df_disinformasi[df_disinformasi["is_layak"] == 1]

In [17]:
len(df_disinformasi)

7995

In [18]:
df_disinformasi.isna().sum()

claim_disinformasi            0
berita_asli                   0
label                         0
is_layak                      0
cot_bantah_disinformasi       4
reasoning_disinformasi        0
cot_bantuh_disinformasi    7991
dtype: int64

In [19]:
df_disinformasi["cot_bantah_disinformasi"] = df_disinformasi["cot_bantah_disinformasi"].fillna(df_disinformasi["cot_bantuh_disinformasi"])

In [20]:
df_disinformasi = df_disinformasi.drop(columns=["cot_bantuh_disinformasi", "is_layak"])

In [21]:
df_disinformasi.head(1)

,claim_disinformasi,berita_asli,label,cot_bantah_disinformasi,reasoning_disinformasi
0,"Heboh! Pemuda Bakar Mobil Mercedes Karena Buatan Prancis, Padahal Aslinya...","Beredar di media sosial sebuah video yang diklaim memperlihatkan seorang pemuda membakar mobil karena buatan Prancis. Faktanya, klaim adanya pemuda yang membakar mobil miliknya karena mobil tersebut buatan Prancis adalah salah. Dikutip dari Turnbackhoax.id, mobil yang dibakar di video itu adalah Mercedes AMG GT 63 S buatan Jerman. Pria dalam video tersebut bernama Misha atau dikenal sebagai Mikhail Litvin, vlogger asal Rusia. Aksi membakar mobil itu disebabkan oleh rasa kesal karena mobil senilai 13 juta rubel Rusia (Rp 2 miliar) yang dibelinya sering rusak dan keengganan pabrikan untuk menerima tanggung jawab (menanggung biaya perbaikan). Jadi, aksi membakar mobil tersebut tidak ada kaitannya dengan Prancis.",Disinformasi,"[Mobil yang dibakar adalah Mercedes AMG GT 63 S, buatan Jerman, bukan Prancis (sumber: Turnbackhoax.id)., Pria dalam video tersebut adalah Mikhail Litvin, vlogger asal Rusia, yang membakar mobil karena masalah teknis dan keengganan pabrikan untuk bertanggung jawab., Aksi pembakaran mobil tidak ada hubungannya dengan asal negara pembuatan mobil tersebut.]",Ini adalah konten menyesatkan yang mencatut nama negara pembuatan mobil untuk menciptakan narasi yang provokatif dan mengecoh publik.

In [22]:
data_disinformasi = df_disinformasi.to_dict("records")

juga df_disinformasi isinya dataframe

In [23]:
import json
def generate_sft_dataset_with_context(raw_data_list, instructions, output_file):
    dataset = []
    
    for data in raw_data_list:
        instruct = instructions
        claim = data.get("claim_disinformasi", "")
        berita = data.get("berita_asli", "") 
        label = data.get("label")
        reasoning = data.get("reasoning_disinformasi", "")
        cot_list = data.get("cot_bantah_disinformasi", [])
        
        # Susun poin-poin fakta
        fakta_points = "\n".join([f"* {point}" for point in cot_list])
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Komentar: '{claim}';\n\n"
            f"Artikel Rujukan: {berita}"
        )

        full_output = (
            f"Penjelasan: {reasoning}\n"
            f"Berikut adalah beberapa poin penting:\n"
            f"{fakta_points}\n"
            f"Label: {label}."
        )
        
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(data_disinformasi, instructiones, "disinformasi.jsonl")

Berhasil membuat 7995 data dengan konteks berita di disinformasi.jsonl

In [24]:
contoh_disinformasi = pd.read_json("disinformasi.jsonl", lines=True)
contoh_disinformasi.head(1)

,instruction,input,output
0,"Anda adalah sistem ahli klasifikasi komentar media sosial. Klasifikasikan [Komentar] ke salah satu Nama Label: [Netral, Disinformasi, Fitnah, Ujaran Kebencian].\nAturan:\n1. Ujaran Kebencian: Serangan SARA/identitas/disabilitas (prioritas utama, abaikan rujukan).\n2. Jika bukan ujaran kebencian, gunakan [Artikel Rujukan] jika ada untuk menilai:\n- Netral: Faktual, opini, atau interaksi wajar.\n- Disinformasi: Informasi keliru yang memicu keresahan/polarisasi.\n- Fitnah: Tuduhan bohong untuk menyerang reputasi individu/kelompok.\nFormat Output WAJIB:\nPenjelasan: [Analisis detail dan alasan label]\nLabel: [Nama Label]","Komentar: 'Heboh! Pemuda Bakar Mobil Mercedes Karena Buatan Prancis, Padahal Aslinya...';\n\nArtikel Rujukan: Beredar di media sosial sebuah video yang diklaim memperlihatkan seorang pemuda membakar mobil karena buatan Prancis. Faktanya, klaim adanya pemuda yang membakar mobil miliknya karena mobil tersebut buatan Prancis adalah salah. Dikutip dari Turnbackhoax.id, mobil yang dibakar di video itu adalah Mercedes AMG GT 63 S buatan Jerman. Pria dalam video tersebut bernama Misha atau dikenal sebagai Mikhail Litvin, vlogger asal Rusia. Aksi membakar mobil itu disebabkan oleh rasa kesal karena mobil senilai 13 juta rubel Rusia (Rp 2 miliar) yang dibelinya sering rusak dan keengganan pabrikan untuk menerima tanggung jawab (menanggung biaya perbaikan). Jadi, aksi membakar mobil tersebut tidak ada kaitannya dengan Prancis.","Penjelasan: Ini adalah konten menyesatkan yang mencatut nama negara pembuatan mobil untuk menciptakan narasi yang provokatif dan mengecoh publik.\nBerikut adalah beberapa poin penting:\n* Mobil yang dibakar adalah Mercedes AMG GT 63 S, buatan Jerman, bukan Prancis (sumber: Turnbackhoax.id).\n* Pria dalam video tersebut adalah Mikhail Litvin, vlogger asal Rusia, yang membakar mobil karena masalah teknis dan keengganan pabrikan untuk bertanggung jawab.\n* Aksi pembakaran mobil tidak ada hubungannya dengan asal negara pembuatan mobil tersebut.\nLabel: Disinformasi."

# Fakta

In [25]:
folderData = Path("Dataset_fakta")
files = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    files.append(df_sementara)

df = pd.concat(files, ignore_index=True)

In [26]:
df_fakta = df[df["is_layak"]==1]

In [27]:
df_fakta = df_fakta.drop(columns=["url", "title", "published_at", "sumber_berita", "label", "is_layak"])
df_fakta["label"] = "Fakta"

In [28]:
df_fakta.head(1)

,text,claim_fakta,cot_analisis_fakta,reasoning_fakta,label
0,"Konsumsi rokok dan minuman beralkohol masyarakat Kabupaten Pangandaran tercatat lebih tinggi dibandingkan belanja ikan dan telur. Kondisi ini mencerminkan adanya kecenderungan prioritas pengeluaran tertentu dalam kelompok konsumsi makanan masyarakat setempat.\nBerdasarkan data Badan Pusat Statistik (BPS) Kabupaten Pangandaran dalam laporan Kabupaten Pangandaran dalam Angka 2025, rokok dan minuman beralkohol diklasifikasikan ke dalam kelompok pengeluaran makanan. Menariknya, alokasi belanja untuk kategori tersebut justru melampaui pengeluaran untuk sumber pangan bergizi seperti ayam, telur, dan ikan.\nMeski demikian, secara umum BPS mencatat bahwa total pengeluaran penduduk Pangandaran untuk konsumsi makanan masih lebih besar dibandingkan pengeluaran non-makanan.\nSCROLL TO CONTINUE WITH CONTENT\nRata-rata pengeluaran per kapita per bulan penduduk Kabupaten Pangandaran pada 2024 tercatat sebesar Rp1.367.729. Dari jumlah tersebut, pengeluaran untuk kelompok makanan mencapai Rp809.992 atau 59,22 persen, sedangkan pengeluaran non-makanan sebesar Rp557.738 atau 40,78 persen.\nJika dibandingkan dengan tahun 2023, proporsi pengeluaran untuk makanan mengalami peningkatan. Pada 2023, pengeluaran makanan tercatat sebesar 55,72 persen, lalu naik menjadi 59,22 persen pada 2024.\nPada kelompok makanan tahun 2024, pengeluaran terbesar dialokasikan untuk makanan dan minuman jadi sebesar 15,56 persen, diikuti kelompok kacang-kacangan, buah-buahan, dan sayuran sebesar 10,51 persen, serta padi-padian dan umbi-umbian sebesar 9,59 persen.\nSementara itu, pengeluaran untuk kelompok ikan, daging, telur, dan susu hanya mencapai 8,76 persen, lebih rendah dibandingkan pengeluaran untuk rokok dan tembakau yang mencapai 9,20 persen. Pada 2023, proporsi belanja rokok dan tembakau tercatat sebesar 8,81 persen dan meningkat pada 2024.\nPada kelompok non-makanan tahun 2024, pengeluaran terbesar dialokasikan untuk perumahan, bahan bakar, penerangan, dan air dengan kontribusi 21,45 persen dari total pengeluaran. Sebaliknya, pengeluaran paling kecil terdapat pada keperluan pesta dan upacara adat yang hanya mencapai 1,13 persen.\nJika dibandingkan dengan tahun 2023, proporsi pengeluaran non-makanan secara keseluruhan mengalami penurunan. Pada 2023, pengeluaran non-makanan tercatat sebesar 23,28 persen, sedangkan pada 2024 tercatat sebesar 40,78 persen seiring meningkatnya total nilai pengeluaran masyarakat.\nPengeluaran untuk aneka barang dan jasa, biaya pendidikan, serta kesehatan tergolong relatif rendah. Pada 2023, kelompok ini menyumbang 9,03 persen dari total pengeluaran, kemudian menurun menjadi 8,82 persen pada 2024. Pengeluaran untuk pakaian dan alas kaki tercatat sebesar 2,80 persen pada 2023 dan turun menjadi 2,46 persen pada 2024.\nTingginya proporsi pengeluaran untuk makanan menunjukkan bahwa tingkat kesejahteraan masyarakat Kabupaten Pangandaran masih tergolong rendah, karena sebagian besar pendapatan digunakan untuk memenuhi kebutuhan dasar.\nNamun, data BPS juga menunjukkan bahwa pada kelompok pengeluaran 20 persen teratas, pola konsumsi mulai bergeser. Pada kelompok ini, pengeluaran non-makanan cenderung lebih besar dibandingkan pengeluaran makanan, yang mengindikasikan peningkatan taraf hidup dan diversifikasi kebutuhan.","Wah, orang di Pangandaran belanjanya lebih banyak buat rokok daripada makanan bergizi kayak ikan dan telur!","[Data BPS menunjukkan bahwa pengeluaran untuk rokok dan minuman beralkohol di Kabupaten Pangandaran mencapai 9,20 persen dari total pengeluaran makanan., Pengeluaran untuk ikan, daging, telur, dan susu hanya 8,76 persen, lebih rendah dari pengeluaran untuk rokok dan tembakau., Total pengeluaran per kapita per bulan penduduk Pangandaran pada 2024 tercatat sebesar Rp1.367.729, dengan pengeluaran untuk makanan mencapai Rp809.992 atau 59,22 persen.]","Klaim ini sesuai dengan data BPS yang menunjukkan pengeluaran untuk rokok dan minuman beralkohol lebih tinggi dibandingkan pengeluaran untuk ikan, daging, telur, dan susu di Kabupaten Pangandaran.",Fakta

In [29]:
len(df_fakta)

7790

In [30]:
df_fakta = df_fakta[:1300]

In [31]:
df_fakta.isna().sum()

text                  0
claim_fakta           0
cot_analisis_fakta    0
reasoning_fakta       0
label                 0
dtype: int64

In [32]:
data_fakta = df_fakta.to_dict("records")

In [33]:
def generate_sft_dataset_with_context(raw_data_list, instructions, output_file):
    dataset = [] 
    label = "Netral" # gw ganti netral bae dah, biar konsisten sama tim sebelah
    for data in raw_data_list:
        instruct = instructions
        claim = data.get("claim_fakta", "")
        berita = data.get("text", "") 
        reasoning = data.get("reasoning_fakta", "")
        cot_list = data.get("cot_analisis_fakta", [])
        
        # Susun poin-poin fakta
        fakta_points = "\n".join([f"* {point}" for point in cot_list])
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Komentar: '{claim}';\n\n"
            f"Artikel Rujukan: {berita}"
        )

        full_output = (
            f"Penjelasan: {reasoning}\n"
            f"Berikut adalah beberapa poin penting:\n"
            f"{fakta_points}\n"
            f"Label: {label}."
        )
        
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(data_fakta, instructiones, "fakta.jsonl")

Berhasil membuat 1300 data dengan konteks berita di fakta.jsonl

In [34]:
contoh_fakta = pd.read_json("fakta.jsonl", lines=True)
contoh_fakta.head(1)

,instruction,input,output
0,"Anda adalah sistem ahli klasifikasi komentar media sosial. Klasifikasikan [Komentar] ke salah satu Nama Label: [Netral, Disinformasi, Fitnah, Ujaran Kebencian].\nAturan:\n1. Ujaran Kebencian: Serangan SARA/identitas/disabilitas (prioritas utama, abaikan rujukan).\n2. Jika bukan ujaran kebencian, gunakan [Artikel Rujukan] jika ada untuk menilai:\n- Netral: Faktual, opini, atau interaksi wajar.\n- Disinformasi: Informasi keliru yang memicu keresahan/polarisasi.\n- Fitnah: Tuduhan bohong untuk menyerang reputasi individu/kelompok.\nFormat Output WAJIB:\nPenjelasan: [Analisis detail dan alasan label]\nLabel: [Nama Label]","Komentar: 'Wah, orang di Pangandaran belanjanya lebih banyak buat rokok daripada makanan bergizi kayak ikan dan telur!';\n\nArtikel Rujukan: Konsumsi rokok dan minuman beralkohol masyarakat Kabupaten Pangandaran tercatat lebih tinggi dibandingkan belanja ikan dan telur. Kondisi ini mencerminkan adanya kecenderungan prioritas pengeluaran tertentu dalam kelompok konsumsi makanan masyarakat setempat.\nBerdasarkan data Badan Pusat Statistik (BPS) Kabupaten Pangandaran dalam laporan Kabupaten Pangandaran dalam Angka 2025, rokok dan minuman beralkohol diklasifikasikan ke dalam kelompok pengeluaran makanan. Menariknya, alokasi belanja untuk kategori tersebut justru melampaui pengeluaran untuk sumber pangan bergizi seperti ayam, telur, dan ikan.\nMeski demikian, secara umum BPS mencatat bahwa total pengeluaran penduduk Pangandaran untuk konsumsi makanan masih lebih besar dibandingkan pengeluaran non-makanan.\nSCROLL TO CONTINUE WITH CONTENT\nRata-rata pengeluaran per kapita per bulan penduduk Kabupaten Pangandaran pada 2024 tercatat sebesar Rp1.367.729. Dari jumlah tersebut, pengeluaran untuk kelompok makanan mencapai Rp809.992 atau 59,22 persen, sedangkan pengeluaran non-makanan sebesar Rp557.738 atau 40,78 persen.\nJika dibandingkan dengan tahun 2023, proporsi pengeluaran untuk makanan mengalami peningkatan. Pada 2023, pengeluaran makanan tercatat sebesar 55,72 persen, lalu naik menjadi 59,22 persen pada 2024.\nPada kelompok makanan tahun 2024, pengeluaran terbesar dialokasikan untuk makanan dan minuman jadi sebesar 15,56 persen, diikuti kelompok kacang-kacangan, buah-buahan, dan sayuran sebesar 10,51 persen, serta padi-padian dan umbi-umbian sebesar 9,59 persen.\nSementara itu, pengeluaran untuk kelompok ikan, daging, telur, dan susu hanya mencapai 8,76 persen, lebih rendah dibandingkan pengeluaran untuk rokok dan tembakau yang mencapai 9,20 persen. Pada 2023, proporsi belanja rokok dan tembakau tercatat sebesar 8,81 persen dan meningkat pada 2024.\nPada kelompok non-makanan tahun 2024, pengeluaran terbesar dialokasikan untuk perumahan, bahan bakar, penerangan, dan air dengan kontribusi 21,45 persen dari total pengeluaran. Sebaliknya, pengeluaran paling kecil terdapat pada keperluan pesta dan upacara adat yang hanya mencapai 1,13 persen.\nJika dibandingkan dengan tahun 2023, proporsi pengeluaran non-makanan secara keseluruhan mengalami penurunan. Pada 2023, pengeluaran non-makanan tercatat sebesar 23,28 persen, sedangkan pada 2024 tercatat sebesar 40,78 persen seiring meningkatnya total nilai pengeluaran masyarakat.\nPengeluaran untuk aneka barang dan jasa, biaya pendidikan, serta kesehatan tergolong relatif rendah. Pada 2023, kelompok ini menyumbang 9,03 persen dari total pengeluaran, kemudian menurun menjadi 8,82 persen pada 2024. Pengeluaran untuk pakaian dan alas kaki tercatat sebesar 2,80 persen pada 2023 dan turun menjadi 2,46 persen pada 2024.\nTingginya proporsi pengeluaran untuk makanan menunjukkan bahwa tingkat kesejahteraan masyarakat Kabupaten Pangandaran masih tergolong rendah, karena sebagian besar pendapatan digunakan untuk memenuhi kebutuhan dasar.\nNamun, data BPS juga menunjukkan bahwa pada kelompok pengeluaran 20 persen teratas, pola konsumsi mulai bergeser. Pada kelompok ini, pengeluaran non-makanan cenderung lebih besar dibandingkan pengeluaran makanan, yang mengindikasikan peningkatan taraf hidup dan diversifikasi kebutuhan.","Penjelasan: Klaim ini sesuai dengan data BPS yang menunjukkan pengeluaran untuk rokok dan minuman beralkohol lebih tinggi dibandingkan pengeluaran untuk ikan, daging, telur, dan susu di Kabupaten Pangandaran.\nBerikut adalah beberapa poin penting:\n* Data BPS menunjukkan bahwa pengeluaran untuk rokok dan minuman beralkohol di Kabupaten Pangandaran mencapai 9,20 persen dari total pengeluaran makanan.\n* Pengeluaran untuk ikan, daging, telur, dan susu hanya 8,76 persen, lebih rendah dari pengeluaran untuk rokok dan tembakau.\n* Total pengeluaran per kapita per bulan penduduk Pangandaran pada 2024 tercatat sebesar Rp1.367.729, dengan pengeluaran untuk makanan mencapai Rp809.992 atau 59,22 persen.\nLabel: Netral."

# Non-DFK

In [35]:
folderData = Path("Dataset_nonDFK")
komentar = []


for file in folderData.glob("*.jsonl"):
    if file.name == "panduan_komunitas.jsonl":
        continue
    
    df_sementara = pd.read_json(file, lines=True)
    komentar.append(df_sementara)

df_nondfk = pd.concat(komentar, ignore_index=True)

In [36]:
df_nondfk["gaya_komentar"].unique()

array(['brutal', 'sarkas', 'simpati', 'enthusiastis', 'halus', 'gaul',
       'ceplas-ceplos', 'nyeletuk', 'enthusiast', 'kebingungan',
       'harapan', 'irasional', 'penasaran', 'reflektif', 'simpatik',
       'informasi', 'alay', 'positif', 'puji', 'empati', 'setuju',
       'harap', 'peduli', 'kaget', 'pikir', 'khawatir', 'hype', 'heran',
       'kesal', 'neutral', 'peringatan', 'netral', 'sarcastik', 'pemuji',
       'sentimental', 'gembira', 'reaksi', 'humor', 'informal',
       'emosional', 'optimis', 'antusias', 'senang', 'normal', 'casual',
       'memuji', 'kagum', 'bujuk rayu', 'mengagumi', 'opinif', 'serius',
       'ringan', 'sedih', 'simpatetik', 'terima kasih', 'curious',
       'stereotip', 'generalisasi kebiasaan buruk', 'celetukan', 'ramah',
       'informatif', 'dukungan', 'ringkas', 'biasa', 'nasihat',
       'pendukung', 'kecewa', 'terkejut', 'keheranan', 'hangat',
       'terkesan', 'singkat', 'praktis', 'resah', 'nostalgia', 'cemas',
       'skeptis', 'tertarik', 'pertanyaan', 'saran', 'empathetic',
       'sarcastic', 'uforia', 'non-stereotip', 'insinuasi',
       'sharing info', 'tanya dong', 'ungkapan kagum',
       'ungkapan antusias', 'sharing', 'seru', 'tag teman',
       'ungkapan kaget', 'dorongan semangat', 'ekspresi kaget',
       'refleksi', 'pembantu', 'info dong', 'nyimak',
       'sharing pengalaman', 'komentar santai', 'ceplas ceplos', 'pujian',
       'komentar nyimak', 'opini', 'expressing concern',
       'expressing hope', 'ekspresi keresahan', 'ekspresi simpati',
       'apresiasi', 'tanya', 'syukur', 'reaksi kaget'], dtype=object)

In [37]:
df_nondfk[df_nondfk["gaya_komentar"] =="stereotip"].head(1)

,title,text,claim_nonDFK,gaya_komentar,is_layak,cot_analisis,reasoning_nonDFK
3225,Film Terlaris Indonesia Skenarionya Ditulis Perempuan,"Di semester pertama tahun 2025 ini, Indonesia memiliki film terlaris yang mampu menggeser posisi film lainnya, yaitu Jumbo. Film animasi pertama di Indonesia ini berhasil meraih box office, sekaligus menjadi film terlaris di Asia Tenggara.\nDi balik cerita yang menyentuh dan hangat, ada sosok seorang perempuan bernama Widya Arifianti, yang bertindak sebagai penulis kenario.\nTak hanya Widya Arifianti sebagai penulis skenario Jumbo, ada sembilan perempuan lainnya yang menulis film laris di Indonesia.","bjir, gue kagum banget sama Widya, nulis skenario keren banget!",stereotip,1,"[Komentar ini hanya mengungkapkan rasa kagum terhadap Widya Arifianti tanpa menambahkan klaim fakta baru., Komentar tidak mengandung fitnah atau tuduhan tanpa bukti., Komentar tidak mengandung ujaran kebencian atau serangan SARA.]","Komentar ini bersifat ekspresif dan hanya mengekspresikan rasa kagum, tanpa menambahkan informasi atau klaim baru. Tidak ada unsur DFK."

In [38]:
len(df_nondfk[df_nondfk["is_layak"] == 1])

6663

In [39]:
df_nondfk = df_nondfk[df_nondfk["is_layak"] == 1]
df_nondfk["label"] = "Bukan DFK" # di kemudian hari jadi Netral

In [40]:
df_nondfk = df_nondfk[:1200]

In [41]:
df_nondfk.head(1)

,title,text,claim_nonDFK,gaya_komentar,is_layak,cot_analisis,reasoning_nonDFK,label
0,Perubahan Positif saat Perempuan Mulai Fokus Perbaiki Diri,"Perempuan sering kali mengalami overthinking atas beragam hal dihadapinya. Mulai dari menjalani kehidupan sehari-hari, melakoni pekerjaan, urusan percintaan, dan lain-lain, bisa membuat mereka begitu kewalahan.\nPadahal, tidak semuanya perlu dipikirkan secara rumit karena memang pada kenyataannya sebagian merupakan hal yang sederhana saja. Namun, kebiasaan overthinking semacam ini tentu tidak muncul begitu saja.\nKaum hawa sering kali belum bisa memegang prinsipnya secara kuat, sehingga mudah terpengaruh ucapan orang lain yang bahkan belum tentu mengerti apa yang disampaikannya. Akibatnya, mereka jadi bingung dan sulit untuk mendapatkan ketenangan.\nOleh karena itu, para perempuan harus belajar untuk mulai fokus pada diri sendiri karena keputusan ini akan menciptakan beragam perubahan positif sebagai berikut.","anjir betul, gw udh mulai fokus ke diri sendiri, beneran beds banget!",brutal,1,"[Komentar ini hanya menyampaikan perasaan pribadi dan pengalaman sendiri tanpa menambahkan informasi baru., Komentar tidak mengandung klaim fakta baru atau pelintiran berita., Komentar tidak mengandung fitnah atau ujaran kebencian., Komentar bersifat ekspresif dan mendukung konten artikel tanpa menimbulkan kontroversi.]","Komentar ini hanya menyampaikan pengalaman pribadi tentang fokus diri sendiri dan perubahan positif yang dirasakan. Tidak ada klaim baru atau informasi yang ditambahkan, serta tidak mengandung fitnah atau ujaran kebencian.",Bukan DFK

In [42]:
df_nondfk.isna().sum()

title               0
text                0
claim_nonDFK        0
gaya_komentar       0
is_layak            0
cot_analisis        0
reasoning_nonDFK    0
label               0
dtype: int64

In [43]:
data_nondfk = df_nondfk.to_dict("records")

In [44]:
def generate_sft_dataset_with_context(raw_data_list, instructions, output_file):
    dataset = []
    label = "Netral" 
    
    for data in raw_data_list:
        instruct = instructions
        claim = data.get("claim_nonDFK", "")
        teks = data.get("text", "") 
        reasoning = data.get("reasoning_nonDFK", "")
        cot_list = data.get("cot_analisis", [])
        
        fakta_points = "\n".join([f"* {point}" for point in cot_list])
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Komentar: '{claim}';\n\n"
            f"Artikel Rujukan: {teks}"
        )

        full_output = (
            f"Penjelasan: {reasoning}\n"
            f"Berikut merupakan alasan alasannya:\n"
            f"{fakta_points}\n"
            f"Label: {label}."
        )
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(data_nondfk, instructiones, "nonDFK.jsonl")

Berhasil membuat 1200 data dengan konteks berita di nonDFK.jsonl

In [45]:
contoh_nondfk = pd.read_json("nonDFK.jsonl", lines=True)
contoh_nondfk.head(1)

,instruction,input,output
0,"Anda adalah sistem ahli klasifikasi komentar media sosial. Klasifikasikan [Komentar] ke salah satu Nama Label: [Netral, Disinformasi, Fitnah, Ujaran Kebencian].\nAturan:\n1. Ujaran Kebencian: Serangan SARA/identitas/disabilitas (prioritas utama, abaikan rujukan).\n2. Jika bukan ujaran kebencian, gunakan [Artikel Rujukan] jika ada untuk menilai:\n- Netral: Faktual, opini, atau interaksi wajar.\n- Disinformasi: Informasi keliru yang memicu keresahan/polarisasi.\n- Fitnah: Tuduhan bohong untuk menyerang reputasi individu/kelompok.\nFormat Output WAJIB:\nPenjelasan: [Analisis detail dan alasan label]\nLabel: [Nama Label]","Komentar: 'anjir betul, gw udh mulai fokus ke diri sendiri, beneran beds banget!';\n\nArtikel Rujukan: Perempuan sering kali mengalami overthinking atas beragam hal dihadapinya. Mulai dari menjalani kehidupan sehari-hari, melakoni pekerjaan, urusan percintaan, dan lain-lain, bisa membuat mereka begitu kewalahan.\nPadahal, tidak semuanya perlu dipikirkan secara rumit karena memang pada kenyataannya sebagian merupakan hal yang sederhana saja. Namun, kebiasaan overthinking semacam ini tentu tidak muncul begitu saja.\nKaum hawa sering kali belum bisa memegang prinsipnya secara kuat, sehingga mudah terpengaruh ucapan orang lain yang bahkan belum tentu mengerti apa yang disampaikannya. Akibatnya, mereka jadi bingung dan sulit untuk mendapatkan ketenangan.\nOleh karena itu, para perempuan harus belajar untuk mulai fokus pada diri sendiri karena keputusan ini akan menciptakan beragam perubahan positif sebagai berikut.","Penjelasan: Komentar ini hanya menyampaikan pengalaman pribadi tentang fokus diri sendiri dan perubahan positif yang dirasakan. Tidak ada klaim baru atau informasi yang ditambahkan, serta tidak mengandung fitnah atau ujaran kebencian.\nBerikut merupakan alasan alasannya:\n* Komentar ini hanya menyampaikan perasaan pribadi dan pengalaman sendiri tanpa menambahkan informasi baru.\n* Komentar tidak mengandung klaim fakta baru atau pelintiran berita.\n* Komentar tidak mengandung fitnah atau ujaran kebencian.\n* Komentar bersifat ekspresif dan mendukung konten artikel tanpa menimbulkan kontroversi.\nLabel: Netral."

# Gabungin non-dfk dan fakta menjadi Netral
## sama tambahin data

### dari YT

In [46]:
folderData = Path("Dataset_yt")
komentar = []


for file in folderData.glob("*.csv"):
    df_sementara = pd.read_csv(file)
    komentar.append(df_sementara)

df_komentaryt = pd.concat(komentar, ignore_index=True)

In [47]:
import re
def bersih_(teks):
    bersih = re.sub(r'_{2,}', ' ', teks)

    return " ".join(bersih.split())

df_komentaryt["komentar_asli"] = df_komentaryt["komentar_asli"].apply(bersih_)

benerin ada yang salah label

In [48]:
kalimat_target = "Biadab mereka zionis apalagi mereka pendukung nya"
alasan = """Terdeteksi Ujaran Kebencian / SARA: Kata "Biadab" adalah kata yang sangat kuat dan dehumanizing. 
Artinya brutal, tidak beradab, savage. Ini bukan kritik biasa, 
tapi langsung menyerang martabat/kemanusiaan kelompok tersebut. 
Frasa "mereka zionis" + "mereka pendukungnya" melakukan generalisasi massal."""

df_komentaryt.loc[df_komentaryt["komentar_asli"] == kalimat_target, "alasan_non_dfk"] = alasan

In [49]:
import numpy as np
kondisi = df_komentaryt['alasan_non_dfk'].str.contains("Terdeteksi Ujaran Kebencian|Terdeteksi unsur seksisme", na=False)
df_komentaryt['kategori_flag'] = np.where(kondisi, "Ujaran Kebencian", "Netral")

In [50]:
df_komentaryt[df_komentaryt["komentar_asli"].str.contains('Tahun lalu gelut krn nempel nempel di photobox trs disogok bunga damai bbrp hari besoknya malah duduk sampingan sama si perek lanjut gelut part 2 akwoakwoakwo makasih bunganya')]

,komentar_asli,mengandung_klaim,search_query,alasan_non_dfk,kategori_flag
2964,Tahun lalu gelut krn nempel nempel di photobox trs disogok bunga damai bbrp hari besoknya malah duduk sampingan sama si perek lanjut gelut part 2 akwoakwoakwo makasih bunganya,False,TIDAK_BUTUH_RAG,"Terdeteksi Ujaran Kebencian / SARA karena penggunaan istilah ""si perek"" yang bersifat seksis dan merendahkan perempuan",Ujaran Kebencian

In [51]:
netral = df_komentaryt[df_komentaryt["kategori_flag"] == "Netral"]
hate = df_komentaryt[df_komentaryt["kategori_flag"] == "Ujaran Kebencian"] # ini nanti di digabung ke dataset ujaran kebencian

netral = netral[netral["search_query"] == "TIDAK_BUTUH_RAG"]
hate = hate[hate["search_query"] == "TIDAK_BUTUH_RAG"]

print(len(netral))
print(len(hate))

3589
484

In [52]:
netral.head(1)

,komentar_asli,mengandung_klaim,search_query,alasan_non_dfk,kategori_flag
0,BEM bayaran singaparna Investor asing sedang keluar Eh dia malah bikin rusuh bikin kacau aja nih Belajar aja yang benar BEM,False,TIDAK_BUTUH_RAG,Hanya berupa opini dan tuduhan tanpa klaim fakta spesifik yang bisa diverifikasi,Netral

In [53]:
datatambahan = netral.to_dict("records")

In [54]:
def generate_sft_dataset_with_context(raw_data_list, instructions, output_file):
    dataset = []
    label = "Netral" 
    
    for data in raw_data_list:
        instruct = instructions
        claim = data.get("komentar_asli", "")
        reasoning = data.get("alasan_non_dfk", "")
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Komentar: '{claim}';\n\n"
        )

        full_output = (
            f"Penjelasan: {reasoning}\n"
            f"Label: {label}."
        )
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(datatambahan, instructiones, "netral.jsonl")

Berhasil membuat 3589 data dengan konteks berita di netral.jsonl

In [55]:
nonDFK = pd.read_json("nonDFK.jsonl", lines=True)
fakta = pd.read_json("fakta.jsonl", lines=True)
netral1 = pd.read_json("netral.jsonl", lines=True)

In [56]:
# bersihin data tamabahan

netral2 = pd.read_json("netrals.jsonl", lines=True)

def bersihkan_output(teks):
    if isinstance(teks, str):
        teks = teks.replace("**", "")
        
        teks = teks.replace("\n*", "")

        target_keyword = "Label: Netral."
        
        # ambil teks berdasarkan keyword, ambil bagian sebelum keyword (indeks 0)
        if target_keyword in teks:
            teks_bersih = teks.split(target_keyword)[0]
            return (teks_bersih + target_keyword).strip()
            
    return teks

netral2["output"] = netral2["output"].apply(bersihkan_output)

### dari HF

In [57]:
folderData = Path("Dataset_hf")
files = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    files.append(df_sementara)

hf = pd.concat(files, ignore_index=True)

In [58]:
hf.head(1)

,komentar_asli,mengandung_klaim,tipe_komentar,search_query,cot_analisis,alasan_kategori
0,gemesnya wkwkkw whitni uga gemes kek gini ueueue ayang whitni jomok lukh,False,netral,,"[Komentar berisi ekspresi kasual berupa kata-kata sayang dan tawa internet (wkwk, ueueue)., Tidak ada pernyataan fakta, rumor, atau informasi yang perlu diverifikasi., Tidak mengandung unsur SARA atau serangan terhadap kelompok tertentu.]",Komentar ini merupakan ekspresi emosional ringan dan santai yang lazim digunakan netizen saat mengomentari sesuatu yang menggemaskan tanpa menyerang siapa pun.

In [59]:
netral_hf = hf[hf["tipe_komentar"] == "netral"]
len(netral_hf)

1407

In [60]:
hate_hf = hf[hf["tipe_komentar"] == "ujaran_kebencian"]
len(hate_hf)

589

In [61]:
netral_hf.head(1)

,komentar_asli,mengandung_klaim,tipe_komentar,search_query,cot_analisis,alasan_kategori
0,gemesnya wkwkkw whitni uga gemes kek gini ueueue ayang whitni jomok lukh,False,netral,,"[Komentar berisi ekspresi kasual berupa kata-kata sayang dan tawa internet (wkwk, ueueue)., Tidak ada pernyataan fakta, rumor, atau informasi yang perlu diverifikasi., Tidak mengandung unsur SARA atau serangan terhadap kelompok tertentu.]",Komentar ini merupakan ekspresi emosional ringan dan santai yang lazim digunakan netizen saat mengomentari sesuatu yang menggemaskan tanpa menyerang siapa pun.

In [62]:
data_netral = netral_hf.to_dict("records")

In [63]:
import json

def generate_sft_dataset_with_context(raw_data_list, instructions, output_file):
    label = "Netral"
    dataset = []
    
    for data in raw_data_list:
        instruct = instructions
        claim = data.get("komentar_asli", "")
        reasoning = data.get("alasan_kategori", "")
        cot_list = data.get("cot_analisis", [])
        
        # Susun poin-poin fakta
        fakta_points = "\n".join([f"* {point}" for point in cot_list])
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Komentar: '{claim}';\n\n"
        )

        full_output = (
            f"Penjelasan: {reasoning}\n"
            f"Berikut adalah beberapa poin penting:\n"
            f"{fakta_points}\n"
            f"Label: {label}."
        )
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(data_netral, instructiones, "netral3.jsonl")

Berhasil membuat 1407 data dengan konteks berita di netral3.jsonl

In [64]:
netral3 = pd.read_json("netral3.jsonl", lines=True)

### gabungin fakta, nondfk, sama data tambahannya

In [65]:
netral3.head(1)

,instruction,input,output
0,"Anda adalah sistem ahli klasifikasi komentar media sosial. Klasifikasikan [Komentar] ke salah satu Nama Label: [Netral, Disinformasi, Fitnah, Ujaran Kebencian].\nAturan:\n1. Ujaran Kebencian: Serangan SARA/identitas/disabilitas (prioritas utama, abaikan rujukan).\n2. Jika bukan ujaran kebencian, gunakan [Artikel Rujukan] jika ada untuk menilai:\n- Netral: Faktual, opini, atau interaksi wajar.\n- Disinformasi: Informasi keliru yang memicu keresahan/polarisasi.\n- Fitnah: Tuduhan bohong untuk menyerang reputasi individu/kelompok.\nFormat Output WAJIB:\nPenjelasan: [Analisis detail dan alasan label]\nLabel: [Nama Label]",Komentar: 'gemesnya wkwkkw whitni uga gemes kek gini ueueue ayang whitni jomok lukh';\n\n,"Penjelasan: Komentar ini merupakan ekspresi emosional ringan dan santai yang lazim digunakan netizen saat mengomentari sesuatu yang menggemaskan tanpa menyerang siapa pun.\nBerikut adalah beberapa poin penting:\n* Komentar berisi ekspresi kasual berupa kata-kata sayang dan tawa internet (wkwk, ueueue).\n* Tidak ada pernyataan fakta, rumor, atau informasi yang perlu diverifikasi.\n* Tidak mengandung unsur SARA atau serangan terhadap kelompok tertentu.\nLabel: Netral."

In [66]:
dataNetral = pd.concat([nonDFK, fakta, netral1, netral2, netral3], ignore_index=True)
dataNetral.to_json("dataNetral.jsonl", orient='records', lines=True)

In [67]:
len(dataNetral)

7546

In [68]:
dataNetral.tail(1)

,instruction,input,output
7545,"Anda adalah sistem ahli klasifikasi komentar media sosial. Klasifikasikan [Komentar] ke salah satu Nama Label: [Netral, Disinformasi, Fitnah, Ujaran Kebencian].\nAturan:\n1. Ujaran Kebencian: Serangan SARA/identitas/disabilitas (prioritas utama, abaikan rujukan).\n2. Jika bukan ujaran kebencian, gunakan [Artikel Rujukan] jika ada untuk menilai:\n- Netral: Faktual, opini, atau interaksi wajar.\n- Disinformasi: Informasi keliru yang memicu keresahan/polarisasi.\n- Fitnah: Tuduhan bohong untuk menyerang reputasi individu/kelompok.\nFormat Output WAJIB:\nPenjelasan: [Analisis detail dan alasan label]\nLabel: [Nama Label]",Komentar: 'Cindy mau ngewe';\n\n,"Penjelasan: Komentar ini bersifat ekspresi kasual berisi kata vulgar yang tidak menyerang identitas SARA atau kelompok tertentu sehingga tidak menimbulkan dampak berbahaya.\nBerikut adalah beberapa poin penting:\n* Komentar hanya berisi frasa vulgar tanpa konteks klaim fakta atau informasi yang dapat diverifikasi.\n* Tidak ada penyebutan identitas SARA, kelompok, atau individu yang ditargetkan secara diskriminatif.\n* Penggunaan kata 'ngewe' bersifat kasual dan tidak mengandung serangan atau ujaran kebencian.\n* Komentar tidak mengarah pada rumor, mitos, atau pernyataan politik/sosial yang memerlukan pengecekan.\n* Sesuai aturan, konten vulgar tanpa unsur SARA dikategorikan netral.\nLabel: Netral."

# Buat Dataset Ujaran Kebencian

In [69]:
folderData = Path("Dataset_UjaranKebencian")
komentar = []


for file in folderData.glob("*.jsonl"):
    if file.name == "panduan_komunitas.jsonl":
        continue
    
    df_sementara = pd.read_json(file, lines=True)
    komentar.append(df_sementara)

df_ujarankb = pd.concat(komentar, ignore_index=True)

In [70]:
df_ujarankb.isna().sum()

claim_disinformasi               0
target                           0
label                            0
jenis                            0
isExplicit                       4
IDPelanggaran                   13
cot_analisis                     4
reasoning_ujaran_kebencian       5
IDPelangguaran                7301
IDPelangguuran                7304
IDPelangguan                  7300
dtype: int64

In [71]:
df_ujarankb = df_ujarankb.drop(df_ujarankb[df_ujarankb["reasoning_ujaran_kebencian"].isna()].index)

In [72]:
eksplisit = df_ujarankb[df_ujarankb["isExplicit"] == 1]
print(len(eksplisit))

5268

In [73]:
eksplisit.isna().sum()

claim_disinformasi               0
target                           0
label                            0
jenis                            0
isExplicit                       0
IDPelanggaran                    7
cot_analisis                     0
reasoning_ujaran_kebencian       0
IDPelangguaran                5265
IDPelangguuran                5268
IDPelangguan                  5264
dtype: int64

In [74]:
# semua yang 5268 kita drop
eksplisit = eksplisit.drop(columns=["IDPelangguuran"])

In [75]:
eksplisit.isna().sum()

claim_disinformasi               0
target                           0
label                            0
jenis                            0
isExplicit                       0
IDPelanggaran                    7
cot_analisis                     0
reasoning_ujaran_kebencian       0
IDPelangguaran                5265
IDPelangguan                  5264
dtype: int64

In [76]:
eksplisit["IDPelangguaran"] = eksplisit["IDPelangguaran"].fillna(eksplisit["IDPelangguan"])
eksplisit["IDPelanggaran"] = eksplisit["IDPelanggaran"].fillna(eksplisit["IDPelangguaran"])

In [77]:
eksplisit.insert(0, "claim_ujaranKebencian", eksplisit["claim_disinformasi"])

In [78]:
eksplisit = eksplisit.drop(columns=["IDPelangguaran", "IDPelangguan", "claim_disinformasi"])

In [79]:
len(eksplisit)

5268

In [80]:
eksplisit.head(1)

,claim_ujaranKebencian,target,label,jenis,isExplicit,IDPelanggaran,cot_analisis,reasoning_ujaran_kebencian
0,"etnis tionghoa emang ges licik main uang panas dr china, ngebulu aja lo semua!",etnis tionghoa,Ujaran Kebencian,komentar,1.0,HS_STEREOTYPE,"[Claim menggunakan kata 'ges licik' yang merendahkan etnis Tionghoa secara kolektif., Menghubungkan perilaku 'main uang panas' dengan etnis Tionghoa, seolah-olah seluruh anggota etnis tersebut memiliki sifat licik., Penggunaan kata 'ngebulu aja lo semua' menunjukkan generalisasi negatif terhadap seluruh anggota etnis Tionghoa.]","Perilaku 'main uang panas' digunakan untuk menggeneralisasi sifat licik pada seluruh etnis Tionghoa, mencerminkan generalisasi negatif berdasarkan etnis (HS_STEREOTYPE). Target: etnis Tionghoa."

In [81]:
eksplisit["IDPelanggaran"].unique()

array(['HS_STEREOTYPE', 'HS_POLITICAL_SARA', 'HS_EXCLUSION', 'HS_GENDER',
       'HS_DEHUMAN', 'HS_CULTURAL', 'HS_VIOLENCE'], dtype=object)

## Panduan Komunitas ga jadi, soalnya ngga ke hit
### ada sedikit salah paham sama tim 2. jadi RAG nya ga kena ke panduan komunitasnya

In [82]:
# path_panduanKomunitas = folderData / "panduan_komunitas.jsonl"

# panduan_komunitas = pd.read_json(path_panduanKomunitas, lines=True)
# panduan_komunitas

In [83]:
# print(f"jumlah qwen halu IDPelanggaran baru 'HS_VIOLENCE' sebanyak: {len(eksplisit[eksplisit['IDPelanggaran'] == 'HS_VIOLENCE'])}")
# print(f"jumlah qwen halu IDPelanggaran baru 'HS_CULTURAL' sebanyak: {len(eksplisit[eksplisit['IDPelanggaran'] == 'HS_CULTURAL'])}")

In [84]:
# eksplisit["IDPelanggaran"].value_counts()

In [85]:
# def panduanKomunitas(baris):
#     return (
#         f"### PEDOMAN KOMUNITAS: {baris['ID']}\n\n"
#         f"**INDIKATOR PELANGGARAN:** {baris['indikator pelanggaran']}\n"
#         f"**DEFINISI:** {baris['isi']}\n"
#         f"**KATA KUNCI PEMICU:** {baris['keywords']}"
#     )

# panduan_komunitas["penjelasan"] = panduan_komunitas.apply(panduanKomunitas, axis=1)

In [86]:
# panduan_komunitas

In [87]:
# id_penjelasan = dict(
#     zip(
#         panduan_komunitas["ID"],
#         panduan_komunitas["penjelasan"]
#     )
# )

In [88]:
# id_penjelasan

In [89]:
# eksplisit["IDPelanggaran"] = eksplisit["IDPelanggaran"].map(id_penjelasan)

## Langsung lanjut sini
### abaiin aja proses pedomean komunitas

In [90]:
eksplisit.isna().sum()

claim_ujaranKebencian         0
target                        0
label                         0
jenis                         0
isExplicit                    0
IDPelanggaran                 0
cot_analisis                  0
reasoning_ujaran_kebencian    0
dtype: int64

In [91]:
eksplisit = eksplisit.dropna()

In [92]:
eksplisit["label"] = "Ujaran Kebencian"
eksplisit.head(1)

,claim_ujaranKebencian,target,label,jenis,isExplicit,IDPelanggaran,cot_analisis,reasoning_ujaran_kebencian
0,"etnis tionghoa emang ges licik main uang panas dr china, ngebulu aja lo semua!",etnis tionghoa,Ujaran Kebencian,komentar,1.0,HS_STEREOTYPE,"[Claim menggunakan kata 'ges licik' yang merendahkan etnis Tionghoa secara kolektif., Menghubungkan perilaku 'main uang panas' dengan etnis Tionghoa, seolah-olah seluruh anggota etnis tersebut memiliki sifat licik., Penggunaan kata 'ngebulu aja lo semua' menunjukkan generalisasi negatif terhadap seluruh anggota etnis Tionghoa.]","Perilaku 'main uang panas' digunakan untuk menggeneralisasi sifat licik pada seluruh etnis Tionghoa, mencerminkan generalisasi negatif berdasarkan etnis (HS_STEREOTYPE). Target: etnis Tionghoa."

In [93]:
data_ujaranKebencian = eksplisit.to_dict("records")

In [94]:
import json
import random

def generate_sft_dataset_with_context(raw_data_list, instructions, output_file):
    dataset = []
    
    for data in raw_data_list:
        instruct = instructions
        claim = data.get("claim_ujaranKebencian", "")
        # teks = data.get("IDPelanggaran", "") # ga jadi kupake 
        label = data.get("label")
        # reasoning = data.get("reasoning_ujaran_kebencian", "") # ga jadi dipake
        cot_list = data.get("cot_analisis", [])
        
        # Susun poin-poin fakta
        fakta_points = "\n".join([f"* {point}" for point in cot_list])

        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Komentar: '{claim}';\n\n"
        )

        full_output = (
            f"Penjelasan:\n"
            f"{fakta_points}\n"
            f"Label: {label}."
        )
        
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(data_ujaranKebencian, instructiones, "ujarankebencian.jsonl")

Berhasil membuat 5268 data dengan konteks berita di ujarankebencian.jsonl

In [95]:
tes = pd.read_json("ujarankebencian.jsonl", lines=True)
tes.head(1)

,instruction,input,output
0,"Anda adalah sistem ahli klasifikasi komentar media sosial. Klasifikasikan [Komentar] ke salah satu Nama Label: [Netral, Disinformasi, Fitnah, Ujaran Kebencian].\nAturan:\n1. Ujaran Kebencian: Serangan SARA/identitas/disabilitas (prioritas utama, abaikan rujukan).\n2. Jika bukan ujaran kebencian, gunakan [Artikel Rujukan] jika ada untuk menilai:\n- Netral: Faktual, opini, atau interaksi wajar.\n- Disinformasi: Informasi keliru yang memicu keresahan/polarisasi.\n- Fitnah: Tuduhan bohong untuk menyerang reputasi individu/kelompok.\nFormat Output WAJIB:\nPenjelasan: [Analisis detail dan alasan label]\nLabel: [Nama Label]","Komentar: 'etnis tionghoa emang ges licik main uang panas dr china, ngebulu aja lo semua!';\n\n","Penjelasan:\n* Claim menggunakan kata 'ges licik' yang merendahkan etnis Tionghoa secara kolektif.\n* Menghubungkan perilaku 'main uang panas' dengan etnis Tionghoa, seolah-olah seluruh anggota etnis tersebut memiliki sifat licik.\n* Penggunaan kata 'ngebulu aja lo semua' menunjukkan generalisasi negatif terhadap seluruh anggota etnis Tionghoa.\nLabel: Ujaran Kebencian."

## Data tambahan

### hate YT

In [96]:
hate.tail(1)

,komentar_asli,mengandung_klaim,search_query,alasan_non_dfk,kategori_flag
4938,Bahelamah Jablay teh dikota ayenamah tatanga JD jablay,False,TIDAK_BUTUH_RAG,Terdeteksi Ujaran Kebencian / SARA karena menggunakan istilah 'jablay' yang bersifat merendahkan dan seksis terhadap perempuan,Ujaran Kebencian

In [97]:
data_hate = hate.to_dict("records")

In [98]:
def generate_sft_dataset_with_context(raw_data_list, instructions, output_file):
    dataset = []
    
    for data in raw_data_list:
        instruct = instructions
        claim = data.get("komentar_asli", "")
        # teks = data.get("IDPelanggaran", "") # ga jadi kupake 
        label = "Ujaran Kebencian"
        reasoning = data.get("alasan_non_dfk", "") 
        # cot_list = data.get("cot_analisis", []) # ga jadi dipake
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Komentar: '{claim}';\n\n"
        )

        full_output = (
            f"Penjelasan: {reasoning}\n"
            f"Label: {label}."
        )
        
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(data_hate, instructiones, "ujarankebencian2.jsonl")

Berhasil membuat 484 data dengan konteks berita di ujarankebencian2.jsonl

### hate HF

In [99]:
data_hate_hf = hate_hf.to_dict("records")

In [100]:
import json

def generate_sft_dataset_with_context(raw_data_list, instructions, output_file):
    label = "Ujaran Kebencian"
    dataset = []
    
    for data in raw_data_list:
        instruct = instructions
        claim = data.get("komentar_asli", "")
        reasoning = data.get("alasan_kategori", "")
        cot_list = data.get("cot_analisis", [])
        
        # Susun poin-poin fakta
        fakta_points = "\n".join([f"* {point}" for point in cot_list])
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Komentar: '{claim}';\n\n"
        )

        full_output = (
            f"Penjelasan: {reasoning}\n"
            f"Berikut adalah beberapa poin penting:\n"
            f"{fakta_points}\n"
            f"Label: {label}."
        )
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(data_hate_hf, instructiones, "ujarankebencian3.jsonl")

Berhasil membuat 589 data dengan konteks berita di ujarankebencian3.jsonl

In [101]:
ujarankebencian3 = pd.read_json("ujarankebencian3.jsonl", lines=True)

In [102]:
ujarankebencian3.head(1)

,instruction,input,output
0,"Anda adalah sistem ahli klasifikasi komentar media sosial. Klasifikasikan [Komentar] ke salah satu Nama Label: [Netral, Disinformasi, Fitnah, Ujaran Kebencian].\nAturan:\n1. Ujaran Kebencian: Serangan SARA/identitas/disabilitas (prioritas utama, abaikan rujukan).\n2. Jika bukan ujaran kebencian, gunakan [Artikel Rujukan] jika ada untuk menilai:\n- Netral: Faktual, opini, atau interaksi wajar.\n- Disinformasi: Informasi keliru yang memicu keresahan/polarisasi.\n- Fitnah: Tuduhan bohong untuk menyerang reputasi individu/kelompok.\nFormat Output WAJIB:\nPenjelasan: [Analisis detail dan alasan label]\nLabel: [Nama Label]",Komentar: 'Mana berani dia Ngaku putra melayu tapi cemen Beraninya teriak2 kirain mau dibantu sama yg lain Hajar aja itu mulut bau congor si ardi koplok';\n\n,Penjelasan: Pelanggaran terletak pada serangan etnis dan penghinaan personal yang bersifat kebencian terhadap individu bernama Ardi dengan menyebut identitas Melayu.\nBerikut adalah beberapa poin penting:\n* Komentar menyerang identitas etnis dengan frasa 'Ngaku putra melayu tapi cemen'.\n* Menggunakan kata-kata kasar dan dehumanisasi seperti 'mulut bau congor' dan 'ardi koplok'.\n* Serangan ditujukan langsung ke individu dengan nada menghasut kekerasan verbal ('Hajar aja').\n* Mengandung unsur SARA karena menyinggung identitas Melayu secara negatif.\nLabel: Ujaran Kebencian.

### Gabungin data ujaran kebencian sama tambahannya

In [103]:
ujarankebencian1 = pd.read_json("ujarankebencian.jsonl", lines=True)
ujarankebencian2 = pd.read_json("ujarankebencian2.jsonl", lines=True)
# ujarankebencian3 udah diatas

dataUjaranKebencian = pd.concat(
    [ujarankebencian1, ujarankebencian2, ujarankebencian3], ignore_index=True
)

dataUjaranKebencian.to_json(
    "dataUjaranKebencian.jsonl", orient="records", lines=True
)

In [104]:
print(f"{len(ujarankebencian1)}")
print(f"{len(ujarankebencian2)}")
print(f"{len(ujarankebencian3)}")
print(f"{len(dataUjaranKebencian)}")

5268
484
589
6341

In [105]:
dataUjaranKebencian.tail(1)

,instruction,input,output
6340,"Anda adalah sistem ahli klasifikasi komentar media sosial. Klasifikasikan [Komentar] ke salah satu Nama Label: [Netral, Disinformasi, Fitnah, Ujaran Kebencian].\nAturan:\n1. Ujaran Kebencian: Serangan SARA/identitas/disabilitas (prioritas utama, abaikan rujukan).\n2. Jika bukan ujaran kebencian, gunakan [Artikel Rujukan] jika ada untuk menilai:\n- Netral: Faktual, opini, atau interaksi wajar.\n- Disinformasi: Informasi keliru yang memicu keresahan/polarisasi.\n- Fitnah: Tuduhan bohong untuk menyerang reputasi individu/kelompok.\nFormat Output WAJIB:\nPenjelasan: [Analisis detail dan alasan label]\nLabel: [Nama Label]",Komentar: 'MEMANG ANAK ANJING KAMPANG';\n\n,Penjelasan: Komentar menyerang dengan kata-kata vulgar dan kejam yaitu 'ANAK ANJING KAMPANG' yang merupakan penghinaan personal\nBerikut adalah beberapa poin penting:\n* Komentar berisi kata-kata kasar dan penghinaan langsung\n* Tidak ada unsur klaim fakta atau informasi yang bisa diverifikasi\n* Serangan bersifat personal dan kejam tanpa konteks SARA spesifik\n* Termasuk kategori ujaran kebencian karena penghinaan kejam\nLabel: Ujaran Kebencian.

# Jadiin semua CSV buat di EDA |

In [107]:
print(f"Kolom df Fitnah: {df_fitnah.columns}")
print(f"Kolom df Disinformasi: {df_disinformasi.columns}")
print(f"Kolom df Fakta: {df_fakta.columns}")
print(f"Kolom df Nondfk: {df_nondfk.columns}")
print(f"Kolom df ujaran_kebencian: {eksplisit.columns}")

print("\n")
# dari yt
print(f"Kolom df yt_netral: {netral.columns}")
print(f"Kolom df yt_hate: {hate.columns}")
print("\n")

# dari hf
print(f"Kolom df hf_netral: {netral_hf.columns}")
print(f"Kolom df hf_hate: {hate_hf.columns}")

Kolom df Fitnah: Index(['title', 'text', 'claim_fitnah', 'cot_bantah_fitnah',
       'reasoning_fitnah', 'label'],
      dtype='object')
Kolom df Disinformasi: Index(['claim_disinformasi', 'berita_asli', 'label', 'cot_bantah_disinformasi',
       'reasoning_disinformasi'],
      dtype='object')
Kolom df Fakta: Index(['text', 'claim_fakta', 'cot_analisis_fakta', 'reasoning_fakta',
       'label'],
      dtype='object')
Kolom df Nondfk: Index(['title', 'text', 'claim_nonDFK', 'gaya_komentar', 'is_layak',
       'cot_analisis', 'reasoning_nonDFK', 'label'],
      dtype='object')
Kolom df ujaran_kebencian: Index(['claim_ujaranKebencian', 'target', 'label', 'jenis', 'isExplicit',
       'IDPelanggaran', 'cot_analisis', 'reasoning_ujaran_kebencian'],
      dtype='object')


Kolom df yt_netral: Index(['komentar_asli', 'mengandung_klaim', 'search_query', 'alasan_non_dfk',
       'kategori_flag'],
      dtype='object')
Kolom df yt_hate: Index(['komentar_asli', 'mengandung_klaim', 'search_query', 'alasan_non_dfk',
       'kategori_flag'],
      dtype='object')


Kolom df hf_netral: Index(['komentar_asli', 'mengandung_klaim', 'tipe_komentar', 'search_query',
       'cot_analisis', 'alasan_kategori'],
      dtype='object')
Kolom df hf_hate: Index(['komentar_asli', 'mengandung_klaim', 'tipe_komentar', 'search_query',
       'cot_analisis', 'alasan_kategori'],
      dtype='object')

In [108]:
netral_hf.head(1)

,komentar_asli,mengandung_klaim,tipe_komentar,search_query,cot_analisis,alasan_kategori
0,gemesnya wkwkkw whitni uga gemes kek gini ueueue ayang whitni jomok lukh,False,netral,,"[Komentar berisi ekspresi kasual berupa kata-kata sayang dan tawa internet (wkwk, ueueue)., Tidak ada pernyataan fakta, rumor, atau informasi yang perlu diverifikasi., Tidak mengandung unsur SARA atau serangan terhadap kelompok tertentu.]",Komentar ini merupakan ekspresi emosional ringan dan santai yang lazim digunakan netizen saat mengomentari sesuatu yang menggemaskan tanpa menyerang siapa pun.

In [109]:
# fitnah
df_fitnah["berita_asli"] = df_fitnah["text"]
df_fitnah["komentar"] = df_fitnah["claim_fitnah"]
df_fitnah["poin_penjelasan"] = df_fitnah["cot_bantah_fitnah"]
df_fitnah["penjelasan"] = df_fitnah["reasoning_fitnah"]

df_fitnah = df_fitnah[["berita_asli", "komentar", "poin_penjelasan", "penjelasan", "label"]]

# disinformasi
df_disinformasi["komentar"] = df_disinformasi["claim_disinformasi"]
df_disinformasi["poin_penjelasan"] = df_disinformasi["cot_bantah_disinformasi"]
df_disinformasi["penjelasan"] = df_disinformasi["reasoning_disinformasi"]

df_disinformasi = df_disinformasi[["berita_asli", "komentar", "poin_penjelasan", "penjelasan", "label"]]

# fakta
df_fakta["berita_asli"] = df_fakta["text"]
df_fakta["komentar"] = df_fakta["claim_fakta"]
df_fakta["poin_penjelasan"] = df_fakta["cot_analisis_fakta"]
df_fakta["penjelasan"] = df_fakta["reasoning_fakta"]

df_fakta = df_fakta[["berita_asli", "komentar", "poin_penjelasan", "penjelasan", "label"]]

# nonDFK
df_nondfk["berita_asli"] = "tidak ada berita"
df_nondfk["komentar"] = df_nondfk["claim_nonDFK"]
df_nondfk["poin_penjelasan"] = df_nondfk["cot_analisis"]
df_nondfk["penjelasan"] = df_nondfk["reasoning_nonDFK"]

df_nondfk = df_nondfk[["berita_asli", "komentar", "poin_penjelasan", "penjelasan", "label"]]

# ujaran kebencian
eksplisit["berita_asli"] = "tidak ada berita"
eksplisit["komentar"] = eksplisit["claim_ujaranKebencian"]
eksplisit["poin_penjelasan"] = eksplisit["cot_analisis"]
eksplisit["penjelasan"] = eksplisit["reasoning_ujaran_kebencian"]

eksplisit = eksplisit[["berita_asli", "komentar", "poin_penjelasan", "penjelasan", "label"]]

# tambahan netral dari YT
netral["berita_asli"] = "tidak ada berita"
netral["komentar"] = netral["komentar_asli"]
netral["poin_penjelasan"] = "tidak ada poin penjelasan"
netral["penjelasan"] = netral["alasan_non_dfk"]
netral["label"] = netral["kategori_flag"]

netral = netral[["berita_asli", "komentar", "poin_penjelasan", "penjelasan", "label"]]

# tambahan netral dari YT
hate["berita_asli"] = "tidak ada berita"
hate["komentar"] = hate["komentar_asli"]
hate["poin_penjelasan"] = "tidak ada poin penjelasan"
hate["penjelasan"] = hate["alasan_non_dfk"]
hate["label"] = hate["kategori_flag"]

hate = hate[["berita_asli", "komentar", "poin_penjelasan", "penjelasan", "label"]]

# tambahan netral dari HF
netral_hf["berita_asli"] = "tidak ada berita"
netral_hf["komentar"] = netral_hf["komentar_asli"]
netral_hf["poin_penjelasan"] = netral_hf["cot_analisis"]
netral_hf["penjelasan"] = netral_hf["alasan_kategori"]
netral_hf["label"] = netral_hf["tipe_komentar"]

netral_hf = netral_hf[["berita_asli", "komentar", "poin_penjelasan", "penjelasan", "label"]]

# tambahan netral dari HF
hate_hf["berita_asli"] = "tidak ada berita"
hate_hf["komentar"] = hate_hf["komentar_asli"]
hate_hf["poin_penjelasan"] = hate_hf["cot_analisis"]
hate_hf["penjelasan"] = hate_hf["alasan_kategori"]
hate_hf["label"] = hate_hf["tipe_komentar"]

hate_hf = hate_hf[["berita_asli", "komentar", "poin_penjelasan", "penjelasan", "label"]]

C:\Users\Dipo\AppData\Local\Temp\ipykernel_123472\448835147.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  netral_hf["berita_asli"] = "tidak ada berita"
C:\Users\Dipo\AppData\Local\Temp\ipykernel_123472\448835147.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  netral_hf["komentar"] = netral_hf["komentar_asli"]
C:\Users\Dipo\AppData\Local\Temp\ipykernel_123472\448835147.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  netral_hf["poin_penjelasan"] = netral_hf["cot_analisis"]
C:\Users\Dipo\AppData\Local\Temp\ipykernel_123472\448835147.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  netral_hf["penjelasan"] = netral_hf["alasan_kategori"]
C:\Users\Dipo\AppData\Local\Temp\ipykernel_123472\448835147.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  netral_hf["label"] = netral_hf["tipe_komentar"]
C:\Users\Dipo\AppData\Local\Temp\ipykernel_123472\448835147.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hate_hf["berita_asli"] = "tidak ada berita"
C:\Users\Dipo\AppData\Local\Temp\ipykernel_123472\448835147.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hate_hf["komentar"] = hate_hf["komentar_asli"]
C:\Users\Dipo\AppData\Local\Temp\ipykernel_123472\448835147.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hate_hf["poin_penjelasan"] = hate_hf["cot_analisis"]
C:\Users\Dipo\AppData\Local\Temp\ipykernel_123472\448835147.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hate_hf["penjelasan"] = hate_hf["alasan_kategori"]
C:\Users\Dipo\AppData\Local\Temp\ipykernel_123472\448835147.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hate_hf["label"] = hate_hf["tipe_komentar"]

In [110]:
csv_gabungan = pd.concat([df_fitnah, df_disinformasi, df_fakta, df_nondfk, eksplisit, netral, hate, netral_hf, hate_hf], ignore_index=True)

In [111]:
csv_gabungan.to_csv("csv_gabungan.csv")

# Sampling dan Gabungin semua dataset
## Jangan lupa kita acak acak biar modelnya nanti belajar

In [112]:
df_disinformasi = pd.read_json("disinformasi.jsonl", lines=True)
df_fitnah = pd.read_json("fitnah.jsonl", lines=True)
df_netral = pd.read_json("dataNetral.jsonl", lines=True)
df_kebencian = pd.read_json("dataUjaranKebencian.jsonl", lines=True)

Cek persebaran total karakter di kolom input

In [113]:
# 2. Gabungkan ke dalam dictionary untuk mempermudah looping
datasets = {
    "Disinformasi": df_disinformasi,
    "Fitnah": df_fitnah,
    "Netral": df_netral,
    "Ujaran Kebencian": df_kebencian
}

for nama, df in datasets.items():
    panjang_karakter = df['input'].astype(str).str.len()
    
    print(f"--- Dataset: {nama} ---")
    print(f"Total baris data : {len(df)}")
    print(f"Rata-rata (Mean) : {panjang_karakter.mean():.2f} karakter")
    print(f"Nilai Tengah (Med): {panjang_karakter.median():.2f} karakter")
    print(f"Paling Pendek    : {panjang_karakter.min()} karakter")
    print(f"Paling Panjang   : {panjang_karakter.max()} karakter")
    
    print(f"Rentang 25% data <= {panjang_karakter.quantile(0.25):.0f} karakter")
    print(f"Rentang 50% data <= {panjang_karakter.quantile(0.50):.0f} karakter")
    print(f"Rentang 75% data <= {panjang_karakter.quantile(0.75):.0f} karakter")
    print("-" * 30 + "\n")

--- Dataset: Disinformasi ---
Total baris data : 7995
Rata-rata (Mean) : 881.18 karakter
Nilai Tengah (Med): 856.00 karakter
Paling Pendek    : 244 karakter
Paling Panjang   : 3436 karakter
Rentang 25% data <= 713 karakter
Rentang 50% data <= 856 karakter
Rentang 75% data <= 1022 karakter
------------------------------

--- Dataset: Fitnah ---
Total baris data : 7211
Rata-rata (Mean) : 2582.84 karakter
Nilai Tengah (Med): 2377.00 karakter
Paling Pendek    : 306 karakter
Paling Panjang   : 16643 karakter
Rentang 25% data <= 1857 karakter
Rentang 50% data <= 2377 karakter
Rentang 75% data <= 3040 karakter
------------------------------

--- Dataset: Netral ---
Total baris data : 7546
Rata-rata (Mean) : 913.31 karakter
Nilai Tengah (Med): 134.00 karakter
Paling Pendek    : 16 karakter
Paling Panjang   : 18733 karakter
Rentang 25% data <= 65 karakter
Rentang 50% data <= 134 karakter
Rentang 75% data <= 1532 karakter
------------------------------

--- Dataset: Ujaran Kebencian ---
Total baris data : 6341
Rata-rata (Mean) : 458.98 karakter
Nilai Tengah (Med): 109.00 karakter
Paling Pendek    : 25 karakter
Paling Panjang   : 1600 karakter
Rentang 25% data <= 80 karakter
Rentang 50% data <= 109 karakter
Rentang 75% data <= 937 karakter
------------------------------

di filter, jadi ga ada alasan lagi input kepanjangan

In [114]:
print("SEBELUM DI FILTER")
print(f"df_netral: {len(df_netral)}")
print(f"df_disinformasi: {len(df_disinformasi)}")
print(f"df_fitnah: {len(df_fitnah)}")
print(f"df_kebencian: {len(df_kebencian)}")

print("\n")
MAX_CHARS = 7500

df_netral = df_netral[df_netral['input'].astype(str).str.len() <= MAX_CHARS]
df_disinformasi = df_disinformasi[df_disinformasi['input'].astype(str).str.len() <= MAX_CHARS]
df_fitnah = df_fitnah[df_fitnah['input'].astype(str).str.len() <= MAX_CHARS]
df_kebencian = df_kebencian[df_kebencian['input'].astype(str).str.len() <= MAX_CHARS]

print("SESUDAH DI FILTER")
print(f"df_netral: {len(df_netral)}")
print(f"df_disinformasi: {len(df_disinformasi)}")
print(f"df_fitnah: {len(df_fitnah)}")
print(f"df_kebencian: {len(df_kebencian)}")

SEBELUM DI FILTER
df_netral: 7546
df_disinformasi: 7995
df_fitnah: 7211
df_kebencian: 6341


SESUDAH DI FILTER
df_netral: 7500
df_disinformasi: 7995
df_fitnah: 7169
df_kebencian: 6341

In [115]:
# sampling, jumlah 5269 kita ikutin total data ujaran kebencian. jadi biar balance 
# kecuali netral, kita banyakin.
jumlahNetral = len(df_netral) # 7546
jumlahData = len(df_kebencian) # 6341

df_netral = df_netral.sample(n=jumlahNetral)
df_disinformasi = df_disinformasi.sample(n=jumlahData)
df_fitnah = df_fitnah.sample(n=jumlahData)
df_ujarankb = df_kebencian.sample(n=jumlahData)

In [116]:
df_combined = pd.concat([
    df_disinformasi,
    df_fitnah,
    df_netral,
    df_ujarankb
])

df_combined = df_combined.sample(frac=1, random_state=42).reset_index(drop=True)
print(len(df_combined))

df_combined.to_json('dataset_sampled.jsonl', orient='records', lines=True)

26523

## Bersihin teks dari kalimat iklan

In [117]:
allDF = pd.read_json("dataset_sampled.jsonl", lines=True)

In [118]:
allDF.head()

,instruction,input,output
0,"Anda adalah sistem ahli klasifikasi komentar media sosial. Klasifikasikan [Komentar] ke salah satu Nama Label: [Netral, Disinformasi, Fitnah, Ujaran Kebencian].\nAturan:\n1. Ujaran Kebencian: Serangan SARA/identitas/disabilitas (prioritas utama, abaikan rujukan).\n2. Jika bukan ujaran kebencian, gunakan [Artikel Rujukan] jika ada untuk menilai:\n- Netral: Faktual, opini, atau interaksi wajar.\n- Disinformasi: Informasi keliru yang memicu keresahan/polarisasi.\n- Fitnah: Tuduhan bohong untuk menyerang reputasi individu/kelompok.\nFormat Output WAJIB:\nPenjelasan: [Analisis detail dan alasan label]\nLabel: [Nama Label]","Komentar: 'Guru Besar UGM tuduh kepala daerah sering ke Jakarta hanya untuk lobi-lobi, pembangunan daerah jadi tumbang!';\n\nArtikel Rujukan: Fenomenakepala daerahyang terlalu sering berada di Jakarta kembali menjadi sorotan publik. Meski sudah menjadi kebiasaan di banyak daerah, praktik ini dinilai berdampak serius terhadap efektivitas pemerintahan dan penyerapan aspirasi masyarakat di daerah.\nGuru Besar Manajemen Kebijakan Publik Universitas Gadjah Mada, Prof. Wahyudi Kumorotomo, menegaskan bahwa kebiasaankepala daerahlebih banyak berada di Jakarta bukan sekadar masalah etika kepemimpinan, tetapi juga soal efektivitas pembangunan.\n""Banyak gubernur, bupati, wali kota, hingga sekretaris daerah yang justru lebih sering menginap di hotel-hotel di Jakarta untuk melakukan lobi-lobi, padahal mereka seharusnya berada di daerah untuk memantau langsung pembangunan dan melayani masyarakat,""ujarnya Selasa (30/12/2025).\nBMKG Prediksi Hujan Lebat Selama Libur Nataru 2025/2026, Pakar UGM Ingatkan Perhatikan Ini Sebelum Berkendara\nMenurut Wahyudi, ketidakhadiran pemimpin daerah secara langsung membuat penyerapan aspirasi rakyat menjadi terhambat. Kehadiran fisik kepala daerah di wilayahnya, menurutnya, tidak dapat digantikan oleh laporan tertulis atau koordinasi jarak jauh.\n""Pemimpin yang jarang hadir di daerah akan kehilangan pemahaman atas persoalan nyata yang dihadapi masyarakat, sehingga kebijakan yang diambil berisiko tidak tepat sasaran,"" katanya.\nWahyudi juga menilai masalah ini sulit diatasi karena sudah mengakar dan dianggap wajar, baik oleh elite politik maupun sebagian masyarakat. Ia menekankan pentingnya teladan dari kepala daerah dan pengawasan dari pemerintah pusat.\n""Mendagri perlu rutin melakukan inspeksi mendadak untuk memastikan kepala daerah benar-benar menjalankan tugasnya di lapangan,""tegasnya.\nDalam konteks hubungan pusat-daerah, Wahyudi menekankan bahwa koordinasi dengan pemerintah pusat seharusnya tidak menjadi alasan kepala daerah meninggalkan wilayahnya terlalu lama.\n""Pejabat pusat perlu terus memantau kinerja pimpinan daerah, sekaligus memperkuat jalur koordinasi institusional agar urusan pusat tidak selalu menuntut kehadiran fisik kepala daerah di Jakarta,""jelasnya.\nIa juga menyoroti pentingnya edukasi politik kepada masyarakat. Menurutnya, kesadaran warga dalam memilih pemimpin yang benar-benar hadir di daerah masih rendah.\n""Faktanya, ada bupati yang hanya pulang ke daerah sebulan sekali, tetapi tetap terpilih kembali. Ini menunjukkan masyarakat perlu disadarkan tentang bahaya politik uang dan pentingnya memilih pemimpin yang benar-benar hadir,""ungkap Wahyudi.\nSatu - Satunya Pasar di Indonesia Punya RPH, Pasar Terban Kota Jogja Siap Beroperasi Penuh 10 Januari 2026\nOleh karena itu, Wahyudi berharap para kepala daerah, khususnya di Papua, memiliki kesadaran moral lebih kuat dalam menjalankan amanah. Ditegaskannya, bahwa kehadiran kepala daerah bukan sekadar soal administratif, melainkan kunci utama dalam memastikan pembangunan berjalan efektif, transparan, dan berpihak pada kesejahteraan masyarakat setempat.\n""Para pejabat publik digaji dari uang rakyat dan sudah seharusnya mengabdikan diri sepenuhnya untuk kepentingan masyarakat. Mereka harus sadar bahwa tugas utama adalah melayani rakyat, bukan menikmati kenyamanan di Jakarta di atas penderitaan masyarakat di daerah,""pungkasnya.","Penjelasan: Pernyataan Prof. Wahyudi dipelintir menjadi tuduhan spesifik terhadap kepala daerah, padahal ia hanya mengkritisi praktik umum yang berdampak pada efektivitas pemerintahan. Kritik tersebut lebih bersifat analitis dan bukan tuduhan langsung.\nBerikut adalah beberapa poin penting:\n* Prof. Wahyudi Kumorotomo tidak menuduh secara langsung, tetapi mengkritisi praktik yang sering terjadi\n* Kritik tersebut berbasis pada efektivitas pemerintahan dan penyerapan aspirasi masyarakat, bukan sekadar tuduhan\n* Fokus kritik adalah pada kehadiran fisik kepala daerah di daerah, bukan hanya lobi-lobi\n* Tidak ada bukti konkret bahwa semua kepala daerah yang sering ke Jakarta hanya untuk lobi-lobi\n* Pernyataan Prof. Wahyudi adalah opini akademis, bukan fakta definitif\nLabel: Fitnah."
1,"Anda adalah sistem ahli klasifikasi komentar media sosial. Klasifikasikan [Komentar] ke salah satu Nama Label: [Netral, Disinformasi, Fitnah, Ujaran Kebencian].\nAturan:\n1. Ujaran Kebencian: Serangan SARA/identitas/disabilitas (prioritas utama, abaikan rujukan).\n2. Jika bukan ujaran kebencian, gunakan [Artikel Rujukan] jika ada untuk menilai:\n- Netral: Faktual, opini, atau interaksi wajar.\n- Disinformasi: Informasi keliru yang memicu keresahan/polarisasi.\n- Fitnah: Tuduhan bohong untuk menyerang reputasi individu/kelompok.\nFormat Output WAJIB:\nPenjelasan: [Analisis detail dan alasan label]\nLabel: [Nama Label]",Komentar: 'RT ini nih yg mau d panggil yg terhormat yg muliakerjanya bikin ngaco negara ayo rame2 golput DPR dan Bubarkan DPR';\n\n,"Penjelasan: Komentar merupakan ekspresi ketidakpuasan politik yang bersifat umum dan tidak mengandung unsur SARA\nBerikut adalah beberapa poin penting:\n* Komentar berisi opini politik dan ajakan golput tanpa pernyataan fakta konkret\n* Tidak menyerang identitas suku, agama, ras, atau golongan tertentu\n* Konteksnya adalah kritik terhadap institusi DPR secara umum\nLabel: Netral."
2,"Anda adalah sistem ahli klasifikasi komentar media sosial. Klasifikasikan [Komentar] ke salah satu Nama Label: [Netral, Disinformasi, Fitnah, Ujaran Kebencian].\nAturan:\n1. Ujaran Kebencian: Serangan SARA/identitas/disabilitas (prioritas utama, abaikan rujukan).\n2. Jika bukan ujaran kebencian, gunakan [Artikel Rujukan] jika ada untuk menilai:\n- Netral: Faktual, opini, atau interaksi wajar.\n- Disinformasi: Informasi keliru yang memicu keresahan/polarisasi.\n- Fitnah: Tuduhan bohong untuk menyerang reputasi individu/kelompok.\nFormat Output WAJIB:\nPenjelasan: [Analisis detail dan alasan label]\nLabel: [Nama Label]","Komentar: 'Camat Kepanjenkidul Kota Blitar Indra Purwanto Ajak Warga Ikut Donasi Pembangunan Sekolah, Hubungi WhatsApp Ini!';\n\nArtikel Rujukan: Beredar sebuah akun WhatsApp mengatasnamakan Camat Kepanjenkidul Kota Blitar Indra Purwanto. Akun tersebut mengirimkan pesan berisi informasi penyaluran dana donasi pembangunan pondasi gedung sekolah. Faktanya, akun WhatsApp mengatasnamakan Camat Kepanjenkidul Kota Blitar Indra Purwanto tersebut adalah akun palsu. Pemerintah Kota (Pemkot) Blitar melalui akun Twitter resminya @PemkotaBlitar mengonfirmasi bahwa akun WhatsApp tersebut bukan milik Indra Purwanto. Kepala Diskominfotik Kota Blitar Mujianto juga mengimbau agar masyarakat selalu berhati-hati dan memastikan kebenarannya ketika dihubungi oleh akun yang mengatasnamakan pejabat.",Penjelasan: Ini adalah modus pencatutan nama yang bertujuan untuk melakukan penipuan. Akun WhatsApp palsu tersebut mengatasnamakan pejabat untuk mendapatkan kepercayaan masyarakat dan mengelabui mereka agar mentransfer dana. Masyarakat harus selalu memverifikasi informasi melalui sumber resmi.\nBerikut adalah beberapa poin penting:\n* Pemerintah Kota (Pemkot) Blitar melalui akun Twitter resminya @PemkotaBlitar telah mengklarifikasi bahwa akun WhatsApp tersebut bukan milik Camat Kepanjenkidul Indra Purwanto.\n* Kepala Diskominfotik Kota Blitar Mujianto mengimbau masyarakat untuk selalu berhati-hati dan memastikan kebenaran informasi ketika dihubungi oleh akun yang mengatasnamakan pejabat.\n* Informasi resmi terkait penyaluran dana donasi pembangunan sekolah selalu diumumkan melalui saluran komunikasi resmi pemerintah daerah.\n* Masyarakat diimbau untuk tidak mentransfer dana ke rekening yang tidak jelas asal-usulnya.\nLabel: Disinformasi.
3,"Anda adalah sistem ahli klasifikasi komentar media sosial. Klasifikasikan [Komentar] ke salah satu Nama Label: [Netral, Disinformasi, Fitnah, Ujaran Kebencian].\nAturan:\n1. Ujaran Kebencian: Serangan SARA/identitas/disabilitas (prioritas utama, abaikan rujukan).\n2. Jika bukan ujaran kebencian, gunakan [Artikel Rujukan] jika ada untuk menilai:\n- Netral: Faktual, opini, atau interaksi wajar.\n- Disinformasi: Informasi keliru yang memicu keresahan/polarisasi.\n- Fitnah: Tuduhan bohong untuk menyerang reputasi individu/kelompok.\nFormat Output WAJIB:\nPenjelasan: [Analisis detail dan alasan label]\nLabel: [Nama Label]","Komentar: 'Gubernur Sulsel cuma mau cari popularitas dengan bantuin pembangunan jalan Balielo aja, gak ada manfaatnya buat rakyat!';\n\nArtikel Rujukan: Jalan Desa Balielo di Kabupaten Wajo. (Foto: Dok. Pemprov Sulsel)\nPemerintah Kabupaten (Pemkab)Wajomengapresiasi sinergi Pemerintah Provinsi (Pemprov) Sulawesi Selatan yang menghadirkan dampak nyata bagi masyarakat desa. Kolaborasi tersebut diwujudkan melalui tuntasnyapembangunan JalanDesa Balielo di Kecamatan Bola.\nPembangunan jalantersebut dibiayaiBantuan Keuangan ProvinsiTahun Anggaran 2025 senilai Rp5 miliar. Infrastruktur sepanjang 1,1 kilometer dengan lebar 4,5 meter itu kini telah rampung 100 persen.\nRampungnya Jalan Balielo memberi dampak signifikan terhadap kelancaran arus transportasi barang dan jasa. Aktivitas ekonomi masyarakat Desa Balielo dan sekitarnya pun semakin bergerak.\nJalan Desa Balielo di Wajo Rampung 100 Persen Lewat Bantuan Pemprov Sulsel\nKepala Dinas PUPRP Kabupaten Wajo, Andi Pameneri, menyampaikan terima kasih kepada Gubernur Sulsel Andi Sudirman Sulaiman atas dukungan anggaran tersebut. Ia menilai bantuan keuangan provinsi menjadi bukti perhatian terhadap pembangunan di tingkat desa.\n""Kami atas nama Pemerintah Kabupaten Wajo mengucapkan terima kasih kepada Bapak Gubernur atas bantuan keuangan yang dialokasikan untuk pembangunan ruas Jalan Balielo di Kecamatan Bola,"" ujar Andi Pameneri, Jumat (6/2/2026).\nEkonomi Sulsel Tumbuh 5,43 Persen di 2025, Tertinggi Sejak Pandemi Covid-19\nIa mengungkapkan sebelum dilakukan pembangunan, kondisi jalan Balielo mengalami kerusakan berat. Kondisi tersebut sempat menghambat mobilitas dan aktivitas warga setempat.\nMenurut Andi Pameneri, kehadiran infrastruktur jalan yang memadai menunjukkan komitmen Pemprov Sulsel dalam memperkuat konektivitas wilayah. Upaya ini dinilai mendorong pemerataan pembangunan hingga ke pelosok desa.\n""Pembangunan ini sangat bermanfaat bagi transportasi masyarakat, khususnya warga Desa Balielo. Sebelumnya kondisi jalan rusak berat, kini sudah layak dan nyaman dilalui,"" katanya.","Penjelasan: Claim tersebut menggunakan framing negatif dengan menuduh Gubernur Sulsel hanya mencari popularitas. Padahal, berita mencantumkan fakta-fakta konkret tentang manfaat pembangunan jalan, termasuk dukungan dari pemerintah daerah dan dampak positif terhadap ekonomi masyarakat.\nBerikut adalah beberapa poin penting:\n* Fakta berita menunjukkan bahwa pembangunan Jalan Balielo telah rampung 100 persen dan mendapat apresiasi dari Pemkab Wajo\n* Kepala Dinas PUPRP Kabupaten Wajo menyampaikan terima kasih atas dukungan anggaran dari Gubernur Sulsel, menunjukkan sinergi antara pemerintah provinsi dan kabupaten\n* Berita menyebutkan dampak positif pembangunan jalan, seperti kelancaran arus transportasi barang dan jasa serta peningkatan aktivitas ekonomi masyarakat\n* Bantuan keuangan provinsi senilai Rp5 miliar untuk pembangunan jalan ini bukan hanya sekadar simbolik, melainkan investasi nyata untuk kesejahteraan masyarakat\n* Infrastruktur yang dibangun memiliki panjang 1,1 kilometer dan lebar 4,5 meter, menunjukkan komitmen serius dalam memperbaiki aksesibilitas di daerah tersebut\nLabel: Fitnah."
4,"Anda adalah sistem ahli klasifikasi komentar media sosial. Klasifikasikan [Komentar] ke salah satu Nama Label: [Netral, Disinformasi, Fitnah, Ujaran Kebencian].\nAturan:\n1. Ujaran Kebencian: Serangan SARA/identitas/disabilitas (prioritas utama, abaikan rujukan).\n2. Jika bukan ujaran kebencian, gunakan [Artikel Rujukan] jika ada untuk menilai:\n- Netral: Faktual, opini, atau interaksi wajar.\n- Disinformasi: Informasi keliru yang memicu keresahan/polarisasi.\n- Fitnah: Tuduhan bohong untuk menyerang reputasi individu/kelompok.\nFormat Output WAJIB:\nPenjelasan: [Analisis detail dan alasan label]\nLabel: [Nama Label]","Komentar: 'Judul: .\n\nTeks: Warga Madura dikenal memiliki sifat keras kepala yang seringkali menghambat proses pembangunan di daerahnya. Hal ini terlihat jelas dalam respons mereka terhadap kebijakan pemerintah yang bertujuan untuk mengatur bisnis informal. Alih-alih menyambut baik kebijakan tersebut sebagai upaya untuk menciptakan lingkungan bisnis yang lebih teratur dan berkelanjutan, warga Madura cenderung menolaknya secara sistematis. Mereka sering berargumen bahwa kebijakan tersebut mengganggu rutinitas dan pendapatan mereka, meskipun fakta menunjukkan bahwa aturan tersebut justru bertujuan untuk melindungi dan meningkatkan kesejahteraan mereka. Kekeraskepalaan ini bukan hanya menunjukkan ketidakmampuan mereka untuk beradaptasi dengan perubahan, tetapi juga mencerminkan sikap yang menganggap diri mereka berada di luar kontrol pemerintah, seolah-olah mereka memiliki hak khusus untuk mengabaikan aturan yang berlaku. Akibatnya, pembangunan di daerah tersebut terhambat dan potensi ekonomi yang besar tidak dapat dimanfaatkan secara optimal.';\n\n","Penjelasan:\n* Claim menggeneralisir warga Madura dengan sifat keras kepala yang menghambat pembangunan.\n* Penolakan sistematis terhadap kebijakan pemerintah digambarkan sebagai sifat kolektif warga Madura.\n* Klaim menegaskan bahwa kekeraskepalaan ini merupakan bagian dari budaya umum masyarakat Madura, yang sulit diubah.\nLabel: Ujaran Kebencian."

In [119]:
regex_iklan = r'\s*"?\.?\s*SCROLL TO CONTINUE WITH CONTENT\s*"?\s*'

# 1. Hapus iklannya dan ganti dengan \n agar kalimat tidak dempet
allDF["input"] = allDF["input"].str.replace(regex_iklan, "\n", regex=True, flags=re.IGNORECASE)

# 2. Hapus sisa-sisa spasi atau enter kosong di awal/akhir teks (opsional tapi sangat disarankan)
allDF["input"] = allDF["input"].str.strip()

In [120]:
allDF.to_json('datasetSFT.jsonl', orient='records', lines=True)

# dibikin TRL

Buat contoh aja sih, harusnya udah di handle sebelum masuk ke finetuning

In [121]:
input_file_jsonl = "datasetSFT.jsonl"      
output_file_jsonl = "datasetSFT_TRL.jsonl"  



print(f"Memulai konversi file {input_file_jsonl}...")

berhasil = 0
gagal = 0

# Membuka file input (baca) dan file output (tulis) secara bersamaan
with open(input_file_jsonl, "r", encoding="utf-8") as f_in, \
     open(output_file_jsonl, "w", encoding="utf-8") as f_out:
     
    for line_num, line in enumerate(f_in, 1):
        if not line.strip():
            continue 
            
        try:
            data = json.loads(line)
            
            instruction = data.get("instruction", "")
            user_input = data.get("input", "")
            output_response = data.get("output", "")
            
            user_content = f"{user_input}"
            
            chat_structure = {
                "messages": [
                    {"role": "system", "content": instruction},
                    {"role": "user", "content": user_content},
                    {"role": "assistant", "content": output_response}
                ]
            }
            
            
            f_out.write(json.dumps(chat_structure, ensure_ascii=False) + "\n")
            berhasil += 1
            
            # Print progres setiap 2000 data agar bisa pantau
            if berhasil % 2000 == 0:
                print(f"Progres: {berhasil} data selesai diproses...")
                
        except json.JSONDecodeError:
            gagal += 1
            print(f"Peringatan: Gagal membaca baris ke-{line_num}")

print(f"\nSelesai! Berhasil mengonversi {berhasil} data.")
if gagal > 0:
    print(f"Ada {gagal} baris yang gagal/rusak.")

Memulai konversi file datasetSFT.jsonl...
Progres: 2000 data selesai diproses...
Progres: 4000 data selesai diproses...
Progres: 6000 data selesai diproses...
Progres: 8000 data selesai diproses...
Progres: 10000 data selesai diproses...
Progres: 12000 data selesai diproses...
Progres: 14000 data selesai diproses...
Progres: 16000 data selesai diproses...
Progres: 18000 data selesai diproses...
Progres: 20000 data selesai diproses...
Progres: 22000 data selesai diproses...
Progres: 24000 data selesai diproses...
Progres: 26000 data selesai diproses...

Selesai! Berhasil mengonversi 26523 data.

In [122]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

trl = pd.read_json("datasetSFT_TRL.jsonl", lines=True)

In [123]:
trl.head(1)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   messages
0  [{'role': 'system', 'content': 'Anda adalah sistem ahli klasifikasi komentar media sosial. Klasifikasikan [Komentar] ke salah satu Nama Label: [Netral, Disinformasi, Fitnah, Ujaran Kebencian].
Aturan:
1. Ujaran Kebencian: Serangan SARA/identitas/disabilitas (prioritas utama, abaikan rujukan).
2. Jika bukan ujaran kebencian, gunakan [Artikel Rujukan] jika ada untuk menilai:
- Netral: Faktual, opini, atau interaksi wajar.
- Disinformasi: Informasi keliru yang memicu keresahan/polarisasi.
- Fitnah: Tuduhan bohong untuk menyerang reputasi individu/kelompok.
Format Output WAJIB:
Penjelasan: [Analisis detail dan alasan label]
Label: [Nama Label]'}, {'role': 'user', 'content': 'Komentar: 'Guru Besar UGM tuduh kepala daerah sering ke Jakarta hanya untuk lobi-lobi, pembangunan daerah jadi tumbang!';

Artikel Rujukan: Fenomenakepala daerahyang terlalu sering berada di Jakarta kembali menjadi sorotan publik. Meski sudah menjadi kebiasaan di banyak daerah, praktik ini dinilai berdampak serius terhadap efektivitas pemerintahan dan penyerapan aspirasi masyarakat di daerah.
Guru Besar Manajemen Kebijakan Publik Universitas Gadjah Mada, Prof. Wahyudi Kumorotomo, menegaskan bahwa kebiasaankepala daerahlebih banyak berada di Jakarta bukan sekadar masalah etika kepemimpinan, tetapi juga soal efektivitas pembangunan.
"Banyak gubernur, bupati, wali kota, hingga sekretaris daerah yang justru lebih sering menginap di hotel-hotel di Jakarta untuk melakukan lobi-lobi, padahal mereka seharusnya berada di daerah untuk memantau langsung pembangunan dan melayani masyarakat,"ujarnya Selasa (30/12/2025).
BMKG Prediksi Hujan Lebat Selama Libur Nataru 2025/2026, Pakar UGM Ingatkan Perhatikan Ini Sebelum Berkendara
Menurut Wahyudi, ketidakhadiran pemimpin daerah secara langsung membuat penyerapan aspirasi rakyat menjadi terhambat. Kehadiran fisik kepala daerah di wilayahnya, menurutnya, tidak dapat digantikan oleh laporan tertulis atau koordinasi jarak jauh.
"Pemimpin yang jarang hadir di daerah akan kehilangan pemahaman atas persoalan nyata yang dihadapi masyarakat, sehingga kebijakan yang diambil berisiko tidak tepat sasaran," katanya.
Wahyudi juga menilai masalah ini sulit diatasi karena sudah mengakar dan dianggap wajar, baik oleh elite politik maupun sebagian masyarakat. Ia menekankan pentingnya teladan dari kepala daerah dan pengawasan dari pemerintah pusat.
"Mendagri perlu rutin melakukan inspeksi mendadak untuk memastikan kepala daerah benar-benar menjalankan tugasnya di lapangan,"tegasnya.
Dalam konteks hubungan pusat-daerah, Wahyudi menekankan bahwa koordinasi dengan pemerintah pusat seharusnya tidak menjadi alasan kepala daerah meninggalkan wilayahnya terlalu lama.
"Pejabat pusat perlu terus memantau kinerja pimpinan daerah, sekaligus memperkuat jalur koordinasi institusional agar urusan pusat tidak selalu menuntut kehadiran fisik kepala daerah di Jakarta,"jelasnya.
Ia juga menyoroti pentingnya edukasi politik kepada masyarakat. Menurutnya, kesadaran warga dalam memilih pemimpin yang benar-benar hadir di daerah masih rendah.
"Faktanya, ada bupati yang hanya pulang ke daerah sebulan sekali, tetapi tetap terpilih kembali. Ini menunjukkan masyarakat perlu disadarkan tentang bahaya politik uang dan pentingnya memilih pemimpin yang benar-benar hadir,"ungkap Wahyudi.
Satu - Satunya Pasar di Indonesia Punya RPH, Pasar Terban Kota Jogja Siap Beroperasi Penuh 10 Januari 2026
Oleh karena itu, Wahyudi berharap para kepala daerah, khususnya di Papua, memiliki kesadaran moral lebih kuat dalam menjalankan amanah. Ditegaskannya, bahwa kehadiran kepala daerah bukan sekadar soal administratif, melainkan kunci utama dalam memastikan pembangunan berjalan efektif, transparan, dan berpihak pada kesejahteraan masyarakat setempat.
"Para pejabat publik digaji dari uang rakyat dan sudah seharusnya mengabdikan diri sepenuhnya untuk kepentingan masyarakat. Mereka harus sadar bahwa tugas utama adalah melayani rakyat, bukan menikmati kenyamanan di Jakarta di atas penderitaan masyarakat di daerah,"pungkasnya.'}, {'role': 'assistant', 'content': 'Penjelasan: Pernyataan Prof. Wahyudi dipelintir menjadi tuduhan spesifik terhadap kepala daerah, padahal ia hanya mengkritisi praktik umum yang berdampak pada efektivitas pemerintahan. Kritik tersebut lebih bersifat analitis dan bukan tuduhan langsung.
Berikut adalah beberapa poin penting:
* Prof. Wahyudi Kumorotomo tidak menuduh secara langsung, tetapi mengkritisi praktik yang sering terjadi
* Kritik tersebut berbasis pada efektivitas pemerintahan dan penyerapan aspirasi masyarakat, bukan sekadar tuduhan
* Fokus kritik adalah pada kehadiran fisik kepala daerah di daerah, bukan hanya lobi-lobi
* Tidak ada bukti konkret bahwa semua kepala daerah yang sering ke Jakarta hanya untuk lobi-lobi
* Pernyataan Prof. Wahyudi adalah opini akademis, bukan fakta definitif
Label: Fitnah.'}]