In [2]:
import pandas as pd
from pathlib import Path
# pd.set_option('display.max_colwidth', None)

In [3]:
instructiones = [
    "Klasifikasikan teks ke dalam label Fitnah, Disinformasi, Ujaran Kebencian, Fakta, atau Non-DFK dengan membandingkan klaim terhadap artikel rujukan yang tersedia.",
    "Analisis teks berikut dan tentukan kategorinya (Fitnah/Disinformasi/Ujaran Kebencian/Fakta/Non-DFK) berdasarkan kesesuaiannya dengan konteks fakta yang disertakan.",
    "Bandingkan klaim di bawah ini dengan artikel rujukan, lalu tentukan apakah masuk kategori Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Tentukan label keamanan konten (Disinformasi/Fitnah/Ujaran Kebencian/Fakta/Non-DFK) setelah melakukan validasi silang antara teks dan artikel rujukan.",
    "Periksa apakah narasi ini sejalan dengan artikel rujukan atau justru melanggar aturan (Disinformasi/Fitnah/Ujaran Kebencian). Jika akurat, beri label Fakta atau Non-DFK.",
    "Evaluasi teks berikut dengan merujuk pada konteks fakta yang ada. Pilih label yang paling tepat: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Gunakan artikel rujukan sebagai dasar untuk menentukan apakah teks ini adalah Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Identifikasi kategori konten (Disinformasi/Fitnah/Ujaran Kebencian/Fakta/Non-DFK) dengan meninjau kontradiksi atau keselarasan teks terhadap rujukan fakta.",
    "Lakukan analisis mendalam pada teks ini menggunakan artikel rujukan, kemudian klasifikasikan ke label: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Tolong validasi klaim ini terhadap konteks informasi yang diberikan. Apakah ini merupakan Fakta, Disinformasi, Fitnah, Ujaran Kebencian, atau Non-DFK?",
    "Bandingkan pernyataan netizen ini dengan rujukan fakta resmi. Tentukan labelnya: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Lakukan screening konten. Berdasarkan artikel rujukan, apakah teks ini termasuk Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK?",
    "Cek kebenaran narasi di bawah ini menggunakan rujukan yang tersedia, lalu pilih label: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Berdasarkan bukti dari artikel rujukan, tentukan apakah teks ini melanggar etika (Fitnah/Ujaran Kebencian), memanipulasi fakta (Disinformasi), atau benar (Fakta/Non-DFK).",
    "Uji integritas klaim ini dengan membandingkannya terhadap konteks fakta. Masukkan ke kategori: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Identifikasi apakah teks ini merupakan informasi valid (Fakta), konten netral (Non-DFK), atau pelanggaran (Disinformasi/Fitnah/Ujaran Kebencian) merujuk pada data rujukan.",
    "Analisis korelasi antara teks dan artikel rujukan untuk menentukan label: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Tentukan status kebenaran teks ini (Fakta/Disinformasi/Fitnah/Ujaran Kebencian/Non-DFK) dengan mencocokkan informasi di dalamnya dengan rujukan yang ada.",
    "Kaji narasi berikut terhadap konteks fakta yang disediakan. Berikan label: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Lakukan verifikasi klaim. Bandingkan poin-poin teks dengan artikel rujukan dan tentukan kategori: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Tinjau kredibilitas teks ini terhadap rujukan fakta. Pilih salah satu: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Lakukan komparasi kritis antara input teks dan data rujukan. Masukkan ke label: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Apakah teks ini akurat (Fakta) atau menyesatkan (Disinformasi/Fitnah/Ujaran Kebencian)? Tentukan berdasarkan rujukan fakta yang tersedia atau labeli Non-DFK jika netral.",
    "Bantu klasifikasikan teks ini ke label Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK dengan mempertimbangkan artikel rujukan sebagai standar kebenaran.",
    "Bedah klaim ini dengan merujuk pada artikel rujukan. Tentukan label yang sesuai: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Evaluasi apakah teks ini mendukung atau membantah rujukan fakta. Labeli sebagai Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Identifikasi intensi teks terhadap artikel rujukan. Klasifikasikan sebagai Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Gunakan data pembanding dalam artikel rujukan untuk menentukan label teks: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Periksa klaim digital ini. Bandingkan dengan konteks fakta untuk menentukan apakah ini Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Lakukan pemeriksaan fakta silang. Tentukan kategori teks (Disinformasi/Fitnah/Ujaran Kebencian/Fakta/Non-DFK) sesuai rujukan informasi.",
    "Ukur tingkat akurasi teks ini terhadap artikel rujukan dan pilih label: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Bandingkan narasi berikut dengan rujukan resmi. Apakah hasilnya masuk label Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK?",
    "Identifikasi adanya penyimpangan informasi dengan membandingkan teks terhadap artikel rujukan (Disinformasi/Fitnah/Ujaran Kebencian/Fakta/Non-DFK).",
    "Analisis apakah klaim ini merupakan manipulasi (Disinformasi), tuduhan (Fitnah), serangan (Ujaran Kebencian), atau informasi benar (Fakta/Non-DFK) merujuk data rujukan.",
    "Labeli teks ini (Disinformasi/Fitnah/Ujaran Kebencian/Fakta/Non-DFK) setelah memastikan kesesuaian narasinya dengan artikel rujukan.",
    "Lakukan verifikasi data. Berdasarkan artikel rujukan, tentukan label: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Kroscek klaim di bawah ini dengan rujukan fakta. Klasifikasikan ke: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Tentukan kategori teks ini berdasarkan bukti-bukti dalam artikel rujukan: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Lihat artikel rujukan dan bandingkan dengan klaim berikut. Berikan label: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Lakukan moderasi berdasarkan fakta. Apakah teks ini termasuk Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK?",
    "Cocokkan informasi pada klaim ini dengan konteks fakta. Pilih label: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Evaluasi kebenaran klaim ini melalui artikel rujukan. Tentukan label: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Analisis potensi pelanggaran konten. Bandingkan teks dengan rujukan fakta dan pilih label: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Tandai klaim ini sebagai Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK dengan mempertimbangkan data dari artikel rujukan.",
    "Pindai integritas teks terhadap artikel rujukan. Masukkan ke kategori: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Gunakan rujukan fakta untuk mengidentifikasi apakah teks ini adalah Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Lakukan perbandingan data lapangan. Tentukan kategori konten: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.",
    "Evaluasi narasi digital ini secara kritis menggunakan artikel rujukan sebagai pembanding (Disinformasi/Fitnah/Ujaran Kebencian/Fakta/Non-DFK).",
    "Bantu sistem menentukan validitas teks ini (Fakta/Disinformasi/Fitnah/Ujaran Kebencian/Non-DFK) berdasarkan perbandingan terhadap rujukan informasi.",
    "Lakukan uji validasi akhir. Bandingkan klaim dengan artikel rujukan dan beri label: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK."
]

# Fitnah

## Buat Artikel

In [4]:
folderData = Path("Dataset_Fitnah/artikel")
files = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    files.append(df_sementara)

df_artikel = pd.concat(files, ignore_index=True)

In [5]:
df_artikel.isna().sum()

url                 0
title               0
published_at        0
text                0
sumber_berita       0
label               0
is_layak          106
teks              106
target            107
\target          3597
dtype: int64

In [6]:
len(df_artikel)

3598

In [7]:
df_artikel["target"] = df_artikel["target"].fillna(df_artikel["\target"])

In [8]:
df_artikel = df_artikel.dropna(subset=["is_layak"])

In [9]:
df_artikel[df_artikel["is_layak"]==1]

,url,title,published_at,text,sumber_berita,label,is_layak,teks,target,\target
0,https://infosumut.id/kendaraan-odol-segera-dit...,Kendaraan ODOL Segera Ditertibkan - Info Sumut,2021-10-28T08:22:30+00:00,MEDAN – Gubernur Sumatera Utara (Sumut) Edy Ra...,infosumut,Politik,1.0,"Gubernur Sumatera Utara, Edy Rahmayadi, disebu...","Gubernur Sumatera Utara, Edy Rahmayadi",NaN
3,https://kaltim.idntimes.com/news/kalimantan-ti...,Korban yang Diduga Keracunan MBG di Ketapang B...,N/A,Korban dugaan keracunan massal akibat menu Mak...,idntimes,Kesehatan,1.0,Korban dugaan keracunan massal akibat menu Mak...,"Kepala Badan Gizi Nasional Kalimantan Barat, A...",NaN
5,https://infosumut.id/kendaraan-odol-segera-dit...,Kendaraan ODOL Segera Ditertibkan - Info Sumut,2021-10-28T08:22:30+00:00,MEDAN – Gubernur Sumatera Utara (Sumut) Edy Ra...,infosumut,Politik,1.0,"Gubernur Sumatera Utara, Edy Rahmayadi, dikrit...","Gubernur Sumatera Utara, Edy Rahmayadi",NaN
7,https://kabarpapua.co/akhirnya-bonus-atlet-per...,"Akhirnya, Bonus Atlet Peraih Medali PON XXI da...",2025-03-27T14:33:20+00:00,Pemerintah Provinsi (Pemprov) akhirnya menyera...,kabarpapua,Politik,1.0,Penyerahan bonus kepada atlet peraih medali PO...,"Penjabat Gubernur Papua, Ramses Limbong",NaN
9,https://matapapua.com/ketua-forkom-imeko-bersa...,MataPapua - Portal Berita Terkini dan Akurat,N/A,The featured articles are selected by experien...,matapapua,Politik,1.0,DPR Provinsi Papua kembali menjadi sorotan pub...,DPR Provinsi Papua,NaN
...,...,...,...,...,...,...,...,...,...,...
3584,https://news.okezone.com/read/2026/04/10/337/3...,Prabowo Berencana ke Rusia dalam Waktu Dekat -...,2026-04-10T22:03:19+07:00,- Presiden Prabowo Subianto diagendakan melaks...,okezone,Politik,1.0,Presiden Prabowo Subianto dikabarkan berencana...,Presiden Prabowo Subianto,NaN
3588,https://www.jawapos.com/ekonomi/2509190274/ket...,Ketua Banggar DPR RI Said Abdullah Sebut Puan ...,N/A,- Badan Anggaran Dewan Perwakilan Rakyat (Bang...,jawapos,Politik,1.0,"Ketua Badan Anggaran DPR RI, Said Abdullah, me...",Ketua DPR Puan Maharani,NaN
3589,https://www.jawapos.com/kasuistika/2603250172/...,"Masuk Rutan Lagi Usai jadi Tahanan Rumah, KPK ...",N/A,- Komisi Pemberantasan Korupsi (KPK) menjadwal...,jawapos,Politik,1.0,KPK kembali memeriksa Yaqut Cholil Qoumas sete...,Yaqut Cholil Qoumas,NaN
3594,https://www.jawapos.com/kesehatan/2502270199/h...,Hadir dalam Diskusi Peringati Hari Kanker Sedu...,N/A,PT Tugu Reasuransi Indonesia (Tugure) menggela...,jawapos,Kesehatan,1.0,Menteri Kesehatan Budi Gunadi Sadikin mendapat...,Menteri Kesehatan Budi Gunadi Sadikin,NaN
3595,https://suarapapua.com/2019/01/17/tersangkakan...,"Tersangkakan Aktivis KNPB, Koalisi Penegakan H...",2019-01-17T19:03:50+09:00,Komite Nasional Papua Barat (KNPB) melalui tim...,suarapapua,Politik,1.0,Koalisi Penegakan Hukum dan HAM untuk Papua me...,Koalisi Penegakan Hukum dan HAM untuk Papua,NaN

In [10]:
folderData = Path("Hasil_Parafrase")
files = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    files.append(df_sementara)

df = pd.concat(files, ignore_index=True)

In [11]:
df_fitnah = df[df["is_layak"] == 1]

In [12]:
df_fitnah[df_fitnah["cot_bantuh_fitnah"].notna()]

,url,title,published_at,text,sumber_berita,label,is_layak,claim_fitnah,cot_bantah_fitnah,reasoning_fitnah,cot_bantuh_fitnah
4305,https://banten.indozone.id/news/2486375917/hin...,"Hingga September 2025, Capaian Pajak Kota Tem...",2025-10-10 12:02:12,"Kepala Bapenda Kota Serang, W Hari Pamungkas (...",indozone,Ekonomi & Bisnis,1.0,"Pemerintah Kota Serang korup, target pajak yan...",NaN,Fakta bahwa capaian pajak meningkat signifikan...,"[Capaian pajak 70,19 persen dari target tahuna..."
11532,https://news.indozone.id/world-update/91486061...,Kronologi Penembakan Donald Trump saat Kampany...,2024-07-14 10:13:12,- Sebuah penembakan terjadi pada rapat umumDon...,indozone,Politik,1.0,Trump sengaja terkena tembakan untuk mendapatk...,NaN,Claim tersebut menggunakan insinuasi dan frami...,[Fakta menunjukkan bahwa penembakan terjadi sa...

In [13]:
pinjemFithahnya = df_fitnah[["url", "title", "published_at", "text", "sumber_berita", "label"]]
pinjemFithahnya.to_json('dataset_sampledbuatFakta.jsonl', orient='records', lines=True, force_ascii=False)

In [14]:
df_fitnah["cot_bantah_fitnah"] = df_fitnah["cot_bantah_fitnah"].fillna(df_fitnah["cot_bantuh_fitnah"])
df_fitnah = df_fitnah.drop(columns=["cot_bantuh_fitnah", "url", "published_at", "sumber_berita", "label", "is_layak"])

C:\Users\Dipo\AppData\Local\Temp\ipykernel_116392\883797873.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fitnah["cot_bantah_fitnah"] = df_fitnah["cot_bantah_fitnah"].fillna(df_fitnah["cot_bantuh_fitnah"])

In [15]:
df_fitnah[df["reasoning_fitnah"].isna()]

C:\Users\Dipo\AppData\Local\Temp\ipykernel_116392\2068391604.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_fitnah[df["reasoning_fitnah"].isna()]

,title,text,claim_fitnah,cot_bantah_fitnah,reasoning_fitnah
2759,Gebrakan Pramono Anung Lantik Tim Pembina Posy...,Pelantikan Pembina Posyandu DKI Jakarta (timur...,Pramono Anung hanya memanfaatkan pelantikan Ti...,[Pelantikan Tim Pembina Posyandu merupakan bag...,NaN

In [16]:
df_fitnah["reasoning_fitnah"] = df_fitnah["reasoning_fitnah"].fillna("Tidak benar")

In [17]:
df_fitnah.isna().sum()

title                0
text                 0
claim_fitnah         0
cot_bantah_fitnah    0
reasoning_fitnah     0
dtype: int64

In [18]:
df_fitnah["label"] = "Fitnah"

In [19]:
# sample, buat dikasih ke mereka udah acc atau belum

# df_fitnah = df_fitnah[["text","claim_fitnah", "cot_bantah_fitnah", "reasoning_fitnah", "label"]]
# df_fitnah = df_fitnah.sample(frac=1, random_state=42).reset_index(drop=True)
# df_fitnah = df_fitnah.sample(n=50)

# df_fitnah.to_csv("sft_fitnah.csv", index=False)

In [20]:
df_fitnah = df_fitnah.to_dict("records")

In [21]:
len(df_fitnah)

7212

In [22]:
kalimat_penutup = [
    "**Selalu pastikan untuk memverifikasi informasi melalui saluran berita resmi guna menghindari penyebaran hoaks.**", 
    "**Mari lebih bijak dalam menyerap informasi dengan selalu merujuk pada sumber data yang valid dan terpercaya.**",
    "**Jangan mudah terprovokasi oleh klaim sepihak; pastikan Anda mengecek fakta dari otoritas terkait.**",
    "**Penting untuk selalu melakukan kroscek terhadap berita yang beredar agar terhindar dari pengaruh informasi palsu.**",
    "**Pastikan untuk selalu memeriksa sumber berita resmi dan kredibel guna mendapatkan fakta yang akurat.**",
    "**Lindungi diri dari misinformasi dengan membiasakan cek fakta melalui media informasi pemerintah atau lembaga resmi.**",
    "**Tetap waspada terhadap narasi negatif; selalu cari konfirmasi dari sumber berita yang memiliki reputasi baik.**",
    "**Verifikasi adalah kunci. Selalu bandingkan informasi yang Anda terima dengan laporan dari pihak berwenang.**",
    "**Demi mendapatkan pemahaman yang utuh, pastikan Anda hanya merujuk pada informasi dari kanal-kanal resmi.**",
    "**Ayo lawan hoaks dengan selalu mengutamakan data dari sumber berita yang sah dan dapat dipertanggungjawabkan.**"
]

In [23]:
import json
import random

def generate_sft_dataset_with_context(raw_data_list, instructions, penutup_list, output_file):
    dataset = []
    
    for data in raw_data_list:
        instruct = random.choice(instructions)
        claim = data.get("claim_fitnah", "")
        berita = data.get("text", "") 
        label = data.get("label")
        reasoning = data.get("reasoning_fitnah", "")
        cot_list = data.get("cot_bantah_fitnah", [])
        
        # Susun poin-poin fakta
        fakta_points = "\n".join([f"* {point}" for point in cot_list])
        closing = random.choice(penutup_list)
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"input: {claim};\n\n"
            f"fakta: {berita}"
        )

        full_output = (
            f"Label: **{label}.** "
            f"penjelasan: {reasoning}\n\n"
            f"Berikut adalah beberapa fakta sebenarnya:\n"
            f"{fakta_points}\n\n"
            f"{closing}"
        )
        
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(df_fitnah, instructiones, kalimat_penutup, "fitnah.jsonl")

Berhasil membuat 7212 data dengan konteks berita di fitnah.jsonl

In [24]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

df = pd.read_json("fitnah.jsonl", lines=True)
df

,instruction,input,output
0,"Bandingkan narasi berikut dengan rujukan resmi. Apakah hasilnya masuk label Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK?","input: BNN sengaja pilih kampung miskin buat dijadikan kambing hitam soal narkoba;\n\nfakta: BNN menggedebek kampung narkoba di Berlan, Matraman, Jakarta Timur. (Antara Foto/Fauzan)\n- Badan Narkotika Nasional (BNN) bersama petugas gabungan menggerebek kawasan Berlan, Matraman, Jakarta Timur, terkait dugaan peredarannarkobapada Selasa (25/11/2025) siang.\nDalam operasi tersebut, puluhan orang yang diduga sebagai pengedar berhasil diamankan.\nPenggerebekan dilakukan sekitar pukul 11.00 WIB. Petugas gabungan melakukan penyisiran ke sejumlah rumah dan langsung melakukan penggeledahan di titik-titik yang telah ditargetkan.\nDari lokasi, petugas menemukan berbagai jenis barang bukti narkoba dalam bentuk bubuk maupun cairan.\nSejumlah paket narkoba ditemukan disembunyikan di lemari hingga gudang-gudang kecil yang berada di dalam rumah warga.\nTerungkap! Ekstasi Rp 207 M Ditemukan Saat Mobil Kecelakaan di Lampung Hendak Disebar di Jakarta\nUntuk mempermudah pencarian barang bukti, petugas juga mengerahkan anjing pelacak (K9).\nLangkah ini dilakukan untuk memastikan tidak ada narkoba yang terlewatkan selama proses penggeledahan.\nDirektur Psikotropika dan Prekursor Deputi Bidang Pemberantasan BNN, Aldrin Marihot Pandapotan Hutabarat, menyampaikan bahwa pihaknya mengamankan puluhan orang dalam operasi tersebut.\n""Ada 10–15 titik yang menjadi target penggerebekan di kawasan Berlan. Dari rangkaian penggerebekan itu, kami mengamankan 25 pelaku,"" ujar Aldrin.\nSeluruh orang yang diamankan langsung dibawa ke kantor BNN untuk pemeriksaan lebih lanjut. Ia menyebut bahwa para pelaku merupakan warga sekitar.\n""Kawasan ini merupakan perkampungan. Semua yang kami amankan adalah warga sipil. Kami akan dalami peran masing-masing,"" pungkasnya.","Label: **Fitnah.** penjelasan: Fakta dipelintir dengan menuduh BNN memilih kampung miskin sebagai kambing hitam, padahal operasi ini didasarkan pada informasi intelijen dan bukti yang ditemukan di lapangan\n\nBerikut adalah beberapa fakta sebenarnya:\n* BNN melakukan penggerebekan di Berlan, Matraman, berdasarkan informasi dan indikasi kuat adanya peredaran narkoba di kawasan tersebut\n* Operasi ini melibatkan petugas gabungan dan menggunakan anjing pelacak (K9) untuk memastikan keakuratan dan efektivitas penggeledahan\n* Berbagai jenis barang bukti narkoba ditemukan di lokasi, termasuk bubuk dan cairan yang disembunyikan di lemari dan gudang-gudang kecil\n* Penggerebekan ini mengamankan puluhan orang yang diduga sebagai pengedar, bukan sembarangan warga miskin\n* Tindakan BNN ini adalah bagian dari upaya nasional untuk memerangi peredaran narkoba, tidak ada indikasi pemilihan target berdasarkan status sosial ekonomi\n\n**Lindungi diri dari misinformasi dengan membiasakan cek fakta melalui media informasi pemerintah atau lembaga resmi.**"
1,"Tentukan kategori teks ini berdasarkan bukti-bukti dalam artikel rujukan: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.","input: DPRD Berau sengaja lambatkan serapan anggaran untuk menutupi korupsi;\n\nfakta: KALIMANTAN TIMUR - Serapan anggaran Pemerintah KabupatenBeraupada semester pertama tahun anggaran 2025 mendapat sorotan dari DPRD. Dalam rapat evaluasi laporan semester pertama dan rencana kerja enam bulan ke depan, DPRD menilai realisasi anggaran masih jauh dari ideal.\nWakil Ketua I DPRD Berau, Subroto, menyebut serapan anggaran secara keseluruhan baru mencapai sekitar 38 persen. Angka tersebut dinilai masih rendah, meski dipahami ada sejumlah proyek besar yang masih dalam tahap lelang.\n""Penyerapan anggaran secara global baru 38 persen. Ini memang belum sesuai harapan, tapi kita pahami banyak pekerjaan besar masih dalam proses lelang,"" kata Subroto.\nBeberapa Organisasi Perangkat Daerah (OPD) seperti Dinas Pendidikan, Dinas Kesehatan, dan Dinas Pekerjaan Umum dan Penataan Ruang (PUPR) disebut sebagai pemilik anggaran terbesar, namun hingga kini masih dalam proses pengadaan.\n""Dari sekitar 400 paket pekerjaan, 90 persen di antaranya sudah masuk proses lelang. Jadi belum bisa diserap ke anggaran karena menunggu tahapan selesai,"" ujarnya.\nSubroto menyebut target penyelesaian proses lelang ditetapkan pada bulan September. Setelah itu, ia berharap serapan anggaran bisa meningkat signifikan di semester kedua.\nIa juga menyoroti persoalan teknis yang menghambat proses lelang, terutama terkait keterbatasan SDM bersertifikasi di Unit Layanan Pengadaan (ULP).\n""Tenaga pelaksana lelang yang bersertifikat masih terbatas, ini jadi kendala utama. Tapi ke depan persoalan ini segera dituntaskan,"" ungkapnya.\nMeski demikian, DPRD tetap optimistis target serapan anggaran di akhir tahun bisa tercapai. Subroto menegaskan pentingnya keseriusan seluruh OPD agar tak terjadi Sisa Lebih Pembiayaan Anggaran (Silpa).\n""Kami harap di akhir tahun nanti serapan bisa maksimal. Jangan sampai ada anggaran yang tidak terserap,"" pungkasnya. (*)","Label: **Fitnah.** penjelasan: Claim ini menggunakan framing negatif dan insinuasi untuk menyudutkan DPRD Berau, padahal fakta menunjukkan bahwa DPRD justru mengkritisi dan memantau proses serapan anggaran dengan transparan.\n\nBerikut adalah beberapa fakta sebenarnya:\n* DPRD Berau menyoroti rendahnya serapan anggaran, bukan menutupinya. Mereka justru mengkritisi hal tersebut.\n* Wakil Ketua I DPRD Berau, Subroto, menjelaskan bahwa banyak proyek besar masih dalam tahap lelang, yang mempengaruhi rendahnya serapan anggaran.\n* Subroto menyebutkan bahwa 90 persen dari sekitar 400 paket pekerjaan sudah masuk proses lelang, menunjukkan transparansi dalam proses pengadaan.\n* Target penyelesaian proses lelang ditetapkan pada bulan September, dan DPRD berharap serapan anggaran akan meningkat signifikan setelah itu.\n\n**Verifikasi adalah kunci. Selalu bandingkan informasi yang Anda terima dengan laporan dari pihak berwenang.**"
2,"Ukur tingkat akurasi teks ini terhadap artikel rujukan dan pilih label: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.","input: Sandiaga Uno hanya memanfaatkan relawan untuk kepentingan pribadi di Pilpres 2024;\n\nfakta: Sandiaga Uno dalam acara silaturahmi dengan para relawan.- Sandiaga Uno mengingatkan para relawan pendukungnya untuk bekerja keras mendukung pasangan bakal capres dan cawapres Ganjar Pranowo-Mahfud MD.Menurut Sandi, hal ini penting dilakukan karena relawan punya peran penting dalam mendulang suara di masa Pemilu 2024.Hal ini disampaikan Sandiaga Uno dalam acara silaturahmi dengan relawan di Aula Attaqwa Sriwijaya, Kebayoran Baru, Jakarta Selatan, kemarin.Kegiatan inti dari acara ini adalah untuk menyerap aspirasi para relawan dan memungkinkan mereka menyampaikan aspirasinya.Dalam kegiatan tersebut relawan-relawan berkumpul dan memberikan masukan yang berharga, yang akan menjadi dasar untuk merancang program dan gagasan yang mendukung visi Ganjar Pranowo dan Mahfud MD.\nMenurut Sandi, para relawan mengharapkan agar kedepan ekonomi hijau, harga-harga murah, mencari kerja mudah, dan hidup berkah.""Ini yang akan saya sampaikan atas masukan dan aspirasi ke relawan seluruh Indonesia untuk disampaikan kepada para dewan pakar yang nanti akan menyusun satu program gagasan,"" kata Sandiaga Uno dalam pernyataan resmi, Senin (30/10/2023).\nSandiaga Uno dalam acara silaturahmi dengan para relawan.""Nanti ditampilkan bagaimana agar memberikan percepatan pembangunan untuk menghadapi beberapa tantangan yang disampaikan para relawan,"" imbuhnya.Sandiaga juga meminta para relawan untuk tetap berpartisipasi dalam membangun pemilu yang kondusif dan pemilu yang damai yang mempersatukan bangsa. Dia juga meminta para relawan untuk bekerja keras agar pasangan Ganjar-Mahfud meraih kemenangan di Pilpres 2024.\nMenurut politikus PPP ini, para relawan memiliki peran strategis dan krusial untuk mencapai tujuan tersebut. Dia mencontohkan apa yang terjadi pada Pilpres 2019, di mana para relawan menyumbangkan suara strategis bagi para kandidat.\n""Di 2019 peran relawan ini sangat besar, para relawan ini menyumbangkan suara yang sangat signifikan dan diatas prediksi dari para lembaga survei,"" kata Sandiaga.Salah satu relawan, Aisyah Mochamed dari Rumah SandiUno Indonesia (RSI) NTB, mengungkapkan rasa terima kasihnya atas undangan dari Sandiaga Uno. Ia merasa terinspirasi dan bertekad untuk mendukung pasangan Ganjar Pranowo dan Mahfud MD.""Mentor kita kan memang Pak Sandi ya jadi arahan dari beliau Insyaallah kita akan mensupport Pak Ganjar. Terima kasih Pak Sandi sudah mengundang kami, dari sini kedepan kita tau arah tujuan yang diinginkan Pak Sandiaga untuk Indonesia,"" kata Aisyah.","Label: **Fitnah.** penjelasan: Claim ini menggunakan framing negatif dan insinuasi untuk menyudutkan Sandiaga Uno, padahal fakta menunjukkan bahwa acara silaturahmi bertujuan untuk mendukung pasangan Ganjar Pranowo-Mahfud MD dan memperkuat visi mereka.\n\nBerikut adalah beberapa fakta sebenarnya:\n* Sandiaga Uno mengingatkan relawan untuk mendukung pasangan Ganjar Pranowo-Mahfud MD, bukan untuk kepentingan pribadinya.\n* Acara silaturahmi bertujuan untuk menyerap aspirasi relawan dan merancang program yang mendukung visi Ganjar Pranowo dan Mahfud MD.\n* Sandiaga Uno menekankan pentingnya peran relawan dalam mendulang suara untuk pasangan Ganjar-Mahfud, bukan untuk agenda pribadinya.\n* Relawan memberikan masukan yang berharga, yang akan menjadi dasar untuk merancang program dan gagasan yang mendukung visi Ganjar Pranowo dan Mahfud MD.\n\n**Mari lebih bijak dalam menyerap informasi dengan selalu merujuk pada sumber data yang valid dan terpercaya.**"
3,"Bandingkan narasi berikut dengan rujukan resmi. Apakah hasilnya masuk label Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK?","input: BPBD DKI Jakarta main-main sama cuaca, bikin hujan buatan biar dapet dana darurat!;\n\nfakta: Ilustrasi cuaca ekstrem. (ANTARA FOTO/Dedhez Anggara)\nBadan Penanggulangan Bencana Daerah (BPBD)DKI Jakartakembali melakukan operasimodifikasi cuaca(OMC) dalam rangka mengantisipasicuaca ekstrem. Hal itu disampaikan langsung oleh Kepala PelaksanaBPBDDKI Jakarta, Isnawa Adji.\n""Rencana penerbangan OperasiModifikasi Cuaca(OMC) dalam rangka kesiapsiagaan menghadapi bencana hidrometeorologi ekstrem di ProvinsiDKI Jakarta,"" kata Isnawa, seperti INDOZONE sadur dari Antara, Sabtu (31/1/2026).\nOperasi tersebut, kata dia, merupakan hasil sinergi antara BPBD DKI Jakarta dengan Badan Nasional Penanggulangan Bencana (BNPB), Badan Meteorologi, Klimatologi dan Geofisika (BMKG), TNI Angkatan Udara, serta unsur terkait lainnya.\nRibuan Hektare Sawah di Karawang Terendam Banjir Akibat Cuaca Ekstrem\nDia menjelaskan pada sorti pertama, pesawat melakukan penyemaian awan di perairan utara Jakarta pada ketinggian 8.000-11.000 kaki. Pada sorti ini, digunakan bahan semai berupa Kalsium Oksida (CaO) sebanyak 800 kilogram.\nSorti kedua, dilaksanakan dengan fokus penyemaian awan di wilayah barat daya Jakarta, penerbangan dilakukan pada ketinggian 7.000-8.000 kaki.\nBMKG Ingatkan Cuaca Ekstrem, Hujan hingga Petir Siap Guyur Sejumlah Daerah\n""Pada sorti ini, digunakan bahan semai berupa Natrium Klorida (NaCl) sebanyak 800 kilogram,"" ujar Isnawa.\nLebih lanjut, dia menyebutkan OMC tersebut dilakukan berdasarkan analisis kondisi atmosfer serta pemantauan cuaca secara berkelanjutan, sehingga penyemaian awan dapat diarahkan ke wilayah yang lebih aman.\nBPBD Provinsi DKI Jakarta terus melakukan evaluasi harian terhadap pelaksanaan OMC serta memperkuat koordinasi lintas instansi guna memastikan kesiapsiagaan menghadapi potensi bencana hidrometeorologi di wilayah DKI Jakarta dan sekitarnya.","Label: **Fitnah.** penjelasan: Claim ini memanfaatkan framing negatif dan insinuasi bahwa BPBD DKI Jakarta melakukan manipulasi cuaca untuk keuntungan pribadi. Fakta sebenarnya, OMC adalah upaya preventif yang dilakukan secara profesional dan transparan untuk mengantisipasi bencana cuaca ekstrem.\n\nBerikut adalah beberapa fakta sebenarnya:\n* Operasi Modifikasi Cuaca (OMC) adalah tindakan preventif yang dilakukan BPBD DKI Jakarta untuk mengantisipasi cuaca ekstrem, bukan untuk menciptakan hujan buatan.\n* OMC dilakukan dengan sinergi berbagai institusi seperti BNPB, BMKG, dan TNI Angkatan Udara, bukan aksi sembarangan.\n* Tujuan utama OMC adalah untuk mengurangi risiko bencana hidrometeorologi, bukan untuk mendapatkan dana darurat.\n* Fakta bahwa OMC menggunakan bahan semai Kalsium Oksida (CaO) dan dilakukan di ketinggian tertentu menunjukkan bahwa ini adalah proses ilmiah yang terencana.\n* BPBD DKI Jakarta telah menjelaskan secara transparan tentang rencana dan pelaksanaan OMC, termasuk ketinggian penerbangan dan jumlah bahan semai yang digunakan.\n\n**Lindungi diri dari misinformasi dengan membiasakan cek fakta melalui media informasi pemerintah atau lembaga resmi.**"
4,"Bantu klasifikasikan teks ini ke label Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK dengan mempertimbangkan artikel rujukan sebagai standar kebenaran.","input: Pemprov Sumut hanya main-main dengan UHC, masyarakat masih susah akses kesehatan!;\n\nfakta: Capaian Universal Health Coverage (UHC) Sumatera Utara kini sudah mencapai angka 98,6%. Pemprov Sumut menegaskan komitmennya memberikan layanan kesehatan optimal bagi seluruh warganya.\nHal ini disampaikan Kepala Dinas Kesehatan Sumut, Faisal Hasrimi, dalam konferensi pers di Kantor Gubernur Sumut, Rabu (17/9/2025). Menurutnya, capaian ini diperoleh lewat pembagian beban premi antara Pemprov dengan Pemkab/Pemko.\nSkemanya, kabupaten/kota menanggung 80% dan Pemprov 20%. Dalam lima tahun ke depan, komposisi ini akan berubah menjadi 70% kabupaten/kota dan 30% Pemprov.\nFaisal menegaskan, pembayaran premi tidak tumpang tindih dengan pemerintah pusat. Setiap tingkatan pemerintahan sudah diatur targetnya. Hal ini memastikan efisiensi dalam program kesehatan.\nDorong Keterbukaan, Bobby Nasution Ingatkan OPD Lebih Transparan ke Publik\nSelain itu, tingkat kepatuhan peserta mandiri membayar iuran BPJS Kesehatan juga harus dijaga. Saat ini, sekitar 80% peserta aktif melakukan pembayaran.\nMenurut Faisal, UHC di Sumut bukan sekadar simbol. ""Kita tidak mau UHC ecek-ecek. Komitmen kita agar layanan benar-benar berjalan,"" ujarnya.\nMulai September, masyarakat bisa berobat gratis hanya dengan membawa KTP. Administrasi akan diurus petugas fasilitas kesehatan. Warga tidak perlu lagi repot fotokopi KTP atau syarat lainnya.\nPemprov bersama BPJS Kesehatan sudah bekerja sama dengan 172 rumah sakit, 619 puskesmas, dan 510 klinik untuk mendukung layanan ini. Semua fasilitas diwajibkan melayani pasien terlebih dahulu sebelum urusan administrasi.\nBPJS Ketenagakerjaan Jadi Prioritas, Pemprov Sumut Dorong Kepatuhan Iuran\nSelain layanan kesehatan gratis, Pemprov juga memberikan beasiswa Program Pendidikan Dokter Spesialis (PPDS). Tujuh putra-putri dari Nias menerima beasiswa dan akan kembali mengabdi di daerah asal.\nDi sisi lain, Kepala BKAD Sumut, Timur Tumanggor, menyebut Pemprov telah menyiapkan Rp297 miliar untuk program UHC di 2025. Anggaran ini meningkat menjadi Rp438 miliar pada 2026.\nKonferensi pers juga dihadiri sejumlah pejabat, termasuk Kepala Bappelitbang Sumut Dikky Anugerah, Dirut RSU Haji Medan Sri Suriani Purnamawati, dan Kabid IKP Diskominfo Sumut Harvina Zuhra.\nDengan komitmen ini, Pemprov berharap tidak ada lagi warga yang kesulitan mengakses layanan kesehatan. Semua masyarakat berhak mendapatkan pelayanan yang layak dan cepat.","Label: **Fitnah.** penjelasan: Fakta menunjukkan capaian UHC yang tinggi dan komitmen Pemprov Sumut untuk memastikan layanan kesehatan yang optimal. Narasi negatif ini melebih-lebihkan isu akses kesehatan dan meragukan komitmen pemerintah.\n\nBerikut adalah beberapa fakta sebenarnya:\n* Capaian UHC Sumut mencapai 98,6%, menunjukkan komitmen kuat Pemprov dalam menyediakan layanan kesehatan bagi warga.\n* Pembagian beban premi antara Pemprov dan Pemkab/Pemko memastikan efisiensi dan keberlanjutan program.\n* Kepala Dinas Kesehatan Sumut, Faisal Hasrimi, menegaskan bahwa UHC bukan sekadar simbol, melainkan program yang benar-benar berjalan.\n* Masyarakat kini bisa berobat gratis hanya dengan membawa KTP, mempermudah akses kesehatan.\n\n**Verifikasi adalah kunci. Selalu bandingkan informasi yang Anda terima dengan laporan dari pihak berwenang.**"
...,...,...,...

In [25]:
text= "Women Okezone menyajikan berita terbaru dan terpercaya seputar dunia perempuan. Dapatkan informasi terkini tentang gaya hidup, kesehatan, karier, dan inspirasi wanita di Indonesia." 

print(len(text))

180

# Disinformasi

## Artikel

In [26]:
folderData = Path("Dataset_disinformasi/artikel")
files = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    files.append(df_sementara)

df_artikel = pd.concat(files, ignore_index=True)

In [27]:
df_artikel[df_artikel["is_layak"] == 1]

,url,title,published_at,text,sumber_berita,label,is_layak,disinformasi_teks,target_subjek,,'; // Note: The last sentence is in Chinese and should be translated to Indonesian for consistency. Here is the corrected version in Indonesian:,); // Note: The,class,&nbsp;,x
0,https://infosumut.id/kendaraan-odol-segera-ditertibkan/?page=all,Kendaraan ODOL Segera Ditertibkan - Info Sumut,2021-10-28T08:22:30+00:00,"MEDAN – Gubernur Sumatera Utara (Sumut) Edy Rahmayadi menyambut baik penerapan Normalisasi Kendaraan Over Dimension Over Loading (ODOL), serta penerapan Peraturan Menteri Perhubungan Nomor PM 75 Tahun 2021 tentang Pengaturan Lalu Lintas Mobil Barang di Ruas Jalan Batas Kota Medan-Batas Kabupaten Karo (Medan-Berastagi) dan Ruas Jalan Batas Kota Pematang Siantar-Parapat.\nMenurut Gubernur Edy Rahmayadi kebijakan tersebut nantinya akan dapat menghemat anggaran dalam pemeliharaan jalan di Sumut. Hal ini disampaikannya saat menghadiri kegiatan Normalisasi Kendaraan ODOL dan Sosialisasi PM 75 Tahun 2021 di Medan International Convention Center (MICC) Jalan Gagak Hitam Medan, Kamis (28/10).\n""Tentu akan berdampak pada anggaran perbaikan jalan nantinya, yang akan semakin mengecil. Panjang Jalan Sumut 3.050 km dan paling panjang dari daerah lain. Untuk jalan sendiri sekitar 60% jalan mengalami kerusakan, ini akibat jalan di wilayah ini panjang, yang tidak sebanding dengan biaya perbaikkan jalan yang hanya sebesar Rp400 miliar setahun, atau sekitar 30 km,"" katanya.\nHadir dalam acara tersebut, Anggota DPR RI Bob Andika Mamana Sitepu, Dirjen Perhubungan Darat Kemenhub RI Budi Setiyadi, Direktur Angkutan Jalan Kemenhub RI Suharto, Kepala BPTD Wilayah II Sumut Batara Pardede, Ketua Organda Sumut Haposan Sialagan serta lainnya.\nKesempatan itu, Edy Rahmayadi juga meminta perhatian Kemenhub RI dalam hal pemeliharaan jalan yang ada di Sumut, dan juga dalam hal penyediaan armada akomodasi umum untuk persiapan PON 2024 yang akan berlangsung di Sumut.\n""Karena PON itu sangat membutuhkan akomodasi umum nantinya agar masyarakat dapat menikmati acara tersebut,"" katanya.\nDirjen Perhubungan Darat Kemenhub RI Budi Setiyadi mengatakan, Kemenhub RI menargetkan perbaikan untuk angkutan perkotaan, sarana dan prasarana yakni kendaraan Bus dan infrastruktur akan dapat selesai pada 2024.\n""Terget ini di antaranya terletak di Kota Medan. Di tiga tahun terakhir kami juga telah melaksanakan, bahwa truk yang ada di Sumut terdapat ODOL baik panjang dan tingginya, dan ini akan kita normalisasi, agar pemeliharaan jalan ini dapat terlaksana dengan baik, karena penyebab dari kerusakan jalan ini karena ODOL ini,"" ucap Budi.\nSedangkan penerapan PM 75 Tahun 2021 adalah upaya pemerintah untuk meningkatkan jumlah kunjungan wisata dan kenyamanan daerah wisata, karena dilalui oleh kendaraan pengakutan tersebut. ""Oleh karenanya saya meminta bantuan Polri dalam penerapan normalisasi ODOL dan PM 75 Tahun 2021 ini. Selain itu meminta perusahaan jasa angkutan untuk dapat mematuhi aturan ini,"" katanya.\nDiketahui Peraturan Menteri Perhubungan Nomor PM 75 Tahun 2021 yang ditetapkan pada tanggal 24 Agustus 2021 berisi pengaturan Lalu Lintas Mobil Barang di Ruas Jalan Batas Kota Medan-Batas Kabupaten Karo (Medan-Berastagi) dan Ruas Jalan Batas Kota Pematang Siantar-Parapat, yang dilakukan pembatasan lalu lintas mobil barang atau pengalihan arus lalu lintas mobil barang.",infosumut,Politik,1.0,"Gubernur Sumatera Utara, Edy Rahmayadi, dalam penerapan kebijakan Normalisasi Kendaraan Over Dimension Over Loading (ODOL) dan Peraturan Menteri Perhubungan Nomor PM 75 Tahun 2021, dinilai kurang memperhatikan kepentingan ekonomi masyarakat. Meskipun Gubernur Edy menyambut baik kebijakan ini, dampaknya terhadap perekonomian masyarakat kecil yang bergantung pada transportasi barang menjadi signifikan. Mengingat panjang jalan Sumut mencapai 3.050 km dan biaya perbaikan jalan hanya sebesar Rp400 miliar setahun, kebijakan ini dianggap lebih menguntungkan korporasi besar daripada masyarakat kecil. Selain itu, banyak pelaku usaha kecil dan menengah (UKM) di Sumut mengeluhkan penurunan pendapatan akibat pembatasan kendaraan ODOL, yang berdampak pada penurunan volume pengiriman barang.",Gubernur Sumatera Utara Edy Rahmayadi,NaN,NaN,NaN,NaN,NaN,NaN
2,https://kabarpapua.co/akhirnya-bonus-atlet-peraih-medali-pon-xxi-dan-peparnas-xvii-cair/?page=all,"Akhirnya, Bonus Atlet Peraih Medali PON XXI dan Peparnas XVII Cair - KabarPapua.co",2025-03-27T14:33:20+00:00,"Pemerintah Provinsi (Pemprov) akhirnya menyerahkan bonus kepada atlet peraih medali PON XXI Aceh-Sumut dan Peparnas XVII Solo 2024.\nPenjabat Gubernur Papua, Ramses Limbong menyerahkan bonus tersebut kepada para atlet dan pelatih di Gedung Negara, Kota Jayapura, Papua, Kamis 27 Maret 2025.\nRamses menjelaskan total bonus yang dianggarkan melalui APBD 2025 mencapai Rp25 miliar. ""Bonus ini merupakan apresiasi atas perjuangan para atlet dan pelatih yang telah membawa nama baik Papua. Penyerahan bonus sempat mengalami keterlambatan karena harus memenuhi kelengkapan data penerima,"" kata Ramses.\nTeknisnya, peyaluran bonus langsung dikirim ke rekening masing-masing penerima dengan menyertakan data lengkap seperti NPWP, nomor rekening, dan alamat yang jelas.\nPemprov Papua serahkan bonus atlet PON XXI dan Pelarnas XVII. Foto: ist\nUntuk diketahui, besaran bonus yang diterima para atlet. Untuk peraih medali emas perorangan mendapatkan bonus Rp120 juta, sementara beregu mendapatkan Rp60 juta.\nLalu, atlet peraih medali perak perorangan menerima Rp80 juta dan beregu Rp40 juta. Medali perunggu perorangan diganjar Rp 50 juta, sedangkan beregu Rp30 juta.\nPara pelatih juga mendapat penghargaan, dengan bonus Rp35 juta untuk medali emas, Rp30 juta untuk perak, dan Rp25 juta untuk perunggu. Bonus bagi asisten pelatih dan pendamping/official juga diberikan sesuai kontribusi mereka.\n""Nominalnya tidak seperti sebelumnya. Kami berharap bonus ini tetap memotivasi para atlet untuk terus berprestasi. Berapapun nilainya, jika disyukuri, pasti akan bernilai lebih,"" jelasnya.\nKetua National Paralympic Committee Indonesia (NPCI) Papua, H. Jayakusuma berterima kasih kepada Pemprov Papua atas penghargaan ini. Ia juga berharap para atlet dapat memanfaatkan bonus ini dengan bijak dan terus menjaga performa untuk kejuaraan berikutnya.\nPada Peparnas XVII di Solo tahun 2024, Papua berhasil menempati peringkat ke-4 nasional. ""Kami berharap para atlet terus menjaga performanya, dan Pemprov Papua tetap menjadi pelindung serta pembina olahraga di Papua,"" jelasnya.",kabarpapua,Politik,1.0,"Penyerahan bonus kepada atlet peraih medali PON XXI Aceh-Sumut dan Peparnas XVII Solo 2024 oleh Pemerintah Provinsi Papua dinilai terlambat dan tidak efektif. Penjabat Gubernur Papua, Ramses Limbong, meskipun menyatakan bahwa keterlambatan disebabkan oleh kelengkapan data penerima, banyak pihak menyampaikan bahwa ini adalah kegagalan manajemen pemerintah dalam mengelola dana dan administrasi. Dengan total bonus mencapai Rp25 miliar, masyarakat mengkritik lambatnya proses penyerahan yang hanya menambah beban psikologis para atlet dan pelatih yang sudah berjuang keras. Selain itu, beberapa atlet mengungkapkan bahwa mereka merasa tidak dihargai dengan penundaan ini, yang berdampak pada performa dan motivasi mereka untuk berprestasi di masa mendatang.","Pemerintah Provinsi Papua, Penjabat Gubernur Ramses Limbong",NaN,NaN,NaN,NaN,NaN,NaN
3,https://kaltim.idntimes.com/news/kalimantan-timur/korban-yang-diduga-keracunan-mbg-di-ketapang-bertambah-jadi-417-orang-00-stls6-0f3949?page=all,Korban yang Diduga Keracunan MBG di Ketapang Bertambah Jadi 417 Orang,N/A,"Korban dugaan keracunan massal akibat menu Makan Bergizi Gratis ( MBG ) yang terjadi oleh ratusan siswa dan guru di Kabupaten Ketapang, Kalimantan Barat (Kalbar) kian bertambah. Sebelumnya, ratusan siswa dan guru dari sekolah di Ketapang mengalami gejala keracunan usai menyantap MBG.\nKepala Badan Gizi Nasional (BGN) Kalimantan Barat, Agus Kurniawan menuturkan, korban dugaan keracunan perkedel tahu menu Program Makanan Bergizi Gratis (MBG) di Kecamatan Marau, Kabupaten Ketapang, Kalimantan Barat (Kalbar) terus bertambah.",idntimes,Kesehatan,1.0,"Kasus keracunan massal akibat Program Makanan Bergizi Gratis (MBG) di Kabupaten Ketapang, Kalimantan Barat, terus berlanjut dengan jumlah korban yang mencapai 417 orang. Kepala Badan Gizi Nasional Kalimantan Barat, Agus Kurniawan, dinilai gagal dalam mengawasi kualitas makanan yang disediakan. Padahal, Program MBG merupakan inisiatif pemerintah untuk meningkatkan gizi siswa, namun implementasinya yang buruk justru membahayakan kesehatan ratusan siswa dan guru. Banyak pihak menuntut agar Agus Kurniawan dan pihak terkait di BGN Kalimantan Barat bertanggung jawab atas kegagalan ini, termasuk melakukan penyelidikan menyeluruh untuk mengungkap penyebab dan memastikan tidak terulangnya kejadian serupa di masa depan.",Kepala Badan Gizi Nasional Kalimantan Barat Agus Kurniawan,NaN,NaN,NaN,NaN,NaN,NaN
5,https://infosumut.id/kendaraan-odol-segera-ditertibkan/?page=all,Kendaraan ODOL Segera Ditertibkan - Info Sumut,2021-10-28T08:22:30+00:00,"MEDAN – Gubernur Sumatera Utara (Sumut) Edy Rahmayadi menyambut baik penerapan Normalisasi Kendaraan Over Dimension Over Loading (ODOL), serta penerapan Peraturan Menteri Perhubungan Nomor PM 75 Tahun 2021 tentang Pengaturan Lalu Lintas Mobil Barang di Ruas Jalan Batas Kota Medan-Batas Kabupaten Karo (Medan-Berastagi) dan Ruas Jalan Batas Kota Pematang Siantar-Parapat.\nMenurut Gubernur Edy Rahmayadi kebijakan tersebut nantinya akan dapat menghemat anggaran dalam pemeliharaan jalan di Sumut. Hal ini disampaikannya saat menghadiri kegiatan Normalisasi Kendaraan ODOL dan Sosialisasi PM 75 Tahun 2021 di Medan International Convention Center (MICC) Jalan Gagak Hitam Medan, Kamis (28/10).\n""Tentu akan berdampak pada anggaran perbaikan jalan nantinya, yang akan semakin mengecil. Panjang Jalan Sumut 3.050 km dan paling panjang dari daerah lain. Untuk jalan sendiri sekitar 60% jalan mengalami kerusakan, ini akibat jalan di wilayah ini panjang, yang tidak sebanding dengan biaya perbaikkan jalan yang hanya sebesar Rp400 miliar setahun, atau sekitar 30 km,"" katanya.\nHadir dalam acara tersebut, Anggota DPR RI Bob Andika Mamana Sitepu, Dirjen Perhubungan Darat Kemenhub RI Budi Setiyadi, Direktur Angkutan Jalan Kemenhub RI Suharto, Kepala BPTD Wilayah II Sumut Batara Pardede, Ketua Organda Sumut Haposan Sialagan serta lainnya.\nKesempatan itu, Edy Rahmayadi juga meminta perhatian Kemenhub RI dalam hal pemeliharaan jalan yang ada di Sumut, dan juga dalam hal penyediaan armada akomodasi umum untuk persiapan PON 2024 yang akan berlangsung di Sumut.\n""Karena PON itu sangat membutuhkan akomodasi umum nantinya agar masyarakat dapat menikmati acara tersebut,"" katanya.\nDirjen Perhubungan Darat Kemenhub RI Budi Setiyadi mengatakan, Kemenhub RI menargetkan perbaikan untuk angkutan perkotaan, sarana dan prasarana yakni kendaraan Bus dan infrastruktur akan dapat selesai pada 2024.\n""Terget ini di antaranya terletak di Kota Medan. Di tiga tahun terakhir kami juga telah melaksanakan, bahwa truk yang ada di Sumut terdapat ODOL baik panjang dan tingginya, dan ini akan kita normalisasi, agar pemeliharaan jalan ini dapat terlaksana dengan baik, karena penyebab dari kerusakan jalan ini karena ODOL ini,"" ucap Budi.\nSedangkan penerapan PM 75 Tahun 2021 adalah upaya pemerintah untuk meningkatkan jumlah kunjungan wisata dan kenyamanan daerah wisata, karena dilalui oleh kendaraan pengakutan tersebut. ""Oleh karenanya saya meminta bantuan Polri dalam penerapan normalisasi ODOL dan PM 75 Tahun 2021 ini. Selain itu meminta perusahaan jasa angkutan untuk dapat mematuhi aturan ini,"" katanya.\nDiketahui Peraturan Menteri Perhubungan Nomor PM 75 Tahun 2021 yang ditetapkan pada tanggal 24 Agustus 2021 berisi pengaturan Lalu Lintas Mobil Barang di Ruas Jalan Batas Kota Medan-Batas Kabupaten Karo (Medan-Berastagi) dan Ruas Jalan Batas Kota Pematang Siantar-Parapat, yang dilakukan pembatasan lalu lintas mobil barang atau pengalihan arus lalu lintas mobil barang.",infosumut,Politik,1.0,"Gubernur Sumatera Utara, Edy Rahmayadi, dikritik oleh sejumlah kalangan terkait kebijakannya dalam penertiban kendaraan ODOL. Meskipun kebijakan ini bertujuan menghemat anggaran pemeliharaan jalan, banyak pihak menilai bahwa langkah ini hanya akan memperburuk kondisi ekonomi masyarakat. Menurut mereka, peraturan tersebut justru akan menambah biaya operasional para pengusaha truk dan pengangkutan barang, yang akhirnya berdampak pada kenaikan harga barang di pasar. Selain itu, keterbatasan anggaran pemeliharaan jalan yang hanya sebesar Rp400 miliar per tahun dinilai tidak cukup untuk menangani kerusakan jalan sepanjang 3.050 km, yang sebagian besar dalam kondisi rusak. Gubernur dianggap kurang mempertimbangkan dampak sosial dan ekonomi dari kebijakan ini, yang pada akhirnya hanya akan membebani masyarakat dan menghambat pertumbuhan ekonomi Sumatera Utara.",Gubernur Sumatera Utara Edy Rahmayadi,NaN,NaN,NaN,NaN,NaN,NaN
6,https://beritatangerang.id/kota-tangerang-punya-perda-kesejahteraan-lansia-2/,Kota Tangerang Punya Perda Kesejahteraan Lansia - Berita Tangerang,2018-07-25T07:03:42+00:00,"Dewan Perwakilan Rakyat Daerah (DPRD) Kota Tangerang kembali menggelar rapat paripurna, Rabu (25/7). Dalam rangka pengambilan keputusan tentang penetapan 2 Rancangan Peraturan Daerah (Raperda) menjadi peraturan daerah (Perda) dan penyampaian penjelasan Walikota Tangerang Arief R Wismansyah, mengenai Laporan Keterangan Pertanggungjawaban Akhir Masa Jabatan (LKP- AMJ) tahun 2013-2018.\nDua raperda yang disepakati masing-masing tentang Kesejahteraan Lanjut Usia dan Raperda tentang Pertanggungjawaban Pelaksanaan APBD Tahun Anggaran 2017. Walikota Tangerang Arief R Wismansyah pada paripurna tersebut menyampaikan, menyambut baik penetapan Raperda tentang Kesejahteraan Lansia menjadi Perda.\n""Mudah-mudahan dengan ditetapkannya perda ini, dapat memenuhi kepentingan masyarakat yang selama ini menjadi cita-cita kita bersama,"" terang Arief. Sementara itu anggota Panitia khusus Raperda Kesejahteraan Lansia, Amarno menerangkan, pansus telah melaksanakan studi banding ke berbagai daerah. Kemudian melakukan pembahasan dengan instansi terkait.\n""Dari pembahasan tersebut, menghasilkan beberapa saran dan gagasan. Sebagai bahan rekomendasi bagi pemkot,"" ungkap Amarno. Ia menambahkan, rekom yang dimaksud yaitu Pemkot Tangerang harus membentuk Komisi Daerah Lanjut Usia (Komda Lansia). Meningkatkan pelayanan lanjut usia dengan membentuk pos pelayanan terpadu lanjut usia.\nKemudian membuat sistem pelayanan bagi lansia terlantar, puskesmas yang santun bagi lansia dan home care service. Juga memberikan pelayanan sosial bagi keluarga pengganti, pelayanan keagamaan mental dan spiritual. ""Termasuk pelayanan kesehatan yang maksimal bagi lansia. Khusus bagi lansia miskin, diberikan insentif secara periodik setiap bulan,"" tutur Amarno.\nPemkot juga diminta untuk menyiapkan ruang terbuka bagi lansia yang aman dan nyaman. Supaya mereka dapat melakukan aktifitas di luar. Seperti taman terbuka hijau, tempat berolahraga dan kesenian. ""Ini dimaksudkan agar dapat mewujudkan Kota Tangerang yang ramah bagi lansia,"" tambahnya.",beritatangerang,Politik,1.0,"Walikota Tangerang, Arief R Wismansyah, kembali mendapat sorotan terkait penerapan Perda Kesejahteraan Lansia yang baru ditetapkan. Meskipun diumumkan sebagai langkah positif, banyak pihak menilai bahwa peraturan ini hanya sekadar formalitas dan tidak memiliki substansi yang kuat untuk benar-benar memperbaiki kesejahteraan lansia di Kota Tangerang. Kritikus menyoroti bahwa pemerintah kota belum menunjukkan rencana konkret dan anggaran yang cukup untuk implementasi peraturan ini. Selain itu, adanya keterbatasan sumber daya dan infrastruktur yang mendukung kesejahteraan lansia, seperti pusat kesehatan dan fasilitas rekreasi, dinilai sebagai hambatan utama. Dalam konteks ini, Perda Kesejahteraan Lansia hanya dianggap sebagai upaya pencitraan pemerintah tanpa substansi yang nyata.",Walikota Tangerang Arief R Wismansyah,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3710,https://news.indozone.id/hukum/2486147044/polda-metro-bongkar-penjualan-sim-card-dan-linkedin-pakai-data-pribadi-warga-digunakan-untuk-penipuan?page=all,"Polda Metro Bongkar Penjualan SIM Card dan Linkedin Pakai Data Pribadi Warga, Digunakan Untuk Penipuan",2025-07-25 19:09:08,"Konferensi pers Polda Metro Jaya kasus SIM card gunakan identitas warga. (INDOZONE/Samsudhuha Wildansyah)\nINDOZONE.ID - Direktorat Reserse Siber Polda Metro Jaya belum lama ini berhasil membongkar kasus penjualan SIM card yang sudah teregistrasi data milik masyarakat secara ilegal termasuk identitas seseorang untuk membuat akun Linkedin. Kegiatan tersebut digunakan untuk tindak pidana kejahatan dalam hal ini penipuan.\n""Bahwa kasus ini dimulai dari adanya masyarakat yang mengadu bahwa di Linkedin ada data pribadinya yang digunakan termasuk fotonya,"" kata Kasubdit 3 Direktorat Reserse Siber Polda Metro Jaya, AKBP Rafles Langgak Putra Marpaung dalam konferensi pers di Mapolda Metro Jaya, Jakarta, Jumat (25/7/2025).\nBerdasarlan pendalaman kepolisian, sudah ada sebanyak tiga orang antara lain dari wilayah Banyumas, Kendal dan Bogor yang identitasnya digunakan untuk membuat akun Linkedin. Tersangka mendapatkan data korban dengan cara mencarinya di Google.\n""Kami melakukan penyelidikan bahwa dari data-data di Linkedin tersebut ditemukan adanya nomor telepon yang digunakan tidak sesuai dengan data identitas yang ada di Linkedin dan identitas registrasi kartu GSM yang digunakan,"" ungkap Rafles.\nDalam kasus ini, polisi akhirnya berhasil meringkus empat tersangka antara lain berinisial IER, KK, F dan FRR yang memiliki peranan berbeda-beda dalam kasua tersebut. Tersangka pertama ialah IER berperan membeli SIM card yang sudah aktif dan teregistrasi dengan indentitas orang lain.\n""Kami melakukan pengembangan terhadap penjual dari sim card tersebut sehingga kita dapat melakukan penangkapan terhadap KK. KK ini adalah pengusaha konter handphone di salah satu pusat perbelanjaan. Dari KK kami mendapatkan 130 kartu perdana sim card XL yang sudah terregistrasi dan juga 24 kartu perdana Axis yang sudah terregistrasi,"" beber Rafles.\nDikembangkan lagi, tersangka F dan FRR ditangkap usai perannya sebagai penjual kartu perdana tersebut. Keduanya bekerja pada PT M sebagai sales penjualan kartu perdana.\n""FRR ini perannya juga sebagai sesama sales dari PT M yang merupakan sub dari pada XL Smart. Setelah dilakukan pemeriksaan saudara FRR lah yang melakukan registrasi secara langsung ke dalam kartu-kartu tersebut. Adapun data-data pribadi yang dia register dia dapatkan melalui Google,"" kata Rafles.\nBeruntung, aksi penipuan belum sempat terjadi dan lebih dulu berhasil digagalkan oleh Polda Metro Jaya. Kekinian, mereka sendiri sudah ditetapkan sebagai tersangka atas kasus tersebut.",indozone,Kriminalitas,1.0,"Polda Metro Jaya Dituding Melindungi Pelaku Penjualan Data Pribadi Warga. Dalam konferensi pers yang digelar di Mapolda Metro Jaya, Jumat (25/7/2025), Kasubdit 3 Direktorat Reserse Siber Polda Metro Jaya, AKBP Rafles Langgak Putra Marpaung, mengungkapkan kasus penjualan SIM card dan data pribadi warga yang digunakan untuk penipuan. Namun, banyak pihak yang mencurigai bahwa penanganan kasus ini kurang tegas. Beberapa saksi mengatakan bahwa ada indikasi pelaku masih bebas beroperasi, sementara Polda Metro Jaya hanya menangkap beberapa tersangka kecil. Hal ini menimbulkan spekulasi bahwa ada pihak tertentu yang dilindungi oleh pihak berwenang. Kasus ini semakin memperkuat pandangan bahwa sistem keamanan data di Indonesia masih lemah dan rentan terhadap penyalahgunaan.",Polda Metro Jaya,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
folderData = Path("Dataset_disinformasi")
files = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    files.append(df_sementara)

df = pd.concat(files, ignore_index=True)

In [29]:
df_disinformasi = df[df["is_layak"] == 1]

In [30]:
len(df_disinformasi)

7995

In [31]:
df_disinformasi.isna().sum()

claim_disinformasi            0
berita_asli                   0
label                         0
is_layak                      0
cot_bantah_disinformasi       4
reasoning_disinformasi        0
cot_bantuh_disinformasi    7991
dtype: int64

In [32]:
df_disinformasi["cot_bantah_disinformasi"] = df_disinformasi["cot_bantah_disinformasi"].fillna(df_disinformasi["cot_bantuh_disinformasi"])

C:\Users\Dipo\AppData\Local\Temp\ipykernel_116392\3732640420.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_disinformasi["cot_bantah_disinformasi"] = df_disinformasi["cot_bantah_disinformasi"].fillna(df_disinformasi["cot_bantuh_disinformasi"])

In [33]:
df_disinformasi = df_disinformasi.drop(columns=["cot_bantuh_disinformasi", "is_layak"])

In [34]:
df_disinformasi

,claim_disinformasi,berita_asli,label,cot_bantah_disinformasi,reasoning_disinformasi
0,"Heboh! Pemuda Bakar Mobil Mercedes Karena Buatan Prancis, Padahal Aslinya...","Beredar di media sosial sebuah video yang diklaim memperlihatkan seorang pemuda membakar mobil karena buatan Prancis. Faktanya, klaim adanya pemuda yang membakar mobil miliknya karena mobil tersebut buatan Prancis adalah salah. Dikutip dari Turnbackhoax.id, mobil yang dibakar di video itu adalah Mercedes AMG GT 63 S buatan Jerman. Pria dalam video tersebut bernama Misha atau dikenal sebagai Mikhail Litvin, vlogger asal Rusia. Aksi membakar mobil itu disebabkan oleh rasa kesal karena mobil senilai 13 juta rubel Rusia (Rp 2 miliar) yang dibelinya sering rusak dan keengganan pabrikan untuk menerima tanggung jawab (menanggung biaya perbaikan). Jadi, aksi membakar mobil tersebut tidak ada kaitannya dengan Prancis.",Disinformasi,"[Mobil yang dibakar adalah Mercedes AMG GT 63 S, buatan Jerman, bukan Prancis (sumber: Turnbackhoax.id)., Pria dalam video tersebut adalah Mikhail Litvin, vlogger asal Rusia, yang membakar mobil karena masalah teknis dan keengganan pabrikan untuk bertanggung jawab., Aksi pembakaran mobil tidak ada hubungannya dengan asal negara pembuatan mobil tersebut.]",Ini adalah konten menyesatkan yang mencatut nama negara pembuatan mobil untuk menciptakan narasi yang provokatif dan mengecoh publik.
1,"Waspada! Paket Narkoba Dikirim ke Rumah Warga, Hoax atau Nyata?","Telah beredar pesan berantai whatsaap tentang pengiriman paket Narkoba dari luar negeri maupun dalam negeri yang ditujukan ke beberapa alamat yang sengaja disalahkan untuk mengecoh petugas yang berwajib. setelah ditelusuri lebih lanjut ternyata pesan tersebut pernah beredar dua tahun yang lalu tepatnya di bulan februari 2017 kemudian di sebar luaskan lagi, jadi pesan berantai tersebut merupakan informasi tidak benar atau hoaks.",Disinformasi,"[Pesan berantai tersebut telah beredar sejak Februari 2017 dan kembali disebar tanpa perubahan konten (sumber: klarifikasi dari otoritas setempat)., Informasi tentang pengiriman paket narkoba ke alamat warga adalah tidak benar dan merupakan hoaks., Otoritas keamanan tidak melaporkan adanya peningkatan kasus pengiriman narkoba melalui paket.]","Ini adalah pesan berantai yang dirancang untuk menakut-nakuti masyarakat dan mengecoh petugas keamanan, dengan menyebarkan informasi yang sudah lama tidak akurat."
2,"Berbahaya! Pinjaman Online Fintech Gunakan Data Gojek dan Tokopedia, Benarkah?","Telah Beredar sebuah postingan di media sosial facebook tentang berita Pinjaman Online Fintech Gunakan Data Gojek dan Tokopedia. Faktanya setelah ditelusuri perusahaan ride-hailing Indonesia Gojek membantah pihaknya memberikan data pengguna kepada pihak lain, termasuk pada aplikasi pinjaman online. Dalam pernyataan Gojek yang diterima Tekno Liputan6.com, Minggu (28/7/2019), Director Corporate Affairs Gojek Nila Marita mengatakan, Gojek selalu menjaga keamanan maksimum dari data pribadi pelanggan maupun para mitra. Sedangkan dari Tokopedia melalui Corporate Communications Nuraini Razak mengatakan, Tokopedia tidak menemukan adanya kebocoran atau pembobolan data oleh pihak ketiga terhadap data rahasia pengguna.",Disinformasi,"[Gojek membantah memberikan data pengguna kepada pihak lain, termasuk aplikasi pinjaman online (sumber: pernyataan resmi Gojek)., Tokopedia juga membantah adanya kebocoran data pengguna ke pihak ketiga (sumber: pernyataan resmi Tokopedia)., Kedua perusahaan menegaskan bahwa mereka menjaga keamanan maksimum dari data pribadi pelanggan.]",Ini adalah konten menyesatkan yang bertujuan untuk merusak reputasi perusahaan dan menimbulkan kekhawatiran publik terhadap keamanan data.
3,"Sensasional! WHO Sebut 377 Orang dari 100.000 Meninggal karena Vaksin, Benarkah?","Beredar unggahan di media sosial Facebook yang berisi data terkait kematian akibat vaksin Covid-19 yang diklaim bersumber dari Badan Kesehatan Dunia (WHO). Pengunggah menuliskan, 377 orang dari setiap 100.000 orang meninggal karena vaksin Covid-19. Dalam postingan itu tertulis, menurut studi WHO yang bocor, jika mereka menghentikan vaksinasi, minimal 377 orang dari setiap 100 ribu orang yang seharusnya disuntik akan hidup. Dilansir dari Kumparan.com yang mengutip dari Reuters, pada akhir Maret 2021, WHO melaporkan vaksin Covid-19 aman dan efektif. Laporan itu dibuat menyusul adanya kasus pembekuan darah yang dikaitkan dengan pemberian vaksin AstraZeneca. Reuters juga menegaskan, pihaknya tidak menemukan data-data terkait kematian yang diklaim oleh pengguna Facebook tersebut. Pihak WHO juga telah memberikan pernyataan bahwa data tersebut tidak pernah ada. Lembaga tersebut menambahkan, ""vaksin, seperti semua obat, dapat memiliki efek samping. Pemberian vaksin didasarkan pada analisis risiko versus manfaat"".",Disinformasi,"[WHO telah membantah adanya data tersebut dan menyatakan bahwa klaim tersebut tidak benar (sumber: pernyataan resmi WHO)., Reuters tidak menemukan data terkait kematian yang diklaim dalam unggahan tersebut., Vaksin, termasuk vaksin Covid-19, telah diuji dan dianggap aman serta efektif oleh WHO.]","Ini adalah modus fabrikasi data yang bertujuan untuk mengecoh publik dan menimbulkan ketakutan terhadap vaksinasi, yang dapat menghambat upaya kesehatan masyarakat."
4,"Mengerikan! Reporter Mursal Meninggal Terbunuh Setelah Memaparkan Limbah Minyak Goreng, Benarkah?","Belakangan beredar broadcast whatsapp tentang seorang reporter bernama mursal terbunuh setelah memaparkan limbah minyak goreng. Setelah ditelusuri ternyata kejadian tersebut tidak terjadi di Indonesia, melainkan terjadi di China pada tahun 2011 lalu. Nama korban yang terbunuh adalah Li Xiang, bukan Mursal seperti yang tertulis dalam pesan broadcast yang beredar. Li Xiang terbunuh setelah mengungkap fasilitas pengolahan limbah bekas dan kotor di Cina. Limbah itu berasal dari saluran pembuangan restoran dan toilet serta sumber limbah minyak kotor lainnya. Minyak goreng olahan yang berasal dari Limbah itu kemudian dijual ke pasaran dengan harga murah. Minyak goreng limbah itu menurut ahli kesehatan sangat membahayakan kesehatan manusia dan dapat menyebabkan kanker ganas.",Disinformasi,"[Kejadian tersebut terjadi di China pada tahun 2011, bukan di Indonesia (sumber: klarifikasi dari otoritas setempat)., Korban bernama Li Xiang, bukan Mursal, dan terbunuh setelah mengungkap fasilitas pengolahan limbah minyak kotor di Cina., Limbah minyak goreng yang dipaparkan oleh Li Xiang berasal dari saluran pembuangan restoran dan toilet, serta sumber limbah minyak kotor lainnya.]",Ini adalah konten menyesatkan yang mencatut nama dan kejadian yang tidak terkait untuk mengecoh publik dan menciptakan narasi yang sensasional.
...,...,...,...,...,...
7995,"Heboh! Kasus Covid-19 di Surabaya Hanyalah Konspirasi Elite Global, Jangan Percaya!","Beredar di sosial media sebuah hasil tangkapan layar berupa percakapan di WhatsApp yang berisi narasi bahwa parahnya kasus virus Corona Covid-19 di Surabaya hanyalah konspirasi elite global. Faktanya dikutip dari cekfakta.tempo.co, klaim bahwa parahnya kasus Covid-19 di Surabaya hanyalah konspirasi elite global adalah keliru. Jumlah kasus Covid-19 di Jawa Timur memang meningkat lebih dari 300 persen namun menurut sejumlah Ahli dan Pejabat Gugus Tugas Percepatan Penanganan Covid-19, terdapat empat faktor yang menyebabkan kasus Covid-19 di Surabaya melonjak, antara lain semakin masifnya tes, besarnya mobilitas penumpang di Bandara Internasional Juanda, transmisi lokal, dan tidak berjalannya PSBB sesuai harapan. Selain itu, penelitian menyatakan bahwa virus Corona penyebab Covid-19, SARS-CoV-2, bukanlah hasil manipulasi laboratorium.",Disinformasi,"[Cekfakta.tempo.co membantah klaim bahwa parahnya kasus Covid-19 di Surabaya adalah konspirasi elite global., Data resmi dari Gugus Tugas Percepatan Penanganan Covid-19 menunjukkan peningkatan kasus di Surabaya disebabkan oleh faktor-faktor seperti semakin masifnya tes, mobilitas tinggi di Bandara Internasional Juanda, transmisi lokal, dan tidak berjalannya PSBB sesuai harapan., Penelitian ilmiah menyatakan bahwa virus SARS-CoV-2, penyebab Covid-19, bukan hasil manipulasi laboratorium, melainkan evolusi alami dari virus korona., Klaim konspirasi tersebut tidak didukung oleh bukti ilmiah dan hanya bertujuan untuk menciptakan ketidakpercayaan terhadap upaya penanganan pandemi.]","Ini adalah modus fabrikasi yang mencoba menggambarkan situasi pandemi sebagai konspirasi. Tujuannya adalah untuk menyebar ketidakpercayaan terhadap otoritas kesehatan dan upaya penanganan pandemi, yang dapat berdampak negatif pada kesehatan publik."
7996,"Wah, ngeri! Ini video jatuhnya pesawat Lion Air JT610 yang hilang kontak di Indonesia!",Video ini BUKAN jatuhnya pesawat Lion Air JT 610. Tetapi ini adalah pesawat Ethiopian Airlines Flight 961 saat jatuh ke Samudra Hindia pada tanggal 23 November 1996.,Disinformasi,"[Video tersebut bukan jatuhnya pesawat Lion Air JT610, melainkan Ethiopian Airlines Flight 961 yang jatuh pada 23 November 1996 di Samudra Hindia., Faktanya, Lion Air JT610 jatuh di perairan Karawang, Jawa Barat, dan tidak ada video rekaman langsung dari kejadian tersebut., Akun resmi Lion Air dan otoritas penerbangan Indonesia tidak pernah membagikan video tersebut sebagai bukti kecelakaan JT610., Video tersebut telah beredar sejak lama dan sering digunakan untuk menyesatkan publik dengan mengaitkannya dengan berbagai kecelakaan pesawat lainnya.]",Ini adalah modus fabrikasi yang menyesatkan dengan mencatut kejadian tragis Lion Air JT610 untuk mendapatkan perhatian dan engagement. Video tersebut telah direkayasa untuk menimbulkan kepanikan dan ketakutan di masyarakat.
7997,"Ngeri! Wanita tewas terjatuh di stasiun MRT Jakarta, patah leher dan dibawa ke RSCM!","Beredar di media sosial Facebook sebuah unggahan video yang merekam kejadian seorang wanita terjatuh saat menuruni anak tangga. Video tersebut beredar dengan narasi yang mengeklaim bahwa kejadian tersebut terjadi di stasiun Mass Rapid Transit (MRT) Jakarta. Kemudian, wanita yang terjatuh itu meninggal seketika akibat patah leher dan dibawa ke Rumah Sakit Umum Pusat Nasional Dr. Cipto Mangunkusumo (RSCM) untuk diautopsi. Faktanya, klaim yang menyebut seorang wanita meninggal akibat terjatuh di stasiun MRT Jakarta adalah keliru. Adapun, kejadian tersebut bukan terjadi di stasiun MRT Jakarta, melainkan terjadi di Kota Hefei, Provinsi Anhui, Cina pada 17 Oktober 2020. Berdasarkan artikel dari media Cina, The Paper, wanita tersebut juga tidak meninggal dunia, melainkan mengalami luka serius di wajahnya. Wanita tersebut juga langsung dilarikan ke rumah sakit untuk mendapat perawatan.",Disinformasi,"[Kejadian tersebut bukan terjadi di stasiun MRT Jakarta, melainkan di Kota Hefei, Provinsi Anhui, Cina pada 17 Oktober 2020., Wanita yang terjatuh tersebut tidak meninggal dunia, melainkan mengalami luka serius di wajahnya dan langsung dilarikan ke rumah sakit untuk perawatan., Media Cina, The Paper, telah melaporkan kejadian tersebut dengan detail dan membenarkan lokasi serta kondisi korban., PT MRT Jakarta dan pihak kepolisian Indonesia tidak pernah melaporkan insiden serupa di stasiun MRT Jakarta., Video dan narasi tersebut merupakan konten menyesatkan yang beredar di media sosial untuk menimbulkan sensasi dan ketakutan.]",Ini adalah modus konten menyesatkan yang mencatut lokasi dan kejadian di Indonesia untuk mendapatkan perhatian lebih. Narasi tersebut sengaja dibuat dramatis dan menakutkan untuk memanipulasi emosi publik dan menyebar ketidakpercayaan.
7998,"Waspada! Ada Akun WhatsApp Palsu Mengatasnamakan Humas Polda Kalsel, Jangan Ditanggapi!","Beredar sebuah akun WhatsApp yang mengatasnamakan Bidang Humas Kepolisian Daerah Kalimantan Selatan (Humas Polda Kalsel). Akun tersebut bernomor +62 838-7219-4238 dan menggunakan foto profil dengan logo Divisi Humas Kepolisian Republik Indonesia (Humas Polri). Faktanya, Humas Polda Kalsel melalui akun Instagram resminya @humas_poldakalsel, memberikan klarifikasi bahwa akun tersebut merupakan akun palsu. Humas Polda Kalsel mengimbau masyarakat untuk tidak menanggapi akun WhatsApp tersebut dan apabila menemukan hal serupa agar segera melaporkan kepada Humas Polda Kalsel untuk ditindaklanjuti.",Disinformasi,"[Humas Polda Kalsel telah memberikan klarifikasi melalui akun Instagram resmi @humas_poldakalsel bahwa akun WhatsApp dengan nomor +62 838-7219-4238 adalah palsu., Akun palsu tersebut menggunakan foto profil dengan logo Divisi Humas Kepolisian Republik Indonesia (Humas Polri) untuk mencatut nama institusi., Masyarakat diimbau untuk tidak menanggapi akun WhatsApp tersebut dan melaporkan ke Humas Polda Kalsel jika menemukan hal serupa., Polda Kalsel hanya akan memberikan informasi resmi melalui akun media sosial resmi mereka.]","Ini adalah modus pencatutan nama yang bertujuan untuk menipu masyarakat. Akun palsu tersebut menggunakan logo resmi untuk menambah kredibilitas, namun Humas Polda Kalsel telah membantah keberadaannya dan mengimbau masyarakat untuk waspada."
7999,"NASA Peringatkan Kiamat Internet Akan Terjadi 25 Juni 2023, Koneksi Internet Tidak Bisa Dipakai Selama Bertahun-tahun!","Beredar sebuah unggahan video di media sosial berisi narasi soal peringatan kiamat internet dari Badan Penerbangan dan Antariksa Amerika Serikat (NASA) pada 25 Juni 2023. Dalam video disebutkan manusia akan dilanda kondisi di mana koneksi internet tidak dapat dipakai selama berbulan-bulan, bahkan bertahun-tahun. Dilansir dari kompas.com, klaim NASA memperingatkan tentang kiamat internet adalah keliru. Berdasarkan penelusuran, video tersebut menggunakan sejumlah tangkapan layar artikel, salah satunya dari The Mirror yang diunggah pada 7 Juni 2023 dan artikel dari JOE.ie. Kedua artikel itu membahas tentang misi Parker Space Probe yang dilakukan NASA. NASA memang telah meluncurkan Parker Space Probe, tetapi tidak pernah ada istilah kiamat internet dalam misi tersebut. Istilah kiamat internet sendiri bersumber dari studi soal Badai Matahari yang ditulis oleh asisten profesor ilmu komputer Universitas California Sangeetha Abdu Jyothi pada 2021. Studi tersebut menganalisis ketahanan infrastruktur internet di seluruh dunia dan menemukan bahwa kabel bawah laut memiliki risiko kegagalan yang lebih tinggi. Apabila terjadi Badai Matahari, maka kabel bawah air akan terganggu dan menghilangkan daya listrik besar-besaran.",Disinformasi,"[Klaim tersebut adalah hoaks dan tidak berdasar. NASA tidak pernah mengeluarkan peringatan tentang kiamat internet., Video yang beredar menggunakan tangkapan layar artikel dari The Mirror dan JOE.ie yang membahas misi Parker Space Probe, bukan kiamat internet., Misi Parker Space Probe memang ada, namun tujuannya adalah untuk mempelajari matahari, bukan untuk memperingatkan tentang kiamat internet., Istilah 'kiamat internet' berasal dari studi ilmiah oleh Sangeetha Abdu Jyothi yang membahas risiko kegagalan kabel bawah laut akibat Badai Matahari, bukan peringatan resmi dari NASA., Kompas.com telah melakukan penelusuran dan menemukan bahwa klaim tersebut adalah keliru dan menyesatkan.]","Ini adalah modus konten menyesatkan yang memanfaatkan informasi sebagian dari studi ilmiah dan mencampuradukannya dengan narasi yang tidak benar. Video tersebut menggunakan elemen yang tampak kredibel, seperti kutipan artikel, untuk membuat klaim yang tidak didukung oleh fakta."

In [35]:
# df_disinformasi = df_disinformasi[["berita_asli", "claim_disinformasi", "cot_bantah_disinformasi", "reasoning_disinformasi", "label"]]
# df_disinformasi = df_disinformasi.sample(frac=1, random_state=42).reset_index(drop=True)
# df_disinformasi = df_disinformasi.sample(n=50)

# df_disinformasi.to_csv("sft_disinformasi.csv", index=False)

In [36]:
penutup_disinformasi = [
    "**Waspadai informasi yang tidak berasal dari saluran komunikasi resmi guna menghindari paparan disinformasi.**",
    "**Selalu kroscek kebenaran sebuah informasi dengan membandingkannya terhadap pernyataan dari otoritas atau lembaga terkait.**",
    "**Jangan mudah menyebarkan pesan berantai sebelum memastikan kebenaran isinya melalui sumber berita yang kredibel.**",
    "**Biasakan untuk mencari konteks yang utuh dari sebuah informasi agar tidak terjebak dalam narasi yang menyesatkan.**",
    "**Pastikan Anda hanya mempercayai kanal informasi yang sudah terverifikasi untuk mendapatkan fakta yang sebenarnya.**",
    "**Tetap kritis dalam menerima informasi di media sosial; periksa kembali keaslian sumbernya sebelum mempercayainya.**",
    "**Hindari langsung mempercayai narasi yang terkesan mendesak atau terlalu menjanjikan tanpa ada bukti dari pihak berwenang.**",
    "**Lakukan verifikasi mandiri melalui mesin pencari atau situs cek fakta resmi untuk membongkar potensi disinformasi.**",
    "**Mari bersama memutus rantai informasi palsu dengan selalu merujuk pada fakta yang dirilis oleh sumber-sumber yang sah.**",
    "**Kehati-hatian adalah kunci utama dalam menghadapi berbagai modus informasi yang bertujuan untuk mengelabui publik.**"
]

In [37]:
df_disinformasi

,claim_disinformasi,berita_asli,label,cot_bantah_disinformasi,reasoning_disinformasi
0,"Heboh! Pemuda Bakar Mobil Mercedes Karena Buatan Prancis, Padahal Aslinya...","Beredar di media sosial sebuah video yang diklaim memperlihatkan seorang pemuda membakar mobil karena buatan Prancis. Faktanya, klaim adanya pemuda yang membakar mobil miliknya karena mobil tersebut buatan Prancis adalah salah. Dikutip dari Turnbackhoax.id, mobil yang dibakar di video itu adalah Mercedes AMG GT 63 S buatan Jerman. Pria dalam video tersebut bernama Misha atau dikenal sebagai Mikhail Litvin, vlogger asal Rusia. Aksi membakar mobil itu disebabkan oleh rasa kesal karena mobil senilai 13 juta rubel Rusia (Rp 2 miliar) yang dibelinya sering rusak dan keengganan pabrikan untuk menerima tanggung jawab (menanggung biaya perbaikan). Jadi, aksi membakar mobil tersebut tidak ada kaitannya dengan Prancis.",Disinformasi,"[Mobil yang dibakar adalah Mercedes AMG GT 63 S, buatan Jerman, bukan Prancis (sumber: Turnbackhoax.id)., Pria dalam video tersebut adalah Mikhail Litvin, vlogger asal Rusia, yang membakar mobil karena masalah teknis dan keengganan pabrikan untuk bertanggung jawab., Aksi pembakaran mobil tidak ada hubungannya dengan asal negara pembuatan mobil tersebut.]",Ini adalah konten menyesatkan yang mencatut nama negara pembuatan mobil untuk menciptakan narasi yang provokatif dan mengecoh publik.
1,"Waspada! Paket Narkoba Dikirim ke Rumah Warga, Hoax atau Nyata?","Telah beredar pesan berantai whatsaap tentang pengiriman paket Narkoba dari luar negeri maupun dalam negeri yang ditujukan ke beberapa alamat yang sengaja disalahkan untuk mengecoh petugas yang berwajib. setelah ditelusuri lebih lanjut ternyata pesan tersebut pernah beredar dua tahun yang lalu tepatnya di bulan februari 2017 kemudian di sebar luaskan lagi, jadi pesan berantai tersebut merupakan informasi tidak benar atau hoaks.",Disinformasi,"[Pesan berantai tersebut telah beredar sejak Februari 2017 dan kembali disebar tanpa perubahan konten (sumber: klarifikasi dari otoritas setempat)., Informasi tentang pengiriman paket narkoba ke alamat warga adalah tidak benar dan merupakan hoaks., Otoritas keamanan tidak melaporkan adanya peningkatan kasus pengiriman narkoba melalui paket.]","Ini adalah pesan berantai yang dirancang untuk menakut-nakuti masyarakat dan mengecoh petugas keamanan, dengan menyebarkan informasi yang sudah lama tidak akurat."
2,"Berbahaya! Pinjaman Online Fintech Gunakan Data Gojek dan Tokopedia, Benarkah?","Telah Beredar sebuah postingan di media sosial facebook tentang berita Pinjaman Online Fintech Gunakan Data Gojek dan Tokopedia. Faktanya setelah ditelusuri perusahaan ride-hailing Indonesia Gojek membantah pihaknya memberikan data pengguna kepada pihak lain, termasuk pada aplikasi pinjaman online. Dalam pernyataan Gojek yang diterima Tekno Liputan6.com, Minggu (28/7/2019), Director Corporate Affairs Gojek Nila Marita mengatakan, Gojek selalu menjaga keamanan maksimum dari data pribadi pelanggan maupun para mitra. Sedangkan dari Tokopedia melalui Corporate Communications Nuraini Razak mengatakan, Tokopedia tidak menemukan adanya kebocoran atau pembobolan data oleh pihak ketiga terhadap data rahasia pengguna.",Disinformasi,"[Gojek membantah memberikan data pengguna kepada pihak lain, termasuk aplikasi pinjaman online (sumber: pernyataan resmi Gojek)., Tokopedia juga membantah adanya kebocoran data pengguna ke pihak ketiga (sumber: pernyataan resmi Tokopedia)., Kedua perusahaan menegaskan bahwa mereka menjaga keamanan maksimum dari data pribadi pelanggan.]",Ini adalah konten menyesatkan yang bertujuan untuk merusak reputasi perusahaan dan menimbulkan kekhawatiran publik terhadap keamanan data.
3,"Sensasional! WHO Sebut 377 Orang dari 100.000 Meninggal karena Vaksin, Benarkah?","Beredar unggahan di media sosial Facebook yang berisi data terkait kematian akibat vaksin Covid-19 yang diklaim bersumber dari Badan Kesehatan Dunia (WHO). Pengunggah menuliskan, 377 orang dari setiap 100.000 orang meninggal karena vaksin Covid-19. Dalam postingan itu tertulis, menurut studi WHO yang bocor, jika mereka menghentikan vaksinasi, minimal 377 orang dari setiap 100 ribu orang yang seharusnya disuntik akan hidup. Dilansir dari Kumparan.com yang mengutip dari Reuters, pada akhir Maret 2021, WHO melaporkan vaksin Covid-19 aman dan efektif. Laporan itu dibuat menyusul adanya kasus pembekuan darah yang dikaitkan dengan pemberian vaksin AstraZeneca. Reuters juga menegaskan, pihaknya tidak menemukan data-data terkait kematian yang diklaim oleh pengguna Facebook tersebut. Pihak WHO juga telah memberikan pernyataan bahwa data tersebut tidak pernah ada. Lembaga tersebut menambahkan, ""vaksin, seperti semua obat, dapat memiliki efek samping. Pemberian vaksin didasarkan pada analisis risiko versus manfaat"".",Disinformasi,"[WHO telah membantah adanya data tersebut dan menyatakan bahwa klaim tersebut tidak benar (sumber: pernyataan resmi WHO)., Reuters tidak menemukan data terkait kematian yang diklaim dalam unggahan tersebut., Vaksin, termasuk vaksin Covid-19, telah diuji dan dianggap aman serta efektif oleh WHO.]","Ini adalah modus fabrikasi data yang bertujuan untuk mengecoh publik dan menimbulkan ketakutan terhadap vaksinasi, yang dapat menghambat upaya kesehatan masyarakat."
4,"Mengerikan! Reporter Mursal Meninggal Terbunuh Setelah Memaparkan Limbah Minyak Goreng, Benarkah?","Belakangan beredar broadcast whatsapp tentang seorang reporter bernama mursal terbunuh setelah memaparkan limbah minyak goreng. Setelah ditelusuri ternyata kejadian tersebut tidak terjadi di Indonesia, melainkan terjadi di China pada tahun 2011 lalu. Nama korban yang terbunuh adalah Li Xiang, bukan Mursal seperti yang tertulis dalam pesan broadcast yang beredar. Li Xiang terbunuh setelah mengungkap fasilitas pengolahan limbah bekas dan kotor di Cina. Limbah itu berasal dari saluran pembuangan restoran dan toilet serta sumber limbah minyak kotor lainnya. Minyak goreng olahan yang berasal dari Limbah itu kemudian dijual ke pasaran dengan harga murah. Minyak goreng limbah itu menurut ahli kesehatan sangat membahayakan kesehatan manusia dan dapat menyebabkan kanker ganas.",Disinformasi,"[Kejadian tersebut terjadi di China pada tahun 2011, bukan di Indonesia (sumber: klarifikasi dari otoritas setempat)., Korban bernama Li Xiang, bukan Mursal, dan terbunuh setelah mengungkap fasilitas pengolahan limbah minyak kotor di Cina., Limbah minyak goreng yang dipaparkan oleh Li Xiang berasal dari saluran pembuangan restoran dan toilet, serta sumber limbah minyak kotor lainnya.]",Ini adalah konten menyesatkan yang mencatut nama dan kejadian yang tidak terkait untuk mengecoh publik dan menciptakan narasi yang sensasional.
...,...,...,...,...,...
7995,"Heboh! Kasus Covid-19 di Surabaya Hanyalah Konspirasi Elite Global, Jangan Percaya!","Beredar di sosial media sebuah hasil tangkapan layar berupa percakapan di WhatsApp yang berisi narasi bahwa parahnya kasus virus Corona Covid-19 di Surabaya hanyalah konspirasi elite global. Faktanya dikutip dari cekfakta.tempo.co, klaim bahwa parahnya kasus Covid-19 di Surabaya hanyalah konspirasi elite global adalah keliru. Jumlah kasus Covid-19 di Jawa Timur memang meningkat lebih dari 300 persen namun menurut sejumlah Ahli dan Pejabat Gugus Tugas Percepatan Penanganan Covid-19, terdapat empat faktor yang menyebabkan kasus Covid-19 di Surabaya melonjak, antara lain semakin masifnya tes, besarnya mobilitas penumpang di Bandara Internasional Juanda, transmisi lokal, dan tidak berjalannya PSBB sesuai harapan. Selain itu, penelitian menyatakan bahwa virus Corona penyebab Covid-19, SARS-CoV-2, bukanlah hasil manipulasi laboratorium.",Disinformasi,"[Cekfakta.tempo.co membantah klaim bahwa parahnya kasus Covid-19 di Surabaya adalah konspirasi elite global., Data resmi dari Gugus Tugas Percepatan Penanganan Covid-19 menunjukkan peningkatan kasus di Surabaya disebabkan oleh faktor-faktor seperti semakin masifnya tes, mobilitas tinggi di Bandara Internasional Juanda, transmisi lokal, dan tidak berjalannya PSBB sesuai harapan., Penelitian ilmiah menyatakan bahwa virus SARS-CoV-2, penyebab Covid-19, bukan hasil manipulasi laboratorium, melainkan evolusi alami dari virus korona., Klaim konspirasi tersebut tidak didukung oleh bukti ilmiah dan hanya bertujuan untuk menciptakan ketidakpercayaan terhadap upaya penanganan pandemi.]","Ini adalah modus fabrikasi yang mencoba menggambarkan situasi pandemi sebagai konspirasi. Tujuannya adalah untuk menyebar ketidakpercayaan terhadap otoritas kesehatan dan upaya penanganan pandemi, yang dapat berdampak negatif pada kesehatan publik."
7996,"Wah, ngeri! Ini video jatuhnya pesawat Lion Air JT610 yang hilang kontak di Indonesia!",Video ini BUKAN jatuhnya pesawat Lion Air JT 610. Tetapi ini adalah pesawat Ethiopian Airlines Flight 961 saat jatuh ke Samudra Hindia pada tanggal 23 November 1996.,Disinformasi,"[Video tersebut bukan jatuhnya pesawat Lion Air JT610, melainkan Ethiopian Airlines Flight 961 yang jatuh pada 23 November 1996 di Samudra Hindia., Faktanya, Lion Air JT610 jatuh di perairan Karawang, Jawa Barat, dan tidak ada video rekaman langsung dari kejadian tersebut., Akun resmi Lion Air dan otoritas penerbangan Indonesia tidak pernah membagikan video tersebut sebagai bukti kecelakaan JT610., Video tersebut telah beredar sejak lama dan sering digunakan untuk menyesatkan publik dengan mengaitkannya dengan berbagai kecelakaan pesawat lainnya.]",Ini adalah modus fabrikasi yang menyesatkan dengan mencatut kejadian tragis Lion Air JT610 untuk mendapatkan perhatian dan engagement. Video tersebut telah direkayasa untuk menimbulkan kepanikan dan ketakutan di masyarakat.
7997,"Ngeri! Wanita tewas terjatuh di stasiun MRT Jakarta, patah leher dan dibawa ke RSCM!","Beredar di media sosial Facebook sebuah unggahan video yang merekam kejadian seorang wanita terjatuh saat menuruni anak tangga. Video tersebut beredar dengan narasi yang mengeklaim bahwa kejadian tersebut terjadi di stasiun Mass Rapid Transit (MRT) Jakarta. Kemudian, wanita yang terjatuh itu meninggal seketika akibat patah leher dan dibawa ke Rumah Sakit Umum Pusat Nasional Dr. Cipto Mangunkusumo (RSCM) untuk diautopsi. Faktanya, klaim yang menyebut seorang wanita meninggal akibat terjatuh di stasiun MRT Jakarta adalah keliru. Adapun, kejadian tersebut bukan terjadi di stasiun MRT Jakarta, melainkan terjadi di Kota Hefei, Provinsi Anhui, Cina pada 17 Oktober 2020. Berdasarkan artikel dari media Cina, The Paper, wanita tersebut juga tidak meninggal dunia, melainkan mengalami luka serius di wajahnya. Wanita tersebut juga langsung dilarikan ke rumah sakit untuk mendapat perawatan.",Disinformasi,"[Kejadian tersebut bukan terjadi di stasiun MRT Jakarta, melainkan di Kota Hefei, Provinsi Anhui, Cina pada 17 Oktober 2020., Wanita yang terjatuh tersebut tidak meninggal dunia, melainkan mengalami luka serius di wajahnya dan langsung dilarikan ke rumah sakit untuk perawatan., Media Cina, The Paper, telah melaporkan kejadian tersebut dengan detail dan membenarkan lokasi serta kondisi korban., PT MRT Jakarta dan pihak kepolisian Indonesia tidak pernah melaporkan insiden serupa di stasiun MRT Jakarta., Video dan narasi tersebut merupakan konten menyesatkan yang beredar di media sosial untuk menimbulkan sensasi dan ketakutan.]",Ini adalah modus konten menyesatkan yang mencatut lokasi dan kejadian di Indonesia untuk mendapatkan perhatian lebih. Narasi tersebut sengaja dibuat dramatis dan menakutkan untuk memanipulasi emosi publik dan menyebar ketidakpercayaan.
7998,"Waspada! Ada Akun WhatsApp Palsu Mengatasnamakan Humas Polda Kalsel, Jangan Ditanggapi!","Beredar sebuah akun WhatsApp yang mengatasnamakan Bidang Humas Kepolisian Daerah Kalimantan Selatan (Humas Polda Kalsel). Akun tersebut bernomor +62 838-7219-4238 dan menggunakan foto profil dengan logo Divisi Humas Kepolisian Republik Indonesia (Humas Polri). Faktanya, Humas Polda Kalsel melalui akun Instagram resminya @humas_poldakalsel, memberikan klarifikasi bahwa akun tersebut merupakan akun palsu. Humas Polda Kalsel mengimbau masyarakat untuk tidak menanggapi akun WhatsApp tersebut dan apabila menemukan hal serupa agar segera melaporkan kepada Humas Polda Kalsel untuk ditindaklanjuti.",Disinformasi,"[Humas Polda Kalsel telah memberikan klarifikasi melalui akun Instagram resmi @humas_poldakalsel bahwa akun WhatsApp dengan nomor +62 838-7219-4238 adalah palsu., Akun palsu tersebut menggunakan foto profil dengan logo Divisi Humas Kepolisian Republik Indonesia (Humas Polri) untuk mencatut nama institusi., Masyarakat diimbau untuk tidak menanggapi akun WhatsApp tersebut dan melaporkan ke Humas Polda Kalsel jika menemukan hal serupa., Polda Kalsel hanya akan memberikan informasi resmi melalui akun media sosial resmi mereka.]","Ini adalah modus pencatutan nama yang bertujuan untuk menipu masyarakat. Akun palsu tersebut menggunakan logo resmi untuk menambah kredibilitas, namun Humas Polda Kalsel telah membantah keberadaannya dan mengimbau masyarakat untuk waspada."
7999,"NASA Peringatkan Kiamat Internet Akan Terjadi 25 Juni 2023, Koneksi Internet Tidak Bisa Dipakai Selama Bertahun-tahun!","Beredar sebuah unggahan video di media sosial berisi narasi soal peringatan kiamat internet dari Badan Penerbangan dan Antariksa Amerika Serikat (NASA) pada 25 Juni 2023. Dalam video disebutkan manusia akan dilanda kondisi di mana koneksi internet tidak dapat dipakai selama berbulan-bulan, bahkan bertahun-tahun. Dilansir dari kompas.com, klaim NASA memperingatkan tentang kiamat internet adalah keliru. Berdasarkan penelusuran, video tersebut menggunakan sejumlah tangkapan layar artikel, salah satunya dari The Mirror yang diunggah pada 7 Juni 2023 dan artikel dari JOE.ie. Kedua artikel itu membahas tentang misi Parker Space Probe yang dilakukan NASA. NASA memang telah meluncurkan Parker Space Probe, tetapi tidak pernah ada istilah kiamat internet dalam misi tersebut. Istilah kiamat internet sendiri bersumber dari studi soal Badai Matahari yang ditulis oleh asisten profesor ilmu komputer Universitas California Sangeetha Abdu Jyothi pada 2021. Studi tersebut menganalisis ketahanan infrastruktur internet di seluruh dunia dan menemukan bahwa kabel bawah laut memiliki risiko kegagalan yang lebih tinggi. Apabila terjadi Badai Matahari, maka kabel bawah air akan terganggu dan menghilangkan daya listrik besar-besaran.",Disinformasi,"[Klaim tersebut adalah hoaks dan tidak berdasar. NASA tidak pernah mengeluarkan peringatan tentang kiamat internet., Video yang beredar menggunakan tangkapan layar artikel dari The Mirror dan JOE.ie yang membahas misi Parker Space Probe, bukan kiamat internet., Misi Parker Space Probe memang ada, namun tujuannya adalah untuk mempelajari matahari, bukan untuk memperingatkan tentang kiamat internet., Istilah 'kiamat internet' berasal dari studi ilmiah oleh Sangeetha Abdu Jyothi yang membahas risiko kegagalan kabel bawah laut akibat Badai Matahari, bukan peringatan resmi dari NASA., Kompas.com telah melakukan penelusuran dan menemukan bahwa klaim tersebut adalah keliru dan menyesatkan.]","Ini adalah modus konten menyesatkan yang memanfaatkan informasi sebagian dari studi ilmiah dan mencampuradukannya dengan narasi yang tidak benar. Video tersebut menggunakan elemen yang tampak kredibel, seperti kutipan artikel, untuk membuat klaim yang tidak didukung oleh fakta."

In [38]:
df_disinformasi = df_disinformasi.to_dict("records")

In [39]:
import json
import random

def generate_sft_dataset_with_context(raw_data_list, instructions, penutup_list, output_file):
    dataset = []
    
    for data in raw_data_list:
        instruct = random.choice(instructions)
        claim = data.get("claim_disinformasi", "")
        berita = data.get("berita_asli", "") 
        label = data.get("label")
        reasoning = data.get("reasoning_disinformasi", "")
        cot_list = data.get("cot_bantah_disinformasi", [])
        
        # Susun poin-poin fakta
        fakta_points = "\n".join([f"* {point}" for point in cot_list])
        closing = random.choice(penutup_list)
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Klaim: {claim}\n\n"
            f"Sumber Berita: {berita}"
        )

        full_output = (
            f"Label: **{label}.** "
            f"penjelasan: {reasoning}\n\n"
            f"Berikut adalah beberapa fakta sebenarnya:\n"
            f"{fakta_points}\n\n"
            f"{closing}"
        )
        
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(df_disinformasi, instructiones, penutup_disinformasi, "disinformasi.jsonl")

Berhasil membuat 7995 data dengan konteks berita di disinformasi.jsonl

# Fakta

In [40]:
folderData = Path("Dataset_fakta")
files = []


for file in folderData.glob("*.jsonl"):
    df_sementara = pd.read_json(file, lines=True)
    files.append(df_sementara)

df = pd.concat(files, ignore_index=True)

In [41]:
df_fakta = df[df["is_layak"]==1]

In [42]:
df_fakta = df_fakta.drop(columns=["url", "title", "published_at", "sumber_berita", "label", "is_layak"])
df_fakta["label"] = "Fakta"

In [43]:
df_fakta

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              text  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Konsumsi rokok dan minuman beralkohol masyarakat Kabupaten Pangandaran tercatat lebih tinggi dibandingkan belanja ikan dan telur. Kondisi ini mencerminkan adanya kecenderungan prioritas pengeluaran tertentu dalam kelompok konsumsi makanan masyarakat setempat.\nBerdasarkan data Badan Pusat Statistik (BPS) Kabupaten Pangandaran dalam laporan Kabupaten Pangandaran dalam Angka 2025, rokok dan minuman beralkohol diklasifikasikan ke dalam kelompok pengeluaran makanan. Menariknya, alokasi belanja untuk kategori tersebut justru melampaui pengeluaran untuk sumber pangan bergizi seperti ayam, telur, dan ikan.\nMeski demikian, secara umum BPS mencatat bahwa total pengeluaran penduduk Pangandaran untuk konsumsi makanan masih lebih besar dibandingkan pengeluaran non-makanan.\nSCROLL TO CONTINUE WITH CONTENT\nRata-rata pengeluaran per kapita per bulan penduduk Kabupaten Pangandaran pada 2024 tercatat sebesar Rp1.367.729. Dari jumlah tersebut, pengeluaran untuk kelompok makanan mencapai Rp809.992 atau 59,22 persen, sedangkan pengeluaran non-makanan sebesar Rp557.738 atau 40,78 persen.\nJika dibandingkan dengan tahun 2023, proporsi pengeluaran untuk makanan mengalami peningkatan. Pada 2023, pengeluaran makanan tercatat sebesar 55,72 persen, lalu naik menjadi 59,22 persen pada 2024.\nPada kelompok makanan tahun 2024, pengeluaran terbesar dialokasikan untuk makanan dan minuman jadi sebesar 15,56 persen, diikuti kelompok kacang-kacangan, buah-buahan, dan sayuran sebesar 10,51 persen, serta padi-padian dan umbi-umbian sebesar 9,59 persen.\nSementara itu, pengeluaran untuk kelompok ikan, daging, telur, dan susu hanya mencapai 8,76 persen, lebih rendah dibandingkan pengeluaran untuk rokok dan tembakau yang mencapai 9,20 persen. Pada 2023, proporsi belanja rokok dan tembakau tercatat sebesar 8,81 persen dan meningkat pada 2024.\nPada kelompok non-makanan tahun 2024, pengeluaran terbesar dialokasikan untuk perumahan, bahan bakar, penerangan, dan air dengan kontribusi 21,45 persen dari total pengeluaran. Sebaliknya, pengeluaran paling kecil terdapat pada keperluan pesta dan upacara adat yang hanya mencapai 1,13 persen.\nJika dibandingkan dengan tahun 2023, proporsi pengeluaran non-makanan secara keseluruhan mengalami penurunan. Pada 2023, pengeluaran non-makanan tercatat sebesar 23,28 persen, sedangkan pada 2024 tercatat sebesar 40,78 persen seiring meningkatnya total nilai pengeluaran masyarakat.\nPengeluaran untuk aneka barang dan jasa, biaya pendidikan, serta kesehatan tergolong relatif rendah. Pada 2023, kelompok ini menyumbang 9,03 persen dari total pengeluaran, kemudian menurun menjadi 8,82 persen pada 2024. Pengeluaran untuk pakaian dan alas kaki tercatat sebesar 2,80 persen pada 2023 dan turun menjadi 2,46 persen pada 2024.\nTingginya proporsi pengeluaran untuk makanan menunjukkan bahwa tingkat kesejahteraan masyarakat Kabupaten Pangandaran masih tergolong rendah, karena sebagian besar pendapatan digunakan untuk memenuhi kebutuhan dasar.\nNamun, data BPS juga menunjukkan bahwa pada kelompok pengeluaran 20 persen teratas, pola konsumsi mulai bergeser. Pada kelompok ini, pengeluaran non-makanan cenderung lebih besar dibandingkan pengeluaran makanan, yang mengindikasikan peningkatan taraf hidup dan diversifikasi kebutuhan.
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        BNN menggedebek kampung narkoba di Berlan, Matraman, Jakarta Timur. (Antara Foto/Fauzan)\n- Badan Narkotika Nasional (BNN) bersama petugas gabungan menggerebek kawasan Berlan, Matraman, Jakarta Timur, terkait dugaan peredarannarkobapada Selasa (25/11/2025) siang.\nDalam operasi tersebut, puluhan orang yang diduga sebagai pengedar berhasil diamankan.\nPenggerebekan dilakukan sekitar pukul 11.00 WIB. Petugas gabungan melakukan penyisiran ke sejumlah rumah dan langsung melakukan penggeledahan di titik-titik yang telah ditargetkan.\nDari lokasi, petugas menemukan berbagai jenis barang bukti narkoba dalam bentuk bubuk maupun cairan.\nSejumlah paket narkoba ditemukan disembunyikan di lemari hingga gudang-gudang kecil yang berada di dalam rumah warga.\nTerungkap! Ekstasi Rp 207 M Ditemukan Saat Mobil Kecelakaan di Lampung Hendak Disebar di Jakarta\nUntuk mempermudah pencarian barang bukti, petugas juga mengerahkan anjing pelacak (K9).\nLangkah ini dilakukan untuk memastikan tidak ada narkoba yang terlewatkan selama proses penggeledahan.\nDirektur Psikotropika dan Prekursor Deputi Bidang Pemberantasan BNN, Aldrin Marihot Pandapotan Hutabarat, menyampaikan bahwa pihaknya mengamankan puluhan orang dalam operasi tersebut.\n"Ada 10–15 titik yang menjadi target penggerebekan di kawasan Berlan. Dari rangkaian penggerebekan itu, kami mengamankan 25 pelaku," ujar Aldrin.\nSeluruh orang yang diamankan langsung dibawa ke kantor BNN untuk pemeriksaan lebih lanjut. Ia menyebut bahwa para pelaku merupakan warga sekitar.\n"Kawasan ini merupakan perkampungan. Semua yang kami amankan adalah warga sipil. Kami akan dalami peran masing-masing," pungkasnya.
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Pemerintah Kabupaten Sragen melakukan hitung cepat atau quick count pada pemilihan Bupati dan wakil Bupati Sragen 2024. Dari hasil hitung cepat yang dilakukan Desk Pilkada, pasangan Calon Bupati dan Wakil Bupati nomor urut 2, Sigit Pamungkas dan Suroto unggul dari pasangan nomor urut 1, Untung Wibowo Sukowati dan Suwardi.\nKepala Dinas Komunikasi dan Informatika Kabupaten Sragen, Catur Sarjanto mengatakan berdasarkan hitung cepat, pasangan Sigit-Suroto mendapat suara 330.358 suara. Sedangkan pasangan Bowo-Suwardi mendapat suara sebanyak 252.719.\n"Hasil hitung cepat kemarin paslon 01 sebanyak 252.719 atau sebesar persentase 43,34 persen, sedangkan Paslon 02 mendapat 330.358 suara atau 56,66 persen," katanya dihubungi, Kamis (28/11/2024).\nSCROLL TO CONTINUE WITH CONTENT\nCatur mengatakan dari 762.352 daftar pemilih tetap atau DPT, hanya 603.235 DPT menggunakan hak pilihnya. Catur menyebut di Kabupaten Sragen ada 1.462 Tempat Pemungutan Suara (TPS).\n"Mekanisme kita ada aplikasi yang buat Diskominfo, kita minta bantuan dengan camat, dari camat kita kirimkan operator untuk input data aplikasi, yang diinput di kantor kecamatan. Dari kecamatan menugaskan petugas untuk mencari data di semua TPS. Kemudian diinput di aplikasi yang ada di kecamatan," bebernya.\nDari data rekapitulasi Pemkab Sragen, pasangan Sigit-Suroto menang di total 20 kecamatan di Kabupaten Sragen.\n"Selesai kemarin pukul 18.00 WIB. Margin error nggak lebih dari 1 persen dengan KPU. Kami untuk aplikasi buka bisa untuk melihat, bisa melihat langsung kita tayangkan dengan video," pungkasnya.

In [44]:
len(df_fakta)

7790

In [45]:
df_fakta.isna().sum()

text                  0
claim_fakta           0
cot_analisis_fakta    0
reasoning_fakta       0
label                 0
dtype: int64

In [46]:
import random

kalimat_akhir = kalimat_penutup + penutup_disinformasi

def ambilRandom():
    return random.choice(kalimat_akhir)

In [47]:
df_fakta = df_fakta.to_dict("records")

In [48]:
import json
import random

def generate_sft_dataset_with_context(raw_data_list, instructions, penutup_list, output_file):
    dataset = []
    
    for data in raw_data_list:
        instruct = random.choice(instructions)
        claim = data.get("claim_fakta", "")
        berita = data.get("text", "") 
        label = data.get("label")
        reasoning = data.get("reasoning_fakta", "")
        cot_list = data.get("cot_analisis_fakta", [])
        kalimat_saran = ambilRandom()
        
        # Susun poin-poin fakta
        fakta_points = "\n".join([f"* {point}" for point in cot_list])
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"Klaim: {claim}\n\n"
            f"Sumber Berita: {berita}"
        )

        full_output = (
            f"Label: **{label}.** "
            f"penjelasan: {reasoning}\n\n"
            f"Berikut adalah beberapa fakta sebenarnya:\n"
            f"{fakta_points}\n\n"
            f"{kalimat_saran}"
        )
        
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(df_fakta, instructiones, penutup_disinformasi, "fakta.jsonl")

Berhasil membuat 7790 data dengan konteks berita di fakta.jsonl

# Sampling and concatting ting ting ayu ting ting

In [49]:
# df_disinformasi = pd.read_json("disinformasi.jsonl", lines=True)
# df_fitnah = pd.read_json("fitnah.jsonl", lines=True)
# df_fakta = pd.read_json("fakta.jsonl", lines=True)

In [50]:
# df_disinformasi = df_disinformasi.sample(n=7200)
# df_fitnah = df_fitnah.sample(n=7200)
# df_fakta = df_fakta.sample(n=7200)

In [51]:
# df_disinformasi.to_csv("df_disinformasi.csv", index=False)
# df_fitnah.to_csv("df_fitnah.csv", index=False)
# df_fakta.to_csv("df_fakta.csv", index=False)

In [52]:
# df_combined = pd.concat([
#     df_disinformasi.sample(n=7200, random_state=42),
#     df_fitnah.sample(n=7200, random_state=42),
#     df_fakta.sample(n=7200, random_state=42)
# ])

# df_combined = df_combined.sample(frac=1, random_state=42).reset_index(drop=True)

# df_combined.to_json('dataset_sampled.jsonl', orient='records', lines=True)

In [53]:
# df_combinedm

# Buat Dataset Ujaran Kebencian

In [54]:
folderData = Path("Dataset_UjaranKebencian")
komentar = []


for file in folderData.glob("*.jsonl"):
    if file.name == "panduan_komunitas.jsonl":
        continue
    
    df_sementara = pd.read_json(file, lines=True)
    komentar.append(df_sementara)

df_ujarankb = pd.concat(komentar, ignore_index=True)

In [55]:
df_ujarankb.isna().sum()

claim_disinformasi               0
target                           0
label                            0
jenis                            0
isExplicit                       4
IDPelanggaran                   13
cot_analisis                     4
reasoning_ujaran_kebencian       5
IDPelangguaran                7301
IDPelangguuran                7304
IDPelangguan                  7300
dtype: int64

In [56]:
print(len(df_ujarankb))

7304

In [57]:
df_ujarankb = df_ujarankb.drop(df_ujarankb[df_ujarankb["reasoning_ujaran_kebencian"].isna()].index)

In [58]:
eksplisit = df_ujarankb[df_ujarankb["isExplicit"] == 1]
print(len(eksplisit))

5268

In [59]:
eksplisit.isna().sum()

claim_disinformasi               0
target                           0
label                            0
jenis                            0
isExplicit                       0
IDPelanggaran                    7
cot_analisis                     0
reasoning_ujaran_kebencian       0
IDPelangguaran                5265
IDPelangguuran                5268
IDPelangguan                  5264
dtype: int64

In [60]:
# semua yang 5268 kita drop
eksplisit = eksplisit.drop(columns=["IDPelangguuran"])

In [61]:
eksplisit.isna().sum()

claim_disinformasi               0
target                           0
label                            0
jenis                            0
isExplicit                       0
IDPelanggaran                    7
cot_analisis                     0
reasoning_ujaran_kebencian       0
IDPelangguaran                5265
IDPelangguan                  5264
dtype: int64

In [62]:
eksplisit["IDPelangguaran"] = eksplisit["IDPelangguaran"].fillna(eksplisit["IDPelangguan"])
eksplisit["IDPelanggaran"] = eksplisit["IDPelanggaran"].fillna(eksplisit["IDPelangguaran"])

In [63]:
eksplisit.insert(0, "claim_ujaranKebencian", eksplisit["claim_disinformasi"])

In [64]:
eksplisit = eksplisit.drop(columns=["IDPelangguaran", "IDPelangguan", "claim_disinformasi"])

In [65]:
eksplisit.head(1)

,claim_ujaranKebencian,target,label,jenis,isExplicit,IDPelanggaran,cot_analisis,reasoning_ujaran_kebencian
0,"etnis tionghoa emang ges licik main uang panas dr china, ngebulu aja lo semua!",etnis tionghoa,Ujaran Kebencian,komentar,1.0,HS_STEREOTYPE,"[Claim menggunakan kata 'ges licik' yang merendahkan etnis Tionghoa secara kolektif., Menghubungkan perilaku 'main uang panas' dengan etnis Tionghoa, seolah-olah seluruh anggota etnis tersebut memiliki sifat licik., Penggunaan kata 'ngebulu aja lo semua' menunjukkan generalisasi negatif terhadap seluruh anggota etnis Tionghoa.]","Perilaku 'main uang panas' digunakan untuk menggeneralisasi sifat licik pada seluruh etnis Tionghoa, mencerminkan generalisasi negatif berdasarkan etnis (HS_STEREOTYPE). Target: etnis Tionghoa."

In [66]:
eksplisit["IDPelanggaran"].unique()

array(['HS_STEREOTYPE', 'HS_POLITICAL_SARA', 'HS_EXCLUSION', 'HS_GENDER',
       'HS_DEHUMAN', 'HS_CULTURAL', 'HS_VIOLENCE'], dtype=object)

In [67]:
path_panduanKomunitas = folderData / "panduan_komunitas.jsonl"

panduan_komunitas = pd.read_json(path_panduanKomunitas, lines=True)
panduan_komunitas

,ID,indikator pelanggaran,isi,keywords
0,HS_DEHUMAN,Penggunaan metafora yang menyamakan kelompok masyarakat dengan ancaman kesehatan atau kebersihan lingkungan.,"Segala bentuk komunikasi yang merendahkan martabat manusia dengan cara menyamakan, mengibaratkan, atau melabeli individu maupun kelompok tertentu sebagai hewan, hama, serangga, penyakit, parasit, atau benda mati yang berkonotasi kotor dan menjijikkan. Tindakan ini dilarang karena bertujuan menghilangkan sisi kemanusiaan suatu golongan sehingga memicu pembenaran atas kekerasan atau pengucilan.","Hama, parasit, virus, kuman, sampah masyarakat, kecoa, anjing, babi, tikus, kotoran, dibasmi, disemprot, dibersihkan, penyakit masyarakat, beban bumi"
1,HS_STEREOTYPE,"Penggunaan kata 'semua', 'selalu', atau penyebutan nama suku/ras yang diikuti dengan klaim perilaku negatif, watak jahat, atau kecenderungan kriminal kolektif.","Tindakan memberikan label negatif, atribut buruk, atau tuduhan kriminal secara pukul rata (generalisasi) kepada seluruh anggota kelompok berdasarkan latar belakang suku, ras, etnis, atau agama tertentu. Pelanggaran terjadi ketika perilaku individu digunakan untuk menghakimi seluruh identitas golongan. Hal ini mencakup tuduhan sifat bawaan (genetik) yang buruk terhadap etnis tertentu.","Suku itu licik, Ras ini pelit, memang wataknya jahat, keturunan pemberontak, genetik kriminal, tidak bisa dipercaya, sok ramah padahal busuk, orang daerah itu kasar, kaum itu memang tukang buat onar."
2,HS_EXCLUSION,"Adanya kalimat perintah atau ajakan untuk memindahkan, mengusir, atau melarang keberadaan suatu kelompok di suatu wilayah geografis atau lingkungan sosial tertentu.","Pernyataan yang mengandung ajakan, hasutan, desakan, atau dukungan untuk melakukan pemisahan wilayah secara paksa (segregasi), pengusiran, boikot tempat tinggal, atau pembatasan hak hidup suatu golongan dari suatu lingkungan masyarakat atau negara. Tindakan ini dianggap sebagai ancaman serius terhadap integrasi sosial dan keselamatan kelompok tertentu.","Usir mereka, kembalikan ke asalnya, jangan kasih tempat tinggal, bersihkan wilayah kita, jangan mau bertetangga, boikot keberadaannya, ganyang, pindahkan paksa, jangan kasih ijin tinggal, bersihkan dari tanah kita."
3,HS_GENDER,"Penggunaan istilah yang merendahkan harga diri berdasarkan peran gender, penyebutan label seksis, atau narasi yang memposisikan satu gender sebagai kelompok yang inferior/lemah.","Segala bentuk penghinaan, perendahan, atau serangan yang menargetkan identitas gender tertentu (laki-laki atau perempuan). Hal ini mencakup penggunaan kata-kata ejekan yang merendahkan maskulinitas atau feminitas, serta generalisasi negatif terhadap perilaku salah satu gender sebagai bentuk serangan kolektif.","Laki-laki banci, perempuan samsak, laki-laki semua sama saja, lemah, tidak berguna, objek, merendahkan martabat gender, serangan berbasis jenis kelamin."
4,HS_POLITICAL_SARA,"Mengaitkan identitas SARA secara langsung dengan label pengkhianat negara, gerakan radikal, atau sejarah organisasi terlarang dengan tujuan menciptakan stigma berbahaya.","Tindakan memberikan label atau tuduhan keterlibatan dalam ideologi politik terlarang, kelompok teroris, atau organisasi terlarang kepada suatu kelompok etnis atau agama tanpa bukti hukum yang sah. Tuduhan ini sering digunakan untuk memicu kebencian publik dan persekusi terhadap kelompok tersebut.","Keturunan PKI, antek asing, kelompok teroris, pengkhianat negara, radikal, ekstremis, penyusup ideologi, menghancurkan negara dari dalam."

In [68]:
print(f"jumlah qwen halu IDPelanggaran baru 'HS_VIOLENCE' sebanyak: {len(eksplisit[eksplisit['IDPelanggaran'] == 'HS_VIOLENCE'])}")
print(f"jumlah qwen halu IDPelanggaran baru 'HS_CULTURAL' sebanyak: {len(eksplisit[eksplisit['IDPelanggaran'] == 'HS_CULTURAL'])}")

jumlah qwen halu IDPelanggaran baru 'HS_VIOLENCE' sebanyak: 1
jumlah qwen halu IDPelanggaran baru 'HS_CULTURAL' sebanyak: 1

In [69]:
def panduanKomunitas(baris):
    return (
        f"### PEDOMAN KOMUNITAS: {baris['ID']}\n\n"
        f"**INDIKATOR PELANGGARAN:** {baris['indikator pelanggaran']}\n"
        f"**DEFINISI:** {baris['isi']}\n"
        f"**KATA KUNCI PEMICU:** {baris['keywords']}"
    )

panduan_komunitas["penjelasan"] = panduan_komunitas.apply(panduanKomunitas, axis=1)

In [70]:
panduan_komunitas

,ID,indikator pelanggaran,isi,keywords,penjelasan
0,HS_DEHUMAN,Penggunaan metafora yang menyamakan kelompok masyarakat dengan ancaman kesehatan atau kebersihan lingkungan.,"Segala bentuk komunikasi yang merendahkan martabat manusia dengan cara menyamakan, mengibaratkan, atau melabeli individu maupun kelompok tertentu sebagai hewan, hama, serangga, penyakit, parasit, atau benda mati yang berkonotasi kotor dan menjijikkan. Tindakan ini dilarang karena bertujuan menghilangkan sisi kemanusiaan suatu golongan sehingga memicu pembenaran atas kekerasan atau pengucilan.","Hama, parasit, virus, kuman, sampah masyarakat, kecoa, anjing, babi, tikus, kotoran, dibasmi, disemprot, dibersihkan, penyakit masyarakat, beban bumi","### PEDOMAN KOMUNITAS: HS_DEHUMAN\n\n**INDIKATOR PELANGGARAN:** Penggunaan metafora yang menyamakan kelompok masyarakat dengan ancaman kesehatan atau kebersihan lingkungan.\n**DEFINISI:** Segala bentuk komunikasi yang merendahkan martabat manusia dengan cara menyamakan, mengibaratkan, atau melabeli individu maupun kelompok tertentu sebagai hewan, hama, serangga, penyakit, parasit, atau benda mati yang berkonotasi kotor dan menjijikkan. Tindakan ini dilarang karena bertujuan menghilangkan sisi kemanusiaan suatu golongan sehingga memicu pembenaran atas kekerasan atau pengucilan.\n**KATA KUNCI PEMICU:** Hama, parasit, virus, kuman, sampah masyarakat, kecoa, anjing, babi, tikus, kotoran, dibasmi, disemprot, dibersihkan, penyakit masyarakat, beban bumi"
1,HS_STEREOTYPE,"Penggunaan kata 'semua', 'selalu', atau penyebutan nama suku/ras yang diikuti dengan klaim perilaku negatif, watak jahat, atau kecenderungan kriminal kolektif.","Tindakan memberikan label negatif, atribut buruk, atau tuduhan kriminal secara pukul rata (generalisasi) kepada seluruh anggota kelompok berdasarkan latar belakang suku, ras, etnis, atau agama tertentu. Pelanggaran terjadi ketika perilaku individu digunakan untuk menghakimi seluruh identitas golongan. Hal ini mencakup tuduhan sifat bawaan (genetik) yang buruk terhadap etnis tertentu.","Suku itu licik, Ras ini pelit, memang wataknya jahat, keturunan pemberontak, genetik kriminal, tidak bisa dipercaya, sok ramah padahal busuk, orang daerah itu kasar, kaum itu memang tukang buat onar.","### PEDOMAN KOMUNITAS: HS_STEREOTYPE\n\n**INDIKATOR PELANGGARAN:** Penggunaan kata 'semua', 'selalu', atau penyebutan nama suku/ras yang diikuti dengan klaim perilaku negatif, watak jahat, atau kecenderungan kriminal kolektif.\n**DEFINISI:** Tindakan memberikan label negatif, atribut buruk, atau tuduhan kriminal secara pukul rata (generalisasi) kepada seluruh anggota kelompok berdasarkan latar belakang suku, ras, etnis, atau agama tertentu. Pelanggaran terjadi ketika perilaku individu digunakan untuk menghakimi seluruh identitas golongan. Hal ini mencakup tuduhan sifat bawaan (genetik) yang buruk terhadap etnis tertentu.\n**KATA KUNCI PEMICU:** Suku itu licik, Ras ini pelit, memang wataknya jahat, keturunan pemberontak, genetik kriminal, tidak bisa dipercaya, sok ramah padahal busuk, orang daerah itu kasar, kaum itu memang tukang buat onar."
2,HS_EXCLUSION,"Adanya kalimat perintah atau ajakan untuk memindahkan, mengusir, atau melarang keberadaan suatu kelompok di suatu wilayah geografis atau lingkungan sosial tertentu.","Pernyataan yang mengandung ajakan, hasutan, desakan, atau dukungan untuk melakukan pemisahan wilayah secara paksa (segregasi), pengusiran, boikot tempat tinggal, atau pembatasan hak hidup suatu golongan dari suatu lingkungan masyarakat atau negara. Tindakan ini dianggap sebagai ancaman serius terhadap integrasi sosial dan keselamatan kelompok tertentu.","Usir mereka, kembalikan ke asalnya, jangan kasih tempat tinggal, bersihkan wilayah kita, jangan mau bertetangga, boikot keberadaannya, ganyang, pindahkan paksa, jangan kasih ijin tinggal, bersihkan dari tanah kita.","### PEDOMAN KOMUNITAS: HS_EXCLUSION\n\n**INDIKATOR PELANGGARAN:** Adanya kalimat perintah atau ajakan untuk memindahkan, mengusir, atau melarang keberadaan suatu kelompok di suatu wilayah geografis atau lingkungan sosial tertentu.\n**DEFINISI:** Pernyataan yang mengandung ajakan, hasutan, desakan, atau dukungan untuk melakukan pemisahan wilayah secara paksa (segregasi), pengusiran, boikot tempat tinggal, atau pembatasan hak hidup suatu golongan dari suatu lingkungan masyarakat atau negara. Tindakan ini dianggap sebagai ancaman serius terhadap integrasi sosial dan keselamatan kelompok tertentu.\n**KATA KUNCI PEMICU:** Usir mereka, kembalikan ke asalnya, jangan kasih tempat tinggal, bersihkan wilayah kita, jangan mau bertetangga, boikot keberadaannya, ganyang, pindahkan paksa, jangan kasih ijin tinggal, bersihkan dari tanah kita."
3,HS_GENDER,"Penggunaan istilah yang merendahkan harga diri berdasarkan peran gender, penyebutan label seksis, atau narasi yang memposisikan satu gender sebagai kelompok yang inferior/lemah.","Segala bentuk penghinaan, perendahan, atau serangan yang menargetkan identitas gender tertentu (laki-laki atau perempuan). Hal ini mencakup penggunaan kata-kata ejekan yang merendahkan maskulinitas atau feminitas, serta generalisasi negatif terhadap perilaku salah satu gender sebagai bentuk serangan kolektif.","Laki-laki banci, perempuan samsak, laki-laki semua sama saja, lemah, tidak berguna, objek, merendahkan martabat gender, serangan berbasis jenis kelamin.","### PEDOMAN KOMUNITAS: HS_GENDER\n\n**INDIKATOR PELANGGARAN:** Penggunaan istilah yang merendahkan harga diri berdasarkan peran gender, penyebutan label seksis, atau narasi yang memposisikan satu gender sebagai kelompok yang inferior/lemah.\n**DEFINISI:** Segala bentuk penghinaan, perendahan, atau serangan yang menargetkan identitas gender tertentu (laki-laki atau perempuan). Hal ini mencakup penggunaan kata-kata ejekan yang merendahkan maskulinitas atau feminitas, serta generalisasi negatif terhadap perilaku salah satu gender sebagai bentuk serangan kolektif.\n**KATA KUNCI PEMICU:** Laki-laki banci, perempuan samsak, laki-laki semua sama saja, lemah, tidak berguna, objek, merendahkan martabat gender, serangan berbasis jenis kelamin."
4,HS_POLITICAL_SARA,"Mengaitkan identitas SARA secara langsung dengan label pengkhianat negara, gerakan radikal, atau sejarah organisasi terlarang dengan tujuan menciptakan stigma berbahaya.","Tindakan memberikan label atau tuduhan keterlibatan dalam ideologi politik terlarang, kelompok teroris, atau organisasi terlarang kepada suatu kelompok etnis atau agama tanpa bukti hukum yang sah. Tuduhan ini sering digunakan untuk memicu kebencian publik dan persekusi terhadap kelompok tersebut.","Keturunan PKI, antek asing, kelompok teroris, pengkhianat negara, radikal, ekstremis, penyusup ideologi, menghancurkan negara dari dalam.","### PEDOMAN KOMUNITAS: HS_POLITICAL_SARA\n\n**INDIKATOR PELANGGARAN:** Mengaitkan identitas SARA secara langsung dengan label pengkhianat negara, gerakan radikal, atau sejarah organisasi terlarang dengan tujuan menciptakan stigma berbahaya.\n**DEFINISI:** Tindakan memberikan label atau tuduhan keterlibatan dalam ideologi politik terlarang, kelompok teroris, atau organisasi terlarang kepada suatu kelompok etnis atau agama tanpa bukti hukum yang sah. Tuduhan ini sering digunakan untuk memicu kebencian publik dan persekusi terhadap kelompok tersebut.\n**KATA KUNCI PEMICU:** Keturunan PKI, antek asing, kelompok teroris, pengkhianat negara, radikal, ekstremis, penyusup ideologi, menghancurkan negara dari dalam."

In [71]:
id_penjelasan = dict(
    zip(
        panduan_komunitas["ID"],
        panduan_komunitas["penjelasan"]
    )
)

In [72]:
id_penjelasan

{'HS_DEHUMAN': '### PEDOMAN KOMUNITAS: HS_DEHUMAN\n\n**INDIKATOR PELANGGARAN:** Penggunaan metafora yang menyamakan kelompok masyarakat dengan ancaman kesehatan atau kebersihan lingkungan.\n**DEFINISI:** Segala bentuk komunikasi yang merendahkan martabat manusia dengan cara menyamakan, mengibaratkan, atau melabeli individu maupun kelompok tertentu sebagai hewan, hama, serangga, penyakit, parasit, atau benda mati yang berkonotasi kotor dan menjijikkan. Tindakan ini dilarang karena bertujuan menghilangkan sisi kemanusiaan suatu golongan sehingga memicu pembenaran atas kekerasan atau pengucilan.\n**KATA KUNCI PEMICU:** Hama, parasit, virus, kuman, sampah masyarakat, kecoa, anjing, babi, tikus, kotoran, dibasmi, disemprot, dibersihkan, penyakit masyarakat, beban bumi',
 'HS_STEREOTYPE': "### PEDOMAN KOMUNITAS: HS_STEREOTYPE\n\n**INDIKATOR PELANGGARAN:** Penggunaan kata 'semua', 'selalu', atau penyebutan nama suku/ras yang diikuti dengan klaim perilaku negatif, watak jahat, atau kecenderungan kriminal kolektif.\n**DEFINISI:** Tindakan memberikan label negatif, atribut buruk, atau tuduhan kriminal secara pukul rata (generalisasi) kepada seluruh anggota kelompok berdasarkan latar belakang suku, ras, etnis, atau agama tertentu. Pelanggaran terjadi ketika perilaku individu digunakan untuk menghakimi seluruh identitas golongan. Hal ini mencakup tuduhan sifat bawaan (genetik) yang buruk terhadap etnis tertentu.\n**KATA KUNCI PEMICU:** Suku itu licik, Ras ini pelit, memang wataknya jahat, keturunan pemberontak, genetik kriminal, tidak bisa dipercaya, sok ramah padahal busuk, orang daerah itu kasar, kaum itu memang tukang buat onar.",
 'HS_EXCLUSION': '### PEDOMAN KOMUNITAS: HS_EXCLUSION\n\n**INDIKATOR PELANGGARAN:** Adanya kalimat perintah atau ajakan untuk memindahkan, mengusir, atau melarang keberadaan suatu kelompok di suatu wilayah geografis atau lingkungan sosial tertentu.\n**DEFINISI:** Pernyataan yang mengandung ajakan, hasutan, desakan, atau dukungan untuk melakukan pemisahan wilayah secara paksa (segregasi), pengusiran, boikot tempat tinggal, atau pembatasan hak hidup suatu golongan dari suatu lingkungan masyarakat atau negara. Tindakan ini dianggap sebagai ancaman serius terhadap integrasi sosial dan keselamatan kelompok tertentu.\n**KATA KUNCI PEMICU:** Usir mereka, kembalikan ke asalnya, jangan kasih tempat tinggal, bersihkan wilayah kita, jangan mau bertetangga, boikot keberadaannya, ganyang, pindahkan paksa, jangan kasih ijin tinggal, bersihkan dari tanah kita.',
 'HS_GENDER': '### PEDOMAN KOMUNITAS: HS_GENDER\n\n**INDIKATOR PELANGGARAN:** Penggunaan istilah yang merendahkan harga diri berdasarkan peran gender, penyebutan label seksis, atau narasi yang memposisikan satu gender sebagai kelompok yang inferior/lemah.\n**DEFINISI:** Segala bentuk penghinaan, perendahan, atau serangan yang menargetkan identitas gender tertentu (laki-laki atau perempuan). Hal ini mencakup penggunaan kata-kata ejekan yang merendahkan maskulinitas atau feminitas, serta generalisasi negatif terhadap perilaku salah satu gender sebagai bentuk serangan kolektif.\n**KATA KUNCI PEMICU:** Laki-laki banci, perempuan samsak, laki-laki semua sama saja, lemah, tidak berguna, objek, merendahkan martabat gender, serangan berbasis jenis kelamin.',
 'HS_POLITICAL_SARA': '### PEDOMAN KOMUNITAS: HS_POLITICAL_SARA\n\n**INDIKATOR PELANGGARAN:** Mengaitkan identitas SARA secara langsung dengan label pengkhianat negara, gerakan radikal, atau sejarah organisasi terlarang dengan tujuan menciptakan stigma berbahaya.\n**DEFINISI:** Tindakan memberikan label atau tuduhan keterlibatan dalam ideologi politik terlarang, kelompok teroris, atau organisasi terlarang kepada suatu kelompok etnis atau agama tanpa bukti hukum yang sah. Tuduhan ini sering digunakan untuk memicu kebencian publik dan persekusi terhadap kelompok tersebut.\n**KATA KUNCI PEMICU:** Keturunan PKI, antek asing, kelompok teroris, pengkhianat negara, radikal, ekstremis, penyusup ideologi, menghancurkan negara dari dalam.'}

In [73]:
eksplisit["IDPelanggaran"] = eksplisit["IDPelanggaran"].map(id_penjelasan)

In [76]:
kalimat_penutup_hate_speech = [
    "**Mari kita jaga ruang digital dengan berkomunikasi secara santun tanpa merendahkan martabat kelompok mana pun.**",
    "**Hindari penyebaran narasi yang memicu perpecahan; pastikan setiap opini tetap mengedepankan nilai toleransi.**",
    "**Bijaklah dalam berpendapat; jangan biarkan perbedaan pandangan berubah menjadi serangan berbasis kebencian atau SARA.**",
    "**Mari bersama-sama melawan dehumanisasi di media sosial demi menjaga keharmonisan dan persatuan bangsa.**",
    "**Penting untuk selalu menghargai keberagaman dan menjauhkan diri dari penggunaan stereotip negatif dalam berinteraksi.**",
    "**Ruang digital yang sehat adalah ruang tanpa ujaran kebencian. Mari fokus pada diskusi yang membangun dan edukatif.**",
    "**Jangan biarkan narasi kebencian memengaruhi cara kita bertindak; prioritaskan etika dan rasa hormat kepada sesama.**",
    "**Setiap kata memiliki dampak. Hindari penggunaan diksi yang memicu kebencian atau diskriminasi terhadap golongan tertentu.**",
    "**Toleransi adalah kunci dalam bersosial media. Mari hentikan penyebaran stigma dan generalisasi negatif terhadap kelompok lain.**",
    "**Ayo ciptakan lingkungan digital yang aman bagi semua dengan menolak segala bentuk ujaran kebencian dan hasutan.**"
]

In [77]:
eksplisit["label"] = "Ujaran Kebencian"
eksplisit.head(1)

,claim_ujaranKebencian,target,label,jenis,isExplicit,IDPelanggaran,cot_analisis,reasoning_ujaran_kebencian
0,"etnis tionghoa emang ges licik main uang panas dr china, ngebulu aja lo semua!",etnis tionghoa,Ujaran Kebencian,komentar,1.0,"### PEDOMAN KOMUNITAS: HS_STEREOTYPE\n\n**INDIKATOR PELANGGARAN:** Penggunaan kata 'semua', 'selalu', atau penyebutan nama suku/ras yang diikuti dengan klaim perilaku negatif, watak jahat, atau kecenderungan kriminal kolektif.\n**DEFINISI:** Tindakan memberikan label negatif, atribut buruk, atau tuduhan kriminal secara pukul rata (generalisasi) kepada seluruh anggota kelompok berdasarkan latar belakang suku, ras, etnis, atau agama tertentu. Pelanggaran terjadi ketika perilaku individu digunakan untuk menghakimi seluruh identitas golongan. Hal ini mencakup tuduhan sifat bawaan (genetik) yang buruk terhadap etnis tertentu.\n**KATA KUNCI PEMICU:** Suku itu licik, Ras ini pelit, memang wataknya jahat, keturunan pemberontak, genetik kriminal, tidak bisa dipercaya, sok ramah padahal busuk, orang daerah itu kasar, kaum itu memang tukang buat onar.","[Claim menggunakan kata 'ges licik' yang merendahkan etnis Tionghoa secara kolektif., Menghubungkan perilaku 'main uang panas' dengan etnis Tionghoa, seolah-olah seluruh anggota etnis tersebut memiliki sifat licik., Penggunaan kata 'ngebulu aja lo semua' menunjukkan generalisasi negatif terhadap seluruh anggota etnis Tionghoa.]","Perilaku 'main uang panas' digunakan untuk menggeneralisasi sifat licik pada seluruh etnis Tionghoa, mencerminkan generalisasi negatif berdasarkan etnis (HS_STEREOTYPE). Target: etnis Tionghoa."

In [78]:
eksplisit = eksplisit.to_dict("records")

In [79]:
import json
import random

def generate_sft_dataset_with_context(raw_data_list, instructions, penutup_list, output_file):
    dataset = []
    
    for data in raw_data_list:
        instruct = random.choice(instructions)
        claim = data.get("claim_ujaranKebencian", "")
        teks = data.get("IDPelanggaran", "") 
        label = data.get("label")
        reasoning = data.get("reasoning_ujaran_kebencian", "")
        cot_list = data.get("cot_analisis", [])
        
        # Susun poin-poin fakta
        fakta_points = "\n".join([f"* {point}" for point in cot_list])
        closing = random.choice(penutup_list)
        
        full_instruction = (
            f"{instruct}"
        )

        full_input = (
            f"input: {claim};\n\n"
            f"Artikel Rujukan: {teks}"
        )

        full_output = (
            f"Label: **{label}.** "
            f"penjelasan: {reasoning}\n\n"
            f"Rincian indikasi pelanggaran dalam teks tersebut mencakup beberapa poin berikut:\n"
            f"{fakta_points}\n\n"
            f"{closing}"
        )
        
        
        entry = {
            "instruction": full_instruction,
            "input": full_input,
            "output": full_output
        }
        dataset.append(entry)

    with open(output_file, 'w', encoding='utf-8') as f:
        for item in dataset:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')
            
    print(f"Berhasil membuat {len(dataset)} data dengan konteks berita di {output_file}")

generate_sft_dataset_with_context(eksplisit, instructiones, kalimat_penutup_hate_speech, "ujarankebencian.jsonl")

Berhasil membuat 5268 data dengan konteks berita di ujarankebencian.jsonl

In [80]:
tes = pd.read_json("ujarankebencian.jsonl", lines=True)

In [81]:
tes

,instruction,input,output
0,"Bandingkan klaim di bawah ini dengan artikel rujukan, lalu tentukan apakah masuk kategori Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.","input: etnis tionghoa emang ges licik main uang panas dr china, ngebulu aja lo semua!;\n\nArtikel Rujukan: ### PEDOMAN KOMUNITAS: HS_STEREOTYPE\n\n**INDIKATOR PELANGGARAN:** Penggunaan kata 'semua', 'selalu', atau penyebutan nama suku/ras yang diikuti dengan klaim perilaku negatif, watak jahat, atau kecenderungan kriminal kolektif.\n**DEFINISI:** Tindakan memberikan label negatif, atribut buruk, atau tuduhan kriminal secara pukul rata (generalisasi) kepada seluruh anggota kelompok berdasarkan latar belakang suku, ras, etnis, atau agama tertentu. Pelanggaran terjadi ketika perilaku individu digunakan untuk menghakimi seluruh identitas golongan. Hal ini mencakup tuduhan sifat bawaan (genetik) yang buruk terhadap etnis tertentu.\n**KATA KUNCI PEMICU:** Suku itu licik, Ras ini pelit, memang wataknya jahat, keturunan pemberontak, genetik kriminal, tidak bisa dipercaya, sok ramah padahal busuk, orang daerah itu kasar, kaum itu memang tukang buat onar.","Label: **Ujaran Kebencian.** penjelasan: Perilaku 'main uang panas' digunakan untuk menggeneralisasi sifat licik pada seluruh etnis Tionghoa, mencerminkan generalisasi negatif berdasarkan etnis (HS_STEREOTYPE). Target: etnis Tionghoa.\n\nRincian indikasi pelanggaran dalam teks tersebut mencakup beberapa poin berikut:\n* Claim menggunakan kata 'ges licik' yang merendahkan etnis Tionghoa secara kolektif.\n* Menghubungkan perilaku 'main uang panas' dengan etnis Tionghoa, seolah-olah seluruh anggota etnis tersebut memiliki sifat licik.\n* Penggunaan kata 'ngebulu aja lo semua' menunjukkan generalisasi negatif terhadap seluruh anggota etnis Tionghoa.\n\n**Setiap kata memiliki dampak. Hindari penggunaan diksi yang memicu kebencian atau diskriminasi terhadap golongan tertentu.**"
1,"Cek kebenaran narasi di bawah ini menggunakan rujukan yang tersedia, lalu pilih label: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.","input: goblok etnis tionghoa pelit bgt pas minta upah pekerja;\n\nArtikel Rujukan: ### PEDOMAN KOMUNITAS: HS_STEREOTYPE\n\n**INDIKATOR PELANGGARAN:** Penggunaan kata 'semua', 'selalu', atau penyebutan nama suku/ras yang diikuti dengan klaim perilaku negatif, watak jahat, atau kecenderungan kriminal kolektif.\n**DEFINISI:** Tindakan memberikan label negatif, atribut buruk, atau tuduhan kriminal secara pukul rata (generalisasi) kepada seluruh anggota kelompok berdasarkan latar belakang suku, ras, etnis, atau agama tertentu. Pelanggaran terjadi ketika perilaku individu digunakan untuk menghakimi seluruh identitas golongan. Hal ini mencakup tuduhan sifat bawaan (genetik) yang buruk terhadap etnis tertentu.\n**KATA KUNCI PEMICU:** Suku itu licik, Ras ini pelit, memang wataknya jahat, keturunan pemberontak, genetik kriminal, tidak bisa dipercaya, sok ramah padahal busuk, orang daerah itu kasar, kaum itu memang tukang buat onar.","Label: **Ujaran Kebencian.** penjelasan: Pemberian upah pekerja digunakan untuk menggeneralisasi sifat pelit pada seluruh etnis Tionghoa, mencerminkan generalisasi negatif berdasarkan etnis (HS_STEREOTYPE). Target: etnis Tionghoa.\n\nRincian indikasi pelanggaran dalam teks tersebut mencakup beberapa poin berikut:\n* Claim menggambarkan etnis Tionghoa sebagai 'pelit' dalam konteks pemberian upah pekerja.\n* Generalisasi negatif ini menunjukkan bahwa seluruh anggota etnis Tionghoa diasumsikan pelit.\n* Penggunaan kata 'goblok' menambah tingkat pelecehan terhadap etnis Tionghoa.\n\n**Setiap kata memiliki dampak. Hindari penggunaan diksi yang memicu kebencian atau diskriminasi terhadap golongan tertentu.**"
2,"Identifikasi intensi teks terhadap artikel rujukan. Klasifikasikan sebagai Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.","input: cina aseng gak pernah cinta nkri, tolol bener sih.;\n\nArtikel Rujukan: ### PEDOMAN KOMUNITAS: HS_STEREOTYPE\n\n**INDIKATOR PELANGGARAN:** Penggunaan kata 'semua', 'selalu', atau penyebutan nama suku/ras yang diikuti dengan klaim perilaku negatif, watak jahat, atau kecenderungan kriminal kolektif.\n**DEFINISI:** Tindakan memberikan label negatif, atribut buruk, atau tuduhan kriminal secara pukul rata (generalisasi) kepada seluruh anggota kelompok berdasarkan latar belakang suku, ras, etnis, atau agama tertentu. Pelanggaran terjadi ketika perilaku individu digunakan untuk menghakimi seluruh identitas golongan. Hal ini mencakup tuduhan sifat bawaan (genetik) yang buruk terhadap etnis tertentu.\n**KATA KUNCI PEMICU:** Suku itu licik, Ras ini pelit, memang wataknya jahat, keturunan pemberontak, genetik kriminal, tidak bisa dipercaya, sok ramah padahal busuk, orang daerah itu kasar, kaum itu memang tukang buat onar.","Label: **Ujaran Kebencian.** penjelasan: Ketidakcintaian terhadap NKRI digunakan untuk menggeneralisasi kurangnya nasionalisme pada seluruh etnis Tionghoa, mencerminkan generalisasi negatif berdasarkan etnis (HS_STEREOTYPE). Target: etnis Tionghoa.\n\nRincian indikasi pelanggaran dalam teks tersebut mencakup beberapa poin berikut:\n* Claim menyebutkan bahwa 'cina aseng gak pernah cinta nkri', menunjukkan generalisasi negatif terhadap etnis Tionghoa.\n* Penggunaan kata 'tolol bener sih' menambah tingkat pelecehan terhadap etnis Tionghoa.\n* Generalisasi ini mengasumsikan bahwa seluruh anggota etnis Tionghoa tidak memiliki nasionalisme.\n\n**Hindari penyebaran narasi yang memicu perpecahan; pastikan setiap opini tetap mengedepankan nilai toleransi.**"
3,"Lakukan verifikasi klaim. Bandingkan poin-poin teks dengan artikel rujukan dan tentukan kategori: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.","input: etnis tionghoa emang pelit bgt, angpao aja gak mau bagi, brengsek!;\n\nArtikel Rujukan: ### PEDOMAN KOMUNITAS: HS_STEREOTYPE\n\n**INDIKATOR PELANGGARAN:** Penggunaan kata 'semua', 'selalu', atau penyebutan nama suku/ras yang diikuti dengan klaim perilaku negatif, watak jahat, atau kecenderungan kriminal kolektif.\n**DEFINISI:** Tindakan memberikan label negatif, atribut buruk, atau tuduhan kriminal secara pukul rata (generalisasi) kepada seluruh anggota kelompok berdasarkan latar belakang suku, ras, etnis, atau agama tertentu. Pelanggaran terjadi ketika perilaku individu digunakan untuk menghakimi seluruh identitas golongan. Hal ini mencakup tuduhan sifat bawaan (genetik) yang buruk terhadap etnis tertentu.\n**KATA KUNCI PEMICU:** Suku itu licik, Ras ini pelit, memang wataknya jahat, keturunan pemberontak, genetik kriminal, tidak bisa dipercaya, sok ramah padahal busuk, orang daerah itu kasar, kaum itu memang tukang buat onar.","Label: **Ujaran Kebencian.** penjelasan: Ketidaksediaan memberikan angpao digunakan untuk menggeneralisasi sifat pelit pada seluruh etnis Tionghoa, mencerminkan generalisasi negatif berdasarkan etnis (HS_STEREOTYPE). Target: etnis Tionghoa.\n\nRincian indikasi pelanggaran dalam teks tersebut mencakup beberapa poin berikut:\n* Claim menggambarkan etnis Tionghoa sebagai 'pelit' dalam konteks pemberian angpao.\n* Generalisasi negatif ini menunjukkan bahwa seluruh anggota etnis Tionghoa diasumsikan pelit.\n* Penggunaan kata 'brengsek' menambah tingkat pelecehan terhadap etnis Tionghoa.\n\n**Hindari penyebaran narasi yang memicu perpecahan; pastikan setiap opini tetap mengedepankan nilai toleransi.**"
4,"Bandingkan pernyataan netizen ini dengan rujukan fakta resmi. Tentukan labelnya: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.","input: etnis tionghoa gak pernah nasionalis, cuman mikirin duit doang tolol.;\n\nArtikel Rujukan: ### PEDOMAN KOMUNITAS: HS_STEREOTYPE\n\n**INDIKATOR PELANGGARAN:** Penggunaan kata 'semua', 'selalu', atau penyebutan nama suku/ras yang diikuti dengan klaim perilaku negatif, watak jahat, atau kecenderungan kriminal kolektif.\n**DEFINISI:** Tindakan memberikan label negatif, atribut buruk, atau tuduhan kriminal secara pukul rata (generalisasi) kepada seluruh anggota kelompok berdasarkan latar belakang suku, ras, etnis, atau agama tertentu. Pelanggaran terjadi ketika perilaku individu digunakan untuk menghakimi seluruh identitas golongan. Hal ini mencakup tuduhan sifat bawaan (genetik) yang buruk terhadap etnis tertentu.\n**KATA KUNCI PEMICU:** Suku itu licik, Ras ini pelit, memang wataknya jahat, keturunan pemberontak, genetik kriminal, tidak bisa dipercaya, sok ramah padahal busuk, orang daerah itu kasar, kaum itu memang tukang buat onar.","Label: **Ujaran Kebencian.** penjelasan: Ketidakcintaian terhadap NKRI dan fokus pada uang digunakan untuk menggeneralisasi seluruh etnis Tionghoa, mencerminkan generalisasi negatif berdasarkan etnis (HS_STEREOTYPE). Target: etnis Tionghoa.\n\nRincian indikasi pelanggaran dalam teks tersebut mencakup beberapa poin berikut:\n* Claim menggambarkan etnis Tionghoa sebagai 'gak pernah nasionalis' dan 'cuman mikirin duit doang'.\n* Generalisasi negatif ini menunjukkan bahwa seluruh anggota etnis Tionghoa diasumsikan tidak memiliki nasionalisme dan hanya mementingkan uang.\n* Penggunaan kata 'tolol' menambah tingkat pelecehan terhadap etnis Tionghoa.\n\n**Mari bersama-sama melawan dehumanisasi di media sosial demi menjaga keharmonisan dan persatuan bangsa.**"
...,...,...,...
5263,"Bandingkan klaim di bawah ini dengan artikel rujukan, lalu tentukan apakah masuk kategori Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.","input: Judul: Invasi Simbol-simbol Kristen di Wilayah Mayoritas.\n\nTeks: Dalam beberapa tahun terakhir, fenomena pembangunan rumah ibadah Kristen di wilayah yang mayoritas berpenduduk non-Kristen semakin marak. Tidak jarang, pembangunan ini diiringi dengan peningkatan jumlah simbol-simbol agama Kristen yang muncul di ruang publik, seolah-olah mencoba mendominasi dan mengubah identitas sosial budaya daerah tersebut. Praktik ini sering kali dianggap sebagai upaya sistematis untuk menanamkan nilai-nilai dan norma-norma agama Kristen, yang pada akhirnya dapat mengancam keseimbangan harmoni sosial yang sudah terjalin selama bertahun-tahun. Masyarakat yang asli merasa terancam dan khawatir bahwa keberadaan mereka akan terkikis oleh kehadiran yang semakin agresif ini. Sudah menjadi hal yang umum bagi penganut Kristen untuk menunjukkan kehadiran mereka dengan cara yang mencolok, baik melalui pembangunan gereja megah maupun penempatan simbol-simbol agama di tempat-tempat strategis. Hal ini menunjukkan bahwa dominasi religius bukanlah hal baru, melainkan sebuah pola yang terus dipraktikkan oleh kelompok tersebut, yang pada akhirnya dapat menimbulkan ketidaknyamanan dan konflik sosial.;\n\nArtikel Rujukan: ### PEDOMAN KOMUNITAS: HS_STEREOTYPE\n\n**INDIKATOR PELANGGARAN:** Penggunaan kata 'semua', 'selalu', atau penyebutan nama suku/ras yang diikuti dengan klaim perilaku negatif, watak jahat, atau kecenderungan kriminal kolektif.\n**DEFINISI:** Tindakan memberikan label negatif, atribut buruk, atau tuduhan kriminal secara pukul rata (generalisasi) kepada seluruh anggota kelompok berdasarkan latar belakang suku, ras, etnis, atau agama tertentu. Pelanggaran terjadi ketika perilaku individu digunakan untuk menghakimi seluruh identitas golongan. Hal ini mencakup tuduhan sifat bawaan (genetik) yang buruk terhadap etnis tertentu.\n**KATA KUNCI PEMICU:** Suku itu licik, Ras ini pelit, memang wataknya jahat, keturunan pemberontak, genetik kriminal, tidak bisa dipercaya, sok ramah padahal busuk, orang daerah itu kasar, kaum itu memang tukang buat onar.","Label: **Ujaran Kebencian.** penjelasan: Pernyataan ini memberikan label negatif dan atribut buruk kepada seluruh penganut Kristen, mencerminkan generalisasi kolektif yang merendahkan martabat mereka sebagai kelompok agama.\n\nRincian indikasi pelanggaran dalam teks tersebut mencakup beberapa poin berikut:\n* Claim menggeneralisir penganut Kristen dengan atribut negatif seperti invasi simbol-simbol agama dan upaya sistematis untuk mendominasi identitas sosial budaya daerah.\n* Pernyataan menegaskan bahwa praktik ini sering kali dianggap sebagai upaya sistematis untuk menanamkan nilai-nilai agama Kristen.\n* Claim menyebutkan bahwa fenomena ini menimbulkan ketidaknyamanan dan konflik sosial, menunjukkan generalisasi kolektif yang merendahkan martabat mereka.\n\n**Setiap kata memiliki dampak. Hindari penggunaan diksi yang memicu kebencian atau diskriminasi terhadap golongan tertentu.**"
5264,"Evaluasi kebenaran klaim ini melalui artikel rujukan. Tentukan label: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.","input: Judul: Topeng Intimidasi Terhadap Pendatang.\n\nTeks: Solidaritas suku Dayak sering kali menjadi alat yang disalahgunakan untuk mengintimidasi dan memarginalisasi kelompok luar. Di berbagai daerah Kalimantan, masyarakat Dayak cenderung memandang pendatang dengan kecurigaan yang berlebihan, menganggap mereka sebagai ancaman terhadap identitas dan kepentingan lokal. Praktik ini bukan hanya sekadar sikap defensif, melainkan bentuk eksklusivisme yang telah tertanam dalam budaya mereka. Solidaritas yang seharusnya menjadi kekuatan positif justru digunakan untuk memperkuat batas-batas sosial yang ketat, sehingga pendatang merasa tidak diterima dan sering menghadapi diskriminasi. Fenomena ini bukan hanya terjadi pada tingkat individu, tetapi juga pada level komunitas, di mana kebijakan dan sikap otoritas adat seringkali mencerminkan sentimen anti-pendatang yang kuat.;\n\nArtikel Rujukan: ### PEDOMAN KOMUNITAS: HS_STEREOTYPE\n\n**INDIKATOR PELANGGARAN:** Penggunaan kata 'semua', 'selalu', atau penyebutan nama suku/ras yang diikuti dengan klaim perilaku negatif, watak jahat, atau kecenderungan kriminal kolektif.\n**DEFINISI:** Tindakan memberikan label negatif, atribut buruk, atau tuduhan kriminal secara pukul rata (generalisasi) kepada seluruh anggota kelompok berdasarkan latar belakang suku, ras, etnis, atau agama tertentu. Pelanggaran terjadi ketika perilaku individu digunakan untuk menghakimi seluruh identitas golongan. Hal ini mencakup tuduhan sifat bawaan (genetik) yang buruk terhadap etnis tertentu.\n**KATA KUNCI PEMICU:** Suku itu licik, Ras ini pelit, memang wataknya jahat, keturunan pemberontak, genetik kriminal, tidak bisa dipercaya, sok ramah padahal busuk, orang daerah itu kasar, kaum itu memang tukang buat onar.","Label: **Ujaran Kebencian.** penjelasan: Pernyataan ini memberikan label negatif dan atribut buruk kepada seluruh suku Dayak, mencerminkan generalisasi kolektif yang merendahkan martabat mereka sebagai kelompok etnis.\n\nRincian indikasi pelanggaran dalam teks tersebut mencakup beberapa poin berikut:\n* Claim menggeneralisir suku Dayak dengan atribut negatif seperti solidaritas yang disalahgunakan untuk mengintimidasi dan memarginalisasi kelompok luar.\n* Pernyataan menegaskan bahwa praktik ini bukan hanya sikap defensif, melainkan bentuk eksklusivisme yang telah tertanam dalam budaya mereka.\n* Claim menyebutkan bahwa fenomena ini terjadi pada tingkat individu dan komunitas, menunjukkan generalisasi kolektif yang merendahkan martabat mereka.\n\n**Mari kita jaga ruang digital dengan berkomunikasi secara santun tanpa merendahkan martabat kelompok mana pun.**"
5265,"Analisis potensi pelanggaran konten. Bandingkan teks dengan rujukan fakta dan pilih label: Disinformasi, Fitnah, Ujaran Kebencian, Fakta, atau Non-DFK.","input: Judul: Hambatan Menuju Penegakan Hukum yang Beradab.\n\nTeks: Konflik horizontal di berbagai daerah Indonesia, khususnya di Papua, menunjukkan pola yang konsisten: budaya perang suku yang mendalam. Fenomena ini bukanlah sesuatu yang baru, namun sudah lama menjadi bagian dari identitas dan cara hidup masyarakat setempat. Suku-suku di Papua tampaknya memiliki kecenderungan alami untuk mempertahankan tradisi perang suku, yang akhirnya menghambat upaya pemerintah dalam menegakkan hukum yang beradab. Setiap kali upaya penyelesaian konflik dilakukan, seringkali dijumpai keengganan dari pihak-pihak yang terlibat untuk menghentikan siklus kekerasan. Hal ini menunjukkan bahwa budaya perang suku telah menjadi sifat yang sulit diubah, bahkan dengan berbagai program pemberdayaan dan pendidikan yang telah diberikan. Akibatnya, Papua tetap menjadi wilayah yang sulit diatur dan memerlukan pendekatan khusus yang berbeda dari daerah-daerah lain di Indonesia.;\n\nArtikel Rujukan: ### PEDOMAN KOMUNITAS: HS_STEREOTYPE\n\n**INDIKATOR PELANGGARAN:** Penggunaan kata 'semua', 'selalu', atau penyebutan nama suku/ras yang diikuti dengan klaim perilaku negatif, watak jahat, atau kecenderungan kriminal kolektif.\n**DEFINISI:** Tindakan memberikan label negatif, atribut buruk, atau tuduhan kriminal secara pukul rata (generalisasi) kepada seluruh anggota kelompok berdasarkan latar belakang suku, ras, etnis, atau agama tertentu. Pelanggaran terjadi ketika perilaku individu digunakan untuk menghakimi seluruh identitas golongan. Hal ini mencakup tuduhan sifat bawaan (genetik) yang buruk terhadap etnis tertentu.\n**KATA KUNCI PEMICU:** Suku itu licik, Ras ini pelit, memang wataknya jahat, keturunan pemberontak, genetik kriminal, tidak bisa dipercaya, sok ramah padahal busuk, orang daerah itu kasar, kaum itu memang tukang buat onar.","Label: **Ujaran Kebencian.** penjelasan: Pernyataan ini memberikan label negatif dan atribut buruk kepada seluruh suku-suku di Papua, mencerminkan generalisasi kolektif yang merendahkan martabat mereka sebagai kelompok etnis.\n\nRincian indikasi pelanggaran dalam teks tersebut mencakup beberapa poin berikut:\n* Claim menggeneralisir suku-suku di Papua dengan atribut negatif seperti budaya perang suku yang mendalam dan kecenderungan alami untuk mempertahankan tradisi perang suku.\n* Pernyataan menegaskan bahwa budaya perang suku telah menjadi sifat yang sulit diubah, menunjukkan generalisasi kolektif.\n* Claim menyebutkan bahwa fenomena ini menimbulkan hambatan dalam penegakan hukum yang beradab, menunjukkan generalisasi kolektif yang merendahkan martabat mereka.\n\n**Toleransi adalah kunci dalam bersosial media. Mari hentikan penyebaran stigma dan generalisasi negatif terhadap kelompok lain.**"